### ISSUE TITLE
Build configuration/settings infrastructure for Admin Dashboard Widgets

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1007]
Pressing wrench icon on a dashboard widget gives an error message

**Comment by drbyte** [comment]
Yes, this is a known issue. The settings infrastructure hasn't been completed yet.

**Comment by scottcwilson** [comment]
Maybe Wilt and I could split the work on this.

**Comment by zcwilt** [comment]
I think the first stage would be to define a db schema for widget settings. I've some ideas here and will update asap

**Comment by zcwilt** [comment]
While we can't use it, https://laravel-backpack.readme.io/docs/crud-fields#standard-field-types
suggests some ideas about defining settings

**Comment by zcwilt** [comment]
Initial Schema.

    CREATE` TABLE dashboard_widgets_settings (
      settings_key varchar(64) NOT NULL,
      widget_key varchar(64) NOT NULL,
      setting_name varchar(255) NOT NULL,
      setting_definition longtext NOT NULL,
      setting_type varchar(32) NOT NULL,
      setting_initial_value longtext,
      PRIMARY KEY (settings_key,widget_key)
    ) ENGINE=MyISAM;

    CREATE TABLE dashboard_widgets_settings_to_user (
      setting_key varchar(64) NOT NULL,
      widget_key varchar(64) NOT NULL,
      admin_id int(10) unsigned NOT NULL,
      setting_value longtext,
      PRIMARY KEY (setting_key,widget_key,admin_id)
    ) ENGINE=MyISAM;

I could have gone  with a more explicit EAV schema, but really don't think it's necessary.
The only benefit of that would have been to give some DB data integrity, which we can just manage in code.
Especially given we really only have 3 data types (DB) 
e.g.

- string/text
- numeric
- datetime

Notes on some of the columns.

``dashboard_widgets_settings.setting_name`` is the title(label) for the input field
To easily manage languages without having a new language table, the entry here would be a language define key, much the same way that the ``dashboard_widgets_description.widget_name`` field works.

``dashboard_widgets_settings.setting_definition`` will be a json definition of the input. As mentioned previously you can see how this might work using 
https://laravel-backpack.readme.io/docs/crud-fields#standard-field-types as an example.
I could have used a mysql json type field here, but that can be problematic for supporting some mysql variants, especially MariaDb.

``dashboard_widgets_settings.setting_type`` describes the input type e.g. select/radio/checkbox/text etc.

**Comment by zcwilt** [comment]
Originally when planning the settings stuff I had thought about using something like https://nnattawat.github.io/flip/ to give access to the settings page. However while it would look nice and cool, it has some problems. 

Given we widgets can be any size it's possible there won;t be enough real estate to display all settings without having ugly scrollbars. Seems to me for simplicity that it's easier to just use a modal here.

**Comment by scottcwilson** [comment]
OK.  I am standing by.

**Comment by zcwilt** [comment]
Taking longer than I thought. Mainly because I decided to go down a refactoring rabbit hole. The original dashboard widget code was a lot of purely static methods in the ``WidgetManager`` class.  This meant it was difficult to use a lot of ``dependency injection``  to load in some supporting classes.

However pretty much done with the refactoring, being able to use DI and new laravel models really tidies up the code and makes it more readable.

**Comment by zcwilt** [comment]
Just a further update. 

I now have code working to allow for defining and managing multiple settings per widget.
If a widget has no settings then no wrench icon appears.

The wrench icon now displays  a modal for editing the settings values and on submit these are stored per admin user. 

There is a new oop infrastructure for managing config settings, which hopefully can be reused for the normal ZC configuration settings as well. 

What's still to do 

**Language Handling**

The example here would be a select list. Currently these can be defined using a json structure. 
e.g. for a refresh rate it might be 

    {"options":[{"id":1,"text":"1 Seconds"},{"id":5,"text":"5 Seconds"},{"id":10,"text":"10 Seconds"},    {"id":20,"text":"20 Seconds"}]}

and in this case the select option text is hard coded. What would be better is to use language defines for the ``text``

Because of the way the config settings classes work, it's definitely possible to do some interpolation to use language defines here, just haven't done it yet.

**Setting Types**

Currently I only have 3 very basic setting types

- A text field
- A boolean field (using a checkbox)
- A select dropdown from a hard coded array e.g. the refresh rate mentioned earlier

As examples would be nice to add some date/datetime fields as these would seem to be the most needed, and a select oprtion the pulls values from a model, rather than being hard coded. e.g. a countries select.

**Validation**

Currently there is no validation done on the settings fields on submit, apart from basic security stuff for CSRF protection.

Need to allow for at least setting some validation requirements in the setting definitions.

**Documentation**

 Have started some documentation but needs more fleshing out.


Hoping to have 90% of this done over the weekend
