### ISSUE TITLE
Create "customers" class

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#1021]
There's a lot of procedural code kicking around, in both admin and catalog, for managing customers.  It would be a lot easier to extend and manage if this were consolidated into a single class which gets used on both catalog and admin sides.

Plugins could then extend the capabilities either through notifier hooks (or optionally (for more advanced developers) by extending the class).

The new class should have a full set of unit tests accompanying it.

Probably best to start by fleshing out specs here first...

**Comment by lat9** [comment]
I guess that the first step in creating a proper class is to define the actions that the class needs to support.  Here's my initial take, based on operations provided by `/includes/functions/functions_customers.php` and `/admin/customers.php` current processing:

- Customize (use this to set the account-creation/update parameters)
- Create a customer record
- Get customer details (this might need to be "sub-divided" to return portions of the information)
- Change password
- Update customer details
- Update customer address record
- Add customer address record
- Delete customer address record
- Count customer address records
- Count customer orders
- Delete customer (needs admin-level permissions)

To enable capabilities to be extended via class-inheritance actions (and this applies to all class-entities), I believe that the class should be loaded **and instantiated** early in the configuration.  That would allow the class to be totally replaced by a class extension by simply unsetting the current instance and re-instantiating the default instance using the extended class.

That said, it's not (necessarily) an approach that will work for broadly-used plugins since you could get "collisions" when plugin1 overrides the class and then plugin2 overrides plugin1's overrides.  The notifier approach will work best in that environment, but the overall class-replacement would more likely be a specific-site-customization.

**Comment by scottcwilson** [comment]
This idea has been resurrected in #3850.
