### ISSUE TITLE
Some dashboard widgets cut off at bottom

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1104]
For example, the General Statistics widget.  If you do a view source, you will see more rows than are actually shown on the screen. 

Please assign to me, I am working on a fix.

**Comment by dakanji** [comment]
FYI, for the "General Statistics" one, there is a scroll bar on my installation and I get all the items shown in the source when I scroll down. Not sure of others.

**Comment by zcwilt** [comment]
@scottcwilson Happy to assign to you, but some things to ponder.

The fixed row height is due to gridstack setting a fixed height for it's outer container, due to its support for multiple row/cols per widget. (I too get a scrollbar) 

We could for instance set the col height for General Statistics to 2, but that feels like a bandage rather than a solution. 

We could enable resizable widgets (which gridstack supports)  although that forces the user to do some work for those widgets that are initially too small.

We could introduce some js to autocalculate column height based the container height 
e.g 

    $( element ).height();

**Comment by scottcwilson** [comment]
Just setting it to 2 looks remarkably good and is a no-brainer solution.  You shouldn't have to scroll for widgets.
