### ISSUE TITLE
Recommendation: get rid of logo at top left of admin page

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1117]
This is a large block of real estate.  I think a logo at the bottom center is good, but the top left should be removed.  This is especially important for people using small screens.

**Comment by drbyte** [comment]
Where then do you recommend moving the 4 buttons that appear to the right of the logo when conditions warrant?  GV release queue, version-checking, latest-orders (in narrow mobile view), log/etc warnings, etc...

**Comment by judygunderson** [comment]
A lot of my customers like the logo there (their logo of course, lol) because it prints out on their packing slips and invoices as opposed to just having the company name / info in text.  I would say maybe 10% of my customers are happy with just the company name/etc on the right of the packing slips, so I just put up a blank .gif file.

**Comment by dakanji** [comment]
Agreed that a single appearance bottom centre is enough for the application and that the top left area should have the actual store's logo.

**Comment by scottcwilson** [comment]
@drbyte Those are below the logo, right?  It seems the logo takes up a row space equivalent to it's height.   Is this not what you see? 

<img width="1634" alt="screen shot 2016-07-19 at 5 21 39 am" src="https://cloud.githubusercontent.com/assets/4391638/16944949/ddef7030-4d70-11e6-924d-9c1598e5c3ef.png">

**Comment by scottcwilson** [comment]
@judygunderson Having the logo on the admin home screen is not what makes it print out on packing slips and invoices.  The two matters are unrelated.

**Comment by Zen4All** [comment]
@judygunderson the logo can still be used for invoice and packing slip. This is unrelated to the logo being present at the top of the page. Although the same image file is used by default.

I like the proposal of removing the top logo.

**Comment by drbyte** [comment]
> Those are below the logo, right? It seems the logo takes up a row space equivalent to it's height.

No.
While there's some disparity while we complete the admin templates, just like v155 there exists additional data to the right of the logo. See these screenshots, for desktop and mobile.

<img width="519" alt="screen shot 2016-07-19 at 9 25 26 am" src="https://cloud.githubusercontent.com/assets/404472/16951460/18144dea-4d93-11e6-9284-d03dfe370caf.png">
<img width="1209" alt="screen shot 2016-07-19 at 9 25 07 am" src="https://cloud.githubusercontent.com/assets/404472/16951461/18288af8-4d93-11e6-80d3-7f10e935cb4a.png">

_These were taken on the customers page, since the home page uses the other template ATM._

**Comment by scottcwilson** [comment]
You could still put View Activity Log / Orders / Gift Certificate Queue on the same line.

**Comment by drbyte** [comment]
> You could still put View Activity Log / Orders / Gift Certificate Queue on the same line.

They are on the same line, on desktop. The cells stack into an additional row on mobile since the screen is narrower.

**Comment by scottcwilson** [comment]
What about a caret icon at the right to compress this row?

**Comment by drbyte** [comment]
> What about a caret icon at the right to compress this row?

Given that that sort of "compressing" is only for the current "draw" of that page, wouldn't one would more likely scroll than ever click to collapse that?

**Comment by scottcwilson** [comment]
I was thinking it could be saved - not just javascript compression but a setting for the current session.

**Comment by drbyte** [comment]
Well, dealing with pending GVs is something someone should just go ahead and do. Then that button goes away.

Perhaps the activity log button isn't needed as prominently and could be squashed into a notification bell indicator.

Your initial point was that the height of the logo takes up some extra space, particularly on mobile where the nav menu is much more minimal.

I think we need to finish with the standardizing of admin template stuff between legacy and lead pages. And then ideas of how to maximize use of this header space could be entertained.

But I disagree that that large block of real estate is unused. It's all got purpose, which varies dynamically depending on what's going on within the store.

**Comment by scottcwilson** [comment]
OK.  Closing.
