### ISSUE TITLE
"There was a security error" msg NOT shown after excessive logins

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1138]
I was suspicious about this, so I wanted to check it before working on #1135.  I confirmed that it does not work as expected.

Repro steps:
- Login with a bad password 8x.  You won't see the error on the 9th or 10th time.

Analysis: 
- admin/includes/functions/admin_access.php line 399 sets the redirect variable, which causes admin/login.php to do a header().  If this is taken out, the message will appear when a bad password is used, BUT the screen which is redrawn does not work - the $_POST variables aren't set when you submit it, so you don't get the normal login behavior.  (Expected: error message would be issued again.)

- Because admin/login.php does not look in $messageStack for a message, you can't save the message for later display, then do the redirect.  (Of course, this logic could be added if it makes sense.)

Thoughts on what to do?

**Comment by netcrop** [comment]
1, Inside admin_access.php, function zen_session_destroy() will cause redraw of admin/index.php. Therefore no need to call zen_redirect() inside login.php in this case.
2, inside login.php Change if ( $redirect != '') zen_redirect($redirect) To if ($message == '' && $redirect != '') zen_redirect($redirect).
3, I set FILENAME_DEFAULT='https://absolutpath/admin/index.php'.

**Comment by netcrop** [comment]
I have verified my suggestion and it works, the suggestion is:
1, inside file admin_access.php inside block
if ($_SESSION['login_attempt'] > 6 || $result['failed_logins'] > 6)
{
Add this line
 $message = ERROR_SECURITY_ERROR;
}
2, inside file login.php inside block
 if ($admin_name == '' && $admin_pass == '') {
...
} else {
Change 
 if ($redirect != '') zen_redirect($redirect);
To
 if ($message == '' && $redirect != '') zen_redirect($redirect);
}
3, During my test, the admin login page shows "There was a security error when trying to login." after 6 wrong passwords attempts.
4, Needs further investigation: 
Inside admin_access.php, function zen_session_destroy() flush the browser cache, the warning message don't show up on 8, 10, 12 ... woring passwords attempts.

**Comment by netcrop** [comment]
I have verified my suggestion and it works, the suggestion is:
* inside file admin_access.php replace block
```
if ($_SESSION['login_attempt'] > 6 || $result['failed_logins'] > 6) { ... }
```
With this block
```
if ($_SESSION['login_attempt'] == 7 || $result['failed_logins'] == 7)
{
    $sql = "UPDATE " . TABLE_ADMIN . " SET lockout_expires = " . (time() + ADMIN_LOGIN_LOCKOUT_TIMER) . " WHERE admin_name = :adminname: ";
    $sql = $db->bindVars($sql, ':adminname:', $admin_name, 'string');
    $db->Execute($sql);
    zen_session_destroy();
    zen_record_admin_activity('Too many login failures. Account locked for ' . ADMIN_LOGIN_LOCKOUT_TIMER / 60 . ' minutes', 'warning');
    sleep(15);
    $message = ERROR_SECURITY_ERROR;
    $redirect = zen_href_link(FILENAME_DEFAULT, '', 'SSL');
    return array($error, $expired, $message, $redirect);
} else if ($_SESSION['login_attempt'] > 7 || $result['failed_logins'] > 7){
    zen_record_admin_activity('Too many login failures. Account locked for ' . ADMIN_LOGIN_LOCKOUT_TIMER / 60 . ' minutes', 'warning');
    sleep(15);
    $message = ERROR_SECURITY_ERROR;
    return array($error, $expired, $message, $redirect);
} else {
    sleep(4);
}
```
* inside file login.php inside block
```
 if ($admin_name == '' && $admin_pass == '') {
...
} else {
    /* Change */
    if ($redirect != '') zen_redirect($redirect);
    /* To */
    if ($message == '' && $redirect != '') zen_redirect($redirect);
}
```
* During test, the admin login page shows "There was a security error when trying to login." on 7th wrong passwords attempts. On 8th attempt the page redraw due to function zen_session_destroy() flushed cache.  And the security warning shows up again and again after 8th attempt as expected.

**Comment by scottcwilson** [comment]
@netcrop Did you want to go ahead and submit a PR based on your changes?

**Comment by netcrop** [comment]
Yes, I would be glad to submit a PR for this issue.

**Comment by drbyte** [comment]
I don't think all those many changes are needed.

Couldn't we simply add one line:

`$message = ERROR_SECURITY_ERROR;`

into:

```
        sleep(15);
        $message = ERROR_SECURITY_ERROR;
        $redirect = zen_admin_href_link(FILENAME_DEFAULT);
```

No need for the extra `elseif`.

Maybe remove the `session_destroy` if that's causing trouble with message display?

**Comment by netcrop** [comment]
I'll be testing it and give you feedback.

**Comment by netcrop** [comment]
* Further investigation shows. IF ```zen_session_destroy()``` been removed, ```$_SESSION['login_attempt']``` will grown unlimited and when it's bigger then 9 and If user click on "Forgot Password" button, the ```header('HTTP/1.1 406 Not Acceptable')``` will take effect inside admin/password_forgotten.php.
* But IF we keep ```zen_session_destroy()```, our problem will Not be solved entirely. Means the Warning message shows 50% of times.
* My suggestion is: In the same location, replace ```zen_session_destroy()``` with ```$_SESSION['login_attempt'] = 0``` and I'll submit a PR based on this solution into v160.

**Comment by netcrop** [comment]
Here is the purpose by using ```zen_session_destroy()``` in admin_access.php

* ```zen_session_destroy()``` could be replaced with                           ```$_SESSION['login_attempt'] = 0;``` since one important aspect is to prevent ```$_SESSION['login_attempt']``` grown beyond a barrier that trigger the             ```header('HTTP/1.1 406 Not Acceptable')``` inside password_forgotten.php.
But what if this trigger was made on purpose as a slam prevention? That would  require a ordinary user to restart the browser for requesting a password       reset. Not so convenient. Therefore ```zen_session_destroy()``` **is** been used.

* The same scenario happens after user had required password reset, but before she activate the reset link via email. When she again tries to login the site  with several invalid attempt that trigger the slam prevention. And that is why **no**```zen_session_destroy()``` been used this time.

**Comment by drbyte** [comment]
Thanks for researching this.

Question: why have slam-protection at all then? 

The purpose of slam-prevention is to MAKE it inconvenient for people who are brute-forcing passwords. Thus the 406 response.  Requiring an "ordinary user to restart the browser" is indeed inconvenient, but "9 failures" is NOT typical of an "ordinary user", and is more likely to be a malicious attacker.

**Comment by netcrop** [comment]
Yes, I **agree**, the question is how to identify an malicious attack, here is a   real world scenario, which could **confuse** an ordinary user:

* A user using multiple browser tabs to access her login accounts across different sites. She messed up her passwords and been locked out from zencart  admin site after **7** invalid attempt (slam prevention not yet triggered). She    reset her password via email, and incorrectly typed in her new password. And   she tried again with the correct one this time. Unfortunately ```login_attempt``` is now **9**, because previous session was stored in memory.   She was been locked out and since the slam prevention been triggered, she      couldn't reset her password, until she restart browser.

* But, since this scenario isn't very common and I am agree to remove          ```zen_session_destroy()``` from the original code.

**Comment by netcrop** [comment]
Further research shows, zen_session_destroy() also cleanup database sessions entry after 6 invallid admin login attempt. This duty can't be coverd by restart browser.
A paradoxical situation: 
* without zen_session_destroy(), the login_attempt keep grown until and after 9 invalid attempt. The slam prevention been triggered as expected. But the database session entry will never been cleaned up.
* with zen_session_destroy(), the login_attempt will be reset after 7 invalid attempt and the database session entry will be cleaned up. But, slam prevention will not be triggered.

**Comment by netcrop** [comment]
I now understand the function **_sess_gc()** will clean up any expired database sessions entries based on time().
The question is, if the zen_session_destroy() function call is still **necessary** in the calling stack from original code base in v160 ?
```
# Invalid login attempt
zen_session_name zenAdminID
zen_session_start
_sess_open /var/lib/php5/sessions zenAdminID
_sess_read o3ro312cjh4adoa5a0lsekect4
_sess_gc
zen_session_name
_sess_write o3ro312cjh4adoa5a0lsekect4
_sess_close

# After login_attempt > 6
zen_session_name zenAdminID
zen_session_start
_sess_open /var/lib/php5/sessions zenAdminID
_sess_read o3ro312cjh4adoa5a0lsekect4
zen_session_name
zen_session_destroy
_sess_destroy o3ro312cjh4adoa5a0lsekect4
_sess_close
zen_session_name

# Valid login
zen_session_name zenAdminID
zen_session_start
_sess_open /var/lib/php5/sessions zenAdminID
_sess_read o3ro312cjh4adoa5a0lsekect4
_sess_gc
zen_session_name
zen_session_recreate
zen_session_name
_sess_write o3ro312cjh4adoa5a0lsekect4
_sess_close

# logout
zen_session_name zenAdminID
zen_session_start
_sess_open /var/lib/php5/sessions zenAdminID
_sess_read o3ro312cjh4adoa5a0lsekect4
zen_session_name
zen_session_destroy
_sess_destroy o3ro312cjh4adoa5a0lsekect4
_sess_close
```
