### ISSUE TITLE
v1.6.0: What happened to the responsive_classic template?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1246]
I finally had a little free time and installed the current 1.6.0 file-set (without issue!) on my localhost environment.  The admin looks great, but the responsive_classic template is nowhere to be found.

What's the story?

**Comment by drbyte** [comment]
Here's the back-story:

At the time of merging 155 and 160 , the responsive_classic wasn't merged because:

a) a different template for v160 was already in progress (still is, but not unveiled yet). Based on Bootstrap (formerly based on Foundation). Wasn't sure whether bringing responsive_classic in would 
be good or bad; still undecided;

b) on the forum it seemed evident that numerous tweaks were still needed to responsive_classic

c) couldn't find someone willing to maintain responsive_classic
Are you offering?

**Comment by scottcwilson** [comment]
My vote would be deprecate responsive_classic in favor of the new template.

**Comment by barco57** [comment]
me gets popcorn, pulls up chair and waits.... This should be interesting

**Comment by scottcwilson** [comment]
I am standing on one foot and then the other waiting to see the new Bootstrap based template. A super-high-quality template is a must-have feature for 1.6.0.

**Comment by lat9** [comment]
> c) hadn't gotten around to finding someone willing to maintain responsive_classic and related updates to DIY
> Are you offering?

Nope, template design is not my fort&eacute;; I'm not into the rock-fetching-exercise that usually accompanies any user-interface design/programming.

> My vote would be deprecate responsive_classic in favor of the new template. 

`<sarcasm>`
So, the release of Zen Cart 1.5.5 was held up for 2-3 months so that `responsive_classic` could be completed, lasting one whole release, and the Zen Cart community's efforts (like the coloring that @dbltoe and @haredo provided) to improve upon that template are to go into the proverbial bit-bucket?
`</sarcasm>`

FWIW, I'm not in favor of deprecating `responsive_classic` for a [pig-in-a-poke](https://en.wikipedia.org/wiki/Pig_in_a_poke).  I'll withhold judgement until there's a responsive template to compare to ... hopefully named something **other than** `responsive_classic`.

**Comment by scottcwilson** [comment]
A couple of points: 
- The lifespan of Zen Cart 1.5.5 could be quite long.  So responsive_classic isn't exactly a throwaway.
- A major issue with Zen Cart is the paucity of high quality responsive templates.  Products like OpenCart and Shopify are built with mobile in mind, and with Google penalizing non-mobile-friendly websites, this issue is only getting hotter.   As a short term fix, the responsive_classic template was the right move.

**Comment by lat9** [comment]
Right, but store-owners that are converting to responsive_classic are most likely not expecting that the template is going to disappear in the next release.

**Comment by drbyte** [comment]
> A super-high-quality template is a must-have feature

What exactly does "super-high-quality template" mean, according to you? 

I gather it has nothing to do with the resolution of graphics/images, and you're referring to about 1000 specific individual  entirely-customizable-with-one-click components and colors and complete-rearrangements and auto-intuiting-where-to-place-sally's-must-have-widget, all out-of-the-box. But you didn't list any of those, so it's not clear.

**Comment by drbyte** [comment]
> Right, but store-owners that are converting to responsive_classic are most likely not expecting that the template is going to disappear in the next release.

Yes, you're right: they're not expecting that. 

But nobody said it was disappearing. Merely undecided the best approach to take going forward. 


So, @lat9 this discussion came about due to your experience of shock when not seeing it in 160 yet. Was your comment about "store-owners that are converting" the main crux of your inquiry? Or is there more that you wanted to add but didn't have words for at the time of first writing?

**Comment by dbltoe** [comment]
Why not take the responsive_classic with the color change and make that the new "classic green" ?  That one has been around since Al invented the internet.

**Comment by lat9** [comment]
@drbyte, my initial posting was as you stated, simply my surprise at seeing the "classic green" template when I first clicked the `Storefront` link on my newly-installed v1.6.0 test-bed.

**Comment by drbyte** [comment]
> Al invented the internet 

Wait! I thought he invented the interwebs!

**Comment by drbyte** [comment]
> surprise at seeing classic-green

Noted. Will be addressing that.

**Comment by proseLA** [comment]
i am a little late to this party, but i am all for resources going towards the new bootstrap template and letting responsive_classic fall by the wayside. ZC's strength has been its customization with added plugins; its weakness has been its template. if the new template is not "super high quality" (again whatever that means), bootstrap provides a solid infrastructure for others to go forward on.

**Comment by bislewl** [comment]
I'v been working on a bootstrap template as well. It's been consuming way more time than I had initially planned. Perhaps someone is a little further. Some issues I'm encountering are old configuration variables like:  COLUMN_WIDTH_RIGHT. If it's included in the core. Do we remove these? Do just disconnect them? Do we change how it works. Anyone with thoughts? My original thoughts were to move to a drag-drop template layout but that is significantly problematic with variables like these.

**Comment by zcadditions** [comment]
WOW,

The DIY code is nothing more than Mobile-Detect, not really much to maintain and it was written for just that reason.

I think the responsive_classic was a bit bloated and should have been simplified and most "store-front" features should have been left out and others made optional as plugins.

As far as 160, the **dev team needs to implement the framework that the DEV team feels comfortable maintaining**, I personally think any 3rd party framework is a mistake.
