### ISSUE TITLE
question on ZC logging....

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#1293]
i am personally a big fan of the ZC error logging.

currently the file renaming adds the -adm- to error logs generated from the admin side.

my opinion is that they are not really necessary as one can see from within the log where the error came from.  obviously it does provide additional information prior to opening the file, but my question remains as to whether or not that is necessary?

i would like to remove the duplicate code from the includes/extra_configures on the storefront and the admin side, and prior to doing too much work on it,  i'm curious whether people like the -adm- or not.

thanks.

**Comment by barco57** [comment]
yes, I like it very much. As someone who works at a host and touches many Zen Carts a day I would probably be pissed if there was not a distinction between them. As it is, I would prefer if all of the things that log to the logs folder had separate sub folders. imagine going into someone files where they ran out of hosting space because they messed something up and wrote 400,000+ myDebug logs, and they are all mixed with paypal logs. if they were all separated out you could just nuke the mydebug sub folder instead of nuking the entire logs folder and loosing the paypal logs in the process. I know someone is going to poke their head in and ask why someone would leave the paypal debug logs on, there are clients that insist upon it.

**Comment by scottcwilson** [comment]
👍 @barco57 This is a very useful facility.

**Comment by proseLA** [comment]
sounds good.  thanks for comments.
