### ISSUE TITLE
error meesage on login - opinions wanted....

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#1295]
if a user enters the wrong credentials, ZC provides the following error message:

Error: Sorry, there is no match for that email address and/or password.

i have clients that want ZC to notify the user if it is the username or password that is the problem.  i am curious what the community thinks with regards to telling the user which one it is.

**Comment by drbyte** [comment]
Proper security protocol is to reveal no identifying information, because a hacker could use any info gleaned from the error message. 
If you tell them they have the right user but wrong password then they're 80% closer to breaking in. 

That's why zen cart reveals none of that sensitive information.

**Comment by proseLA** [comment]
I am not sure what proper security protocol means.

I can understand this philosophy when protecting admin credentials; but user accounts?  What exactly are we trying to protect?  Order history?  Credit card tokens?  Address information?

Furthermore, I have yet to see a hacker waste his time on credentials for logging in to the storefront side of any ZC site.  The only reason I can see for this behavior would be to exploit a known weakness in ZC, and what would prevent said hacker from creating his own account?

200 million yahoo credentials were offered for $1800 on the dark net.   Do you really see hackers getting at user accounts?

Furthermore, let’s assume a hacker wants to get into the user account section of ZC.  Do you think they are sitting in front of a screen and keyboard making attempts?  They are using a bot to handle this.  And I suppose a sophisticated hacker can get the bot to read the error message, but I doubt it.

Personally, I see hackers attempting to break in via SSH into servers.  I see hackers attempting to get credentials on the admin side.  I never see them on the catalog side.

Does anyone see this type of activity in the logs?

Security measures make it difficult for valid users to transact business.  This measure, in my mind, tends to upset customers to the point that they shop elsewhere.

Finally, please see the attached screenshot of how another retailer handles this situation.
![screenshot from 2016-09-23 09-24-59](https://cloud.githubusercontent.com/assets/1095136/18793947/f88425fa-8171-11e6-89fa-448f01245bab.png)

**Comment by drbyte** [comment]
I fully understand your arguments. 

I was referring to PCI rules. And general industry best practices around logins in general. 

Your point about customer accounts being non issues as attack vectors has merit given that zen cart out of the box can't store card data or recurring charges etc. 

I hear your point about what Amazon does. 

I'm not prepared to do that in zen cart without having a PADSS person assert in writing that it would be acceptable while still retaining PADSS compliance ... since it was done(changed to) this way for the purpose of compliance.  

Of course you're free to do what you like on your own sites, since you're responsible for your own compliance. 

That's my view at this moment.

**Comment by drbyte** [comment]
You suggested that your customers are confused about username vs pwd. But zen cart uses email address for username. Are you saying your customers are forgetting their email address?

Or are they just confused because they have to re check what they typed?


Just looking for clarification on the deeper root issues, which might be deeper than the choice of wording in the messages displayed.

**Comment by proseLA** [comment]
first off, and most important, i totally understand about PCI-DSS compliance.  it seems to be a marketing tool for ZC, and i would not want ZC to lose that certification over this issue....  despite my feelings about PCI-DSS....

second, i hear about this issue second hand, as in general, i'm not in touch with customers.  i can see situations where they typed it in wrong, or they had more than one email address, and perhaps used the wrong one...  who knows?  i can only see the validity of the comments....

if a hacker really wanted to confirm an email address, they could do it by trying to establish a new account with the same email address, which would confirm the existence of said email address.   it is a discussion discussed frequently on the web....

third, yes, i am free to do what i want on my clients sites, and i do... :)  my conversation is more about making the base ZC install as good as it came be for current users and future users.  i bring this stuff up for the good of the community, not for myself and my clients...

**Comment by zcwilt** [comment]
I just wanted to chime in here.

At the risk of repeating. In terms of security, best practice is to reveal as little information as possible. Hence the message we use on an invalid login. 
As noted we also had to do that for PA-DSS compliance. For the Zen Cart team PA-DSS compliance, while it may have started as a unique product offering (call that marketing if you want) following PA_DSS guidelines has had a huge impact on how we write/document and release code. It's hopefully made Zen Cart a much better product in terms of security. 

That said, we also realize that some of the burdens of PA-DSS compliance are not what some store owners  want. As such we already provide some switches to relax those compliance’s. 
e.g. PADSS_PWD_EXPIRY_ENFORCED

If you want to provide a Pull Request that provides the functionality you envisage, and as long as that functionality can be turned on/off and provide appropriate warnings, 
then we would be open to incorporating it.

**Comment by zcwilt** [comment]
Also https://www.owasp.org/index.php/Testing_for_user_enumeration_%28OWASP-AT-002%29
