### ISSUE TITLE
Align the "query" and "cart" methods in the order class

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#1315]
Question about differences between admin/storefront orders.php class query function:

I've seen that the two classes will be combined (yeah!) in 1.6.0, but is there a reason why the admin version's `totals` array contains the floating-point value and the storefront one doesn't?

**Comment by drbyte** [comment]
I assume your question is related to pre-1.6.0, right? 

And do you mean this line? 
https://github.com/zencart/zencart/blob/v155/admin/includes/classes/order.php#L57

If so, the reason it was added to the Admin was so that admin-side pages that do lookups would have access to that info.  On catalog-side it was never needed by core code, so it was never included. It was added to the Admin back in 1.5.0-ish, I think, because we started adding things to display that data in specific ways, or display calculations (maybe currency-exchanges?) with it.

So, ya, the legacy of it is that `totals` didn't even exist initially. It's been added and grown based on need.

At least, that's my recollection anyway ;)

**Comment by lat9** [comment]
I do, and thanks for pulling from "far" memory!  It's just been kicking my butt with Edit Orders, where the storefront version of the class is used but the `value` is "expected".

For 1.6.0, other than the `create` function which pushes the order to the database, are all versions (whether via query or cart) of the order-class output going to "look" the same?

**Comment by drbyte** [comment]
Good idea ;)

**Comment by lat9** [comment]
Thanks, DrByte.  That alignment will help reduce confusion (mine, anyway!) for the future!

**Comment by lat9** [comment]
Another thought, as 1.6.0 gets more class-based rather than procedural:

Should the order-class encapsulate **_all_** order-related actions, e.g. updating an order's status or removing an order?

**Comment by drbyte** [comment]
> as 1.6.0 gets more class-based rather than procedural:
> Should the order-class encapsulate all order-related actions, e.g. updating an order's status or removing an order?

It already does :) ie: ... https://github.com/zencart/zencart/blob/v160/includes/classes/order.php#L1558

**Comment by drbyte** [comment]
It's a few lines earlier

**Comment by drbyte** [comment]
https://github.com/zencart/zencart/blob/v160/includes/classes/order.php#L1383

**Comment by drbyte** [comment]
@lat9 wrote:
> Question about differences between admin/storefront orders.php class query function:

> I've seen that the two classes will be combined (yeah!) in 1.6.0, but is there a reason why the admin version's totals array contains the floating-point value and the storefront one doesn't?

>  It's just been kicking my butt with Edit Orders, where the storefront version of the class is used but the value is "expected".

> For 1.6.0, other than the create function which pushes the order to the database, are all versions (whether via query or cart) of the order-class output going to "look" the same?


I was just looking through the code trying to find disparity on this, but it appears the `order_total` code deals with `value` and `text` the same for both `create` and `query`.

**Comment by lat9** [comment]
Cool, I'll review the order-class changes as I'm currently refreshing my plugins for 1.5.5b with an eye towards 1.6.0.
