### ISSUE TITLE
Repetitive Queries: zen_get_products_stock()

### ISSUE THREAD

**Issue by robryanx** [zencart/zencart#1346]
Mainly just curious if this is a current design choice or just a leftover from the past. I notice this for a lot of things but in this specific case for getting product stock in the cart.

```php
if (STOCK_CHECK == 'true') {
    $qtyAvailable = zen_get_products_stock($products[$i]['id']);
    // compare against product inventory, and against mixed=YES
    if ($qtyAvailable - $products[$i]['quantity'] < 0 || $qtyAvailable - $_SESSION['cart']->in_cart_mixed($products[$i]['id']) < 0) {
      $flagStockCheck = '<span class="markProductOutOfStock">' . STOCK_MARK_PRODUCT_OUT_OF_STOCK . '</span>';
      $flagAnyOutOfStock = true;
    }
  }
```

This will run a query for each product in `zen_get_products_stock` to get the current stock count. What could be done though is using the cart function `function get_products` which is already querying the products table and returning the quantity in `$products_array[]`

**Comment by drbyte** [comment]
Good point.  Wanna submit a PR?

**Comment by mc12345678** [comment]
Is the intention to then do away with the function zen_get_products_stock or maintain two different ways to obtain the stock quantity? One with a "singular" query the other called for each instance of the product.  Asking because of the changes to a plugin that may/should be considered with this modification.

While in that application it can be a little more convenient to have an overrideable version of a function that is to obtain stock quantity, it does appear that expanding this function would only support verifying quantity associated with product already in the cart and not be usable to obtain/determine the possibility of a product to be in stock if it is not yet in the customer's cart.

**Comment by drbyte** [comment]
I'd say that if the shopping-cart class already has knowledge of available stock, then it can forego making any calls to `zen_get_products_stock()`.  At least, that's where I'd start exploring how best to optimize things, within that class anyway.

But there's over a half-dozen other places where `zen_get_products_stock()` is called, some which are replicating similar use as `shopping_cart` and could be similarly adjusted, and some which are called from completely separate positions, and might not warrant retiring.  

So I don't see the `zen_get_products_stock()` function going away, even if other places can be optimized to reduce unnecessary queries.

**Comment by proseLA** [comment]
hey,
i was thinking about taking a crack at this enhancement, as i am all for less hits to the database.  

are we talking about v160 or v155?  after looking it seems that the checkout flow is completely different in v160 and would require changing the AbstractFlowStep.php (unless i am mistaken...) as well as adding the products_quantity to the get_products function in the shoppping_cart class....

for v155, different places...  of which i am more familiar...

**Comment by drbyte** [comment]
New dev is focused on 160.

Further to my earlier post, there are spots that can't be changed as easily, but to give an idea of scope for what I'd change, in looking at it for v155 I'd change only the following:
- `classes/shopping_cart.php` - add `products_quantity,` to line 1204, and replace the commented-out line 1366 with `'quantity_on_hand' => $products->fields['products_quantity'],`
- `checkout_shipping/header_php.php`, `checkout_payment/header_php.php`, `shopping_cart/header_php.php` -- change `$qtyAvailable = zen_get_products_stock($products[$i]['id']);` to `$qtyAvailable = $products[$i]['quantity_on_hand'];`

**Comment by proseLA** [comment]
ok...
in looking at the code, i think you have some line numbers a little off in the shopping_cart class....  but i will give it a shot...

i'm also curious about the `AbstractFlowStep.php` script.  it seems that when i put break points into the other scripts (ie `checkout_shipping/header_php.php`) they are never executed; however placing a breakpoint  in the `AbstractFlowStep.php`, it is...

if you could explain what i am missing or point me to a link where i could read up on this (i did do a cursory look), that would be great.  in that script there is a function `checkValidStock()` that seems to be doing a similar thing....

**Comment by proseLA** [comment]
@drbyte i seem to have misread your post; specifically with regards to what you are looking for.  you mention new dev is for v160, and then you tell me where things would need to get changed for v155 (hence my confusion on the lines numbers).  i can do a PR for v155 if desired, no problem.  just let me know...

w regards to v160, this specific problem of unnecessary database hits remains.  IMO, we can resolve it by:

- modifying the shopping cart class to include products inventory
- modifying the orders class to also include products inventory
- modifying the function `zen_check_stock` to include this additional variable and eliminate the need to call ` zen_get_products_stock` from within that function.  (there are only 3 calls to the `zen_check_stock` function in the code).
- the `zen_get_products_stock` function remains unchanged.

i can do a PR for those changes to v160 if so desired.  again, just let me know.

best.

**Comment by drbyte** [comment]
Sure. Let's focus on fixing it for v160.

**Comment by mc12345678** [comment]
While am curious to see the proposed change for ZC 1.6.0, was wondering how the "there are only 3 calls to the `zen_check_stock` function" factors into the decision to split out `zen_check_stock` from `zen_get_products_stock`. 

Seems that if anything modifies `zen_get_products_stock` then the same modifications would be needed to `zen_check_stock` in order to obtain the same stock level information within `zen_check_stock` that is provided back from `zen_get_products_stock`.

Or is this going to make `zen_check_stock` dependent on the contents of $shopping_cart and/or $orders and lose its additional independent functionality of checking if a selected quantity of product would result in exceeding the currently available quantity?

**Comment by zcwilt** [comment]
@mc12345678 said
> i'm also curious about the AbstractFlowStep.php script. it seems that when i put break points into the other scripts (ie checkout_shipping/header_php.php) they are never executed; however placing a breakpoint in the AbstractFlowStep.php, it is...

So currently we have left old code in core that is no longer used. 
e.g. `includes/modules/pages/checkout_shipping/header_php.php
`
The header_php.php files for checkout steps are now deprecated and code in the library 
`checkoutFlow/src/flowSteps/ `is used

**Comment by proseLA** [comment]
@zcwilt makes perfect sense....  as that is what i was seeing...

thanks.

**Comment by mc12345678** [comment]
> <strike>@mc12345678</strike>@proseLA said

>>    i'm also curious about the AbstractFlowStep.php script. it seems that when i put break points into the other scripts (ie checkout_shipping/header_php.php) they are never executed; however placing a breakpoint in the AbstractFlowStep.php, it is...

>So currently we have left old code in core that is no longer used.
e.g. includes/modules/pages/checkout_shipping/header_php.php
The header_php.php files for checkout steps are now deprecated and code in the library
checkoutFlow/src/flowSteps/is used

I had a concern of a different nature, which is the removal of the functionality offered by zen_check_stock which in ZC code has been used in the checkout process, but as written has not been restricted to in cart query.  I.e. at any time during code execution, with or without items in the cart, the zen_check_stock function can identify the presence/absence of a requested quantity.  If this is moved into the checkout process only and/or requiring product to be in the cart/order then that functionality would need to be duplicated elsewhere for other programs.  If that's the decision, then so be it, just seems like it removes a function that could be of use for other cases.

**Comment by drbyte** [comment]
@mc12345678 a couple times here you've left comments that suggest you're wanting the `zen_check_stock()` function to remain as-is, because you think there may be things that depend on it. 

But, it strikes me that the function's current return value isn't really relevant except for displaying a hard-coded out-of-stock HTML SPAN text block.

So I wonder about the function's usefulness for "other purposes".  I'm inclined to prefer to move such an HTML response out of the function, more towards the template.

Thoughts?

**Comment by drbyte** [comment]
As I've been re-reading this issue, and looking at code in the #1423 PR, it strikes me that it may be best to split up the response to this matter.

Some stores have inventory limits that require real-time checking of what's on-hand, particularly during a Sale, or for popular limited-supply items. 

If we push the inventory query all the way back to the shopping-basket, and only leave it there, isn't there a risk of the data being stale at the point of creating the order? Particularly if there's a delay in navigating through checkout or completing payment?

**Comment by mc12345678** [comment]
> @mc12345678 a couple times here you've left comments that suggest you're wanting the `zen_check_stock()` function to remain as-is, because you think there may be things that depend on it.
>
> But, it strikes me that the function's current return value isn't really relevant except for displaying a hard-coded out-of-stock HTML SPAN text block.
>
> So I wonder about the function's usefulness for "other purposes". I'm inclined to prefer to move such an HTML response out of the function, more towards the template.
>
> Thoughts?

Generally speaking, quite the contrary related to leaving as-is.  My initial response (call it shock to change), was to encourage thoughtful application/modification and how the function plays into the overall process as well as the type of "status" that it provides.  Yes, it returns HTML; however, that HTML (or absence of it) represents a status.  No HTML, in stock, HTML out-of-stock (or less than 0 in inventory).  Yes it is unfortunate that the "answer" to the question is HTML, but the ability to get an answer to the question itself is what seems most important.

So then later enquiry (not having seen the proposed code) related to the concern expressed of:
>As I've been re-reading this issue, and looking at code in the #1423 PR, it strikes me that it may be best to split up the response to this matter.
>
>Some stores have inventory limits that require real-time checking of what's on-hand, particularly during a Sale, or for popular limited-supply items.
>
>If we push the inventory query all the way back to the shopping-basket, and only leave it there, isn't there a risk of the data being stale at the point of creating the order? Particularly if there's a delay in navigating through checkout or completing payment?

Initially, I reviewed the change against ZC 1.5.5, but then when somewhere in the chain it was recommended to move this against ZC 1.6.0, I performed a similar review with that concern in mind.  It seemed to me though, that in stepping through the process that in actuality the test may occur more often which could lead to a more real time knowledge of the product being out-of-stock.  While I am at the moment basing this off of my recollection, it seems that at each new page where the order/shopping cart is evaluated that the stock is checked or at least provided back for checking which then gives an earlier "response" opportunity to the out-of-stock condition rather than waiting until the checkout_process portion of the process. 

I also was trying to divorce the two (somewhat three) concepts.  This initially started with identification of too many/additional queries.  Part of the solution to that was to modify a function such that it could take an additional field and provide the answer to the question: Does the identified unique product have enough quantity available to support the requested change in stock? Another part was to modify the dependency of `zen_check_stock` on `zen_get_products_stock`, where the operation of `zen_get_products_stock` would have already been performed by the function calling `zen_check_stock`.  Yes, this could result in a quantity adjustment occurring from the time of the initial query (`shopping_cart`) to the time that `zen_check_stock` is called to do the math as compared to the current process that would wait until the question is asked (is there enough) to perform that query. The third item/issue to divorce was the `shopping_cart` response which seems to be an entirely different topic and unrelated to determining whether an adjustment is needed at all.

I agree, the actual value returned by `zen_check_stock` in my opinion is irrelevant, boolean, HTML, text, whatever, its a result that can be used to say yes in stock or no out-of-stock that is important there.  Then, there is the timing issue, is it in stock now, or was it in stock a micro- or nanosecond ago? It appeared that in chasing the path, that as I described in the closed PR, the order pulls from the shopping cart and the shopping cart would gather the data and from there whenever it was desired to know the stock status it would be available as based on that pull. It seemed further that through the checkout sequence that the orders class was relatively frequently created/recreated affording frequent identification of the stock status.  

As to a dependency, with the further alignment of functions to classes, namespaces, etc..., the function has historically out-right provided "real-time" data by use/call to `zen_get_products_stock`, allowing other code to use a ZC built-in function to determine that status.  Things change and that code would have to follow if it were to remain operational/available.  That aspect somewhere herein has been described as a necessary action which was one of the reasons I wanted to see where it was headed so that I could make the changes necessary to step away from or use the newly defined ZC code and as necessary incorporate the existing functionality directly into that code.  

When I incorporated the use of `zen_check_stock` and `zen_get_products_stock` I seriously weighed whether to use a modified version of the core code, a separate function, or both in order to provide the necessary/desired functionality.  Going down the path suggested above to create however many other functions but mainly to capture the `quantity_on_hand` in the shopping cart class, seemed to solve at least the need/use of a modified version of `zen_check_stock` and I was hopeful that it would also affect `zen_get_products_stock` in a similar manner.  But to support the plugin's operation/integration, the function `zen_get_products_stock` seems like it would still need to be modified (without modifying many other template type/style files or the includes/modules/page/ related code including those that are added through other plugins or templates).  

While I can not say that I know of many other plugins that need to know the quantity on hand and/or whether the provided quantity can be handled as part of the initial customer entry, part of what I was looking out for was potential future use with a minor weight on ZC being a little more of a learning platform as compared to a major selling platform.  I am ever considering that weight to be less and less of a factor as the code continues to be improved from multiple directions and with expansion/integration being ever considered.

The HTML function response discussion seems to be ongoing and nearly eternal; however, I am also seeing in use of javascript/jquery, that without further refinement/addition of template tags that it provides a consistent response when provided the desired initial data and that even in such case that those functions (albeit javascript/jquery) return or affect html... From the perspective of my concern, I don't care what the result/answer is as much as I have a way to understand the response and as necessary incorporate the functions response into the code of concern.

I do think that 100% of the determination of quantity-on-hand/still in stock should not be at the initial establishment of the `shopping_cart` (even if recreated/queried frequently), and it seemed like from the response above:
> But there's over a half-dozen other places where `zen_get_products_stock()` is called, some which are replicating similar use as `shopping_cart` and could be similarly adjusted, and some which are called from completely separate positions, and might not warrant retiring.
>
>So I don't see the `zen_get_products_stock()` function going away, even if other places can be optimized to reduce unnecessary queries.

That there would still be "targeted" points at which to reel in the situation.

**Comment by proseLA** [comment]
> As I've been re-reading this issue, and looking at code in the #1423 PR, it strikes me that it may be best to split up the response to this matter.

>Some stores have inventory limits that require real-time checking of what's on-hand, particularly during a Sale, or for popular limited-supply items.

>If we push the inventory query all the way back to the shopping-basket, and only leave it there, isn't there a risk of the data being stale at the point of creating the order? Particularly if there's a delay in navigating through checkout or completing payment?

first off, to me it is crucial to check inventory at all points during the process, and ESPECIALLY just before the order is created.  we can NOT create orders if the store owner has his store configured to not accept orders if there is not enough inventory.  i am a big fan of single page checkout, so there would really only be 2 times when inventory is checked - 1.) when added to the cart, and 2.) just before order creation.  and if not enough inventory, then we need to redirect back to the shopping cart.  however, if we are not in the single page checkout, the 2 aforementioned spots are still the minimum places to check inventory.

in addition, i am still of the opinion that html should NOT be in any of these functions.  leave the html for the templates and nowhere else.

best.
