### ISSUE TITLE
Products Attributes Image length

### ISSUE THREAD

**Issue by bislewl** [zencart/zencart#1564]
I just ran into an issue where the product attribute image wouldn't load and it was coming back to a 404 because the image wasn't present. Upon looking at it, it appears that it was looking for something like: "attributes/revenge_of_the_nerds_2-greek_clubs-lambda_lambda_lambda.j" of course I noticed it was missing the "peg" or "pg" from the end. Which drilled down to be that, the products_attributes.attributes_image had the same value and was limited to 68.  However I'm wondering if there was something we can do? Perhaps there should be some sort of check during the upload that would either a) Fail/Reject the upload and or b) rename and notify of such change?  The other solution of course be to increase the size of the products_attributes.attributes_image field beyond the current 68, but then how long should it be?

**TEMPORARY WORK AROUND:**
For this install as a quick work around I increased the size of the field. However that isn't a current perfect solution as someone could always upload something with a super long long name and it would still show a 404 to the end customer, however it would show a good upload in the admin.
  
##  ##
  
*NOTE: The filename has been been changed to protect the innocent*

**Comment by drbyte** [comment]
In fact, newer MySQL versions by default enforce a stricter rule which would have thrown a SQL fatal error when trying to insert that value because it was too long for the column definition.

Yes the first workaround is to increase the column length ... which is necessary if the customer wants to actually use such long filenames. 

I agree that it would be better to fail more gracefully than to leave corrupted data in the field.
