### ISSUE TITLE
ATTRIBUTES_PRICE_FACTOR_FROM_SPECIAL is not defined

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1566]
https://github.com/zencart/zencart/blob/250431248409287aee66b30fe46510a11f4a7fe4/admin/includes/functions/functions_prices.php#L944-L955

the above code is throwing warnings in php 7.2, which made me aware that this define (ATTRIBUTES_PRICE_FACTOR_FROM_SPECIAL) is not set on the admin side.
below is one of the warings
```
[18-Dec-2017 08:46:43 Europe/Amsterdam] PHP Warning:  Use of undefined constant ATTRIBUTES_PRICE_FACTOR_FROM_SPECIAL - assumed 'ATTRIBUTES_PRICE_FACTOR_FROM_SPECIAL' (this will throw an Error in a future version of PHP) in /xxxxxxxxxx/public_html/admin/includes/functions/functions_prices.php on line 946
[18-Dec-2017 08:46:43 Europe/Amsterdam] Request URI: /admin/attributes_controller.php?products_filter=1&current_category_id=4
#1  zen_get_attributes_price_factor() called at [/xxxxxxxxxx/public_html/admin/includes/functions/functions_prices.php:1053]
#2  zen_get_attributes_price_final_onetime() called at [/xxxxxxxxxx/public_html/admin/attributes_controller.php:1553]
```

**Comment by mc12345678** [comment]
I already have something lined up to address this in what will/would be #1404. It doesn't actually define it per se, but will prevent the generation of notice errors. 

By adding `defined('ATTRIBUTES_PRICE_FACTOR_FROM_SPECIAL') && ` to the beginning of the if, when it is not defined then the code will quietly move on to the else portion of the code. Thus far the definition has been otherwise supplied obscurely in the shopping_cart class, but even then only partially last time I looked, though had proposed it be more universally applied in one of the versions.

**Comment by drbyte** [comment]
Thanks. 
Fix included in PR https://github.com/zencart/zencart/pull/1571
