### ISSUE TITLE
Date input fields

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1587]
Do we still need to rely upon a "fancy" JavaScript, or is it okay to use the html 5 "date" and "datetime-local" types, for an input field?

**Comment by drbyte** [comment]
I'm assuming you're talking about SpiffyCal ... vs the jQueryUI-datepicker ... vs just marking the field as 'date' or 'time' or 'datetime-local'? Specifically in the Admin.

It would be helpful if it could be just an HTML tag, since that also helps ensure the date or time value is transmitted in a standard format. 

I'm surprised that support for it seems to still be weak: https://caniuse.com/#feat=input-datetime

Must also consider that we expect date-only in some fields, date+time in others.

**Comment by Zen4All** [comment]
Yes that was my point 😉 . 
After reading the page you linked to, I think it is best to use the jQueryUI-datepicker for now. since that gives better support for date+time fields.
