### ISSUE TITLE
Illegal access on whos_online

### ISSUE THREAD

**Issue by drillsar** [zencart/zencart#1611]
Getting Illegal access when I click

If you click any of the boxes example Exclude Spiders No

you get Illegal access. Not sure if its a permission issue or what

**Comment by drbyte** [comment]
Same feedback as I posted in your other issue: #1612 

I'm trying to understand why this is posted on github instead of in the Support Forum.

Is this an issue with the code?
If so, which version are you reporting this code problem against?

"Not working" isn't a problem description. It is a symptom. And hundreds of thousands of sites are using the officially released versions of Zen Cart without these symptoms.
So that suggests your issue is either with un-released development code, or it is unique to your own site.

If it's unique to your site, then you should be posting the issue on the Support Forum, where you've already posted other site-related and plugin-related issues you've had.

If it's with unreleased code, and only exists in the unreleased code, then please begin by providing the details of which version you're using, and how you've arrived at these symptoms.

**Comment by drillsar** [comment]
V160 is for sure an issue; when you click on anything like Exclude Spiders it says:

Illegal access. It works for V155

**Comment by proseLA** [comment]
ok.  i can confirm this behavior on v160.

lines 125 and 126 of whos_online.php look to be incorrect.  they should be something like:

`  $optURL = 'index.php?cmd=' . FILENAME_WHOS_ONLINE . '&' . zen_get_all_get_params(array('t', 'na', 'ns'));
  $listingURL = 'index.php?cmd=' . FILENAME_WHOS_ONLINE . '&' . zen_get_all_get_params(array('q', 't', 'na', 'ns'));`

lmk and i can do a PR on it.
