### ISSUE TITLE
Shipping Estimator

### ISSUE THREAD

**Issue by drillsar** [zencart/zencart#1612]
Not working, when you click on it it does nothing

**Comment by drillsar** [comment]
I think issue is that if your in SSL.

The link is http and should be https

zen_href_link?

**Comment by drillsar** [comment]
I am going to try this code:
zen_href_link(FILENAME_POPUP_SHIPPING_ESTIMATOR, '', 'SSL') .

**Comment by drbyte** [comment]
I'm trying to understand why this is posted on github instead of in the Support Forum.

Is this an issue with the code? 
If so, which version are you reporting this code problem against?

"Not working" isn't a problem description. It is a symptom. And hundreds of thousands of sites are using the officially released versions of Zen Cart without these symptoms.  
So that suggests your issue is either with un-released development code, or it is unique to your own site. 

If it's unique to your site, then you should be posting the issue on the Support Forum, where you've already posted other site-related and plugin-related issues you've had. 

If it's with unreleased code, and only exists in the unreleased code, then please begin by providing the details of which version you're using, and how you've arrived at these symptoms.

**Comment by drillsar** [comment]
I tried it with V160 and it works with V155. When you click on Shipping Estimator it does nothing. 

In V160 I noticed it says http instead of https.

**Comment by scottcwilson** [comment]
This issue should be closed.  The link is working fine in a fresh install.
