### ISSUE TITLE
PayPal supports INR. Lets not convert INR to USD

### ISSUE THREAD

**Issue by pons1991** [zencart/zencart#1668]
Hello Zen's, 

I am Sundar from PayPal and I am here with a requirement and half way through the solution. Actually, PayPal India going to start in a month and we are getting some integrations with zencart. 

zencart is converting the INR amount to USD when sending to PayPal. We dont need to convert the currency anymore to make the Payment. 
Please create an issue and lets start the work. I will add my code changes in a day. 

Thanks.

**Comment by drbyte** [comment]
INR is only being converted because it's a new currency to PayPal, which wasn't previously supported, and therefore not listed in the module.

You can add it to the list and if the storeowner configures it to accept INR then it won't convert it:
https://github.com/zencart/zencart/blob/develop/includes/modules/payment/paypalwpp.php#L1185
and
https://github.com/zencart/zencart/blob/develop/includes/modules/payment/paypalwpp.php#L694

Repeat for `paypal.php` and `paypalwpp.php`

**Comment by pons1991** [comment]
Can we make the above changes in the module itself? So that our merchants will not find it hard to solve this issue. Atleast new zencart installations will work without any problem. please.

**Comment by drbyte** [comment]
Hi @pons1991 can you provide documentation link indicating which PayPal products support the INR currency?  Particularly, is it just for Standard and Express Checkout? Or also for Payments Pro?

**Comment by pons1991** [comment]
I am not able to find the documentation specifically. But I can share you the home page of PayPal india. https://www.paypal.com/in/home

Also, We are supporting INR only in **Standard and Express checkout Payments** not in Payments Pro.

**Comment by drbyte** [comment]
Closed via PR #1769
