### ISSUE TITLE
Provide the option of not going to 404 when product status is 0

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1699]
Right now, due to checks in includes/modules/pages/product_info/header_php.php  and includes/modules/pages/product_info/main_template_vars.php, products which are in the catalog but have status = 0 return a 404. 

Should we (optionally) show the product info page with the add to cart button grayed out instead?  This way vendors could show back in stock notification, related items, etc.

**Comment by drbyte** [comment]
What about items that are discontinued or otherwise permanently out of stock?

The 404 is intended to tell Search Engines that the page should be de-listed.

**Comment by scottcwilson** [comment]
Part of this would also be adding a new field "Treat out of stock as Permanent (1=default) Temporary (0)."

**Comment by torvista** [comment]
To not answer the question, I have had to add these options to my products:

1) auto hide the add to cart/stock info when not in stock: to stop people buying rarely-ordered items.
2) manually hide the add to cart/stock info: when its an informational (not physical) product, or it's a carrot I want people to enquire about (back-in-stock notifications).

Status = 0 means to me a product is dead/never-to-be available again so a 404 is valid.

My thinking is that an out of stock product should not be removed from display, but just optionally not available for purchase.

**Comment by proseLA** [comment]
for my clients, i do a 404, but rather than providing the generic 404 page, i provide a page that says:
'Sorry, Product A is no longer in stock."
while i like the idea of a flag to indicate temporary v permanent, i look at the number of switches that currently exist in ZC and wonder if it's getting to be too much.  everything is configurable to the point that store owners have no idea what is configurable and where to set it.  frankly the developers tool searching is a great page, and perhaps we need to feature it more as a way for store owners to search for settings....
sorry for the thread drift....

**Comment by torvista** [comment]
>  wonder if it's getting to be too much. everything is configurable to the point that store owners have no idea what is configurable and where to set it. 

I think there is no doubt the whole configuration settings needs a fresh look/reorganisation. I've just proposed this:
https://www.zen-cart.com/showthread.php?224054-Admin-configuration-settings-search-box-in-the-Admin-navigation-bar&p=1346312#post1346312

But that should not be a bar to adding more functionality. Every time I upgrade and have to carry forward a mod, it's time and effort wasted and it is almost impossible that a mod is only useful to one person, so include the kitchen sink I say!

**Comment by proseLA** [comment]
torvista, i'm just not sure these are worthy goals, nor measurable.  getting people to upgrade from 1.38 is not a worthy goal....  and we already run the risk of being "bloatware".  my opinion remains that providing a single method of includes for both admin and customer facing, better override system for mods, and more modern templates are more measurable and would make people's lives much easier.

back on point, i agree that each product should have the ability to throw a 404 for permanent out-of-stock, or not for temporary out-of-stock.  and these links should not go to a generic 404 page.  in addition, we should be able to allow store owners to decide whether a customer can buy a temp out-of-stock item or not.

**Comment by scottcwilson** [comment]
Guys, let's please stick to the question raised by this issue.

**Comment by dakanji** [comment]
> The 404 is intended to tell Search Engines that the page should be de-listed.

Should that return a page similar to  @proseLA 's 'Sorry, Product A is no longer in stock." but with a "410 Gone" code instead ... if the aim is to get search engines to delist such?

**Comment by scottcwilson** [comment]
The product may just be *temporarily* out of stock though.  Which is why I wanted to add this flag.

**Comment by dakanji** [comment]
Flag is not a bad idea although I note the issue raised about there being a multitude of options. However a lot of options are not necessarily a bad thing when there are defaults in place so that users that don't want to delve into such do not have to.

So in this case, a good default would be the "temporary" option which would return a 404 status and the "permanent" one could return the info page with a 410 status.

**Comment by proseLA** [comment]
why not add another acceptable status value(s) to the existing status field?  i think that could solve a number of things.  in addition, how and what page ZC shows should be handled by the template while the http code should come back from the core.  for example, i see 4 possible stock situations:

status | situation | http response
---------|-------------|-----------------
In-Stock | OK to order | 200
Out-of-Stock | OK to order | 200
Out-of-Stock | Can not order; but coming back into stock | ??
Out-of-Stock | Permanently Gone | 410

i'm not sure about the 3rd situation and providing search engines with a 404.  while a customer can not order for the time being, i'm not sure we want to tell search engines that the resources is gone; temporary or not.  i see no problem with a 200 and a greyed out ability to order. In fact, i suppose I/we are providing 404 status codes in situations that really require a 410.

from here:
http://www.digitalthirdcoast.net/blog/difference-404-410

"...The page you wanted to view is no longer there, so you shouldn’t have been able to get to that non-existent page in the first place. Rule of thumb: 404s are bad. You don't want your site returning 404s...."

i learn something new every day....

**Comment by dakanji** [comment]
Your third option would also be a 200.

**Comment by drbyte** [comment]
So, how do you propose tracking each of these 4 product states?

**Comment by scottcwilson** [comment]
The 4 states that @proseLA enumerated would be good if we didn't already have STOCK_ALLOW_CHECKOUT.  Since we do, I think we really only need to support 3 and 4 in addition to 1. 

As the OP, I would suggest the following baby step forward: 
- add a flag called (something like) restockable, default true. 

If out of stock and restockable, show the product info page (HTTP 200).  If STOCK_ALLOW_CHECKOUT, show the add to cart button on the page; otherwise, show a warning in its place.

if out of stock and not restockable, return a 410. 

I quite agree that returning 404s is not something the cart should do by design.

**Comment by drbyte** [comment]
A binary flag probably suits. Then the shop just has to know how to combine the various flags when it needs to make decisions. 

This brings up two more factors to consider/decide-upon:

1. Apart from a 410-vs-404-vs-200 header status, what else in the catalog or admin might need to take special action if the item is "restockable" vs "not"?
(ie: so far we've only discussed the combination of `products_status` and `STOCK_ALLOW_CHECKOUT`)

2. Nomenclature.
a. Particularly from an Admin UI perspective, what should the binary choice be displayed as?  Keeping in mind that "not restockable" could be because it was one-of-a-kind, or is discontinued/end-of-line/end-of-life. 
 b. Any special treatment for virtual items? 
 c. Any different treatment for various/other product-types?

**Comment by drbyte** [comment]
If the schema changes are straightforward (ie: merely adding another flag), doing this for v156 is a potential possibility.

However, we should enumerate other side-effects and consider the other questions I posed above before final code is decided upon.

**Comment by scottcwilson** [comment]
Suggest removing the v156 milestone from this issue due to complexity.

**Comment by zcwilt** [comment]
Do we have a consensus here. If not then we should remove the milestone.

**Comment by drbyte** [comment]
I think it should be included, despite some details still needing to be decided upon.

**Comment by drbyte** [comment]
In v2 there's a product-availability flag.

Perhaps this issue is resolvable by just ensuring we're sending the proper response headers under the right conditions.

**Comment by proseLA** [comment]
please please please....  no more config flags!

at some point, i would like to go through all of them and see which ones are superfluous and can be safely eliminated.  troubleshooting with the multitude of config flags in ZC gets frustrating.  you think you have solved a problem, it does not work, and its due to a config flag set incorrectly.  all of the overrides make my head spin...  rant over.

**Comment by zcwilt** [comment]
Just a note here. As @drbyte said. There can be a fine line to be had in adding new settings. One of the reasons that I think people fight against new defines is the way config settings are handled. The current system is unwieldy and hides settings behind a bloated interface, which just gets more obscure as time has gone by. 

On of the original goals of v2 was to move a lot of settings closer to the menu entries they are applicable to. For example the GV Coupons settings being directly accessible from the Gv/Coupon admin pages. 

The current system is also difficult in that while there is some grouping of config settings, that grouping is not always very logical. e.g the My Store settings is a bit of a mish mash. Again pulling out some of those settings( say the tax settings) to a more logical place in the admin would help.

Part of #1007 infrastructure is to allow config settings to be defined in an easier way, and for them to be editable as a group, rather than singly as we do now with config settings. 

Now I'm not proposing this be done as part of releasing an MVP for v2.0, we can add this iteratively once we do have a stable release candidate.

**Comment by scottcwilson** [comment]
Should we close this out as a v2 item or do something (even if MVP) for 1.5.7 ?
