### ISSUE TITLE
Calling trigger_error in plugin_version_check_for_updates seems wrong

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1718]
I'd like to remove these calls.  Debug logs should only be produced if there's a serious problem with the site.

**Comment by drbyte** [comment]
But ... it IS only called if there's a problem getting a response.

https://github.com/zencart/zencart/blob/d8af28605269f2428be0df4bd0aff75fa1f71aff/includes/functions/plugin_support.php#L39-L43

**Comment by scottcwilson** [comment]
Agreed - but it's called once for each active user, for the duration of the outage.  So you get a lot of logs for a situation that you can't fix, that's ultimately not that important.  Even one log is really too much in my opinion; you can make it a warning in the admin.

**Comment by drbyte** [comment]
I guess there's 2 ways to look at this:

1 - you, the one bothered by the presence of any debug-log files, would prefer not to have the log files

2 - the storeowner, who doesn't need to know there's a problem in-real-time, since there's nothing they can do about it in-real-time, would prefer not to see admin messages, but would like their technical team to have access to failure logs in case there are any recurring internal technical issues

**Comment by scottcwilson** [comment]
Better - but I'd much rather it was a database field so that multiple users wouldn't drop multiple logs.

**Comment by drbyte** [comment]
Fair. 
Who's going to maintain the additional code?

**Comment by drbyte** [comment]
Question to everyone reading: how critical is this matter? 

Does it warrant adding all the additional db-and-code infrastructure required to support tracking every plugin, just to record its last-failure-to-check date?
Does it warrant the sudden surge of new-feature-development-requests that is likely to come if plugins are all enumerated with this much granularity?

**Comment by scottcwilson** [comment]
What if we just made "create a debug log" optional?

**Comment by lat9** [comment]
How about if the error is only issued once per admin session?  That would keep the number of logs down while not over-complicating the solution.

**Comment by proseLA** [comment]
this is an interesting issue.  i am a fan of logs, but i'm not the big fan of automatically checking for updated versions of plugins.  so i would have to agree with scott...  it is up to the tech team of the store  to look for updated versions of plugins...  and i am WHOLLY against building any additional infrastructure to support this.

i am not a fan of the ZC team making a decision with regards to what constitutes a "serious problem with the site."  i always thought that the error logs were in essence capturing the apache error log messages and writing it to a file.  granted that may be a bit simplistic, but i hate digging into code to find out that the developers made a decision inconsistent with what apache deems an error and not writing that to a file.

**Comment by barco57** [comment]
@proseLA This issue is about a specific failure of communication between the site and the Zen Cart server, which in my experience rarely happens. You dislike that the cart checks for new versions of plugins at all, which to me seems to be saying "I don't like it when the cart tells my clients there are updates to modules, that probably still work fine in their current version for the time being, and the client perceives as a problem that needs to be fixed now, in conflict with your schedule and billing policy for doing updates"

I think what you would rather have is a define entry in the configure.php that would turn off plugin checks globally that is an optional developer entry that could be added and warrants its own github issue if you feal that strongly about it.
`define('PLUGIN_UPDATE_CHECKS', 'false');`

My experience is that apache level errors are not captured and written to a Zen Cart myDEBUG by the cart. The myDEBUG logs are for PHP warnings/errors.

**Comment by proseLA** [comment]
@barco57 mighty big assumptions you seem to be making there.  not really sure what point you are making.  i think it might be better to stay on topic as opposed to discerning what my intentions might be.

@drbyte posed a question.  i gave a response.  frankly, i and my clients never see a plugin update message because the plugins in use are either up-to-date or don't do the check to start off with.  which seems to be the case more often than not.

as the default for php is to write errors to the same log file that apache uses, excuse if i accidentally used apache when i meant php.

**Comment by lat9** [comment]
We already have `Configuration->My Store->Show if version update is available`.  Why not have a global admin setting for plugins as well?  They're all using that built-in Zen Cart function for the checks, aren't they?

FWIW, I hate those plugin version update checks.  When I'm running off-line (I know I could use an `extra_configure` file to disable), they drive me crazy since each and every update-check has to time out before the page I'm interested in is rendered.

**Comment by barco57** [comment]
@proseLA Sorry, I was probably projecting my experience as someone who babysits a thousand Zen Carts a day. When the USPS module updates some percentage of hosting clients contact us because they noticed the warning about the update on the shipping module page, rather than their developer, to update the module because they believe we will do it for free/cheap but their developer will charge them the hourly rate. So I get a pile of requests when a module reports that there is an update.

@lat9 I completely forgot timeout when communication fails or offline developing. I have only rarely run into that issue as I rarely do offline development having so many servers available to me to do the development on.

**Comment by drbyte** [comment]
I've been working on a PR to address these concerns. I hope to submit it soon.

**Comment by drbyte** [comment]
Closed via #1762
