### ISSUE TITLE
v1.5.5f - Stored XSS

### ISSUE THREAD

**Issue by honcbb** [zencart/zencart#1775]
I found in the background administrator, and then (new) products, the title and content are not escaped filtering encoding processing, resulting in the insertion of JS syntax to create storage-type XSS

Admin New Category - Stored XSS

List：

http://127.0.0.1/hUrry-YAo-stUff/index.php?cmd=categories&cPath=&action=new_category

http://127.0.0.1/hUrry-YAo-stUff/index.php?cmd=categories

Poc Payload：

"><svg/onload=alert(domain)>"

Test Images：

![default](https://user-images.githubusercontent.com/20026264/45736096-92a20d00-bc1c-11e8-97f1-03cef8c160d7.PNG)

![1](https://user-images.githubusercontent.com/20026264/45736097-92a20d00-bc1c-11e8-9ddf-913a1ce55754.PNG)

![2](https://user-images.githubusercontent.com/20026264/45736098-933aa380-bc1c-11e8-9a76-e91e99a0c549.PNG)

I found out after you output, direct  "Echo" is not processed causing XSS to trigger：

![3](https://user-images.githubusercontent.com/20026264/45736153-b6655300-bc1c-11e8-8861-e566f6c68b00.PNG)

![4](https://user-images.githubusercontent.com/20026264/45736154-b6655300-bc1c-11e8-8269-2569dfe0b6a8.PNG)

**Comment by zcwilt** [comment]
Hi thanks for the report.

Just a bit of history.

Zen Cart has always allowed the use of html in certain admin fields, most notably product names/descriptions.

The very fact that we allow this does of course allow for reflected xss, as any html/js will be displayed in catalog code.

This issue came up when Zen Cart code was audited by a Qualified Security Assessor as part of our PA-DSS certification.

The QSA allowed that there were specific use cases where fields may allow html in the input.

The QSA agreed that there were specific mitigations for this.

1. Admin access must be granted to an admin user before they can update these fields

2. CSRF protection and the introduction of Admin Sanitizer code (required by QSA) meant there is no vector for an unauthorized user to exploit this.

3. The QSA required specific logging in admin to show when entries to these fields were flagged.

As such, and at the moment, it's not something we feel needs addressing.

**Comment by honcbb** [comment]
Hey, zcwit

Okay, thanks for the reply.

Thanks

**Comment by zcwilt** [comment]
No problem, and thanks  anyway for posting. We always appreciate security related posts.
