### ISSUE TITLE
Proposed: remove the filter for EZ page display

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1823]
Sometimes I want to create some EZ page content just for display in a specific page (the product info page, for example), and don't want it in the header, footer or sidebox. But the current system doesn't allow me to do this - a check in `includes/modules/pages/page/header_php.php` on line 30 will stop it.  Now I know you can comment out the check, but I think this ought to be the default. Thoughts?

**Comment by drbyte** [comment]
It's one of those things I see affecting people 50/50. 
Some sites use it extensively; some don't.

But maybe since v156 is changing the schema (to support Multilingual EZPages), maybe now is the right time to add a `visible` flag, and modify the query to accommodate the two statuses, and split the response:

visible = 'Y' = normal display
visible = 'N' = 503/unavailable
deleted/not-in-db = 404/notfound

**Comment by scottcwilson** [comment]
Seems like a reasonable compromise.  I am working on a PR.

**Comment by drbyte** [comment]
k

**Comment by drbyte** [comment]
PR welcome for v156

**Comment by scottcwilson** [comment]
This is ready to go as soon as #1860 is merged (because that file will need to be changed too).

**Comment by scottcwilson** [comment]
This ticket should be closed; it was resolved by merged PR #1861.
