### ISSUE TITLE
v2: Template needed for 2.0 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1918]
Let's figure out the plan for getting this up to date.

**Comment by Zen4All** [comment]
My vote would go to the new bootstrap template from @zcadditions

**Comment by scottcwilson** [comment]
@Zen4All Thanks for your suggestion.  Is there a demo we can look at?

**Comment by Zen4All** [comment]
it's in the Zen Cart download area, and here https://github.com/zcadditions/ZCA-Bootstrap-Template

**Comment by barco57** [comment]
I second that recommendation

**Comment by wiztechinc** [comment]
Considering the fact that a responsive template that passes google inspection only requires a bit of php code and some CSS changes, as I have always said, bootstrap templates are bloated and unnecessary.  Oh, not to mention hard to alter. Back to my usual complaint and one reason why i've become disenchanted with zen cart when I used to be a HUGE supporter and promoter.

**Comment by zcadditions** [comment]
Just a "why" I choose bootstrap, if you dig into earlier forum posts, I too was against any 3rd party frameworks for the exact same reason but my person feeling had to be set aside for better design and development.

https://www.ostraining.com/blog/webdesign/bootstrap-popular/

> But I think it's clear that Bootstrap remains the most popular design framework on the web today. It's been that way for several years now and it really has no close competitors:
> 
>     18% of all websites.
>     Between 52% and 72% market share amongst frameworks.
>     The most popular code repo in Github.
>     Used on all Joomla sites.
>     Used on 20% of Drupal 8 sites.

**Comment by Zen4All** [comment]
:laughing: I always thought I was the only person not understanding why I needed bootstrap or another frame,but once you get used to it, like getting used to Zen Cart, it is real simple to use.

**Comment by drbyte** [comment]
> Considering the fact that a responsive template that passes google inspection only requires a bit of php code and some CSS changes, as I have always said, bootstrap templates are bloated and unnecessary. Oh, not to mention hard to alter. Back to my usual complaint and one reason why i've become disenchanted with zen cart when I used to be a HUGE supporter and promoter.

Delia, your comment has me baffled, because Zen Cart's built-in front-end templates have never (yet) had Bootstrap in them.

**Comment by drbyte** [comment]
... then I'm doubly puzzled by your "disenchanted" comment.

**Comment by mesnitu** [comment]
Well, zencart choose bootstrap, (I actually would / do prefer foundation), and I use foundation because it was back then very modular, so no need to load tons of css and js, when actually you just use 20% if such. If you need it, you load it to a page. But bootstrap 4 now supports sass, and (I guess from the documentation), and more or less follows the foundation way.
Apart from what template to use ( not sure if you're talking admin / front-store template or both) I really think, that in both, **would be a good idea to move to bootstrap 4, and use grunt to generate the css needed using zencart defined classes, and not bootstrap classes.** 
Right now, I'm following the admin template, placing col-md-x col-sm-x allover the place, and one day they change the grid system, and more work to do.

So in sum: Template Zencart + Bootstrap Not Bootstrap + Zencart

**Comment by drbyte** [comment]
I think maybe this will suit as the default bootstrap theme: https://kristopolous.github.io/BOOTSTRA.386/

:D
