### ISSUE TITLE
Should additional parameters for htmlspecialchars be included in admin sanitizer?

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#2064]
https://github.com/zencart/zencart/blob/f9752c8f01d031756c0bb31de0c43a35ef716531/admin/includes/classes/AdminRequestSanitizer.php#L782

Was looking over the strict sanitizer values code to support identification of what characters are sanitized and noticed that at the above file location, `htmlspecialchars($string)` is used "alone" and without the added parameters seen throughout much of the catalog side where it typically is used as: `htmlspecialchars($string, ENT_COMPAT, CHARSET, TRUE)`.  Was wondering if that should be updated?

The php manual identifies that in absence of providing the above parameters, that effectively for ZC 1.5.6 having a published lower band PHP of 5.6 that the same is executed, although the CHARSET defaults to UTF-8 regardless of the characterset setting for the site (i.e. still using ISO-8859-1 or other).

Meanwhile at: https://github.com/zencart/zencart/blob/f9752c8f01d031756c0bb31de0c43a35ef716531/admin/includes/classes/AdminRequestSanitizer.php#L456 the encoding is forced to `'utf-8'` and at: https://github.com/zencart/zencart/blob/f9752c8f01d031756c0bb31de0c43a35ef716531/admin/includes/classes/AdminRequestSanitizer.php#L491 there also is no additional parameters for function `filterSanitizeEmailAudience` which supposedly again would default to `'UTF-8'`.

**Comment by drbyte** [comment]
I think it's safe, and relevant, to specify the `CHARSET` for all instances.
So, for consistency, we should pass all 4 parameters.
Save for the case here where `false` is passed for the 4th param (double-encoding) (which we should keep), like we do catalog-side: `, ENT_COMPAT, CHARSET, true (or false where needed)`.

Also note: while at one point we used uppercase for TRUE, FALSE, NULL, since we're now embracing PSR2 we're using lowercase for these keywords when touching code which uses them.
