### ISSUE TITLE
jAlert vertical-align issue on timing out

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#2083]
perhaps someone who is a bit better with this jAlert library can figure this out.... 

lets say you are at the server_info.php page and you get logged out. the little jAlert popup comes up, but the top margin on the pop-up requires you to scroll all the way to the bottom to see it.  which on this page can be quite far.  it should be in the middle of the screen.

i have played around for far too long for something that seems to be reasonably simple.

**Comment by mc12345678** [comment]
I noticed this as an issue with my mobile device where the popup window had to be located somewhere along the length of the screen.

My look at this identified that `$(window).height()` and `$(document).height()` are providing the same result which is as described the height of the content in the window.

In admin/includes/javascript/jAlert.min.js changed 
````javascript
var viewportHeight=$(window).height()
````
changing to this worked to keep the window positioned in the middle from top to bottom even when zooming in/out.
````javascript
var viewportHeight=window.innerHeight
````
Although I had also seen this as potential solution where any of three values were possible to be returned with the first existing result being the one that actually got sent when viewing the watch expressions.  The thing was that the first and third reported the same smaller height, the second reported the same as what has been seen. so it seems that if the first doesn't work, but the second and third do work as presented in this order then the floating window would again appear at the bottom of the screen. 
````javascript
var viewportHeight=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight
````
The suggestion based on that information would instead be to have it in this sequence:
````javascript
var viewportHeight=window.innerHeight||document.body.clientHeight||document.documentElement.clientHeight
````

One good thing about the use of a set vertical location though is that one can scroll, zoom, or whatever and the window will remain stationary. If the window is sized *just* too big, then there is the possibility that one may not be able to reach the button because the image is moved to keep the button just out-of-reach.  Would suggest more testing.

**Comment by drbyte** [comment]
Agreed, this seems surprisingly more difficult than it ought to be.

**Comment by drbyte** [comment]
I can't seem to replicate this problem anymore.
Perhaps the updated jAlert has already addressed this.

Can you re-test?

(I've also pushed a commit to update the size of the text and buttons, making usability better.)

**Comment by proseLA** [comment]
i agree.  my test seems to suggest that the jAlert popup now comes up in the middle of the viewport as opposed to the middle of the page.

i tested on a desktop as well as simulated version of a mobile device.  do you need me to close?

**Comment by drbyte** [comment]
Great - thanks for confirming.
