### ISSUE TITLE
build un-customized meta tag notifier

### ISSUE THREAD

**Issue by mesnitu** [zencart/zencart#2167]
There are some notifiers in metatags module file, but for this section there are none. 
Example: With a book product type, I need ( want )  to add isbn, or author, or that the product has free shipping or whatever. 
THe only way is to copy the file to the modules template folder. 
Perhaps this is the best solution, but it's another file to maintain.
I do have a site using a observer, and I don't see much performance downsides using it.  

so before
```
define('META_TAG_TITLE', str_replace('"','',$review_on . $meta_products_name . $meta_products_price . PRIMARY_SECTION . TITLE . TAGLINE));
      define('META_TAG_DESCRIPTION', str_replace('"','',TITLE . ' ' . $meta_products_name . SECONDARY_SECTION . $meta_products_description . ' '));
      define('META_TAG_KEYWORDS', str_replace('"','',$meta_products_name . METATAGS_DIVIDER . KEYWORDS));
```
a notifier would be quite helpful.

**Comment by mc12345678** [comment]
Ummm... perhaps the notifiers that are present just aren't being used to their fullest potential?

If you know you want to define `META_TAG_TITLE`, `META_TAG_DESCRIPTION`, and/or `META_TAG_KEYWORDS` based on some sort of known condition/situation, it seems to me that you could observe the provided notifiers, modify the variables that are in the global space as necessary to either prevent execution of one or more sub-areas of code or for that matter to cause it to be executed and then after whatever portion of code is to be executed to use an observer again to ensure the desired data is available for continued operation... 

I guess I'm just not seeing what the additional notifier accomplishes that can not already be done with what is present. I'd be interested to see what issue is not able to be overcome with the code as provided. There's even a notifier area available for pages that are not otherwise defined for `$metatag_page_name`.

What is it that I'm missing?

**Comment by mesnitu** [comment]
Hi
Well, I've tried some options. Maybe I'm doing this in the wrong way. 
Again, this is a file that can be overridden, so one could actually skip all this stuff and make the necessary changes. And I guess that's the best option. 
However, it might (or not) conflict with other modules. My only concern is that I updating a module, so, less files = sounds great. For personal use, I've using this for a while. 
For other product types, Zencart offers some notifiers but for some reason, skips others. 
There are 5 notifiers in that file. 
I was using the `$zco_notifier->notify('NOTIFY_MODULE_META_TAGS_BUILDKEYWORDS' `to build the keywords, but now, it seems keywords are a thing of the past, i've actually drop them. 

`$zco_notifier->notify('NOTIFY_MODULE_META_TAGS_UNSPECIFIEDPAGE'` -> using it for filter pages ( bookx module) 

Then there's this one : $zco_notifier->notify('NOTIFY_MODULE_META_TAGS_OVERRIDE', 
I guess this is the one that you are referring to. However, I've not accomplish much with this one. 

The way I see it : 
``` php
case (strstr($_GET['main_page'], 'product_') or strstr($_GET['main_page'], 'document_')):
if ($product_info_metatags->EOF) {
    $meta_tags_over_ride = true;
  } else {
    // custom meta tags per product
if (!empty($product_info_metatags->fields['metatags_keywords']) or !empty($product_info_metatags->fields['metatags_description'])) {
// there are metatags defined in the admin 
} else {
// build un-customized meta tag
// I need to be here
}
}
break;
```
And even I add a notifier, there are constants defined after, like TITLE and TAGLINE
``` php
define('META_TAG_DESCRIPTION', str_replace('"','',TITLE . ' ' . $meta_products_name . SECONDARY_SECTION . $meta_products_description . ' '));
```

**Comment by scottcwilson** [comment]
Closing issue due to lack of interest and activity.
