### ISSUE TITLE
Upgrade problem when default language files are missing

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2228]
Install ZC156a.
Import existing production database (english/spanish, spanish set as default) via phpMyAdmin.
Change no files at all.
Run zcinstall, no errors.

Catalog: shows items with no template applied, so there is database access.

Admin: white screen. No debugs.

Even setting strict and display errors on screen, nothing shows up.

I eventually traced the failure to the final line in this:

ADMINFOLDER/includes/init_includes/init_languages.php

```
  if (is_file(DIR_WS_LANGUAGES . $_SESSION['language'] . '/' . $current_page)) {
    include(DIR_WS_LANGUAGES . $_SESSION['language'] . '/' . $current_page);
  }
  if ($za_dir = @dir(DIR_WS_LANGUAGES . $_SESSION['language'] . '/extra_definitions')) {
    while ($zv_file = $za_dir->read()) {
      if (preg_match('~^[^\._].*\.php$~i', $zv_file) > 0) {
        require(DIR_WS_LANGUAGES . $_SESSION['language'] . '/extra_definitions/' . $zv_file);
      }
    }
    $za_dir->close();
  }
  require(DIR_WS_LANGUAGES . $_SESSION['language'] . '.php');
```

My database has a default language of spanish so I assume in the absence of $_SESSION['language'], it tries to use that. But there are no files yet.
Once I put ?language=en on the url, it worked subsequently.
Putting ?language=es on the url breaks it again.

I note that on a vanilla ZC156a (db) install, there is no problem.
Importing the same db with english set as default works ok.

I can supply a barebones copy of my db for testing if required. 

Why no debug log?

**Comment by mc12345678** [comment]
The assignment for `$_SESSION['language']` does not review the existence of files, though does use the database for determination of if the language selected/chosen is acceptable.  

The error that occurs in `admin/includes/init_includes/init_languages.php` essentially occurs in the autoloader scripts.  As identified in `admin/includes/application_top.php`, `DEBUG_AUTOLOAD` needs to be set to boolean `true` in order to identify the output provided by the associated script (otherwise a "blank screen" occurs).  This appears to be why a myDebug file is not generated when the `require` of the last line fails to load/find the file.

**Comment by torvista** [comment]
I get the DEBUG_AUTOLOAD needs to be set to see what is being processed, I needed that to pinpoint the issue.
But I don't get why no php error was flagged, since it was a require.

And so, should not a check for files existing be added there, falling back to english on a fail?

**Comment by mc12345678** [comment]
> But I don't get why no php error was flagged, since it was a require.

I believe at one point, I had figured out why errors in the autoloader scripts didn't get logged; however, I am drawing a blank at the moment and haven't found anything that directly explains why the absence of error logs during that process.  I'm thinking it has something to do with the error occurring within the foreach loop(s), though I thought I have seen errors generated when in testing code I have made a mistake within a for or foreach loop. 

> And so, should not a check for files existing be added there, falling back to english on a fail?

That may be one solution to the upgrade of a database without having installed all associated software before attempting to access and without testing on a default installation.  I depending on "acceptance" I would think that the file check might be better served at the point of setting `$_SESSION['language']` and the other associated `$_SESSION` data as in:
1)
````php
// set the language
  if (!isset($_SESSION['language']) || isset($_GET['language'])) {

    include(DIR_WS_CLASSES . 'language.php');
    $lng = new language();

    if (isset($_GET['language']) && zen_not_null($_GET['language'])) {
      $lng->set_language($_GET['language']);
      $zco_notifier->notify('NOTIFY_LANGUAGE_CHANGE_REQUESTED_BY_ADMIN_VISITOR', $_GET['language'], $lng);
    } else {
      $lng->get_browser_language();
      $lng->set_language(DEFAULT_LANGUAGE);
    }

    // Check if the language's directory can be found, if not then default to English.
    // Added to account for attempting to access an upgraded database that identifies a default
    //  language that has not been installed on the server. This will ignore if English has been deleted 
    //  from the database.
    if (!(zen_not_null($lng->language['directory']) && file_exists(DIR_WS_LANGUAGES . $lng->language['directory'] . '.php'))) {
      $lng->language['directory] = 'english';
    }

    $_SESSION['language'] = (zen_not_null($lng->language['directory']) ? $lng->language['directory'] : 'english');
    $_SESSION['languages_id'] = (zen_not_null($lng->language['id']) ? $lng->language['id'] : 1);
    $_SESSION['languages_code'] = (zen_not_null($lng->language['code']) ? $lng->language['code'] : 'en');
  }
````

Now even this, which may have had some discussion in #1449, could be done a little differently based on overall effect/intention. 
2) Could modify just the `$_SESSION['language']` value and leave the `$lng` variable alone, or as recommended by DrByte something more could be done in the language class' `set_language` method, though I would think that in that file wouldn't really want to do a "file" check, whereas in this file that is the end result of the file.  
3) The other option, like you suggested is to check for the file's existence on each and every page load instead of just when setting the session or trying to change it.

**Comment by torvista** [comment]
As usual, several ways to skin the cat. I would not consider someone having deleted the default english from the db.
I would stick an else on this to reset the session language to english, then all the subsequent would work. That seems to the least code required.
```
if (is_file(DIR_WS_LANGUAGES . $_SESSION['language'] . '/' . $current_page)) {
    include(DIR_WS_LANGUAGES . $_SESSION['language'] . '/' . $current_page);
  }

```

**Comment by mc12345678** [comment]
So are you possibly also proposing that the admin's language files be potentially overrideable on a file-by-file basis?

Actually, if the `$_SESSION['language']` were reset specifically at that point without any other modification, then `$template_dir` would still be set to the other language. 

As to consideration of deleting the default English from the database, its kind of funny as I wouldn't have really considered that in doing a site upgrade that the associated language files for which the site operated wouldn't be included as part of the process.

As to the method of correction, I was going for a method that wouldn't unnecessarily add frequent work to the system (testing the file(s) on each page load).  With the if statement proposed above:
````php
  if (is_file(DIR_WS_LANGUAGES . $_SESSION['language'] . '/' . $current_page)) {
    include(DIR_WS_LANGUAGES . $_SESSION['language'] . '/' . $current_page);
  }
````
The session language could be changed "on the whim" if a specific page didn't have a translated file.

If in fact that one page's translation didn't exist, is there a reason that the entire screen be modified to another language and not just the one set of defines for the specific content in the working area?

I could see in a "development" situation where the English language files were not copied over to the alternate language and then translated, that such a "if not present, use the default" condition for the current page could be useful.  I'm also thinking about the messages that have been presented regarding PHP 7.2/7.3 where if a constant is used that is not defined that an error will be thrown in a future version.  If that is the case/consideration, then it would seem that the "alternate" language and the default English language files should be loaded with the expectation that at least all defines would be provided in the default English files...

**Comment by torvista** [comment]
I have to admit I get brain freeze with your answers!
All this is about is that I got a white screen of death that I found not-so-straightforward to fix, and by reporting it, hope to help others less experienced to avoid.
The "best" way to plug the hole, I'll leave to others.
