### ISSUE TITLE
coupon warning messages - improvements

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2264]
For a coupon set to single use and single use per customer, when exceeded this is the result:
![Clipboard01](https://user-images.githubusercontent.com/4391026/55708149-782b5780-59e5-11e9-9afe-69c0a589b405.gif)
Not very good.

I think this is better:
![Clipboard02](https://user-images.githubusercontent.com/4391026/55708581-8ded4c80-59e6-11e9-87a3-bac060ed4b92.gif)

I have a doubt about this change, for example:
Current
`$messageStack->add_session('redemptions', TEXT_INVALID_USES_COUPON . $coupon_result->fields['uses_per_coupon'] . TIMES . ' ' . ($dc_link_count ==0 ? $dc_link : '') ,'caution');`

To
`$messageStack->add_session('redemptions', sprintf(TEXT_INVALID_USES_COUPON, $dc_link) . $coupon_result->fields['uses_per_coupon']  . ($coupon_result->fields['uses_per_coupon']  == 1 ? TIME : TIMES), 'caution');`

Is this original clause necessary 
`($dc_link_count ==0 ? $dc_link : '')`
or can be used as shown in the sprintf, just as $dc_link?

**Comment by mc12345678** [comment]
Or could further use placeholders in the sprintf text so that the text could better support multiple languages:
`sprintf(TEXT_INVALID_USES_COUPON, $dc_link, $coupon_result->fields['uses_per_coupon'], ($coupon_result->fields['uses_per_coupon'] == 1 ? TIME : TIMES))`
Where `TEXT_INVALID_USES_COUPON` in this case could be:
`'The coupon %1$s could only be used %2$d %3$s'`

In this way another language or rewording of the statement can be made by moving the text around in the one define rather than in the original php file.

**Comment by lat9** [comment]
Agreed, @mc12345678.  Using `argument swapping` is a great solution to that formatting problem.

**Comment by torvista** [comment]
https://github.com/zencart/zencart/pull/3104
