### ISSUE TITLE
156 admin: disabling/enabling categories and contained products

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2280]
Currently, disabling a category 
- also disables its subcategories (logically)
- also disables all the products contained therein. I have this with an option for no change, same as when ENabling a category, as I have many linked products.

Prior to submitting a pr for this,
a) agreed?
b) and in
admin/category_product_listing.php
I find this code:
```
foreach ($product_ids as $product_id) {
            $products[$product_id['products_id']]['categories'][] = $categories[$i]['id'];
          }
```
but see no use of this array...please enlighten?

**Comment by torvista** [comment]
This what I have ended up with:

![Clipboard01](https://user-images.githubusercontent.com/4391026/56428830-127e7b80-62c1-11e9-8eec-10632aeeb040.gif)

**Comment by drbyte** [comment]
1. It's a bit unclear from your post, but I'm assuming your intention here is to add the option to control whether products are also disabled when choosing to disable a category. If so, I'm okay with that.

Current functionality includes:
<img width="453" alt="Screen Shot 2019-04-19 at 12 51 38 PM" src="https://user-images.githubusercontent.com/404472/56434394-73e32200-62a2-11e9-86ee-86fffba93735.png">

<img width="460" alt="Screen Shot 2019-04-19 at 12 51 22 PM" src="https://user-images.githubusercontent.com/404472/56434397-78a7d600-62a2-11e9-93c7-cdae1c48f625.png">

2. I agree: the `$products` var you mention is apparently unused since at least as far back as v1.5.0.
