### ISSUE TITLE
156: undefined constant SITE_TAGLINE

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2307]
use demo products.
open metatags for Matrox G200 MMS 
change nothing: all radio options Yes and text fields empty.
Proceed to Preview, constant is missing and generates corresponding debug.
![Clipboard01](https://user-images.githubusercontent.com/4391026/56847897-2853f800-68e2-11e9-86e5-fc9bc5d90852.gif)

**Comment by torvista** [comment]
I note also that the Back button on this page does not work!

**Comment by drbyte** [comment]
The problem is actually much worse than just the undefined constant. It's displaying the *admin* TITLE constant contents too, which makes displaying the title/tagline pointless anyway.

I'm inclined to remove both constants altogether.
Until a final course of action is decided, ironically SITE_TAGLINE fits well as a visual placeholder.
