### ISSUE TITLE
Possible bug in includes/classes/payment.php

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2364]
Line 220 checks
        if (!(isset($confirmation['fields']) && is_array($confirmation['fields']))) $confirmation['fields'] = array();

shouldn't this be 

        if (!(isset($confirmation['fields'])) $confirmation['fields'] = array(); 

I am seeing logs from the reading of this field in /tpl_checkout_confirmation_default.php that say, 
--> PHP Warning: sizeof(): Parameter must be an array or an object that implements Countable ... 

The log is pointing to the line in the template file that does 
                    for ($i = 0, $n = sizeof($confirmation['fields']); $i < $n; $i++) {

**Comment by mc12345678** [comment]
Actually would say that the issue is from something before the line 220 (221 in current file) as the only reason that it appears that $confirmation['fields'] would not be an array (implementing countable) appears to be if either of the first two if statements evaluate as false:
````php
  function confirmation() {
    if (is_array($this->modules)) {
      if (is_object($GLOBALS[$this->selected_module]) && ($GLOBALS[$this->selected_module]->enabled) ) {
        $confirmation = $GLOBALS[$this->selected_module]->confirmation();
        if (!is_array($confirmation)) $confirmation = array('title' => '');
        if (!(isset($confirmation['fields']) && is_array($confirmation['fields']))) $confirmation['fields'] = array();
        if (!isset($confirmation['title'])) $confirmation['title'] = '';
        return $confirmation;
      }
    }
  }
````

With the more likely culprit being that the payment module is not enabled at the time of processing the confirmation function.

Say this because, if as suggested, the test were `!isset($confirmation['fields'])` only then, that is already checked/verified in the original code above such that if it is not set, then the array test is not performed and the key and value are both set.

But, if at the point of executing the confirmation function either modules is not an array or the selected method is not selected or not enabled, then a non-array value is returned (void).

I would think that the "fix" may be:
````php
  function confirmation() {
    $confirmation = array('title' => '', 'fields' => array());
    if (is_array($this->modules)) {
      if (is_object($GLOBALS[$this->selected_module]) && ($GLOBALS[$this->selected_module]->enabled) ) {
        $confirmation = $GLOBALS[$this->selected_module]->confirmation();
        if (!is_array($confirmation)) $confirmation = array('title' => '');
        if (!(isset($confirmation['fields']) && is_array($confirmation['fields']))) $confirmation['fields'] = array();
        if (!isset($confirmation['title'])) $confirmation['title'] = '';
        return $confirmation;
      }
    }
    return $confirmation;
  }
````

This way, confirmation would be set with an empty title and an empty fields array up until the inner assignment where that assignment would get evaluated as well to ensure at least an empty title and an empty array of fields.

There may be other solutions.

**Comment by scottcwilson** [comment]
Thanks to @mc12345678 for suggestions on this.  I think I used most of your ideas plus added a few.
