### ISSUE TITLE
Request: Integrate Report All Errors as a core feature

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2460]
This is tremendously useful for developers.  Alternately, instead of integrating the entire module, perhaps it could be integrated without configuration, and triggered when STRICT_ERROR_REPORTING was set.

**Comment by lat9** [comment]
If integrated, my preference would be to keep the configuration settings, as the `IgnoreDups` and `Backtrace on Notice` settings can be quite useful.

Debugging, for example, anything to do with the `account_history_info` page results in a ton of duplicated-constant notices since the language files for `account` and `account_history` are loaded as well.

**Comment by scottcwilson** [comment]
Good point - I guess I was thinking that IgnoreDups would be the default setting because there are many of them.

**Comment by torvista** [comment]
> there are many of them.

...not in the Admin anymore, apart from payment modules (paypal)
