### ISSUE TITLE
Column hiding on admin product listing screen too aggressive

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2614]
In versions 1.5.5 and prior, you could see a lot of information on products on the admin listing screen (Admin-Catalog->Categories/Products).  Any interest in resurrecting this capability, even if as only an option?  I have had client complaints about this.

**Comment by drbyte** [comment]
You're referring to columns disappearing when on smaller screens, right?

**Comment by scottcwilson** [comment]
Even on the big screen they're not there.

**Comment by drbyte** [comment]
Help me out. What exactly is missing?

Looking back on live sites I see the same columns as what's currently in 157. These screenshots are from v157:

<img width="1578" alt="Screen Shot 2019-07-20 at 3 45 49 PM" src="https://user-images.githubusercontent.com/404472/61583415-a7358700-ab05-11e9-9fab-809240ede8cb.png">
<img width="1574" alt="Screen Shot 2019-07-20 at 3 45 58 PM" src="https://user-images.githubusercontent.com/404472/61583416-a7358700-ab05-11e9-9a0a-3914a28ca8b7.png">

**Comment by scottcwilson** [comment]
Apparently I have small window syndrome. :(   Seems like the cutoff for hiding the fields is a bit aggressive? 

<img width="1184" alt="screen" src="https://user-images.githubusercontent.com/4391638/61583461-35aa0880-ab06-11e9-9b5a-5ba0974a94d8.png">

**Comment by drbyte** [comment]
I think @Zen4All posted something on the forum in the last couple weeks about a couple bootstrap styles to change in the html (changing from md to sm in a few places). That's probably worth a PR.

**Comment by Zen4All** [comment]
Yes I did post something about that. I am on my summer holiday now, but  can make a pr after that.

**Comment by mc12345678** [comment]
And I got chastised for opening an issue about it with addressing the same concern (#1979) that was then closed before I had an opportunity to get back to it. (Not even going to use sarcasm to hide my thoughts on that.)

So @scottcwilson you want to close this issue seeing that all of the content is actually there? *(Ok, **there's** the sarcasm <sub>from the day I'm having</sub>.)*

**Comment by scottcwilson** [comment]
I reviewed the issue you linked and am unable to see where you were chastised. You said it was operator error, and I suggested you close it.  If you had said, "no, let's leave open and fine tune the CSS" that would have been sufficient to leave it open.

**Comment by drbyte** [comment]
> opening an issue about it with addressing the same concern (#1979)

Aha - that's where it was. I thought I'd seen an issue for it before, but clearly I used the wrong search to find it. Thanks for linking back to it.

As I said, a PR to fix it is welcome. The smaller breakpoint is evidently more common.

**Comment by scottcwilson** [comment]
Updated title to reflect actual issue.   Have fun on your holiday @Zen4All!

**Comment by torvista** [comment]
I still think it is too aggressive.

![listing 1](https://user-images.githubusercontent.com/4391026/153925343-0f6a79a3-4e41-42a2-9f28-e0073c999288.gif)

![listing 2](https://user-images.githubusercontent.com/4391026/153925366-93cb790d-73d7-4b16-8fa4-392466b0ac3e.gif)

![listing 3](https://user-images.githubusercontent.com/4391026/153926006-85317aa4-caa9-4d81-a46c-53eed9516070.gif)

My opinion is that ADMIN users are in the admin to DO admin things...they are not browsing, and possibly using a small screen from necessity (some urgent matter needing to be done on the hoof) rather than choice.
I think hiding anything apart from the image just makes such work even more frustrating. It is less frustrating to scroll than
If I enter the admin via any device I want to see all the information I am used to seeing, to get something done.
I suggest that nothing should be hidden except the image.
![listing 4](https://user-images.githubusercontent.com/4391026/153926827-c94855c7-e1d8-44bb-8163-173c840ffa9b.gif)
