### ISSUE TITLE
Better name for includes/functions/functions_general_shared.php

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2657]
@drbyte wasn't wild about this name but my creativity-foo is weak.  

shared_general.php? 
shared.php? 

Ideas?

**Comment by lat9** [comment]
How about either functions_general_common.php or common_general_functions.php?

**Comment by drbyte** [comment]
Discuss: What are the downsides of just making it `general.php` (assuming all it contains are functions that are truly general)?

Asides:
- Here I dropped the word "functions" because @zcwilt pointed out that it's already located in the "functions" directory. That's not a final decision, but it does allow for renaming in order to prevent clashes. 
- While I'd prefer "common" over "shared", I still think neither gives context: "common to 'what'?", "shared with 'what'?".  I'm slightly more inclined to put as much catalog-side as possible, and for things that are truly admin-specific (ie: truly admin-only, such as UI-related, and not something that could be used by things/areas/api other than admin-only), prefix those with "admin_".

Anyway, just adding these thoughts for commentary/discussion.

**Comment by scottcwilson** [comment]
I'm happy to go with general.php but then we have general.php and functions_general.php. Is that confusing?  If no, I'll go with that.

**Comment by drbyte** [comment]
I envision that the consolidation would eventually remove the need for the old functions_general and it could be replaced with a stub saying "not needed; if you're merging a plugin, go put your plugin changes in the right place ... " (or something to that effect, but more helpful :) )

**Comment by scottcwilson** [comment]
If we merged the old functions_general.php with the new shared file, there would be a bunch of collisions with functions defined on admin.  Wouldn't it be better to keep them separate?

**Comment by drbyte** [comment]
I see this as an opportunity to fix whatever is causing the collisions, not by merely adding "is admin" conditionals, but actually fixing the inconsistencies. That of course requires a careful review of each collision, and assess whether the difference is needed, and why, and why it needs to be different ... if in fact there is really a good reason for it.

**Comment by drbyte** [comment]
A bunch of this was done in v2 already.

**Comment by torvista** [comment]
Blimey charlie, this discussion is worthy of the spanish (lack-of) parliament.
How about this?
A bunch of function files in 
catalog../functions/functions_named with some logic as to the type of functions they contain. Like they are now. 
But, almost all of them will be used by the admin too. 
Apart from one named eg. catalog_functions.php (not functions_catalog)
And in the admin,,,,/functions/admin_functions.php...and nothing else as all the rest come from the catalog.
The idea being that all functions are accessible in both places apart from a few that are specifically NOT.
i.e. instead of arguing about the name of the shared file, assume they are all shared, and argue about the name of the specific one.
This would be an end-point, Now, how to get there.....

**Comment by lat9** [comment]
How about simply adding a /common sub-directory to the storefront, e.g. `/includes/functions/common`, in which the functions _common_ to both admin and storefront reside?

**Comment by scottcwilson** [comment]
No - a subdirectory means you have to search in functions and that folder *but not in extra_functions* to find something native to Zen Cart.  That would be a pain.

**Comment by scottcwilson** [comment]
I misunderstood the requirement - Chris's real request was not so much a renaming of the file as a merging of all but truly needed separations.   Closing this.
