### ISSUE TITLE
Admin zen_draw_input_field() $required parameter causing layout issues

### ISSUE THREAD

**Issue by lankeeyankee** [zencart/zencart#2668]
The merge of PR #2590 can break page layouts. 

I have not tested this with changing "Required" to "*" but that might be better since it is smaller and would not push things out of line so far.

![required](https://user-images.githubusercontent.com/7685560/62012137-408d1a80-b150-11e9-81a7-d236f2f171a6.jpg)

![required3](https://user-images.githubusercontent.com/7685560/62012138-4551ce80-b150-11e9-8d83-25db8f9d3b50.jpg)

**Comment by scottcwilson** [comment]
Edit Orders is a mod.  Submit a PR or an issue to Cindy's repo to set the define for required on that page only to *.

**Comment by scottcwilson** [comment]
... and please close this issue.

**Comment by lankeeyankee** [comment]
Is it more the point that using the default html_output dropdown creates issues on pages?

**Comment by drbyte** [comment]
Since on the admin side the `$required` flag (formerly did nothing, but now) only outputs the `* Required` string (or whatever is defined by the constant), 
I see 3 possible approaches:

1. In mods, just stop passing `true` for the `$required` parameter, as that would give you what it did previously.

2. If `required="required"` is truly what's needed, pass it to the `$parameters` param and then it'll be part of the HTML, and the browser will enforce the requirement.

3. Explore custom-defining the constant for just that page, and/or other layout adjustments that might be relevant for updating the mod.

4. (Not going to do this ...) Rollback the core code to completely ignoring the `$required` parameter.

I suggest actually doing 1 and 2 and 3.

**Comment by drbyte** [comment]
Nevertheless, your issue draws attention to the importance of watching for the impact of merging this function with catalog-side, where we could end up being more aggressive with adding the `required="required"` attribute to the output (which would be more semantically expected, although maybe too harsh in some cases).

**Comment by drbyte** [comment]
I do also wonder whether having the `$required` param just output warning text is over-stepping. Maybe it should be up to the template/view to output the red "required" alert text on a case-by-case basis, instead of having the helper function force a static constant without prejudice.

**Comment by scottcwilson** [comment]
Can this issue be closed?
