### ISSUE TITLE
[Suggestion] Google Analytics or alternatives

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2692]
As part of my spring clean I have been revising the GA plugin (which I have quite modified), although I admit I never ever look at the data.
What is the panel's view on the tracking world these days?
Is GA so ubiquitous that it should be in the core? In which case I can bear that in mind prior to presenting a PR to the plugin repository.
Or, are there now preferable alternatives to feeding the Google machine, that are more in keeping with open-source ideals?

**Comment by drbyte** [comment]
IMO https://matomo.org would be better.

I'm definitely not interested in obliging myself to constantly tweak any analytics components in core code, particularly since it's a constantly-changing landscape.

Hooks to allow plugins that are separately maintained is preferable. That way people can sell themselves out to whatever analytics service they wish. Even if it's a user-tracking plugin they install in their same db.

**Comment by torvista** [comment]
Agreed.

**Comment by wiztechinc** [comment]
when google analytics is free? Why in the world would a normal cart owner want to pay out over 20 a month?  But this is a problem and has been for several years now - no one either can keep up with code or dies/leaves. For those who use google adwords, they need google analytics. There is no substitute for that much less a program that isn't free and does not deliver / or doesn't deliver on google adwords. I didn't look into to it too deeply but that's what it looks like to me.

**Comment by drbyte** [comment]
> when google analytics is free?

But, it's not really free. 

> no one either can keep up with code or dies

You've just proved my point. It's not free, because someone's gotta keep up with it.  Are you volunteering to be that expert, to keep-up-with-it ... for free?

**Comment by drbyte** [comment]
Plus, matamo is free if you host it yourself. If you call that free.
The same way Zen Cart is free. If you host and maintain it yourself.

But businesses whose model is "always give it away for free" don't last if nobody's providing sustenance.

**Comment by wiztechinc** [comment]
Install something like that on each website? cause I sure ain't doing that for clients from my server. I'm trying to get as sustainable as possible. It's not good business sense to not have your clients need you but I almost died 2 years ago so to everyone's benefit - including the zen cart project - I have to do things that don't rely so much on me in the future. I personally hate google and hate the monopoly but the truth is that between the analytics, the adwords and google shopping, this is part of SEO and that is paramount for a business.  You cannot discard them now. It's still quite possible to install the code without a mod. It's not even difficult but it is just easier to have a mod to plunk in and the ga code and it's a go. I'm all about efficiency and ease in my business.

**Comment by drbyte** [comment]
My point was that there are options. And "free" should never be used as a justification, because there's always a cost, even if the cost is "only" mining of your data.

Another great alternative, if it suits the store's needs, is www.visitor-analytics.io -- lower price, and focuses on the core analytics that most actually pay attention to. 

Plus, you can still have your "adwords" support too if your store is bought-into that mindset, since
all these analytics tools can co-exist, at the cost of a bit of extra page-load slowdowns, but even that can be minimized by putting it at the bottom of the page instead of the top.

**Comment by lankeeyankee** [comment]
I agree that hooks are the best way to go. Let folks decide for themselves what analytics they want to use. Choice, options, that is always the most preferable way in my opinion.

**Comment by drbyte** [comment]
Several more alternatives discussed here: https://twitter.com/chriscoyier/status/1171183160907816960

**Comment by drbyte** [comment]
Are any additional "hooks" needed? There are already tons of hooks at critical stages of the application execution path that can be leveraged for this.
