### ISSUE TITLE
[Suggestion] Edit Email default text from Admin

### ISSUE THREAD

**Issue by judygunderson** [zencart/zencart#2695]
Just a thought because I get asked this probably a couple of times a month.  Is there any way to incorporate changing the verbiage of the various emails that go out into the define pages editor or some place else?
I'm one of those kind of people that like to give my customers as much control over their websites as possible. :)

**Comment by wiztechinc** [comment]
yay, Judy! This would be nice but it's really difficult to edit that text anyway. I could see real difficulty in incorporating this type of text in any edit situation. I usually just tell my folks to deal with it and certainly can change some text for them if necessary but they don't want different wording. They want to remove and add paragraphs which has been way more complicated.

**Comment by judygunderson** [comment]
Yeah you are right Delia.  Actually it was just a hairbrained thought because I had just gotten an email from a customer asking that question.  lol  I just told him he would probably want to have ME do it because it involved coding.  :)

**Comment by scottcwilson** [comment]
Definitely an interesting idea.  Can you be specific about which defines you think are good candidates?

**Comment by wiztechinc** [comment]
well, one line sticks out in the welcome email - "Products Reviews - Share your opinions on our products with other customers." Some folks don't allow this and I find it rare that folks write reviews on small sites.  And, the English teacher in me objects to "Address Book - We can deliver your products to an address other than yours! This is perfect to send birthday gifts direct to the birthday-person themselves." birthday-person is just wrong. I just ignore but some of my clients are way more picky than that.

**Comment by wiztechinc** [comment]
I can certainly lend my English teacher - writer brain to fix some of these things in a version but in the meantime......

**Comment by lankeeyankee** [comment]
I think this is a great idea. I don't see how it could cause issues, can you please elaborate? You mean due to security needing to make the define pages read-only once they are created/edited?

**Comment by wiztechinc** [comment]
emails can't be normal text without massaging? The templates now insert line breaks/non html to make paragraphing/spacing work. Does it have to be this way? I don't know.

**Comment by lat9** [comment]
FWIW, I've always wondered why the HTML emails have boilerplate templates but the TEXT emails don't.  

If there was, for instance, both an `email_template_checkout.html` and an associated `email_template_checkout.txt`, then site's could have full control of the TEXT-formatted emails as well.

Granted, it would be an initial PITA to remove that text-formatting from the .php modules that are building those emails, but I think the change would be welcomed in the long-run.

**Comment by scottcwilson** [comment]
I wonder if we could just make the .html email template do double duty by stripping tags from it to build the text email?

**Comment by lat9** [comment]
It's certainly possible as the PHPMailer has had such support for a long time now.  I'm just thinking that having a separate .txt which allows full control over the formatting might be a better way to go, since those emails get formatted (pretty much) once.

**Comment by lankeeyankee** [comment]
While many emails would be set and forget, having an admin area to edit the content would make it easier to add promotional messages in various emails like order confirmation, status update, etc. There is a lot of scope for this and I think would be a very welcome additional feature.

**Comment by neekfenwick** [comment]
This issue is clouded by the user of notifiers to allow custom hooks that modify email content, re:  https://github.com/zencart/zencart/pull/1670 and https://github.com/zencart/zencart/pull/3207 .. any solution involving define pages containing email content will require breaking changes with anyone using these hooks.

Thinking of the programming side of things, what's the history of using a templating system to generate the output?  I've been using Smarty for years to generate some text in our system, which is a pretty solid PHP text based template generation system.  Current Zen Cart seems to use Composer to control dependencies, currently only seems to require `ext-curl` and `ext-json`.  It would be possible to require `smarty`, and then have email templates contain a single BODY or similar element, have that element taken from a define page, and have that define page contain Smarty parameters such as `{$orders_id}` to fill in that data.

@lat9 makes a great point about different text and html templates.  I think in many cases a single template that is convertible would suffice, and others where two independent ones would be required.  I would suggest an HTML format one be the prime candidate, because you can strip tags from it to make reasonable text content, but if a customised TEXT version is required then a .txt version of the email template file could be present and detected by the code and used if present.

I know this is bread and butter developer talk and the old fashioned way the Zen Cart email content is put together has been obsolete by many standards for a decade or more, what's the thinking on a total overhaul, and putting the breakage of writing bad Smarty templates in define pages in the hands of the users?  This would be the killer in terms of "if you have to think you haven't been zenned".

Does anyone on this thread think that being able to completely edit the main content of an email, right down to strings like `Your order number is {$orders_id}`, would be too user unfriendly?  Of course the solution to user unfriendliness is proper on screen direction (hints and tips beside the editor, for example) and documentation updates (oh joy).  I can see that some would make mistakes and cause a lot of noise on the message boards.

**Comment by scottcwilson** [comment]
Love the enthusiasm.  Here's the challenge: 
- A breaking change like this would need to be put in a major release, not just a letter addition to 1.5.8.  This is probably 1-2 years out. We need to get people over the hump in terms of PHP 8 first.
- A reworking of this would require a commitment over an extended period of time from a developer.  Would that be you?

**Comment by neekfenwick** [comment]
> * A breaking change like this would need to be put in a major release, not just a letter addition to 1.5.8.  This is probably 1-2 years out. We need to get people over the hump in terms of PHP 8 first.
Fair enough.

> * A reworking of this would require a commitment over an extended period of time from a developer.  Would that be you?

Maybe :) It sounds like a major breaking change, so some discussion is warranted.

It occurred to me that instead of strings for the emails being in language defines, like a made up example:
- includes/languages/english/lang_email.php - defines EMAIL_GREETING 'Hello'
- includes/languages/spanish/lang_email.php - defines EMAIL_GREETING 'Hola'
- email/email_template_welcome.html 

The difference in language would instead be in each email template, and you'd need a template per supported language, e.g.
- includes/languages/english/html_defines/email_template_welcome.html - contains "Hello ${customer_name}"
- includes/languages/spanish/html_defines/email_template_welcome.html - contains "Hola ${customer_name}"

Is this an acceptable direction? Any other suggestions for how to structure it?

On the subject of data, I'm a fan of putting conditional logic, loops etc in my Smarty templates, so having a order details and a list of products would be by something like:
```
$tmpl_data = [
    'orders_id' => $orders_id,
    'some_config_switch' => SOME_CONFIG_SWITCH,
    'products' => $products_array
];
```
and in the template, have Smarty functions like `if` and `foreach`, instead of writing PHP code that acts on configuration and logic before settings strings that go into the template:
```
<p>Greetings {$customer_name},</p>

{if some_config_switch}
<p>We also provide service xyz.</p>
{/if}

<p>Your invoice number is {$orders_id}, for the following products:</p>
<table><thead>blah blah</thead>
<tbody>
{foreach from=products item=product}
  <tr><td>{$product.products_name}</td><td>{$product.final_price}</td></tr>
{/foreach}
</tbody></table>
```

This is standard templating technique and very different to how Zen Cart currently builds its email content, we'd be moving a lot of PHP logic into the Smarty template.  Any feedback on this general approach?

The ticket author @judygunderson only wanted to control verbiage in the emails, but I'm proposing something a few steps beyond that and may not be welcomed by users.  Always good to ask for feedback :)

**Comment by scottcwilson** [comment]
Please take the comment above and open a new Discussion (click the Discussions link at the top of the page.)

**Comment by neekfenwick** [comment]
> Please take the comment above and open a new Discussion (click the Discussions link at the top of the page.)

Done #5499

**Comment by scottcwilson** [comment]
Thanks.  Closing this issue; conversation will continue in the thread linked above.
