### ISSUE TITLE
Put tool for accessing customer-order uploads in core?

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2718]
This tool https://www.zen-cart.com/downloads.php?do=file&id=1134 allows you to easily download files which customers have uploaded when they have file attributes.  Without it, I don't see how people run stores that have uploadable attributes - isn't it critical to running such a store?

(There's a small bug in the plugin right now- need to add global $db to line 31 of the main file.)

**Comment by drbyte** [comment]
Wouldn't it make more sense to just give access to the uploads directly on the order-details page? particularly since in order to fulfill the order you need to know what those files are supposed to be used for (products/attributes they're to be applied to)?

In theory that'd be less code to maintain too, wouldn't it?

**Comment by scottcwilson** [comment]
Very good.  Will pursue and PR shortly.
