### ISSUE TITLE
Admin login page forgotten username

### ISSUE THREAD

**Issue by judygunderson** [zencart/zencart#2723]
I was on a site yesterday and saw where it not only had a "forgotten password" but it also had a "forgotten username" as well.  I see this a lot on different sites I shop at.

I think that would be good to have on the admin login and maybe even on the return customer login as well.  I have customers who will tell me they can't log in and request a password, but are looking in the WRONG email account for the password.

**Comment by drbyte** [comment]
If the hints for helping recover something forgotten are sent by email, then that's still not going to help solve the problem where they're looking in the wrong email account.

How were you thinking of solving that?

**Comment by judygunderson** [comment]
Good question.  How about this,, I have seen some sites that will, when you ask for your password and hit submit, it will say something like... A temporary password has been sent to **chris@abc.com.**
That way, if they are paying attention (anyone want to guess the percentage that will? lol) they will automatically know the username and where the temp password went.

**Comment by wiztechinc** [comment]
After the problems we are now seeing with admins getting broken into, there needs to be very careful discussion on this. I don't know what the best way to do this is but with customers, they can do stupid things like putting a space at the beginning or ending email. This is a constant problem with my clients. Being able to change the password in admin is definitely a help. So perhaps showing just part of the email? Seen that recently - delia@t*********h.com but then there's the folks who can even type correctly and not see where they might have switched letters. But fully displaying the email? I'm not liking that.

**Comment by drbyte** [comment]
It's not safe to disclose the full email address to an unauthenticated visitor, otherwise malintentioned visitors would learn information they could use against you.

We can only go "so far" in saving the user from themselves. 

The Forgot Password already gives the Admin username in the email containing the reset token. This is already risky enough.

Why are your customers forgetting their password? AND their email address? Maybe there's a deeper problem that needs solving?

**Comment by barco57** [comment]
> The Forgot Password already gives the Admin username in the email containing the reset token.

What version does sends the Admin username? I just went through a bunch of admin password reset emails I have and none of them have the admin username in them.

**Comment by drbyte** [comment]
You're right, it's not in the body of the email.
It's in the "To" address of the email headers.

**Comment by judygunderson** [comment]
It could be like me....old age and too many email addresses. lol
Other things I hear are they changed their ISP and don't have that email address any more or that is an old email and I hardly check it anymore.

It's no big deal - especially since we can now send a new password through admin and can change their email address if we need to.  I certainly would not want anything that would risk security or PCI Compliance.  I just saw it on another site and thought I would pass it along.

[QUOTE]Why are your customers forgetting their password? AND their email address? Maybe there's a deeper problem that needs solving?{/QUOTE]

**Comment by barco57** [comment]
> It's in the "To" address of the email headers.

At first, I was like "what is the good doctor talking about as I have used Thunderbird forever, and when I look at the "to" address I only see this 

> Me <michael@geekhost.ca>

I figured that you couldn't possibly be wrong, so I viewed message source and that is where I could finally see that it does indeed send the Admin username... Never even realized that

**Comment by drbyte** [comment]
> but it seem Thunderbird translates it to "Me"

Ya, many email clients translate incoming recipient names to match Contacts in your address book.

> it does indeed send the Admin username

It could be made more clear I suppose, by putting it into message body.

I'm not sure that's what people are most often experiencing any trouble with though.

**Comment by judygunderson** [comment]
> I'm not sure that's what people are most often experiencing any trouble with though.

You are correct, its not what they are having the problems with.  

Its the part about actually getting the email to the account they THINK they used to set up an account.  Another thing is sometimes it goes into junk (which I always tell them to check) and in the case of yahoo and AOL - sometimes they just don't deliver the email at all even though the server is clean from spamming.

I have lots of repeat customers, and sometimes it will be a year or two before they need anything - like an upgrade or a mod.  That is where the problem lies I think.  But, even if we can do what Delia said and obfuscate part of the email when they request a new password, who knows if they will even see it.  Everyone is always in a hurry - so they either pick up the phone, text or email me when this problem occurs.  

Sometimes they contact me later in the evening and I am not going to respond after business hours because I am a **meany brat** and I don't want them to get used to being able to get a response from me 24/7 lol

**Comment by barco57** [comment]
From my experience, at two hosting companies specializing in ZC, most admins forget which email address they used. Particularly those people who don't log in to their admins very often because they just work off the order emails. They assume that the email was sent because the feedback is that if the email address exists you will receive an email, but if they used the wrong email address the email never comes, and then they get a hold of me and I dig in and have to inform them they used the wrong information to do the admin password reset. I understand that the password reset for the admin is not supposed to indicate whether or not a given email is in the system due to PCI requirements, though the store owners don't really understand why when you try to explain it to them, they just want the smart application to fill in the ~intelligence gaps~ holes in their knowledge. I do note that having issues with admin passwords tends towards a high repeat offender rate. Normally it is the same crowd that can not seem to figure out that if you fail the admin login 5+ times you will have been locked out from login admin even if you do remember the password or have done the reset correctly...finally (though isn't there a pull request or something to auto-reset that?) So I figure there are those people I can not fix and will have to reset their password for them and tell them what admin user name and/or email address is attached to which admin, over, and over, and over again.

**Comment by barco57** [comment]
@judygunderson This issue started as "Admin login page forgotten username" and you have drifted off to front end customer password resets... which is a whole other ball of wax, similar but different from an admin login. I know a number of people, have resorted to guest checkout to solve the stupid and sometimes abusive customer problem when they can not remember what email address they used....

**Comment by wiztechinc** [comment]
ahem, I have to say that after I explain to them what happens when they get blocked, I also tell them I have to access the database to fix their problem after 22 failed logins. I normally never get another call because I don't do this for free except under a maintenance plan. Generally the concept of spending money rather than actually doing it properly does work. Or else they give up on their store and ecommerce or switch to another solution. Those who pay to have this done never contact me again about this issue.  But at the same time not getting any messaging and waiting for the forgot password to come throws a kink into anyone's day making them grumpy. So again there's got to be a way that makes this easier on everyone. 

But back to what shows in the actual email.   I don't see the admin username - just the email address.  Where does that show in the header? Specifically this is from a 1.5.6 cart that I'm looking at.

**Comment by barco57** [comment]
> I don't see the admin username - just the email address. Where does that show in the header? Specifically, this is from a 1.5.6 cart that I'm looking at.

As noted above, many email clients rewrite the "To:" to match a contact in the address book, in my case the admin username is changed to "Me". If you look at the full message source you can see what was sent.

**Comment by wiztechinc** [comment]
okay, I see that with gmail. But someone kept mentioning the username - no it's just the email address. Just had a phone call from someone who can't get into his admin because....he changed it yesterday and obviously doesn't remember correctly his new one.

I appreciate what you say about older folks, Judy, but this one isn't that dang old!  We are all so busy and if you aren't using a password saver, this is going to be an issue for nearly anyone. So not unusual and just time out of my day - where I just told him to use the forgot password function but then he realized he might not even be using the correct username. Thus reinforcing this whole conversation about how this might be changed. 

By the way COWOA (the version I use) creates it's own issues for buyers and cart owners so no solution there at all.

**Comment by judygunderson** [comment]
> 
> 
> @judygunderson This issue started as "Admin login page forgotten username" and you have drifted off to front end customer password resets... which is a whole other ball of wax, similar but different from an admin login. I know a number of people, have resorted to guest checkout to solve the stupid and sometimes abusive customer problem when they can not remember what email address they used....

Yes, I did, didn't I?  I think I will blame that on lack of sleep from my dog waking me up at 5am!  As opposed to old age!  lol  

What I MEANT to say was my **_hosting customers_** are constantly doing this - even though I have to charge them to reset the password - Like Delia said, the same ones do it over and over, only mine don't stop when they see they have to pay.  Maybe I'm not charging enough to make it hurt!  lol

Sometimes its a pain - if they have been blocked - other times I can just log into their admin and reset it and it doesn't take that long and I don't generally charge for that.

**Comment by wiztechinc** [comment]
Yup, raise your rates, girl!

**Comment by drbyte** [comment]
When a store administrator uses the Forgot Password feature, they will see a message like this: 
<img width="505" alt="screen shot of status msg" src="https://user-images.githubusercontent.com/404472/62902490-c9e64480-bd2d-11e9-9a25-a5dcbe1c0bc3.png">

Since the forgot-password feature requires entering their email address, there's no point displaying that email address back to the screen again.

And, for security reasons we cannot safely tell them if they entered an invalid email address.

Another administrator can assist them with a reset or with looking up their correct admin email address.

**Comment by drbyte** [comment]
> no it's just the email address

The email "body" contains only the reset instructions.

But the "To" address contains BOTH the "admin name and their email address". 
ie: `To: "AdminUsername" <admin@example.com>`

Now, as @barco57  and I were dialoging above, some email programs override the displayed To "name" by looking up the email address in your email program's address book and displaying that name instead of the actual "To" name in the original email message.

You can inspect the actual headers of your email message to see the original To name and address.

**Comment by judygunderson** [comment]
> You can inspect the actual headers of your email message to see the original To name and address.

Assuming you remember what email address you used for the admin area. :) 

This suggestion can be closed if you want to.  I will just keep getting my meager pay for unblocking them and sending them a new email address. 

Hope you all have a great evening!

**Comment by drbyte** [comment]
I think we're already doing the right things for handling this.
