### ISSUE TITLE
Comma in the first name breaks zen_mail

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#2854]
If someone enters

Acme Widgets, LLC 

in the first name field, the email address parser in Zen  Mail goes crazy.  Not sure what the right fix is - I'd be open to saying no commas in first or last name to prevent this.

**Comment by drbyte** [comment]
> goes crazy

Care to elaborate?

**Comment by scottcwilson** [comment]
oh sorry.  It misparses the email address and issues the failed validation notice.

**Comment by mc12345678** [comment]
Is this issue then happening at the "name <email>" entry in the configuration area or at a point such as sending the email? (Title and previous messages do not clearly state where/when the issue is occurring.

I expect that the problem begins at the configuration entry point because of the initial parsing by comma where the comma has historically been used as the divider for email addresses that are in a list (May be better to use some other "divider" but that too seems would introduce an issue.  

In order to support a comma within the name portion of `name1 <email1>, name2 <email2>, email3`, something needs to be modified in the filtering to potentially regroup adjacent "records" as they are identified to not be acceptable entries until either a satisfactory result is found or there is nothing remaining to attempt. Of course then there becomes potential of email address like data in the name portion that has a comma separator.  When does one stop chasing the squirrel? 

In the above example `name1 <email1>, name2 <email2>, email3`: if name1 = 'Company, LLC' then, when `Company` fails as an email, it could be joined with `LLC <email1>` with a comma and then that grouping sent back through.

**Comment by scottcwilson** [comment]
It happens when the email is sent because the comma is used to separate name-email pairs (but in this case, it's embedded in a name).

**Comment by scottcwilson** [comment]
Could be fixed perhaps by simply stripping "," out of $to_name at the top of Zen Mail.

**Comment by scottcwilson** [comment]
I can't repro this in 1.5.7.  Occurred on a site running 1.5.5e.

**Comment by scottcwilson** [comment]
Closing since I can't reproduce.
