### ISSUE TITLE
admin: category_listing.php, some $cInfo fields missing (class object_info)

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2859]
When deleting a category, two checks are made:
```
if ($cInfo->childs_count > 0) {
if ($cInfo->products_count > 0) {
```
to display appropriate warning messages....this does not work, and it appears these values are not set anywhere.

**Comment by mc12345678** [comment]
There is some commented out code around line 632 that has the values sought and a method to merge the information into the query:
https://github.com/zencart/zencart/blob/247209cdbbe59f3014543ccac59257cf8e039c6e/admin/category_product_listing.php#L632-637
````php
                if ((!isset($_GET['cID']) && !isset($_GET['pID']) || (isset($_GET['cID']) && ($_GET['cID'] == $category['categories_id']))) && !isset($cInfo) && (substr($action, 0, 3) != 'new')) {
                  //$category_childs = array('childs_count' => zen_childs_in_category_count($category['categories_id']));
                  //$category_products = array('products_count' => zen_products_in_category_count($category['categories_id']));
                  //$cInfo_array = array_merge($category, $category_childs, $category_products);
                  $cInfo = new objectInfo($category);
                }
````
Where it looks like the final commented out line should be modified to change `$cInfo_array` to `$category` and then all comments removed.  

If that code isn't to be made operational there, at least the concept is present and possibly needs to be otherwise incorporated.

**Comment by torvista** [comment]
Thanks, you are correct. It was staring me in the face!
