### ISSUE TITLE
156 php notice: free shipping, in checkout_payment

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2880]
php 7.3.7, Report All Errors, catalog no dups.
I can't reproduce this on 157, and would normally fix it and move on, but this is odd.

Product has free shipping and on entering the checkout_payment (not checkout_shipping as you would expect), gives this error:

> [15-Oct-2019 12:00:54 Europe/Madrid] PHP Notice:  Undefined variable: free in ...\tienda-156\includes\modules\pages\checkout_shipping\header_php.php on line 158

from
```
157 list($module, $method) = explode('_', $_POST['shipping']);
158 if ( is_object($$module) || ($_POST['shipping'] == 'free_free') ) {
```
$_POST['shipping'] is at this point free_free, so $module == "free".
The error comes from the fail of the is_object test on $$module.
As far as I can find, this should return false if the variable does not exist, and not a notice, as that is its function.
So, what gives? and how to fix it?

**Comment by mc12345678** [comment]
The issue is not so much in the `is_object` function as it is in referencing (anywhere) a variable that is not defined.  `is_object($undefined_variable)` does not "silently" evaluate to false (it throws a notice). 

Although `$module === 'free'`, this substitutes to attempt to reference the variable `$free` which doesn't appear to exist at this point. Either it needs to be defined in advance or this code could be updated to:
````diff
list($module, $method) = explode('_', $_POST['shipping']);
-if ( is_object($$module) || ($_POST['shipping'] == 'free_free') ) {
+if ( (isset($$module) && is_object($$module)) || ($_POST['shipping'] == 'free_free') ) {
````
I'm not sure yet why it seems that this is not an issue in 1.5.7, though I wonder if something else provides a substitution for freeshipper prior to reaching this point of evaluating the posted data... :/

**Comment by torvista** [comment]
ok, thanks. It seems to be ok with the fix.
