### ISSUE TITLE
One page checkout

### ISSUE THREAD

**Issue by bislewl** [zencart/zencart#290]
I noticed in the 1.6.0 core, COWOA is present. What is everyone's thoughts on a one page checkout? Of course we would need to have noscript fallback as well.

**Comment by zcwilt** [comment]
COWOA is only present in a very minimal form. 
Some work was done a while ago on updating the checkout to be more flexible, in terms of defining entry points and the flow. dependant on configuration (Basically a simple state machine)

I think we still intend to integrate something like this, which will allow for differing checkout flows. e.g. standard, guest, shortened (2 page checkout) and possible single page checkout. 

Once I have some time, I'll try and push up a RFC type document regarding checkout.

**Comment by DivaVocals** [comment]
I think that one-page checkouts are nothing more than smoke and mirrors. They tend to confuse more than they do HELP because so many of these one-page checkout implementations tend to cram WAY too much data in one location.. 

There is no real PROOF that they improve conversions either other than anecdotal musings.. If this direction is pursued, may I suggest that some SERIOUS usability studies be conducted to ensure that whatever changes are implemented HELP and do not hinder the user experience.. and before I get flack for that last statement I would be HAPPY to take the lead on that last suggestion..

That said, the current Zen Cart checkout flow could use some modernizations.. At the very least the billing and shipping "steps" should be combined..

**Comment by wiztechinc** [comment]
I agree and made some changes to the COWOA checkout that addressed my
concerns delineated here:
http://www.teamwiztech.com/blog/whats-wrong-with-zen-cart-checkout/.  The
biggest change was the login page which includes the create account on it
reducing the number of clicks.

Delia Wilson Lunsford
WizTech, Inc., (formerly Delia Wilson Design, LLC.)
434-202-4307
Terms and Conditions for working with WizTech, Inc.
(http://www.teamwiztech.com/terms-conditions.php)

**Comment by mprough** [comment]
http://www.getelastic.com/single-vs-two-page-checkout/
http://www.smashingmagazine.com/2011/04/06/fundamental-guidelines-of-e-commerce-checkout-design/

It's just not smoke, mirrors, nor confusing done correctly. There have been ample discussions, studies and usability testing (even by Google) regarding this very issue. While options are certainly all over the place, Google, Cornwall university, usability experts such as Steve Krug and all the hard data i have ever seen says that shorter is less confusing and significantly more likely to convert sales.

**Comment by wiztechinc** [comment]
definitely does depend on how it's done, no question.

Delia Wilson Lunsford
WizTech, Inc., (formerly Delia Wilson Design, LLC.)
434-202-4307
Terms and Conditions for working with WizTech, Inc.
(http://www.teamwiztech.com/terms-conditions.php)

**Comment by DivaVocals** [comment]
Let me be clear.. I'm all for "less confusing".. However, an awful lot of the "one-page" checkout chatter comes from folks who've not really looked at it from a TRUE process improvement POV. They've also not done the real work to TEST their "theories" for some of the truly awful "one-page" checkout solutions I see pushed or offered up.. Much like some of the rhetoric surrounding URL re-writers.. Too many folks are looking for and pushing "magic bullets" out there.. Hence my "smoke & mirrors" comment..  I'm all for process improvement, I'm all for improving the user experience.. I think that instead of focusing on a "one-page" checkout solution, the focus should be on improving the user experience in the checkout process and from that it follows that what will follow is a better checkout solution..

The *Get Elastic* usability study by itself is not wholly conclusive at all in fact they even concede that point in the last paragraph.
> While this number is impressive, it should not be used as an indicator for how every single-page 
> checkout will perform. Your results will vary, depending on your product, target market etc. There’s 
> no silver bullet checkout process that works best for all business models.

I do find it interesting that 4 years later, the  official Olympic store does not follow the same checkout process..
> So when we started re-working the [Official Vancouver 2010 Olympic Store] (http://www.vancouver2010.com/store/), we challenged 
> ourselves to take it to the next level — and we cut the checkout process down to just single page.

The Smashing Magazine study is a LOT more compelling as they took the time to do a REAL usability study by studying existing online retailers checkout processes..
> The 15 e-commerce websites that we tested were: 1-800-Flowers, AllPosters, American Apparel, Amnesty, Apple, HobbyTron, Levi’s, Newegg, Nordstrom, Oakley, Perfume.com, PetSmart, Thomann, Walmart and Zappos.

They also echo a sentiment that I think makes GREAT sense..
> *advanced features shouldn’t be the focus until basic usability guidelines are met.* If we add the latest technology just because it’s new and exciting, then today’s abandonment rate of 59.8% is unlikely to decrease.

> Things like meaningful flow (see guideline 1), good copywriting (2, 3), simple form design (4, 5, 6, 7, 8, 9), and privacy considerations (10 and 11) go a long way to creating a great checkout experience.

Their findings on appear very much on point. IMHO findings like this should guide any changes to Zen Cart..

That said going back to the *Get Elastic* study, the reduced steps checkout proposed by *Get Elastic* for the Official Vancouver 2010 Olympic Store speaks to my earlier point of combining shipping and billing into one step. Adding the shopping cart summary to this page is a good look, and placing it to the right makes perfect sense.. 

While I took a play from Delia's playbook and moved the "Create Account" form to the login page in the current version of COWOA in my Github repo, I REALLY like the idea of removing the login page as a separate step and allowing folks to login right on the shipping and billing page if they have an account, while the process of creating an account is offered after completing their purchase. The Smashing Magazine study seems to suggest something similar to this.

**Comment by wiztechinc** [comment]
Thank you.
