### ISSUE TITLE
use of mb_ functions.....

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2905]
ZC157: 
On the dashboard I noticed this
![Clipboard02](https://user-images.githubusercontent.com/4391026/68026843-2152db80-fcb1-11e9-86ec-4901b464a5e0.gif)
which comes from 
index_dashboard.php
`<a href="<?php echo zen_href_link(FILENAME_ORDERS, 'oID=' . $order['orders_id'] . '&origin=' . FILENAME_DEFAULT); ?>" class="contentlink"><?php echo substr($order['customers_name'], 0, 20); ?></a>`
which can be fixed by using the mb_substr version
`<a href="<?php echo zen_href_link(FILENAME_ORDERS, 'oID=' . $order['orders_id'] . '&origin=' . FILENAME_DEFAULT); ?>" class="contentlink"><?php echo mb_substr($order['customers_name'], 0, 20, "UTF-8"); ?></a>
`
But, what is the big picture/plan for these functions...a global change or other methods:
https://stackoverflow.com/questions/12446877/php-is-it-possible-to-correctly-substr-a-utf-8-string

**Comment by drbyte** [comment]
The problem is that traditionally the `mb_` functions aren't consistently installed (compiled into) with PHP on most hosts.

So, to use them would require always writing `if (function_exists('mb_whatever')) { mb_whatever('foo', params); } else { whatever('foo', params);}` or writing custom wrappers for every function. It's a highly invasive change, so it's been left on the backburner in hopes that PHP would actually implement proper core support for mb characters natively ... unfortunately that's been a disappointment.

**Comment by torvista** [comment]
ok, thanks

**Comment by lat9** [comment]
Perhaps it's time for the Zen Cart base to provide shims (e.g. `zen_strlen`, `zen_substr`) for various scripts to use, in a manner similar to what I've done for [DbIo](https://github.com/lat9/dbio).

Essentially, that plugin provides two function files (`dbio_string_functions.php` and `dbio_mb_string_functions.php`).  The `DbIo.php` class determines which of these to load, based on the presence/absence of the `mb_internal_encoding` function:
```
        if (!function_exists('mb_internal_encoding')) {
            require_once DIR_WS_FUNCTIONS . 'dbio_string_functions.php';
            $this->using_mbstring = false;
        } else {
            require_once DIR_WS_FUNCTIONS . 'dbio_mb_string_functions.php';
            dbio_string_initialize();
            $this->using_mbstring = true;
        }
```

That way, the DbIo handlers just issue a `dbio_strlen` function call and that will use `mb_strlen` (if present) or fall back to `strlen` if not
