### ISSUE TITLE
Location of CHARSET?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2944]
At the moment this is defined in the main language file and consequently not available to any code loaded prior to that file.
So, in 2019, this day and age of multibyte things, is there really a valid reason why this core constant should be language-dependant / not be defined "elsewhere", once, and prior to all else, like in the configure.php?

**Comment by drbyte** [comment]
For v2 we had moved it (and several others) out to a separate "locale"-specific file, since a number of things can be isolated to that context.

Question: in what ways are you trying to use CHARSET before the language system is loaded? In what ways is it "not language specific"?

I do note that it's different than the DB charset/collation, regardless of the combination of languages used in a given store.

**Comment by torvista** [comment]
CEON URI mapping references it in a catalog observer and triggers a php notice as it is still undefined at that point (I have moved them to the configure files, so that is resolved for the moment).
So that made me think, since there can be only one definition of a charset for the database, is there really any real-world-use case for more than one definition of CHARSET for both admin and catalog for all languages?

**Comment by drbyte** [comment]
> is there really any real-world-use case for more than one definition of CHARSET for both admin and catalog for all languages?

For Admin vs Catalog, probably not. Not so certain about individual languages.

But there's also not much in ZC core that hooks both systems so early in the process.

**Comment by syntaxerror** [comment]
The charset should indeed be set to UTF-8 for the whole system and all languages.
If any language packs still uses Latin1 or something else, it's really time for them to update.

**Comment by mc12345678** [comment]
> The charset should indeed be set to UTF-8 for the whole system and all languages.
If any language packs still uses Latin1 or something else, it's really time for them to update.

Based on? If for no other reason than curiosity about why it ***should***.

**Comment by syntaxerror** [comment]
Because we are in 2020, the world has moved on.
Having sites with several languages using Latin1 etc. is just making problems for people, also when they integrate to third parties where most has been on UTF-8 for years already.

**Comment by mc12345678** [comment]
So then not because of a requirement or to meet a specific standard. Understand. Thank you for providing a response to me.

**Comment by syntaxerror** [comment]
Indeed a requirement, to avoid charset issues on a site and integrated systems.
I'm sure you'll find lots of articles, forum posts etc. about all possible issues it creates having mixed up charsets - if you actually is interested in the topic.

Also you can turn the question around, why would anyone like or need to continue to use mixed charsets?

**Comment by mc12345678** [comment]
> Also you can turn the question around, why would anyone like or need to continue to use mixed charsets?

Sure, until "recently" when ajax.php basically required UTF-8, the "mix" was between what was displayed to what was stored in the database where at least in my experience if the front end used an alternate encoding that also then carried over to the admin such that both the admin and catalog were displayed in the same encoding, then because the language files were expected to translate all items (or be forced to use English), then there was no real "mix" that occurred... Further, unless the forced English used some sort of unicode character such as an emoji or other "special" character, then there was no display issue.  

Probably though the "primary" reason.. To support a store that is presented to an audience in "their" language without fully knowing the language (to be able to translate it to UTF-8), to potentially pay someone to do that, or because those that have translated the file(s) to UTF-8 for their own reason(s) haven't shared it with the ZC community... So, individual either uses what is available at the "cost" of mixed charset or doesn't offer their site in the "foreign" language. I know for myself, while I have been fluent in a secondary language, I didn't really learn the "computer" terms for that foreign language even though I used such a computer.  Getting things done was always a chore, but I was able to do what I needed to get done.

**Comment by drbyte** [comment]
While UTF8 is relatively ubiquitous in large parts of the world, CJK languages don't always fit into UTF8 nicely. Have you any experience that demonstrates the happy co-existence of both? eg: if Zen Cart were to rigidly "force" UTF8 without any configurable override, what hoops would CJK stores have to go through to support their language plus non-CJK languages in the same store?

**Comment by syntaxerror** [comment]
I'm not sure what you're trying to tell us here mc12345678, that said most text editors and systems saves files as UFT-8 by default these days, so it happens quite often there is mixing happening both in extensions and language files. E.g. a ISO-8859 language file also need to be stored as such. Moving to online translations tools they mostly use UTF-8, haven't seen anything else.

I haven't heard about any big issues for Chinese and Japanase Chris, even if Joomla etc. has used UTF-8 since 1.5, supporting quite many languages, including RTF. So could you please share some light on those issues?

Back to https://www.w3.org/International/questions/qa-choosing-encodings.en (which I sincerly hope people takes time to read):
> There are three different Unicode character encodings: UTF-8, UTF-16 and UTF-32. Of these three, only UTF-8 should be used for Web content. **The HTML5 specification says "Authors are encouraged to use UTF-8.** Conformance checkers may advise authors against using legacy encodings. Authoring tools should default to using UTF-8 for newly-created documents."

What's the alternatives?

**Comment by lat9** [comment]
I'll note, too, that most payment-providers now-a-days expect the data to be transmitted via `UTF8`.  A `latin1` store that takes an order from a customer whose first name is _José_ will receive a response from the provider with that name mangled and subsequently stored in the database as _JosÃ©_.

**Comment by syntaxerror** [comment]
I checked around a bit Chris, and I see there is support for **more** Chinese characters and Emojis in utf8mb4, which is also the charset Joomla 4 will be using.

So using **database charset** utf8mb4, and a **collation** like utf8mb4_unicode_ci would solve your concerns. 

HTML document and files will still be regular UTF-8 from my understanding.

**Comment by drbyte** [comment]
Zen Cart's default database collation has been utf8mb4 since v1.5.6
And default language charset has been utf8 since v1.5.0

**Comment by syntaxerror** [comment]
Great, then just remove the CHARSET setting from language files to avoid the issues it's creating. ;)

> And default language charset has been utf8 since v1.5.0
You probably means UTF-8

**Comment by drbyte** [comment]
> then just remove the CHARSET setting from language files to avoid the issues it's creating

Or ... just leave it there, using it for exactly the purpose that a defined constant is used anywhere: to have a constant value that can be referred-to everywhere in the application.

The "issues it's creating" are not because the constant exists or because it's wrong. It's that people are using old stuff that needs updating. 

Merely removing the constant hard-coding its value everywhere the constant is used doesn't fix the problem. It only hides the fact that people using outdated character sets and collations have some work to do to bring their stuff into the modern era.

**Comment by drbyte** [comment]
@syntaxerror what's the back-story behind why you started new conversation yesterday on this otherwise dormant issue, which isn't really about "what is CHARSET defined as" at all?

Something else has caused you to start this conversation: what is it?

**Comment by syntaxerror** [comment]
If the upgrade script handled the database charset issues, it would help those poor people to run a more user friendly stores. Also by removing it and forcing UTF-8 all over would hopefully educate the extensions devs to avoid creating issues by saving their files in Latin1 or whatever, as some still does today.

**Comment by syntaxerror** [comment]
> @syntaxerror what's the back-story behind why you started new conversation yesterday on this otherwise dormant issue, which isn't really about "what is CHARSET defined as" at all?
> 
> Something else has caused you to start this conversation: what is it?

Lol, nothing else that i was looking at the language issues and found this. At the same time as I'm helping one of those poor store owners to fix their charset issues... :)

**Comment by syntaxerror** [comment]
Btw! Regarding:
> which isn't really about "what is CHARSET defined as" at all?

That's true, but still it's related. Making it a system default would solve both.

**Comment by syntaxerror** [comment]
> Zen Cart's default database collation has been utf8mb4 since v1.5.6

Btw! Noticed you're using collation set to **utf8mb4_general_ci**  instead of **utf8mb4_unicode_ci** or better, so I'll recommend reading t.ex. this then: https://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci

_*Just a language interested translator who like to see systems working nicely in different languages, preferable with multilingual support out of the box. ;) Thanks for reading, over and out, and sorry for bothering you. :)_

**Comment by drbyte** [comment]
@syntaxerror would you mind testing this utility on the database you're converting?

https://github.com/zencart/utf8mb4-converter

**Comment by syntaxerror** [comment]
Cool Chris, great work, I'll test it as soon as possible.
But for this particular site I can't as it's a 1.5.5 at the moment, and it's still unsure if it's going to be updated or migrated.

**Comment by scottcwilson** [comment]
Closing; UTF8 is now the recommended charset and a utility is available for conversion.

**Comment by torvista** [comment]
> UTF8 is now the recommended charset and a utility is available for conversion.

I'd point out that this comment is relevant for the off-topic/hijacked conversation but not the original issue: whether CHARSET should be in a language file.

**Comment by syntaxerror** [comment]
> > UTF8 is now the recommended charset and a utility is available for conversion.
> 
> I'd point out that this comment is relevant for the off-topic/hijacked conversation but not the original issue: whether CHARSET should be in a language file.

Well, the conclusion from what you refer to as off-topic/hijacking is that it should NOT be in the language files, but better defined elsewhere if there actually is a need for it. ;)

**Comment by torvista** [comment]
ok, thanks,
