### ISSUE TITLE
array syntax: traditional or short

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#2999]
IDE likes to suggest short array syntax is the path to happiness.
Does the team have a preference?

1) $contents[] = array('text' => '<br>' . TEXT_INFO_DATE_ADDED . ' ' . zen_date_short($sInfo->specials_date_added));
or
2) $contents[] = ['text' => '<br>' . TEXT_INFO_DATE_ADDED . ' ' . zen_date_short($sInfo->specials_date_added)];

**Comment by drbyte** [comment]
I didn't respond immediately when you posted this because I didn't want people to think that "my" post should shut down any discussion on the topic.

I will point out that the only reason to use long syntax is to prevent pain for upgraders:
Anyone currently running ZC 1.5.1 or older (which requires PHP 5.3 or older) will not be able to "stage" an upgraded version of their site if the upgraded version uses short-array syntax.

So I'm torn: While I definitely prefer short syntax, I don't enjoy forcing people into an unnecessarily painful upgrade path.

**Comment by lat9** [comment]
Having 'thumbs-up'd that, it's kind of water-under-the-bridge at this point, since there are a number of short-array-syntax changes already booked.

**Comment by drbyte** [comment]
Agreed. Again, torn.

v1.5.1 was the "latest official" release until July 2014 when 1.5.3 was published, and then 1.5.4 in Dec 2014.

So, that's 5+ years during which someone "had the chance" to upgrade without this PHP-version-constraint pain.

I guess they could just do a temporary step into 1.5.6 so they can get onto newer PHP (ideally 7.x), before going to 1.5.7.

**Comment by torvista** [comment]
I think it takes a non-trivial effort to stay on 5.x these days (my hosting does not offer anything below 5.5, and makes it clear 5.5, 5.6, 7.0 are obsolete), so those late adopters should be well aware that they are on borrowed time and should be planning to upgrade before they are pushed by their hosting. If not, well, that is a non-businesslike way to run a business and I don't have much sympathy for that lethargy. They are custodians of people's data and should always be on top of the latest version.

**Comment by wiztechinc** [comment]
well, I just upgraded someone from 1.5.1 recently. Not their fault - whoever was taking care of stuff just let it go on a private server. I was the one who had to upgrade them. The only cost the website owner is extra money - I have to deal with the fall out and problems. If you don't feel for them, you really should consider us who do upgrades.

**Comment by dakanji** [comment]
Thumbs up for long syntax over the short one here.

Clarity over Brevity always.

**Comment by drbyte** [comment]
Various considerations:

1. First-Time Upgraders.
  This is the hardest situation to accommodate, as they're not familiar with how to recognize when a problem is a result of something in their control, or something they've done, or something they haven't considered.
  In this situation an ideal user-experience would be to present a message alerting the PHP version constraint; I suppose then offering suggestions for how to stage it in a compatible environment (instead of their current outdated server) is useful too, albeit necessarily brief.

2. Experienced Upgraders.
  These folks will benefit from the same version-constraint screen above. I expect they're capable of staging in a compatible environment independent of the outdated server. Mea culpa.

3. Modern PHP practice uses short-array syntax. Everybody sees it as best-practice nowadays.

Given these considerations I suspect the best course of action is to do early-detection before any short-array syntax files are used/loaded/cached, and display a friendly message about compatibility.

**Comment by drbyte** [comment]
Even with this early-alerting in place, there is a caveat: short-array-syntax must be avoided in 3 places:

1. zc_install's system-inspection and all files used until the PHP version failure is reported.
2. catalog - until application_top is done
3. admin login page (er, well, maybe that's moot)
