### ISSUE TITLE
Multi lingual Zen Cart installer

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#3018]
The Zen Installer has the option to display in multiple languages (like Magento, Woo-commerce, and others), but only English is present at this time.
So at the moment this features is pretty useless.

Can we add language files to the Zen Cart package so people can use the installer in their native language? Since the English of not all shop-owners is sufficient, or they don not speak English at all.

Having a multi lingual installer may help to get more people to use Zen Cart again.

**Comment by torvista** [comment]
Speaking only for spain, there is zero community here. I make the point in my language pack that if you can't get through the installer in english, look for another solution, as all support info is in english and you'll only be frustrated lookling for answers, instead of building the business.

That said, since all the rest of the code is multilingual-ready, so should be the installer. It's not much text.
At least it shows willing on the part of the project to reach out. You can't do anymore to encourage more users.

**Comment by drbyte** [comment]
I'm not convinced that appearing in English-only is a primary deterrent.

But ... I'm curious: Which languages were you anticipating would be included?

I'm certainly not qualified to maintain them, as I only know a couple.

**Comment by torvista** [comment]
> I'm not convinced that appearing in English-only is a primary deterrent.
No.
I just get the feeling it's something to be done for completeness rather than need....programmer point of view rather than business person,  I think.

**Comment by Zen4All** [comment]
We could start with a few
English, Dutch, French, German, Spanish.
Then if people want to contribute we can add more.

There are a lot of German and French people who rater use their native language then English, even if they understand it. The Germans even build their own translated Zen cart version.

**Comment by drbyte** [comment]
I'm okay with PRs to put those in. Particularly if you're willing to maintain them.

We should of course test to be sure that if a define is missing in another language that it falls back properly to the existing English define, so at least something is said ;)

**Comment by Zen4All** [comment]
I'll push the Dutch tomorrow.
I am willing to maintain the files.
The missing defines is something that should be solved on a global level for Zen Cart, as this is also true for admin, and shop side

**Comment by drbyte** [comment]
> The missing defines is something that should be solved on a global level for Zen Cart, as this is also true for admin, and shop side

It generally already does this for admin and catalog.

**Comment by Zen4All** [comment]
Great, I missed that updare

**Comment by Zen4All** [comment]
> It generally already does this for admin and catalog.

mmm.... I just did a quick test on a Zen Cart 1.5.7 admin,in which i removed some defines for a second language, but they are not substituted with the first language. I only see the defines printed on screen.

**Comment by mc12345678** [comment]
A lot of what I've been seeing regarding the path of language defines has been to prevent the potential duplicate load which means that only one language file is loaded (not likely to catch/replace a missed define in the secondary language).  It seems as if there is some preparation for the upcoming/discussed array style of defines which would in essence need a reverse load compared to the current process.

Array method (modifiable on a whim):
1. Load primary/source language.
2. Load alternate language.
3. Load overrides.

With the define methodology (once defined can not be modified), has to be the other way around:
1. Load the overrides. <-- currently isn't really done until later if at all.
2. Load the alternate language.
3. Load the "backup" primary/source language.

**Comment by drbyte** [comment]
Yes. Adjusting language translations is a MAJOR and INTRUSIVE change. Too large for discussion here in relation to zc_install. It requires breaking all admin logic (because its overrides are backwards, ie: fallbacks don't), and revamping a bunch of catalog logic.

My point about fallbacks posted earlier is just that if we're adding a few language packs to zc_install then zc_install should be tested to see whether its multilang logic is correct. While it's present I've not tested it in ages, so don't know if it's missing something.

**Comment by torvista** [comment]
Slightly off thread....once new users have got all excited over installing in their own language and have easily got to the end screen...now what? They have to go hunting for a language pack to manually install? Ouch.

Ideally they would be presented with a nice "Install Language pack" button which would automagically download and install the language pack as it is at that moment (from Github), and optionally set it as the default language.
Meanwhile, back in the real world, I'm just saying this may yet need more glue in there than just the translation of the installer to join things up.

**Comment by Zen4All** [comment]
> Yes. Adjusting language translations is a MAJOR and INTRUSIVE change. Too large for discussion here in relation to zc_install. It requires breaking all admin logic (because its overrides are backwards, ie: fallbacks don't), and revamping a bunch of catalog logic.
> 
> My point about fallbacks posted earlier is just that if we're adding a few language packs to zc_install then zc_install should be tested to see whether its multilang logic is correct. While it's present I've not tested it in ages, so don't know if it's missing something.

Started to do some testing. Most translations are working fine.
One thing that does not work are the help popups (when clicking on the blue labels), These are always shown in English, even though a translation is present.

**Comment by drbyte** [comment]
> once new users have got all excited over installing in their own language and have easily got to the end screen...now what? They have to go hunting for a language pack to manually install? Ouch.

Ya, I've been thinking the same. Makes me revisit whether this is a good idea.

**Comment by torvista** [comment]
> Makes me revisit whether this is a good idea.
Depends what the master plan is for Zen Cart.
If the plan is world domination, then the language thing has to be inplace end-to-end.
If then users come to a halt because they cannot find community support in their language, well that's out of developer's hands but at least as much as possible has been done to facilitate it.
"If you build it, they will come"...maybe.

**Comment by zcwilt** [comment]
I too have a PR ready to go for this.
It uses arrays rather than the legacy define file.

While the use of arrays for the installer is fairly easy to do, the development load for doing this in both admin/catalog is as mentioned earlier, very high.

**Comment by Zen4All** [comment]
I am all for the array. We do not have to do all the strings in one go. We could start converting with a few files at a time.

**Comment by zcwilt** [comment]
A bit off topic, but.
Not particularly bothered about the conversion of defines files, as I have a little utility script for turning these into array based files.

I guess 1 major issue is that for some time we are going to need a hybrid system, unless we want to break all plugins straight away. 

Will play around with some ideas and maybe create a new issue to cover conversion.

**Comment by drbyte** [comment]
Closed in #3115

**Comment by zcwilt** [comment]
Have created a gist containing the script I use to convert defines to arrays.
It is not perfect however.

https://gist.github.com/zcwilt/866106fc9791c64aa9e0e80b7652fb26


The main problem is managing defines that refer to other language defines 

e.g. 

`define('DATE_TIME_FORMAT', DATE_FORMAT_SHORT . ' %H:%M:%S');`

This gets converted to 

`'DATE_TIME_FORMAT' => DATE_FORMAT_SHORT . ' %H:%M:%S',`

As DATE_FORMAT_SHORT is undefined at this point it will through warning/notices.

It needs hand tweaking to 

`'DATE_TIME_FORMAT' => 'DATE_FORMAT_SHORT' . ' %H:%M:%S',`

Files like admin/includes/languages/english.php need even more attention due to the amount of php code contained within.

**Comment by Zen4All** [comment]
@zcwilt Thanks,I'll give it a try this week, and let you know how it went.

**Comment by torvista** [comment]
> That said, since all the rest of the code is multilingual-ready, so should be the installer. It's not much text.

Wrong, it's four pages (since I do it Word for spell-checking) of translation. Very hard to justify...

**Comment by scottcwilson** [comment]
Multi-lingual friends: it would be great if someone with experience in this area would convert https://www.zen-cart.com/wiki/index.php/Languages (and any other relevant content) and put it here: https://docs.zen-cart.com/user/localization/ 

As an American, I am uniquely unsuited to this job.  WE JUST SPEAK LOUDER TO BE UNDERSTOOD.

**Comment by torvista** [comment]
What makes you think the Brits are any different?
