### ISSUE TITLE
zc_install: Database upgrade completion indication

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3021]
I'm in the process of upgrading a site (zc155f->zc156c) that has a _humongous_ database (75k+ customers, for instance).  When I ran the `zc_install`, I thought that the process had hung but after getting a cup of coffee, it _finally_ completed.

That caused confusion for the site's other programmers, too, running independent test upgrades in preparation for the live site's actual upgrade.  Bailing during that installation process is, of course, not a "good thing".

Is there any chance of getting some progress indication?

**Comment by drbyte** [comment]
The best a progress-indicator could do is tell you what percentage of "statements have run".
Unfortunately that's not realistic about "how long it will take".

The actual culprit is the `alter table` statements against the order-related tables, since those are massive tables with lots of records to update. I've run into the same confusion a couple times. Even accidentally ran the upgrade twice not realizing it was normal; just slow cuz the table was huge.

**Comment by lat9** [comment]
Understood, but it would be better than _silence_.

**Comment by lat9** [comment]
The other programmers for the site I mentioned above did another test-run of the install process.  They tried checking the MySQL 'processlist' during the process, but saw nothing running.

Note also that the "Completion" message never displayed automatically, but after waiting for some (I'm checking to see how long) amount of time, they simply refreshed the screen to see:
![image](https://user-images.githubusercontent.com/2685585/73124578-01a71880-3f6b-11ea-87bb-afecbb20d50a.png)

**Comment by zcwilt** [comment]
It should be fairly easy to add the json/ajax progress indicator to upgrades similar to the clean install.

**Comment by scottcwilson** [comment]
This would be a great comfort feature.  Would someone like to sign up to take it?

**Comment by drbyte** [comment]
Regardless what tweaks we make to the UI, I think we should embrace a couple standards in how we present the Upgrade SQL:

1. Put all potentially-long-running upgrade steps at (near) the end of any given version's upgrade SQL file.
2. Ensure that one of the "detections" (`systemChecks.yml`) of whether the upgrade is complete is able to detect whether these longer-running steps has completed.

This way if someone bails due to apparent non-response, then subsequent refreshes of the upgrade-detect page will show the need to re-run the upgrade steps. (And we already fail silently on duplicated steps.)
Some of these longer-running steps may take longer than the store's PHP-max-time-limit BUT they will complete in the background, because MySQL will finish them whether PHP stays around to wait or not.

Obviously sometimes one upgrade step depends on another being done already, so there may be a need for some quick statements interspersed with long-running statements. But if they're towards the end of the script and well-detected, it should avoid potential db issues caused by aborts-due-to-apparent-silence.

**Comment by zcwilt** [comment]
@drbyte @lat9 

Do we have any ideas as to which parts of the upgrade are the major culprits here.

**Comment by zcwilt** [comment]
I have been thinking about ways to better show the progress of the install/update and am toying with this.

Have a separate modal to show more detailed information about what the install/update is doing.

This would be triggered by specifically constructed comments within the sql files 

e.g 

# FEEDBACK: About to alter the Orders table. This may take some time

**Comment by drbyte** [comment]
Yes, that big bold text would do the job!  🤣 

<img width="589" alt="Screen Shot 2024-01-06 at 4 43 52 PM" src="https://github.com/zencart/zencart/assets/404472/842ac3e5-45c6-4fae-911d-cd37d426c094">

**Comment by drbyte** [comment]
> Do we have any ideas as to which parts of the upgrade are the major culprits here.

It's the ones that touch the largest tables. For example, when we do `alter table` on `orders`, if there are gazillions of rows and the site is a busy one, it can take a long time for the server to update every row. 
Obviously, upgrades are normally done while the site is down-for-maintenance so the table itself should be fighting for locks, so not terribly worried about that. Probably only `whos-online` and `sessions` table fight for locks even in maintenance mode. And we usually truncate those at the beginning of upgrades, so kinda moot.

**Comment by scottcwilson** [comment]
This is a nice improvement.

**Comment by lat9** [comment]
Closed via #6137.
