### ISSUE TITLE
PHP Warning issued on initial admin-access post initial installation

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3036]
Running PHP 7.3, 'current' zc157 branch. A log, similar to the following, is generated:

```
[24-Jan-2020 13:06:15 Europe/Berlin] Request URI: /test_utf8/claCk-pvS-brIck/index.php?cmd=login, IP address: ::1
#1  substr() called at [C:\xampp\htdocs\test_utf8\claCk-pvS-brIck\includes\classes\class.admin.zcObserverLogEventListener.php:145]
#2  zcObserverLogEventListener::prepareLogdata() called at [C:\xampp\htdocs\test_utf8\claCk-pvS-brIck\includes\classes\class.admin.zcObserverLogEventListener.php:55]
#3  zcObserverLogEventListener->updateNotifyAdminActivityLogEvent() called at [C:\xampp\htdocs\test_utf8\includes\classes\class.base.php:103]
#4  base->notify() called at [C:\xampp\htdocs\test_utf8\claCk-pvS-brIck\includes\classes\class.admin.zcObserverLogEventListener.php:210]
#5  zen_record_admin_activity() called at [C:\xampp\htdocs\test_utf8\claCk-pvS-brIck\includes\functions\admin_access.php:519]
#6  zen_reset_password() called at [C:\xampp\htdocs\test_utf8\claCk-pvS-brIck\includes\functions\admin_access.php:583]
#7  zen_validate_pwd_reset_request() called at [C:\xampp\htdocs\test_utf8\claCk-pvS-brIck\login.php:47]
#8  require(C:\xampp\htdocs\test_utf8\claCk-pvS-brIck\login.php) called at [C:\xampp\htdocs\test_utf8\claCk-pvS-brIck\index.php:11]
--> PHP Warning: substr() expects parameter 3 to be int, string given in C:\xampp\htdocs\test_utf8\claCk-pvS-brIck\includes\classes\class.admin.zcObserverLogEventListener.php on line 145.
```

**Comment by drbyte** [comment]
I'm guessing this is related to https://github.com/zencart/zencart/commit/dc4ba2e8f5adeca66f0233bb5fd5e32756688534

But then the original reason for increasing this was to accommodate the situation where that substr wasn't doing the truncating in the first place.

Chicken-Egg ... 

Hmmmm

**Comment by ScotteSolutionsLtd** [comment]
This happens (for me) when zen_field_length doesn't return an integer for the 'attention' column.

'attention' is a MEDIUMTEXT column so mysql _won't_ return a value indicating its size, it returns an empty string. Therefore zen_field_length also returns an empty string. Mysql documentation says a MEDIUMTEXT is 16MB large so in this case truncating may not be necessary, though I have no context on what the column is used for.

If the truncating _is_ necessary to prevent more than 16 MB from going into that field (eg. super nasty admin backtrace?) then:

- an extra if statement in the logging method **prepareLogdata** could be in order to truncate values larger than 16MB
- perhaps a condition in the **zen_field_length** function can account for the TEXT type fields and return large integers for column sizes as defined in the docs: https://dev.mysql.com/doc/refman/5.7/en/storage-requirements.html#data-types-storage-reqs-strings

Just throwing it out there, maybe there's something else going on.

**Comment by drbyte** [comment]
The truncating is probably largely moot if the field is increased to MEDIUMTEXT. 
I think for now simply skipping the substr step is sufficient.
