### ISSUE TITLE
Upgrade of database fails on zc_install

### ISSUE THREAD

**Issue by judygunderson** [zencart/zencart#3056]
Started with vanilla 1.5.7 install.  Then brought over tables from a 1.5.6c functioning website.

It gives me this

Upgrade to version 1.5.6 completed.
Could not update to version 1.5.7. We detect that you currently have v1.5.5, and must perform the updates to get to version 1.5.6 first.

Doesn't make any sense because the database is already upgraded to 1.5.6

**Comment by judygunderson** [comment]
Thought I had better add this - it is from the 1.5.6c site I am upgrading / testing with


Server Host: ()
Database: tjsattic_156c
Server OS:
Server Date: 02/08/2020 19:59:01  
Server Up Time:
HTTP Server: Apache
PHP Version: 7.1.33 (Zend: 3.1.0)
PHP File Uploads: On
Upload Max Size: 180M
PHP Memory Limit: 128M
POST Max Size: 180M
Database Engine: MySQL 5.5.5-10.1.44-MariaDB
Database Host: localhost (127.0.0.1)
Database Date: 02/08/2020 19:59:01
Database Data Size: 871 kB
Database Index Size: 718 kB
MySQL Slow Query Log Status: On
MySQL Slow Query Log File: server-slow.log
MySQL Mode: (None set)

Zen Cart
Zen Cart 1.5.6c
Database Patch Level: 1.5.6
v1.5.6c   [2019-09-02 00:44:41]   (Version Update 1.5.5->1.5.6c)
v1.5.5a   [2016-07-30 19:28:45]   (Version Update 1.5.4->1.5.5a)
v1.5.4   [2015-09-24 16:49:08]   (Version Update 1.5.3->1.5.4)
v1.5.3   [2015-09-24 16:49:08]   (Version Update 1.5.2->1.5.3)
v1.5.2   [2015-09-24 16:49:08]   (Version Update 1.5.1->1.5.2)
v1.5.4   [2015-09-21 10:48:53]   (New Installation)
v1.5.4   [2015-09-21 10:48:53]   (New Installation)

**Comment by drbyte** [comment]
In https://github.com/zencart/zencart/blob/1226c58d171a23dd3a23c6283d3e9946a009d70d/zc_install/includes/systemChecks.yml#L266-L287 zc_install checks for 3 conditions to see if the v1.5.6 upgrade steps have been performed on the database or not. If you've overturned any of those steps (ie: altered the table configurations from what it's testing for) then it will assume the steps haven't all been completed. Hence the objection to proceed.

**Comment by judygunderson** [comment]
So how are you supposed to upgrade a 1.5.6 web site if it has a module installed that might affect the database?  Very seldom do you find a site that doesn't have mods - some HEAVILY modded.

**Comment by drbyte** [comment]
Surely you're not saying that the core dev team needs to be completely familiar with every mod that could change the site, are you?

Allow me to rephrase: Go check your database to see which of those 3 situations is no longer correct, and figure out why. If for some reason the "why" is because something has reverted the structure to older format, then fix it. If the "why" is because something has assumed some other approach is more appropriate for the site, then maybe you can just temporarily set it back to what v156 expects, run the upgrade, and then redo whatever the mod requires. Kinda identical to how you merge PHP customizations. 

If in the process of your research you stumble upon something that's highly likely to affect the majority of sites, then report *that* information so that a fix for the masses can be offered. Thus far as far as I can tell it's only this one site affected.

**Comment by judygunderson** [comment]
Ahhh come on... surely the dev team knows all 15,000 mods written for ZC!  LOL

I have tried it on two different 1.5.6.c sites with no joy yet.  Will keep digging.

Thanks for your input.

**Comment by drbyte** [comment]
> I have tried it on two different 1.5.6.c sites with no joy yet. Will keep digging.

Translating the code above:
1. `sessions` table has a `sesskey` field of type `varchar` length `191` chars.
2. `ezpages_content` table has a field named `pages_html_text`.
3. `configuration` table has a `val_function` field of type `text`.
Which of those is not true in your database, and why?  This can be checked yourself in phpMyAdmin before you even attempt an upgrade.

**Comment by judygunderson** [comment]
Ok, thanks Chris.  I will check it out.
