### ISSUE TITLE
Add telephone to address(es)?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3088]
Maybe this is more a trade thing for distinct addresses where the shipping address needs a specific contact name and number for the courier, normally different to the customer invoicing address and contact details. 
But anyway, I did this long ago, any interest in adding this or reason against it?

**Comment by lankeeyankee** [comment]
I think it would be good although it would require another config switch which many would find as less than ideal.

**Comment by torvista** [comment]
Why would it need an admin switch?

**Comment by lankeeyankee** [comment]
Not everyone will want this and would want the option to turn it off. I personally have no issues with lots of config settings although I think at some point a reorganizing would be helpful, with headings within a page to delineate the sections. Because right now it can be confusing to find the one you need, but I digress.

**Comment by wiztechinc** [comment]
Some folks may not want the phone number showing? I was actually wondering about this yesterday. Seems silly to have the phone number field and it rarely ever shows up anywhere (just 2 payment mods?). Folks would expect more to be done with it.

**Comment by lankeeyankee** [comment]
We require phone numbers since gmail, hotmail/live/msn, yahoo and some others can block our emails as spam because they have links. And if we have a question about their order it is usually the fastest way to reach them. But we have not included them in the shipping label(yet).

**Comment by wiztechinc** [comment]
lankeeyankee beat me to it. But there's no question that the admin settings are just problematic. The reason why I was thinking about this yesterday is a site I made years ago to document the settings. I'm working on updating it. I cannot live without having a way to search for a setting - even this many years later. http://allthingszencart.com

**Comment by drbyte** [comment]
> I cannot live without having a way to search for a setting - even this many years later.

I guess you haven't looked into the Developers Toolkit in awhile?

**Comment by wiztechinc** [comment]
Well it certainly works better than it did. But if you are in admin and trying to find a key, sometimes one prefers to find out where to look - by using another browser window so you don't have to go scrabbling about in admin. As useful as the developer tool is, I think perhaps the average site owner is never aware of it and how to use it. Anything listed with developer as the name will not be where a lay person goes to find information first.  So as always words and messaging are crucial - which, sorry everyone, is not a forte of many developers. That's why before I did the allthingszencart site, I offered to do something similar for the community.

**Comment by drbyte** [comment]
> allthingszencart site, I offered to do something similar for the community

It's definitely a handy reference. Thanks for doing that.

**Comment by wiztechinc** [comment]
and you don't have to log in to admin anywhere to find out what you need. It's going to take some work to get it updated and mobile. Now I'm wondering if I should bother.

**Comment by torvista** [comment]
In my opinion...
1) Very off-topic:
The admin settings labyrinth was solved for the moment by the addition of the "Search in Configuration Settings/Keys" option. After 12 years, I bother less than ever to remember "where" and just use this, although that's probably due to old age.
When there are so many admin options available (a strong indicator as to the capabilities of ZC and so not necessarily a bad thing), it is impossible for any admin interface to be intuitive for all types of intuitions or the lack thereof.... and there are many more relevant issues to be addressed before the never-ending discussion of "where to put which option" begins.
But since most admin users should be able to articulate a keyword related to an option they seek, and they can type, I think that search is perfectly adequate. If they cannot, should they really be in the admin of a business application?

If an external website was really required to find things (as maybe in the past), that would indicate the GUI desperately needs improving. But I don't think that is the case now.

2) As for the topic under discussion, I still don't get why an option is required at all at the moment.
 I'm just proposing adding a column for telephone to the address definition table. 
Where that leads off to is a subject for later development.

**Comment by drbyte** [comment]
> I'm just proposing adding a column for telephone to the address definition table.
>  Where that leads off to is a subject for later development.

I have no objection to the addition of the column.

Of course one would argue that there's little point having the column if there's no corresponding UI updates to match, particularly on the Admin side where data-entry might be needed in order to edit it, or at least read-only view it. (Currently there's no admin UI for editing customers' secondary addresses, and the current phone number fields are stored to the customer record not to a specific address-book record.)

As to generating an address-label HTML snippet with/without the phone number (if it's available), there will be varying opinions on when it's relevant for that to be included or not. I'm inclined to not include it in the generated HTML, and simply retrieve and render it when relevant in the places it's needed. Unfortunately that may require a repeated db query, but given it'd be an immediate repeat it'll already be cached in the db engine so I'm not bothered about performance hit there, particularly since it wouldn't be occurring on any high-traffic pages anyway. Rendering it on-demand when needed, instead of as part of the existing function which generates address `<label>` HTML would negate much of the need to worry about config switches.

**Comment by wiztechinc** [comment]
"If an external website was really required to find things (as maybe in the past), that would indicate the GUI desperately needs improving. But I don't think that is the case now."

One thing my website does is offer more explanation. Many settings simply are not explained and when I look at one and don't know what the results will be if I change something, then yes, an external website or something else is necessary. There used to be books and now there not; many of the tutorials on zen cart are out of date, most of the youtube tutorials are out of date, finding answers on the forum is never easy, etc. Anyone - business owner, lowly employee and even developers need help sometimes. I also offered to set up a help facility in admin years ago and that would be the best way to do this. I'm all in for a concerted effort but fully expect to be ignored again. Sorry if I sound a bit bitter but as a writer, teacher, trainer, I come from a different place than most who work on zen cart. I'm a zen cart trainer and I know what a struggle it can be without a solid source. So, yep off- topic. Shall I start a new thread here or will that be for naught?

**Comment by lankeeyankee** [comment]
>        I'm just proposing adding a column for telephone to the address definition table.
>        Where that leads off to is a subject for later development.

Sorry, I misunderstood what you were saying. I thought it was to add the phone number to the shipping address which would show up in a label.

**Comment by drbyte** [comment]
> Many settings simply are not explained

> offered to set up a help facility in admin

> Shall I start a new thread

Yes, new thread. 

In it please explain more about how you envision it would work. I can't find past descriptions of your offer, so let's start afresh from where we're at today, regardless of "back then".

Also, from a technical perspective, keep in mind that I'm not in favor of adding any database entries for help text. It'd need to go into PHP files.

**Comment by wiztechinc** [comment]
No problem, thinking text files

**Comment by torvista** [comment]
ok, I'm thinking of two fields for the address_book table
entry_contact
entry_telephone

with initial code in create account populating them with the customer name (firstname+lastname) and customer telephone.

From a trade perspective, I have clients where the "customer" is a company (single invoicing details) with multiple shops who order individually and have the products sent to those shops separately. But, I would not allow them to create their own addresses.
From an end-user perspective, is that a fraud vector, allowing completely different shopping address details...or should the customer name always appear, followed by a c/o for the contact name?

I think there is a lot of discussion possible as to implementation, but I was interested in getting these fields in there before release, so at least they are there to build on.
If that's ok , I'll do a PR..?

**Comment by scottcwilson** [comment]
Suggest this thread be closed and a new one opened titled "Add telephone field to TABLE_ADDRESS_BOOK".  @torvista 's Mar 6 post would be a good start to that thread.

**Comment by torvista** [comment]
Why not just change the title?

**Comment by scottcwilson** [comment]
Because it's filled with misunderstanding and completely off topic remarks.  A fresh start would be better.
