### ISSUE TITLE
admin: who's online, php noticePHP Notice: Undefined variable: info

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3109]
(Report All Errors)
PHP Notice: Undefined variable: info ADMIN/whos_online.php on line 339.
Triggered by clicking on a different session.
I added some code to output the variables concerned.
![Clipboard01](https://user-images.githubusercontent.com/4391026/76168150-22b77780-616d-11ea-8939-e1aaf307a1e2.gif)
 On a session click, $info is always empty and $get[info] != session_id so the code that loads $info does not run at 340.

**Comment by proseLA** [comment]
i am not able to reproduce this error.  how would one reproduce it?  not sure how to click on a different session.

that said, it does seem the Last URL column as well as the Session column is never displayed in the table.  why was that left in the code?

https://github.com/zencart/zencart/blob/50020d417efe52eb756046ee4843e9f18de36caf/admin/whos_online.php#L389

https://github.com/zencart/zencart/blob/50020d417efe52eb756046ee4843e9f18de36caf/admin/whos_online.php#L392

**Comment by torvista** [comment]
Actually a 156 version has the same issue, either you need to test on a live site with real separate sessions, or one test site using two browsers where one is through a vpn (opera has one built in) and show the admin session. That'll give you two sessions.
You need the Report All Errors mod on to show the error.

**Comment by proseLA** [comment]
what happens if right after this line:
https://github.com/zencart/zencart/blob/50020d417efe52eb756046ee4843e9f18de36caf/admin/whos_online.php#L336
you add:
```$info ='';```
would the error go away without any unintended consequences?

i am of the opinion that one should not need to install a plugin to demonstrate an error.  tell me what vars in php.ini need to be changed in order to see the error; either via the ZC logging, or in the apache log (assuming you are running apache and not nginx).  

with regards to multiple sessions, i am not sure that is needed to demonstrate the error i potentially see.  if this is not the error, then w/o modifying a base install, how could one see this error?

**Comment by torvista** [comment]
That change you suggested works as far as I can see. Thanks,

Regarding errors, the idea of the plugin (for me at least) is pre-emptive strikes on errors that php will be notifying of in the near future.
Due to me using it on a live site for the last year I have reduced these notices and warnings to zero, and fed them all back into the ZC157 core.
On the forum people are gradually posting about these debug errors ocurring in ZC156 as their hosting incrementally updates php, and it gets more strict.
I think it is especially important that a fileset with such a long incubation period as ZC has these far-in advance fixes in place, or a few months after a release/way before the next release, the forum starts to be clogged with threads about them.
In the end, these **are** errors albeit non-breaking, and the investigation of which does prompt 
 (me at least) to review the file for other low-hanging errors (html usually).

I know others use Report All Errors, I really think it should be in the core as an important developer tool option to encourage core file review/improve a plugins. The more tools that point out errors, the better, in my view,

**Comment by drbyte** [comment]
> i am of the opinion that one should not need to install a plugin to demonstrate an error. tell me what vars in php.ini need to be changed in order to see the error; either via the ZC logging, or in the apache log (assuming you are running apache and not nginx).

Ya, you don't need a mod for that. Just set error-reporting to E_ALL in `/includes/extra_configures/enable_error_logging.php`: 
`$errors_to_log = E_ALL;`

**Comment by proseLA** [comment]
thanks @drbyte for that.

sorry for the late response.  i could see the 'error' but i could not get my server to see it.  it was then that i realized i was running php7.1 on an older debian box; tried updating it; failed; built up a new one and now running buster and php7.3.  hard to keep track of all my virtual boxes for testing.  

i suppose my question is now whether this is a problem only visible in php7.4 as 7.3 does not report the problem.  in the following code, the empty does not produce an error, while the print_r does:
```php
                 //$info ='';
                  echo '--------> ' .empty($info) . ' <----------';
                  print_r($info);
```

i know the solution has already been merged, but i am now curious if the problem will only start in php7.4 or if this is just another line of wasted code.  thanks.

**Comment by drbyte** [comment]
`empty()` treats "not declared", "not defined", "doesn't exist", "is null", "is blank" and "equals 0" as `true`.

`print_r()` expects the variable to exist, and if it doesn't, will throw an undefined-var notice, just like most other parts of the code will.

`empty()` is a handy desired equivalent of 
`isset() && !is_null() && != 0 && != false && != '0' && != ''`

So, if you're checking whether a variable is present, and not empty and not false and not worried about its value being 0, `empty()` is very expressive, and saves cluttering the code with a bunch of other conditions.

I'm using PHP 7.4 and haven't run into it being a problem. But since it seems evident that people want to add other checks in the code before where that var actually gets set, I merged it so that the var is initialized early.  For readability it does help to make it clear that it's expected to be a string.
