### ISSUE TITLE
Suggestion : Choose Hyphen over CamelCase in IDs and Classes Naming 

### ISSUE THREAD

**Issue by IronLady** [zencart/zencart#312]
This is just my opinion on why we should choose Hyphens over Camel Case style.

#### 1. "Hyphen Style" is easier to read than "CamelCase Style"
```css
#acctNewslettersDefaultHeading {}
#acct-newsletters-default-heading {}
```
The second line is absolutely more readable.

#### 2. CSS syntax use hyphen as its delimiter
```css
#acct-newsletters-default-heading {
   padding-top: 0;
   font-size: 1em;
   ...
}
```
By default CSS rule properties using hyphen. <code>padding-top, font-size, overflow-x, ...</code>

#### 3. "Camel Case Style" can create a new inconsistency/ambiguity/etc
```css
.header {}
.pageHeader {}
```

I know that the core code use CamelCase Style and it may take more effort to migrate to Hyphen Style. But, I think it it's worth to try for better consistency and readability.

**Comment by wiztechinc** [comment]
And then I disagree. I prefer camel code - having chosen it years ago as the better option. No one ever told me which to use.

**Comment by drbyte** [comment]
@IronLady For the benefit of broader consideration, can you cite online references where the industry "best practices experts" are advocating hyphenated-everything specifically in favor over camelCase which you're disliking?

**Comment by drbyte** [comment]
FYI, 
I'm not disagreeing with you at all. Just have to properly assimilate relevant information so that people who challenge the decision later can see the supporting references.

In fact I tend to agree with your suggestion, personally.

**Comment by DivaVocals** [comment]
@drbyte there aren't any studies out there.. If you Google "camelcase versus hyphens", and you will see a TON of stuff that amounts to nothing more than debates and personal preferences.. I however found this answer the most useful: 

>[Source:](http://programmers.stackexchange.com/questions/186407/why-bootstrap-3-changes-camelcase-to-dashes-is-it-more-readable)
There are lots of things in software design and development that are driven, not by the result of formal studies, but by convention and pragmatism. That's why defacto standards exist; they arise out of everyday use, and many people discovering over time what works and what doesn't.

>When it comes to choosing between camelCase and hyphenated names this is particularly true, as studies are inconclusive:

[To camelCase or under_score](http://ieeexplore.ieee.org/xpl/articleDetails.jsp?tp=&arnumber=5090039&contentType=Conference%20Publications&queryText=underscore%20camelcase) - Dave Binkley, Marcia Davis, Dawn Lawrie, Christopher Morrell

>The study described in this paper shows that although those without training take longer to recognize identiﬁers in the camel case style, all subjects are more accurate when identifying a camel-cased identiﬁer. In addition, subjects trained to use camel casing take less time to identify a camel-cased identiﬁer than an underscore identiﬁer.

The next step is to consider higher-level tasks in more realistic settings. One task would investigate the impact of camel casing versus underscores when reading blocks of code. For example, subjects might be asked to search for a particular identiﬁer. Another task would ask subjects to read natural language paragraphs modiﬁed to use camel casing or underscores. This would enable more direct comparisons with previous work done in psychology such as Epelboim et al.

[An Eye Tracking Study on camelCase and under_score Identifier Styles](http://ieeexplore.ieee.org/xpl/articleDetails.jsp?tp=&arnumber=5521745&contentType=Conference%20Publications&queryText=An%20Eye%20Tracking%20Study%20on%20camelCase%20and%20under_score%20Identifier%20Styles) - Bonita Sharif, Jonathan Maletic

>An eye-tracking study analyzing the effect of identifier style (camel-case and underscore) on accuracy, time, and visual effort is presented with respect to the task of recognizing a correct identifier, given a phrase. Visual effort is determined using six measures based on eye gaze data namely: fixation counts and durations. Although, no difference was found between identifier styles with respect to accuracy, results indicate a significant improvement in time and lower visual effort with the underscore style. The interaction of Experience with Style indicates that novices benefit twice as much with respect to time, with the underscore style. This implies that with experience or training, the performance difference between styles is reduced. These results add to the findings of Binkley et al.’s study. Future work includes conducting more eyetracking studies (with a larger subset of identifiers and larger subject sample), on reading source code consisting of both identifier styles, in the context of a specific task such as debugging. Another possible direction is to determine if there is an advantage for a programmer to change their current style to what is determined to be a better overall style.

Like @drbyte I don't disagree with the suggestion.. Just trying to help provide some frame of reference..

**Comment by drbyte** [comment]
This resource, referenced "in that other discussion", suggests hyphenated is preferred: https://mdo.github.io/code-guide/

And I know that Foundation and Bootstrap both use hyphenated.

I'm torn whether to leave ZC-specific classes and IDs as camelCase for distinction and to prevent clashes with a CSS framework.

**Comment by lhungil** [comment]
I'm a fan of hyphenated for CSS classes. Mainly just because in HTML all values are case-insensitive and using camelCase or PascalCase can be misleading.

I'd also prefer id attributes are not added to every element (and growing longer with each element in a tree). I'm not saying there should not be IDs on many of the common "parent" sections (there should be)! But every child element does not need to have an id attribute if it is close in the DOM to the parent element (a class attribute would be sufficient in this case). Why? It keeps the HTML content shorter (therefore keeping the download size smaller and the memory footprint for the browser smaller). Same reason optimizing images for mobile is a good idea.

I cringe a little at the thought of dealing with CSS conflicts when a CSS Frameworks is involved... But these are not too difficult to work around (and any good "base" theme will probably take these into account)... Just some thoughts.

**Comment by DivaVocals** [comment]
> I'm torn whether to leave ZC-specific classes and IDs as camelCase for distinction and to prevent clashes with a CSS framework.

>I cringe a little at the thought of dealing with CSS conflicts when a CSS Frameworks is involved... But these are not too difficult to work around (and any good "base" theme will probably take these into account)... Just some thoughts.

I think that in the case of dealing with CSS Frameworks that the best way to avoid conflicts is to have the base theme create it's OWN framework that will not conflict with a CSS framework.. Though there are inconsistencies with regards to classes and IDs in the current default template, for the **most part** there are few conflicts with Bootstrap currently.. I can't speak for Foundation, but I will assume the same generally holds true there as well..

**Comment by DivaVocals** [comment]
Just read the article @drbyte referenced in his [last post](https://github.com/zencart/zc-v1-series/issues/312#issuecomment-76845123)..

I agree with all except this section:
>Place media queries as close to their relevant rule sets whenever possible. Don't bundle them all in a separate stylesheet or at the end of the document.

I know others will disagree, but I am a fan of the MobileDetect script.. Media queries alone cannot possibly cover all of the range of what should or should not be included/viewed on mobile devices.. MobileDetect allows me to create a responsive template with behaviors that mimic a mobile specific template. For example in the template I am working on now, I grew weary of navigation menus trying to be all things to all sites.. I also don't really like that the way many of them work is by simply using different classes/IDs so that the desktop menu is hidden on smartphones and tablets, and the mobile menu is hidden on desktops and larger tablets.. I simply don't want the mobile menu rendered at all on desktop devices, and I don't want the desktop menu rendered at all on the mobile devices.. I wanted a menu expressly for smartphones and small tablets, and a completely different menu to be used with desktop and larger devices.. The Mobile detect script allows me to do this by rendering only on the devices I specify..

I also like that the MobileDetect script allows me to specify which stylesheets to load for mobile versus desktop.. Don't see how I can do that with one stylesheet.. or maybe it's just that I don't know how to achieve that with one stylesheet..

**Comment by IronLady** [comment]
> And then I disagree. I prefer camel code - having chosen it years ago as the better option. No one ever told me which to use.
> @wiztechinc

I guess we have to move on from our old habit and style. But, it's okay to disagree.


> @IronLady For the benefit of broader consideration, can you cite online references where the industry "best practices experts" are advocating hyphenated-everything specifically in favor over camelCase which you're disliking?
> 
> I'm torn whether to leave ZC-specific classes and IDs as camelCase for distinction and to prevent clashes with a CSS framework.
> @drbyte

I don't have any. But thanks for referencing mdo code guide. 
It's just my style preference. I think the autocomplete feature of any text editor works better with dashed style in css.

Just take a quick look at the default css, I think only one element will conflict with some framework
<code>ul.pagination</code> really need namespace there. Let me know if I missed something


> I'd also prefer id attributes are not added to every element (and growing longer with each element in a tree). I'm not saying there should not be IDs on many of the common "parent" sections (there should be)! But every child element does not need to have an id attribute if it is close in the DOM to the parent element (a class attribute would be sufficient in this case). Why? It keeps the HTML content shorter (therefore keeping the download size smaller and the memory footprint for the browser smaller). Same reason optimizing images for mobile is a good idea.
> @lhungil 

I'm completely agree with you. 
```css
#popupShippingEstimatorBody, #popupSearchHelpBody, #popupImageAdditionalBody, #popupImageBody, #popupCvvHelpBody, #popupCouponHelpBody, #popupAtrributesQtyPricesBody, #infoShoppingCartBody {}
```
Can be simplified maybe using only <code>.popup-body</code>


> I know others will disagree, but I am a fan of the MobileDetect script.. Media queries alone cannot possibly cover all of the range of what should or should not be included/viewed on mobile devices.. MobileDetect allows me to create a responsive template with behaviors that mimic a mobile specific template.
> @DivaVocals 

I am not sure about MobileDetect script you use. But you always can append some class to html/body tag to create separate style. For example : 
```css
.site-navigation ul li {
   display: inline-block;
}
@media (max-width: 768px) {
   .site-navigation ul li {
      display: block;
   }
   /* Your detection class */
   .android .site-navigation ul li {
      display: none;
   }
}

**Comment by barco57** [comment]
I will toss my vote towards hyphenation

**Comment by DivaVocals** [comment]
@IronLady the device specific classes are not reliable, and don't always work.. the MobileDetect script (and it is called MobileDetect) is a LOT MORE reliable in my experience.. There are places where a media query alone doesn't quite cut it, and in some cases, I DON'T want to simply "hide" something from one viewport using "display:none".. I'd rather instead that it not render at all.. The MobileDetect script allows me to do just that..

**Comment by IronLady** [comment]
@DivaVocals It's just an example. I am not sure what mobile detect script you use. But, maybe with that script you can append <code>android, mobile, iOS</code> class to the body so you can override the style just like the example above.

Media queries to detect the device and load all content then "hide" it at some viewport is the main key of RWD (Responsive Web Design). 

On the other hand, if you use server-side(PHP) or client-side(JS) script to detect the device and serve specific content for specific device like you did, it's called AWD (Adaptive Web Design)

It looks the same but it's completely different.

**Comment by DivaVocals** [comment]
> I am not sure what mobile detect script you use

At the risk of being a smart a$$, it's REALLY called **[MobileDetect](https://www.google.com/search?q=MobileDetect&ie=utf-8&oe=utf-8)**.. 

seriously :smile:  
That's what it's called...

>But, maybe with that script you can append android, mobile, iOS, small-screen, hide-nav class to some element so you can override the style just like the example above.

Well that still means I am HIDING things versus not rendering them at all at specific viewports..

>Media queries to detect the device and load all content then "hide" it at some viewport is the main key of RWD (Responsive Web Design).

>On the other hand, if you use server-side(PHP) or client-side(JS) script to detect the device and serve specific content for specific device like you did, it's called AWD (Adaptive Web Design)

There is no rule that says a site can't use a combination of RWD (Responsive Web Design) and AWD (Adaptive Web Design).. The PicaFlor templates use a combination..

>It looks the same but it's completely different. 

Right.. :laughing: It's like correcting someone's spelling huh?? If I understood the point of someone's writing, do I really have to tell them that *their, they're, and there* aren't the same word if they used the wrong one??

Point is, that I'm aware of the difference.. I appreciate the correction :smile: However, I think most of us here understood exactly what I meant even if I didn't use **exactly** the correct terminology.. BTW, good luck getting shopowners to use these terms properly.. Most folks understand ANYTHING that lends itself for rendering correctly on a mobile device as responsive.. (and yeah that includes some I.T. pros to..)

**Comment by IronLady** [comment]
@DivaVocals TRUE, you can always combine them (AWD-RWD)  <strong>My point is not the terminology.</strong>

I just want to clarify things you say you don't agree with
> Place media queries as close to their relevant rule sets whenever possible. Don't bundle them all in a separate stylesheet or at the end of the document

It's a quote from mdo (The Bootstrap Dev Guy), since BS is RWD Framework of course they use <code>media-queries</code> to detect viewport and "filter" the content. 
Foundation has a little [AWD taste](http://foundation.zurb.com/docs/components/interchange.html) but they are still using RWD approach (hide things).

I won't do like mdo suggest. I always keep the responsive rule set on seperate stylesheet so I can enable/disable the responsive feature and I always hang on to RWD, it's simpler. On the other hand you try to combine AWD-RWD, it's really good for "Custom Theme".

But, with all due respect it'll create another dependency (Mobiledetect script) which is not a really good idea for "Default Template". 

Let's get back to the main topic Hyphenation.

Cheers @DivaVocals  :)

**Comment by DivaVocals** [comment]
Right.. I think the point I was making has gotten lost in all this MobileDetect talk.. Though I would not object to the MobileDetect script's inclusion, that also was not the point I was making.. 

I I was simply saying that overall, I agree in GENERAL with many of the principals in the MDO except the one about not keeping separate mobile/responsive/WHATEVER stylesheets.. On that point I think we agree..

But I will say that the same case that can be made against the MobileDetects scripts inclusion is the same case that can be made for the inclusion of BootStrap, Foundation or even jQuery..

**Comment by wiztechinc** [comment]
My point was that I am untrained, unschooled and self-taught. My eye and
head told me that camel case worked best for me. I had to make a choice
years ago and camel case seemed to be the better way. Not that it's just
the way I'm used to.
ᐧ

Delia Wilson Lunsford
WizTech, Inc., (formerly Delia Wilson Design, LLC.)
434-202-4307
Terms and Conditions for working with WizTech, Inc.
(http://www.teamwiztech.com/terms-conditions.php)

**Comment by mc12345678** [comment]
Old discussion I know... :) 

My vote - tokenized (tokenizable) separation.  CamelCase is not "parseable"...  You can't have variations on one or more parts of it without restricting the variable/class/etc.. to a set number of characters...  It's the old database style of record keeping, no variable length information, very rigid, and also seems difficult to electronically search at least if things can be presented in both ways. (NOTIFIERS_ARE_AN_EXAMPLE where the observer class function becomes updateNotifiersAreAnExample for those that care to keep some form of readability in the name)  Would be happier with update_notifiers_are_an_example or some variation on that... Formatted this way, the "variable" can be split into its component parts and evaluated as necessary/desired.  Five words, 5.4 characters per word, 4th word has two characters and begins with "an", etc.... Also searches (non-case sensitive) would find all occurrences unless the search utility offers camelization or the ability to omit (easily) the token.
