### ISSUE TITLE
continued support for authorize.net

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3120]
in looking at the authoize.net upgrade guide, they have deprecated the use of the Name Value Pair (NVP) method.  both of the included modules for ZC make use of NVP as opposed to JSON or XML (the supported methods for authorize.net going forward).  if we want to continue to support authorize and make it part of the base package, we will need to update accordingly.

see:
https://developer.authorize.net/api/upgrade_guide.html

**Comment by scottcwilson** [comment]
Do you know if Authorize's approach to deprecation is to remove it in the next release (like PHP) or  to keep it forever but call it deprecated (like Java)?

**Comment by drbyte** [comment]
They've been talking of deprecating it for years, but they continue to keep it alive because tons of merchants still use it. I think they have actually terminated some of their other services.

I've built 80% of a new module using their SDK in preparation for ZC core.  @proseLA has used some of that in his CIM module.

**Comment by scottcwilson** [comment]
Thanks for your hard work in this area, @proseLA.  A nice improvement for the product.
