### ISSUE TITLE
Suggestion: Admin category / product listing, sort order independence

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3121]
Personally I want the categories by name and the products by model descending.
How about removing the combined (and so never perfect) CATEGORIES_PRODUCTS_SORT_ORDER from the admin interface and making two separate constants for categories and products, hidden but defined/updated by the selected sort order on the page?

**Comment by proseLA** [comment]
no idea what 2 constants give you.  this page only displays 1 thing, so there is only 1 sort order.  the selection of what that sort is, is currently based on what is displayed.  i think v157 has changes so that if no category is being displayed, it defaults to the product sort, which i think is better than presented in v156.

with regards to your personal preferences, my clients do not even make use of a model number.  i think the idea of contributing code is to make it for the better good of all; as opposed to one's personal preferences.  if one wanted to contribute something to easily define a preference for a sort order, i would be all for it.  but i'm not for taking one's personal preferences and enforcing it on others.  just my opinion.

**Comment by Zen4All** [comment]
I do not think this is a personal preference. I switch a lot between sorting by ID, Name and or status. And I am convinced there are more users doing this :relaxed:

**Comment by torvista** [comment]
My comment on preference was an example of how one constant cannot cope with all permutations.
I already did a hacky fix for this long ago but would like to do it better, and I think having a preference/constant set by whatever the user selects on the page (so it's the same next time) would be the ideal. No looking for a constant you probably don't know even exists. I knew it existed but had to use the toolkit to find it. 
In my opinion, the more of these obscure/not in view constants that can be assigned on the fly/removed from enormous menu lists, the better.

**Comment by proseLA** [comment]
ok, i misunderstood what @torvista was saying.  i understand it now.

i do a lot of sorting when using this script as well.  you can see some of the merged changes i made in this script for sorting after searching.  sorting on this script is no doubt a very useful feature.

i agree the constants in the config file are quite large and unwieldy.  i do not even use the developers toolkit anymore; i run sql statements directly on the database when looking for a config constant.

the idea that there is a configurable default sort, well i guess that's great...  adding another configurable default sort depending on whether we are using the categories sorter or the product sorter...  whatever.  i do not feel that strongly about it.

i suppose i would like to see a more long term view about development, and customization.  for example, steve wants these constants set on the fly and retained for further use.  the last sort seems to be already retained for the session.  so now we want to update the config file to be updated every time we set the session sort?

maybe it is time to look at the object of admin/user.  and perhaps store the the last sort there for each user?  (where there is very little if anything about an admin/user other than passwords.) i have no idea about the amount of stores out there that make use of multiple admin users.  perhaps 95% of the stores out there make use of only a single admin?  so more development on the object of admin/user is not warranted, and the constants file is fine.  i do not know, and frankly a default sort... not that big a deal to me.

being able to sort products based on fields that are not part of the default product, ie sorting based on record_company_id (i do not use the product_music, i have my own custom product types, but hopefully someone gets the idea); that is something that excites me and something that i frequently have to do for my clients.  default sorting?  eh....

**Comment by drbyte** [comment]
> being able to sort products based on fields that are not part of the default product, that is something that excites me and something that i frequently have to do for my clients.

Given that you've gotta do custom coding to *display* those custom fields, aren't you already therefore able to add a line to custom sort for those same fields?

Thinking here of how ZC can serve the masses, vs the one-off wishes

**Comment by proseLA** [comment]
i am able to add code for custom sorting, yes...

my sites tend to be all highly customized.  but i'm also thinking about how to help the masses.  hope u see that....

i dread updating any of my clients sites, for that reason....  each time i do, i try and move more and more of the custom code into separate classes, when possible, and make use of observers so that maintenance gets easier.  maintenance issues is why i am not a fan of `!important` in css, and why i have advocated for common functions between the admin and customer facing.  something the team has been doing and which i always applaud...

but overriding core ZC classes and functions gets hard, as you know, due to the legacy nature of ZC.  i played around with magento for a while.  the customization available with product definitions, sorting, etc was pretty awesome.  as was the ability to easily extend classes, and override functions within those classes. but using those xml overrides was mind blowingly hard at times.  you have to be working on it, 24/7, which unfortunately i am not able to do...  and moving my ZC sites to another platform is not in the cards for me...

guess i'm just hoping for something in-between.  i think its hard because magento really requires an IT guy to setup and maintain, while ZC attempts to allow a non-coder to setup and maintain.  which gets more and more difficult as the site gets more complex...

**Comment by drbyte** [comment]
v160 had a nice datatable display, which would make this whole discussion moot.
But it's such a massive overhaul ... :(

**Comment by torvista** [comment]
>v160 had a nice datatable display

Column sorting too?
