### ISSUE TITLE
Contribution to template refactoring

### ISSUE THREAD

**Issue by Spike00** [zencart/zencart#314]
Hi all, I'd like to discuss how to develope the new base template, but reading @drbyte in #311 it seems to me that this is not the place because there's already people at work but not here (I understand he was referring to pull requests, but saying that there's people at work on it offline I thought that this was not the right place). So the question is, is it possible to discuss this topic? In #304 I proposed to use whitepapers to discuss such a kind of broad topic, maybe using the forum. Is it feasible?

**Comment by DivaVocals** [comment]
If you think it's impossible to discuss this HERE, try opening up a discussion topic on the forum.. :laughing: I promise you that it will be a FUN discussion (not!)

Not sure why you STILL think this is not the place to discuss this.. we now have three distinct discussions going on and I think they are all productive discussions.. Nothing @drbyte said in #311 would tend to indicate that it precludes any discussion of the topic of templates.. Besides, in post #311 I merely made a suggestion for a SIMPLE change to the classic template so an out the box install is not stuck with a very unattractive default look.. It's FAR from a major template change..

I closed #304 because it started out as a good exchange of ideas, and devolved into a chest bumping session because of the poor behavior on the part of one contributor, and then further devolved into a discussion on the best way to have a discussion.. The good discussion that was started was LOST once the off-topic stuff crept in.. So I closed it and encouraged everyone to start NEW topics so that we could have more focused on-topic discussions..

Glad to see you started your own topic.. Apparently you still want to discuss HOW to discuss this.. :smile: So in the name of adding my 3 cents, I will state here again what I stated in #304.. I think that the whitepaper idea is a LOT overkill.. For me it's an issue of time.. I can handle this medium.. Don't have time or interest in writing a whitepaper.. Others may feel differently..

**Comment by Spike00** [comment]
@DivaVocals I referred what drbyte said in #311 , not the topic of #311.
This is the sentenced I referred to: Don't go so far as to rewrite it all to HTML5. That's already in the works offline.

Issues in github are obviously related to code available in github and as Chris wrote, the template refactoring is being done outside github. 

So, how to discuss, if possible about how to do the refactoring?

**Comment by drbyte** [comment]
@Spike00 said:
> I'd like to discuss how to develope the new base template, 
> So the question is, is it possible to discuss this topic?

Sure. What is your list of pet features you wish to see considered?

**Comment by DivaVocals** [comment]
>Issues in github are obviously related to code available in github and as Chris wrote, the template refactoring is being done outside github.

>So, how to discuss, if possible about how to do the refactoring?

I guess I don't get your trepidation.. If you want to discuss a topic, then raise it and discuss it.. That's what we've ALL been doing.. Not sure why you feel you can't discuss things because you don't SEE it..

**Comment by Spike00** [comment]
Hi, I'm sorry but I had a bunch of problems. In next days I'll write down my thoughts.
