### ISSUE TITLE
Product Delete no longer works

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3160]
Go to admin-catalog-categories/products.
Drill down to the products level.
Press the trash can icon on a product

Expected result: product is deleted
Actual result: product is not deleted

**Comment by torvista** [comment]
Works for me. I note that the master category has to be selected.

**Comment by scottcwilson** [comment]
Why was this extra step added?  You didn't have to click any checkboxes in 1.5.6.

**Comment by scottcwilson** [comment]
Somehow we have conflated deleting linked products from the categories_products table with DELETE PRODUCT.  Surely the latter should be the default behavior.  Many stores don't even have linked products.

**Comment by torvista** [comment]
I've just tried a ZC156 vanilla and it also opens an infobox.
The only difference is that the master category is unticked by default. 
You could make it ticked if there are no linked categories.
Better safe than sorry I thought.

**Comment by drbyte** [comment]
@torvista Given that the intent when clicking the delete button is probably to "delete", let's set all the checkboxes as "checked" by default. Then if the user wants to keep it in a certain category they can uncheck the corresponding boxes.

**Comment by torvista** [comment]
Just to be clear, I have it set so that all except the master category is checked by default.
![Untitled-1](https://user-images.githubusercontent.com/4391026/79138465-d89d6380-7db4-11ea-9b2c-87c239ddac6b.gif)

In a big list it is easy to make a mistake when you only want to delete some linked categories if master is pre-checked too.
I know, I've done it and deleted a product by mistake with the corresponding wailing and gnashing of teeth. So that was my thinking behind it.
I understand if you don't read the accompanying text then you may think why has it not worked. But if there is only one category shown, that's only one to tick. 

A further planned enhancement for this cat listing was in alpha-order but with the master category first. But not got round to it.

I'll submit a PR as requested to revert it.
But not on my site.
