### ISSUE TITLE
Determine ultimate disposition of OSH_ language constants

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3208]
For @lat9 
This is per the discussion with @drbyte surrounding #3187

**Comment by scottcwilson** [comment]
(Cindy, if this title is not good, just let me know.)

**Comment by lat9** [comment]
The title's just fine, I've been busy with other things.  I'll try to give this a look-see over the weekend.

**Comment by lat9** [comment]
Let's start here:

> One of the tenets embraced in the implementation of the email-template capability feature was that all the email-related language defines began with `EMAIL_TEXT_` (or at least `EMAIL_`), but the OSH defines break that pattern.
> 
> With all the efforts y'all are doing right now to streamline and reduce inconsistencies keeping this one feels odd.
> 
> I always hate making life difficult for mod authors, so I'm not wanting to put up a big fight here. Just trying to figure out the best way forward that doesn't confuse end-users any more than necessary, and doesn't require cluttering the docs with "oh, and in this additional special case you'll find a broken pattern here too". :)
> 
> Thoughts?

Originally posted by @drbyte in #3187

This is where documentation (so that there's history and direction) is _good_.  When I originally published [os_updated_by](https://github.com/lat9/osh_updated_by) back in 2005, I had absolutely no visibility into the above-stated tenet.  That plugin was derived from a client-specific customization and is distributed by [SNAP Affiliates](https://github.com/lat9/snap_affiliates) as well as a couple of my commercial plugins.

Now, these language constants are a bit of a conundrum, since there are sites that have a vested interest in the admin's `orders.php` constant-definitions (i.e. they've made site-specific language changes) and there are sites that have their 'interest' in the `osh-updated-by` constants, too.

I suggest that we declare that **_the horse has left the stable_** and simply remove the now unused constants from the `admin/includes/languages/orders.php`.  In addition, there _should_ probably be some guidance for sites upgrading from Zen Cart versions prior to zc156 noting the change in language-text location.

**Comment by lat9** [comment]
Note, also, that those constants are replicated for use on the storefront in `/includes/languages/english/extra_definitions/orders_status_updates.php` since, as mentioned in the original PR, there are processes that update an order's status-history during storefront operation as well.

**Comment by drbyte** [comment]
> One of the tenets embraced...

Apologies. In hindsight, `tenet` is too strong a word. `pattern` would have been more fair. 

> simply remove the now unused constants from the `admin/includes/languages/orders.php`. 
In addition, there _should_ probably be some guidance for sites upgrading from Zen Cart versions prior to zc156 noting the change in language-text location.

As I've been pondering this subject I've come to largely the same conclusion.

I think that what bothers me more than the pattern changes is that we're using `extra_definitions` for something that has become a core feature.

**Comment by scottcwilson** [comment]
> there _should_ probably be some guidance for sites upgrading from Zen Cart versions prior to zc156 noting the change in language-text location.

There's a what's new file for 1.5.7 in the PR queue; as soon as that gets approved I can update it to add these remarks.

**Comment by lat9** [comment]
> I think that what bothers me more than the pattern changes is that we're using `extra_definitions` for something that has become a core feature.

I'm unclear as to what makes these OSH constants different from the others that are provided in the admin's english/extra_definitions sub-directory:

![image](https://user-images.githubusercontent.com/2685585/79047517-0cc22a00-7be5-11ea-8d60-4f5e3947818b.png)

**Comment by drbyte** [comment]
I knew someone would list those. That's why I talked about "core feature". 
I see the extra product-types as non-core, since they're rarely used.

My point is that it's unintuitive to the end-user to expect to look in "extra_definitions" when the very vast majority of definitions that they're likely to edit are in the directory above.

Clearly y'all strongly oppose me on this.

**Comment by lat9** [comment]
It's not that I'm opposing you; it's just that it's _water under the bridge_ at this point since those files were distributed as part of zc156.  Just trying to reduce upgrade 'churn'.

**Comment by scottcwilson** [comment]
Why don't we bite the bullet just once in 1.5.7 and then things will be right again? 
We could put empty stub files in there to ensure even careless upgraders would no longer have the defines in the wrong place.

**Comment by wiztechinc** [comment]
So if major changes were in one edition that pushed out the next edition further, I would be okay with that - but I don't have a majorly used mod at risk here - because I wasn't able to keep pace. I do think major changes instead of incremental changes makes more sense because it's really more efficient.  I know I'm looking at it from a more limited perspective in some ways but it doesn't matter to me when upgrading a website since I charge by the amount of work I need to do. I make more money from upgrading than I do from any mod work.
