### ISSUE TITLE
V2 and roadmap?

### ISSUE THREAD

**Issue by lankeeyankee** [zencart/zencart#3213]
I was late to the github party and didn't see/couldn't find why V2 has been shelved/abandoned. Can anyone point to some links or just say what happened? And is it properly being abandoned or just paused?

I have not been able to find any type of development roadmap here, either. Is there one somewhere? It seems to me the development has been very piecemeal with no clear path forward to create the improved system that will get this project back into some greater relevance and usability for the average user. There have been some good additions to the 157 branch, but nothing really that would make anyone want to go through the pain of upgrading.

**Comment by drbyte** [comment]
These are the sort of questions for which there is never an answer that satisfies everyone.

In no particular order, I offer the following comments.

v2 is paused - this is because the vast majority of contributors screamed that upgrading is too difficult and that they'd rather have incremental updates to get to "the new" instead of a wholesale replacement where the new code looks nothing like the old. Both for core code and for plugin authors.
So, efforts have been redirected to building on the 1.x series.
I would say that v2 would have made a roadmap easier to formalize because its core code base offered a lot more flexibility, even though it requires some paradigm shifts.

Granted, one could say that the same people requesting to avoid that "wholesale replacement  pain" are also advocating for (or directly contributing) some pretty expansive alterations that are now in 1.5.7.  While lots of the core code still "looks the same", there's lots of core files that have been changed -- and in the admin many of those changes are huge. (I'm NOT saying they're not good/useful changes. Many of them are wonderful, some long-overdue.)

On the plus side, many of the v157 changes that have been made will make for easier maintenance. And also easier integration of plugins (both because of the way some of those files have been reworked, but also because of the plugin infrastructure that's been added (although examples of it are still needed)).

All the catching of PHP notices/warnings will make the code run faster since every time a notice/warning occurs (or error for that matter) extra CPU time must be used to process those conditions; avoiding those conditions altogether results in better speed. Combine that with running on newer PHP versions which are also faster in and of themselves that means noticeable performance gains for those making the transition.

**Comment by lankeeyankee** [comment]
Excellent, thank you for the information. It's good to hear that it's only paused.

**Comment by scottcwilson** [comment]
You can view https://htmlpreview.github.io/?https://github.com/zencart/zencart/blob/v157/docs/whatsnew_1.5.7.html to see the list of updates for 1.5.7 (in a very nascent form).

**Comment by scottcwilson** [comment]
If there was a v2 feature you were particularly keen on, you could always backport it to 1.5.7; this has already been done for a few changes (like default attribute).

**Comment by proseLA** [comment]
as someone who has done some minimal contributions to this project, i agree that there is no easy answer to please everyone.

over the years, i have seen some positive movements in code.  and specifically the removal of duplicate code sets on the admin v store side.  but there is more than needs to be done. specifically i remember the messageStack class as well as html functions output (or whatever it is called); there is some progress, and i applaud that.

unfortunately, i wish there was more of a roadmap; even for the v1.5.x series.  i find any number of the changes to be a haphazard group that someone who supports some ZC clients did on their sites and now wants to incorporate into the base (i am guilty as anyone else, and i suppose that's how a lot of development does get done).

the addition of the notifier and observer class, i think is huge, as it allows 3rd party plugins to operate without hopefully changing any of the core code.

i think some of the biggest things that need to get done, include:

- a better default template.  i frequently see ZC sites from store bought templates that look awesome.  contributors on the forum will say they don't work, blah, blah, blah...  but out of the box, the ZC template is pretty lame.  and i'm not even a design guy.
- continued work on templating on the admin side.  the amount of duplicate code there is... well, there seems to be work getting done.
- would love to be able extend classes easier than it currently is...
- a default javascript/jquery function for add to cart.  it's a shopping cart!  we need to get so much more current.
- a default one page checkout.  customers are now using to putting something into a cart clicking buy and being done with it.
- the removal of security by obscurity and adding of 2 factor authentication on the admin side.

at the end of the day, i would love to see more of a roadmap with regards to features and making ZC perhaps easier to use for store owners.  i'm frequently amazed at shopify and how they have come onto the scene and done so well.  it's a completely different model; but shopify sites tend to look great at the box, and because they offer their own credit card/merchant services, stored cards on 1 shopify site can be used on other shopify sites.  i think that's pretty cool.

**Comment by scottcwilson** [comment]
Your list of  "biggest" things is excellent.  Can you pick your favorite and build a PR?

**Comment by proseLA** [comment]
@scottcwilson ha ha....  i'm currently working on an updated version of authorize.net with CIM (customer integration management, ie stored credit cards).  perhaps you want to test it?  it's ready for some testing with a v156 install.  only 1 added field to the customers table.  no ZC core file modifications..

also, in looking at your list for v157 changes, i'm curious what was done to address spam?  perhaps you can point me to that PR.  ZC is a shopping cart, and the way to address spam is via SPF, DKIM and DMARC; none of which are part of a ZC install.  i would hate to get users hopes up.

**Comment by scottcwilson** [comment]
The spam changes were the integration of (portions of) the zenNonCAPTCHA mod. PR #2581.

**Comment by drbyte** [comment]
And https://github.com/zencart/zencart/pull/2580 addresses deliverability also.

**Comment by torvista** [comment]
From time to time these "discussions" flare up and die out again. But they never coalesce into a roadmap with milestones, that contributors can at least bear in mind to focus progress in some way.
Without that in view, contributions will of course be haphazard.
My opinion was that 1.5x should be maintenance releases only while v2 +plugins are developed, in the hope that the few contributors with their little spare time, invest it on the future.
V2 needs to happen, but it needs to be at least the equivalent of 1.5 + popular plugins to even get off the starting block: who would upgrade to less functionality?
I think this is the reason it was shelved....that is just too much work/too much time with insufficient resources (developers) to be feasible in the near future.
So, back to tinkering until there is a published plan.

**Comment by wiztechinc** [comment]
Was just talking about the default template yesterday with another zc person. I really wish we could do something better but I can foresee major fights again on that. No one listened to me last time and as I actually have a different approach to responsive, I figure I would get ignored again. 

Used to the tinkering now but I might be able to better help if there was more a plan.

**Comment by scottcwilson** [comment]
Delia, please submit a PR or a contribution.

**Comment by drbyte** [comment]
> No one listened to me last time

I'm sorry you feel that way. I recall numerous times spending whole days studying many of your posts around templating and cart improvements, and even implementing many of them into core. 

> I actually have a different approach to responsive

For an open source project where end-users beg to see the embracing of common standards, "different" is potentially dangerous ... because if it's so "different" that most people won't be able to understand it, or it doesn't embrace commonly-used techniques that most designers/developers have contemporary skills for, then it doesn't take things much further ahead than where we are today. That said, I'd like to see us at a different spot than we are now.

> I figure I would get ignored again

You have valuable insights and opinions. For your thoughts about the template, I'd like to see them combined into a clear specific proposal with working examples. That way they can be discussed collectively, weighing pros and cons, and exploring how it effectively meets the desired end goal of improved usability for both mobile and desktop.

**Comment by drbyte** [comment]
@proseLA wrote:
> a better default template

Ya, you've said that elsewhere.

And not just you. Others have said it too.

We hear you.

Nobody posting about it has taken charge to come up with one though. Clearly everyone just wants "someone else" to do it.

You've never seen the core team reject the idea of a new template. In case you haven't figured it out: graphic-design is not our core strength. 

Sure, I'd love an updated default template that works with all of Zen Cart's core feature switches, includes features that embrace all the fancy modern buzz-phrases that you can dream up, and lets you magically drag-and-drop things from one spot to another.
I don't have the time (or the design skill) to do it.

It's always been an open topic. But merely saying "me too" helps nobody. It just creates frustration.

**Comment by proseLA** [comment]
> Was just talking about the default template yesterday with another zc person. I really wish we could do something better but I can foresee major fights again on that. No one listened to me last time and as I actually have a different approach to responsive, I figure I would get ignored again.
> 
> Used to the tinkering now but I might be able to better help if there was more a plan.

i don't remember if i was involved last time or not; but if you were to submit something, i would gladly look at it, test it, and give my honest opinion.  as i have previously stated, i am not good at design; i'm a back end make it work kind of guy.  and i just think CSS is awesome!  (sarcastic...)

**Comment by proseLA** [comment]
> @proseLA wrote:
> 
> > a better default template
> 
> Ya, you've said that elsewhere.
> 
> And not just you. Others have said it too.
> 
> We hear you.
> 
> Nobody posting about it has taken charge to come up with one though. Clearly everyone just wants "someone else" to do it.
> 
> You've never seen the core team reject the idea of a new template. In case you haven't figured it out: graphic-design is not our core strength.
> 
> Sure, I'd love an updated default template that works with all of Zen Cart's core feature switches, includes features that embrace all the fancy modern buzz-phrases that you can dream up, and lets you magically drag-and-drop things from one spot to another.
> I don't have the time (or the design skill) to do it.
> 
> It's always been an open topic. But merely saying "me too" helps nobody. It just creates frustration.

ok.  but to be clear, i have never had any problems with the ZC core team, nor the decisions that they make.  i may not agree with them, but i have no problem with them.  this looked like an opportunity to express a few things...  i'm not saying "me too".  i am trying to make ZC better for others.  not just for myself...  i hope you see that...  i try to restrict my limited contributions to what i think is better for the community, not just for myself.

so, how do we can get a KILLER design graphic person on board?

**Comment by drbyte** [comment]
> i hope you see that

Yes. I should have been more clear: my post wasn't targeted solely at you. 

I absolutely appreciate the contributions everyone makes!!!!!  Everyone!!!
(Even if I don't always agree with them: the fact that you took the time to share code, or even just thoughts, is always appreciated!)

**Comment by wiztechinc** [comment]
So first a smidge of explanation. I was a graphic designer before turning to the web. My idea was to make beautiful websites. Ha. My speciality for years was pixel perfect CSS. Give me an image, I'll reproduce it on a website, totally crossbrowser. Forget design. Then responsive interrupted it all. I absolutely do not agree with mobile first - I design for desktops first and then add css for responsive. I do not use any css producer of any kind. I consider most of it as a web developer tool because they can't do the css and design. I absolutely hate any generated css class/div names. Yes, @drbyte, I agree the template should be done as more a "normal" thing now for a project like this. So, I'm just frustrated. Sorry to everyone for that seeping into the conversation. Not helpful. Thanks @drbyte for the kind words. That actually did help. 

Am I an outstanding graphic designer? No, because in general, graphic designers, good or bad, do not produce anything that can be attractive and fast loading that doesn't rely on images. So I actually don't think an "outstanding" one is necessary, though a creative person could definitely add to the conversation. And I'm more a technician than a creative at this point.

I do have ideas about how to approach such a thing but as much as I want to help and wouldn't even mind the responsibility of taking a very active role, I don't think it's a good idea for the zen cart project as I cannot promise that I can see something thru due to my physical issues. Picking around the edges is what I know I can manage. I truly want to do more and that also is frustrating.

Any template discussion should start with the basics though. I can do a separate pr to lay out what I consider to be those basics for web design, leaving aside the technical issues. As long as folks will chime in and stay on topic. Snicker.

**Comment by wiztechinc** [comment]
Why is it that I always seem to stop a conversation?  :) I know that folks are concentrating on getting things wrapped up for this version but there's little I can do to assist that. Shall I just table this or start a pr for later? I can also write a book ......

**Comment by scottcwilson** [comment]
Suggest this thread be closed.  Question has been answered as much as possible at this time.
