### ISSUE TITLE
Did you make an important change/fix/feature addition to 1.5.7?

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3217]
If so, reply here and write it up BRIEFLY for inclusion into the 1.5.7 what's new file.  (You write the content, I'll update the file.)

You can see the file now at: 
https://htmlpreview.github.io/?https://github.com/zencart/zencart/blob/v157/docs/whatsnew_1.5.7.html

**Comment by torvista** [comment]
Admin – Products to Categories Link Manager. Addition of global tool to copy linked categories to another product.
Admin – Product Copy. Expanded to include copy of metatags and linked categories.
Email – hard-coded text removed…removing need for a separate set of language-specific email templates.

**Comment by scottcwilson** [comment]
> …removing need for a separate set of language-specific email templates.
please let me know when this is done and merged.   Other items added.

**Comment by torvista** [comment]
already done: https://github.com/zencart/zencart/pull/2850

**Comment by scottcwilson** [comment]
oh ok - the fact that it wasn't in past tense mixed me up.

**Comment by proseLA** [comment]
i think customer search on admin side is vastly improved due to #3079.  allows multi word searching for first name, last name, email address, etc.

**Comment by scottcwilson** [comment]
@mc12345678 ? @lat9 ? Others?

**Comment by mc12345678** [comment]
Significant or otherwise, below is a list of accepted modifications to ZC that I could find by way of my edits.  There are others made to adjust against the work of others or to correct minor issues or things observed.

(https://github.com/zencart/zencart/pull/3052)
- Updated the store front end for `buy now` selection to use the minimum quantity that satisfies both the units and minimum quantities when the product is not yet in the cart.
- Added messages in the admin during product save process to notify if the minimum quantity is less than the units and/or if the minimum quantity is not a factor of the units.

(https://github.com/zencart/zencart/pull/3024)
- Addressed strict PHP notices for loading the popup_image_additional page

(https://github.com/zencart/zencart/pull/3025)
- Addressed strict PHP notices for loading the contact us page when the user is not logged in.

(https://github.com/zencart/zencart/pull/2912)
- Ensure catalog side `$_GET` keys have at least one occurrence not beginning with `amp;`.

(https://github.com/zencart/zencart/pull/2984)
- On admin side, load `$messageStack` (`messageStack` class) earlier allowing messages to be added at/after load point 32, with display to occur at the previously existing load point of 100.  To do this, a class method `add_from_session` was added to support adding messages from the session.

(https://github.com/zencart/zencart/pull/2855)
- In admin attributes controller, provide popup text upon hover over the links for edit and delete.

(https://github.com/zencart/zencart/pull/2700)
- Added a notifier `NOTIFY_FUNCTIONS_LOOKUPS_REQUIRES_ATTRIBUTES_SELECTION` to support recognizing attribute data types that require attribute selection when using non-default attribute data types.

(https://github.com/zencart/zencart/pull/2681, https://github.com/zencart/zencart/pull/2267)
- Added an sanitizer code to support more complex sanitization for configuration menu items to include email and Boolean type sanitization.  This concept also added val_function type rules to support error message notification for configuration value sanitization issues when a configuration key is identified to have a sanitizer. This also added language components and ranges associated with the sanitization.

(https://github.com/zencart/zencart/pull/2647)
- Consolidate admin and catalog side `zen_get_uprid` functions to remove duplication between sides.

(https://github.com/zencart/zencart/pull/2510)
- Verify that the provided products_id is valid for the store on initial page load and, if not, redirect to the resulting page for handling missing product.

(https://github.com/zencart/zencart/pull/2521)
- Remember entries made supporting the latest developer's tool kit search.

(https://github.com/zencart/zencart/pull/2469)
- Attempt to maintain mobile detect status for responsive templates that override a key file.

(https://github.com/zencart/zencart/pull/2408)
- Added ability to identify a product's file upload attribute as required.

Like many others took part in eliminating debug messages associated with strict PHP processing.

Note that in the page referenced above:
> You can see the file now at:
https://htmlpreview.github.io/?https://github.com/zencart/zencart/blob/v157/docs/whatsnew_1.5.7.html

There is this link
>A detailed list of all edits to all files can be seen on Github at: [v1.5.6...v1.5.7](https://github.com/zencart/zencart/compare/v156...v157) 

which is incorrect for those that have installed say v1.5.6c where this link should be: [v1.5.6c...v1.5.7](https://github.com/zencart/zencart/compare/v1.5.6c...v157) as there are/were changes made to the 1.5.6 branch after 1.5.6c was issued that at the same time were/are already in 1.5.7 and therefore would not appear by the above review/comparison.

I do know I have one item yet to add; however, it is not included above because the communication within the PR has not been edited enough to be satisfactory to me nor the lead developers...

**Comment by scottcwilson** [comment]
Great - thanks for your hard work.

**Comment by scottcwilson** [comment]
> which is incorrect for those that have installed say v1.5.6c where this link should be: v1.5.6c...v1.5.7 ... 

I see your point, and the tradition is also to do it the way you are suggesting, so I will change it on the next checkin.  Thanks for catching that.

**Comment by drbyte** [comment]
I would prefer we leave the github compare link as 156...157, not 156c
- the changes between minor versions are typically small
- if we're providing the link then we should provide visibility between major versions. They can adjust it themselves for minor versions if they wish.

**Comment by mc12345678** [comment]
> I would prefer we leave the github compare link as 156...157, not 156c
the changes between minor versions are typically small
if we're providing the link then we should provide visibility between major versions. They can adjust it themselves for minor versions if they wish.

Sure, but looked at the changes that have been made to the v156 branch as compared to v1.5.6c? https://github.com/zencart/zencart/compare/v1.5.6c...v156  Makes me think of the few in the forum that have said that they will not apply such changes until they are incorporated into a "release" version... 

Presumably all of those changes already exist in ZC 1.5.7 and therefore when comparing just the *main versions* then all of the things seen in the above comparison "don't exist".. Might only be a couple of things, but they also seem to have a significant impact on operations at least with higher PHP versions.

For example, v156 has a commit that supports/allows files to be uploaded while v1.5.6c will complain to the user that there is a problem with the file with something like the extension being wrong.

ot_shipping will not get the update that has been done to it.

PayPal looks like it will have problems if the v156 differences are not incorporated/considered.

Okay, so if the link remains beginning with v156...v157, what guidance is being provided to explain how to adjust comparison against the provided link?

**Comment by drbyte** [comment]
> Okay, so if the link remains beginning with v156...v157, what guidance is being provided to explain how to adjust comparison against the provided link?

None.

**Comment by lat9** [comment]
Plugins now incorporated into the core: 

- Report All Errors
- Sortable Orders Status
- Encrypted Master Password

**Comment by scottcwilson** [comment]
Closing now.  If someone was left out, please PM me on the forum with the details of the change you made, and I will update the page.
