### ISSUE TITLE
Upgrade issue: drop final_price not firing

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3278]
mysql_upgrade_zencart_156.sql contains the statement

ALTER TABLE customers_basket DROP final_price;

This is not firing, for some reason I can't figure out.   I fixed a couple of upgrade issues this morning and AFAIK this is the last one, but I can't seem to crack it.  

Repro steps:
- Install Zen Cart 1.5.5, build database through installer. 
- On Zen Cart 1.5.7, attempt to upgrade the 1.5.5 database you have just created.

After upgrade completes, you will see the table customers_basket still has the field final_price.

This can also be reproduced with an older database; I first saw this issue testing an upgrade from 1.3.9.

**Comment by mc12345678** [comment]
Basically, because the default operation within parseraltertable is executed for that specific SQL statement, the presence of the field to be dropped causes the parser to ignore the line and therefore not get executed...  Note that this is to some extent buried within an existing `switch` statement intended to support other "verbiage" in the SQL statement, such as: `ALTER TABLE xxxx DROP COLUMN yyyy` Although that too would have failed in this case as well, because `$exists` would evaluate to true within the `COLUMN` section and therefore would cause the SQL line to be skipped...

Added a second commit to provide a single line evaluation instead of using a second line.  More complicated logic though...  Action may still be desired to be added just before the check to see if `$exists == true` to set `$this->ignoreLine = true`.

**Comment by scottcwilson** [comment]
Thank you - this is a potentially huge breakthrough.  Once this is confirmed and merged I will retest with adding the DROP to the 1.5.7 upgrade - to be sure it gets done!

**Comment by mc12345678** [comment]
As you may see in the commit history of that PR, I have provided at least two versions, there may be a third which would apply more globally, its just I am not so sure that `DROP` is applicable/appropriate for every "feature" of `ADD` and thus, either the code allows whatever might be entered in the SQL file or it is to be more intelligent and only provide the negation in certain cases... 

I remember seeing an issue with this in ZC 1.5.6; however, that version didn't execute a `DROP` and therefore wasn't researched further... I sort of thought it would get resolved "independently'; however, it popped up again and actually needs to be correct now.

**Comment by scottcwilson** [comment]
Hang on!  It ain't done yet!  I need to modify the 157 update script to do this again because it would have been missed for folks who are on 156.
