### ISSUE TITLE
break style <br> or <br />

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3284]
For html5/new files/files that get modified for **other** reasons, are we standardising on `<br>`

 these days?

**Comment by Zen4All** [comment]
Use ```<br>``` for HTML5 by default. If you don't it's okay, browsers don't care that much, and interpret the correct style.

**Comment by drbyte** [comment]
Yes, use `<br>`. No slash.

**Comment by torvista** [comment]
The install sql has 849 br / and 72 br. The upgrade also has mixed. Would it not be an appropriate moment to rationalise these?

**Comment by drbyte** [comment]
Perhaps.

How do you envision "doing" it? 
Does a mass search-replace risk damaging any content that the user maintains/wants?
Also, some things are escaped, so those would need accommodating.

**Comment by torvista** [comment]
> How do **you** envision "doing" it?

**I**, wasn't...purely to shirk responsibility.

I would have tried out mass search-replace: a new install doesn't overwrite anything.
Any update of existing texts (157->158 upgrade) overwrites what they have anyway.
And plenty of time between now and 158 release to detect anomalies.

If it's a possibility I'll have a try-out.

**Comment by drbyte** [comment]
Note: we can't "only" make the change in the `install` SQL. Must also handle updates so that existing stores have the same changes. There are some scripts that look for specific content (primarily for detection of upgrade-needed)... I don't recall whether any of those also contain the extra slash. If the updates aren't done to existing stores then everything is out of sync.

**Comment by torvista** [comment]
Ugh. Sounds like a world of pain.
Best to just keep the updates and file refactors consistent then.
