### ISSUE TITLE
addresses in the order class.

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3295]
https://github.com/zencart/zencart/blob/fa29cbeafe5265a6edc29aaa7727dcd12e75cbe6/includes/classes/order.php#L258-L259

there are 3 addresses in the order class:
- customer address
- bill-to address
- ship-to address

frankly, i have no idea why we have 3.  customer have a multitude of addresses, one address they would use for bill-to information for a specific payment method (or lets just say an order), and then a ship-to address for that order.  why there is a third address in the order class, i am not really sure.

(i know it confuses the few clients i support on ZC and i have modified the order to only display 2 addresses on the admin side.)

in addition, there is a default address tied to the customer, stored in the customers table.  that address is ONLY used for the address that i do not understand, the customer address.

given the legacy nature of this code, i am reluctant to request the removal of the customer address.  HOWEVER, what are people's thoughts about modifying the code above, so that if the session vars are not set, instead of using 0, we use the default_customers_address_id from the customers table?    it makes sense to me.

**Comment by torvista** [comment]
Valid points.

I think the most complicated case (which one might say should be the design spec), would be trade customers: 
Customer address being the billing address
Multiple shipping addresses to branch offices/franchises.
Billing address probably the same. I can't think of a case where it is different, with the 1000+ trade accounts we have (although most went bust in 2008, and the rest this year probably!).

Related unimplemented tinkering:
https://github.com/zencart/zencart/issues/3088
https://github.com/zencart/zencart/issues/3253

**Comment by mc12345678** [comment]
I had written something to this a day or two ago; however, in submitting the comment, it got lost even though I knew I should have copied it before submitting...

Here goes with what I remember as highlights.  If the addresses are set to anything other than a specific known not expected value when an unexpected action occurs, then there will be no indication in use of that data to identify that an unknown/unexpected situation existed.  I.e. defaulting to the customer's default address at all times when the cart is reviewed rather than to the value set in the session or a value of zero has the potential of items being sent to said default location without the customer having selected that destination which then could lead the store owner to additional shipping costs/reshipment, etc... If instead the value remained set as zero even to the admin orders page, then the store owner would have an obvious issue presented and an action to take... If in that same situation where an empty address record were stored, instead the default address were stored, then there would be no indication of an issue and the item(s) would be sent to the default address whether they really should have been shipped at all or to that location...

Originally led off with the rehashed statement that the "third" address is the customer's default address (address entered upon account creation or as last selected in the customer's account information), and is used for the initial selection/identification of the address for shipping.

There is a relationship of the above to the likes of `includes/modules/checkout_shipping/header_php.php` and `includes/modules/checkout_payment/header_php.php`, which I did look further into before and provided a detailed discussion on, but at the moment am moving on...  Basically to indicate that there are some things done in those two files (and potentially any other) that either would be impacted or probably should be changed to accommodate that the address would always be set to something non-zero regardless of the input or other operation.

I also had something to say about the removal of the third address from the orders screen... This is the place where the owner has the opportunity to look over all of the information associated with placing the order and this third piece of information could serve as an indicator that perhaps something unusual was occurring such as for where the country associated with all three addresses are different. Doesn't necessarily mean that there is a problem, but it would certainly provide a flag that perhaps something is awry.  

I personally think that the default should remain to be assigned a value of 0 if the session is not set, if there is some reason/need to have it default to something else there are notifiers that can be used to observe and modify that behavior.  The current default supports assignment of a value and a known value if there is something that was amiss and the process to obtain the known value does not need to be known it is just simply an output that is expected and predictable. The thing is that I don't see where the need for the described change is stated... I likely could understand, but I don't see the need... I know that I've helped others to make the address selection the first thing to do instead of presenting the shipping method, they had a good reason that was basically needed for each purchase. Maybe something more could be said about why this is/becomes an issue?

**Comment by proseLA** [comment]
ok,  your comment has forced me to re-look at this issue.  and what caused me to create an issue.  I had reset the primary address, but the SESSION for ship to and bill to had already been set…  so the problem that I hoped to address was a problem with me as opposed to with ZC.

so unless there is additional comments, I will close this issue in the next day or two.

but while we are here, I will express my opinion about 3 addresses associated with an order.  I say it is wrong.  nothing will convince me otherwise.

a customer to addresses is a one to many relationship.

in an out of the box order system, like ZC, every order has a billing address, associated with the payment, and a shipping address associated with where the product is going.

(for purposes of this discussion, I will not talk about orders with multiple payment types, nor multiple ship-to locations for a single order.  none of these order systems are necessary or exist in ecommerce sites straight out of the box;  especially for small businesses.)

customer → address; 1 → many.  order → address; 1→ 2.  

this is not something I want to debate.  if you think differently, that’s fine.  but I will not come around to your way of thought on it.

currently ZC has 1 primary address.  this is used as the default for the bill-to and for the ship-to.  if you have already established your SESSION and then change the primary address it does not change; this is where I went adrift and decided to create this issue.  for that I apologize.  I have no problem with that behavior given the current setup.

however, to me, a well designed e-commerce system would have a default billing address and a default shipping address for a customer.  ZC currently only has 1 default.

an order has 2 addresses, a billing address and a shipping address.  ZC currently has 3.

there is a reason why ZC has 3 order addresses, and only 1 default address.  some of the long time ZC contributors understand the history and why that it is.  if it is, as you say, for store owners to see if something may be adrift in the order, ie fraud, I would say to you that there are better fraud prevention tools out there, and it is very much a part of the legacy of ZC.  I have seen orders where the bank comes back with EXACT match on the AVS and the order is fraudulent (and i am talking about orders from other systems as well as ZC orders).

alas, I digress.  my initial issue with regards to the SESSION was  a problem with me not with ZC.
