### ISSUE TITLE
CC Slamming: Why reset customer's basket?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3320]
As seen in `/includes/modules/checkout_process.php`:

```php
// BEGIN CC SLAM PREVENTION
$slamming_threshold = 3;
if (!isset($_SESSION['payment_attempt'])) $_SESSION['payment_attempt'] = 0;
$_SESSION['payment_attempt']++;
$zco_notifier->notify('NOTIFY_CHECKOUT_SLAMMING_ALERT', $_SESSION['payment_attempt'], $slamming_threshold);
if ($_SESSION['payment_attempt'] > $slamming_threshold) {
  $zco_notifier->notify('NOTIFY_CHECKOUT_SLAMMING_LOCKOUT');
  $_SESSION['cart']->reset(TRUE);
  zen_session_destroy();
  zen_redirect(zen_href_link(FILENAME_TIME_OUT));
}
// END CC SLAM PREVENTION
```

The cart's reset on a credit-card slam attempt.  Why is that?  I've seen cases where people have card-related issues (a bank-decline, for instance) and once they reach the _magic number_ of failed attempts, their carts are wiped.

**Comment by drbyte** [comment]
> The cart's reset on a credit-card slam attempt. Why is that?

If a bad-actor is slamming (testing stolen) credit cards through your store, you probably want to stop them quickly. Resetting the cart requires them to re-add items to the cart before they can make another purchase. It's one more barrier to blocking their fraudulent activity.

Plus, you the storeowner are paying a service charge for each attempt. To reduce those costs you probably want to stop the bad-actor as quickly as possible. The more barriers the better.

That's "why".

A reasonable threshold is implemented. If a shopper fails to enter a successful payment that many times, their next attempt will trigger the reset.

**Comment by lat9** [comment]
Thanks, as always, @drbyte!  I appreciate the explanation.

**Comment by drbyte** [comment]
@lat9 A possible improvement opportunity is to limit the slamming counter to fire only on modules that are collecting card payments on-site (even tokenized or with iframes), since slamming is already guarded-against by gateways that redirect customers to do payment on "their" hosted pages, and for digital wallets like paypal-express or goog/appl/amz.

An interim step for exploring that would be an observer that decrements the session slam-counter if the last-attempted module can be determined to have been offsite. There's no guaranteed indicator of that status though. But for a specific site that's having issues, you could certainly hard-code things.

To be more clear, an example of what I'm talking about is the case of the legitimate customer who's having troubles making a payment (limited funds challenges, or typos, or whatever), and the store offers more than one payment choice. Perhaps the user tries a card once, gets a decline, then tries the card again, gets insufficient funds, or avs failure, then tries paypal express, gets a failure but goes and fixes their paypal issue, and tries paypal again: if that fails then the slamming algo boots them. While that 4th failed attempt probably shows they're unlikely to be able to pay, the 2 paypal express attempts aren't "slamming", and even if they were, PayPal has the slammer's identity and will invoke their own systems. 
The store probably still wants to do slamming prevention, but might increase the threshold slightly. Kinda depends on the combination of modules offered.
Before making changes for a specific store I'd be inclined to study payment-failure logs, if you have any, to see what patterns the store's customers are typically running into. Then use that data to decide a strategy unique to that store's actual needs. Probably worth re-reviewing annually.

**Comment by lat9** [comment]
Thanks for the update, @drbyte.  The store I'm investigating this for uses the _Ceon Sage Pay Direct_ payment method.  When the account is set to use AVS filters and a filter is requested, the payment cycles through `checkout_process` **_twice_** for each attempt, once to redirect to Sage Pay and the second after receiving the AVS filter requirement coming back from Sage Pay.

I was seeing a fair number of `checkout_process` requests being redirected to `time_out` and finally tracked it down to a credit-card decline or AVS failure followed by an additional request.  That second request (now at 4 entries to the  `checkout_process`) puts the customer over the slamming threshold.

I've added an observer that increases the slamming-threshold if the current checkout's payment method is `ceon_sage_pay_direct`.

**Comment by scottcwilson** [comment]
@lat9 this was also the case on the payment method you checked for me, right?  (Gateway Processing Services)

**Comment by lat9** [comment]
@scottcwilson, I'm having a hard time lately remembering my name, much less how some payment method that none of my clients use operates.

**Comment by scottcwilson** [comment]
Who is the scottcwilson guy and why do I keep getting messages for him?
GET OFF MY LAWN, YOU KIDS!

**Comment by barco57** [comment]
Well, that explains a lot...
