### ISSUE TITLE
Feature request: use Ask A Question for Call for price

### ISSUE THREAD

**Issue by papanco** [zencart/zencart#3341]
"Call for price": it makes more sense that the link refers to the "ask a question" page instead of "contact_us"
On the "product_info" page there is the image below the price and the "Call for price" link under the options: it is better to use the image with the links, the text is seen by few users and risks not being used. correctly.
Same thing for "product_listing"

**Comment by mc12345678** [comment]
@drbyte, et al...

What is a way to detect the origination point of arriving at say ask a question from the product information page? E.g. when on the product information page if selecting the call for price button it seems that it may be desirable for the ask a question page to either provide more information to the customer and/or to the email generated upon submission.  I understand one way is to add something to the url, but I'm wondering about a more "intuitive" way by reviewing something like some sort of "came from" data.  The solution may be to incorporate an additional flag in the link and then for the ask a question page to evaluate the presence of that flag and take additional action.

I'm also thinking that the additional information might include an additional `define_xxx` page possibility and/or something additional in the email such as perhaps a default/editable "call for price clicked" notification/text... Obviously open to suggestions which is the basic intent of this comment.

**Comment by scottcwilson** [comment]
You can *only* get to AAQ through product info.  That's the only place the link exists.

**Comment by papanco** [comment]
the link call for price refers to the generic contact_us page: it would not be more logical for a better user experience to link to the AAQ page so the store manager immediately understood which article he was referring to?

**Comment by wiztechinc** [comment]
If the call for price and ask a question have the same result, a dropdown menu actually makes sense to me. They get a choice of questions in a dropdown. I can see someone clicking on call for price and getting frustrated 1) if there is no phone number to call and 2) but "I just wanted to quickly find the price and you are making me work for it more. Ah, forget about it. Never mind."

No matter what form the call for price goes to, the problem is the same.  Helps the owner to determine at least which product he/she is referring to if it goes to answer a question but can still frustrate the user.  And, aha, a use for a separate phone field! click on call for price and get a phone number displayed. Of course I have clients who have changed the call for price button into email me your question, too.

**Comment by drbyte** [comment]
@mc12345678 Probably best to be explicit by passing a `pID` (product_id) in the URL.

**Comment by mc12345678** [comment]
> @mc12345678 Probably best to be explicit by passing a pID (product_id) in the URL.

That or a similar URL parameter is already provided.  Was more interested in recognizing that the source was "Call for price" versus "Ask a Question" with clicking on either ultimately going to the Ask a Question area (as discussed in this issue) and *offering* some variation based on the associated selection.  Further taking that to perhaps support some sort of "filtering" capability within the ask a question area for developers to build upon as desired/needed.

**Comment by drbyte** [comment]
@wiztechinc I've seen storeowners do the email and phone thing too.

**Comment by drbyte** [comment]
> > @mc12345678 Probably best to be explicit by passing a pID (product_id) in the URL.
> 
> That or a similar URL parameter is already provided when using ask a question. Was more interested in recognizing that the source was "Call for price" versus "Ask a Question" with clicking on either ultimately going to the Ask a Question area (as discussed in this issue) and _offering_ some variation based on the associated selection. Further taking that to perhaps support some sort of "filtering" capability within the ask a question area for developers to build upon as desired/needed.

Yes, good point.
Given these "buttons" are just `a href` links, I'd stick with adding a $_GET parameter, perhaps `src=p` and `src=q` for price and question respectively.  Brief is fine, as it's not necessary for the end-user to understand the purpose of this parameter IMO.

Changing it to POST requires creating a whole new `form` element, and restructuring the page so that this form doesn't get nested inside any other form on the product page.
Granted, a form could be helpful if other fancy javascript stuff were being done for displaying a phone number or email address.

**Comment by mc12345678** [comment]
@wiztechinc that's also why I am looking for a way from the ask a question page to determine how the individual arrived there.  If they clicked the call for price button/link then whatever additional information to be displayed (associated with calling for a price) could be made available.  Perhaps call it the "easy" way out on my question, because the obvious solution immediately available is to change the link displayed on the product information/product list screens to include some additional parameter identifying that the link is associated with calling for a price... Or... The super easy solution (invalidating the request for the feature) is for the store owner to just provide whatever information is desired to get the next level of support if that were even to include the request to identify product detail (ahem... which is already one of the features of ask a question).

**Comment by papanco** [comment]
on the AAQ page there are already the contact details including the telephone number: if the customer sends an e-mail we have an additional "contact", the single call instead can only be a waste of time for both. I would not add other variables to avoid confusion: if they want to know the price they will write "how much does it cost?" if instead they want to know more details, they will ask what they want to know ...
The best thing would also be to place a Whatsapp button on the "product" page to allow the customer to dynamically send a message with the product name directly on the Whatsapp phone to inform you of their interest.

**Comment by scottcwilson** [comment]
Note that the contact us page has its own define page, where a storeowner can add details like their phone number, links to messaging apps, etc.

**Comment by wiztechinc** [comment]
> Note that the contact us page has its own define page, where a storeowner can add details like their phone number, links to messaging apps, etc.

Of course they can. They can also put the phone number in the configure setting as well. Not ignoring that at all. I just have seen way too many clients who simply don't do that. Lack of training - please remember that you can still install zen cart with a click of button on some hosting. Some zen cart newbies actually pay 1000s to other zen cart newbies to set up their sites. I've seen both in the last month.

**Comment by papanco** [comment]
> 
> 
> Note that the contact us page has its own define page, where a storeowner can add details like their phone number, links to messaging apps, etc.

what I refer to is always linked to the user experience: if the customer can contact you in the best possible way with a single click it means that you have done a good job: if the customer has to click several times to contact you, he ends up give up and leave the site.
This is what I think.

**Comment by torvista** [comment]
>AAQ page there are already the contact details including the telephone number:

I don't see the telephone number.

Anyway, not all shops want/can handle telephone enquiries, especially damned Whatsapp.
If a shop is happy with calls, the number should already be prominent on the page, so Call for Price invites a call. If the user clicks on it and they see the store details with a phone number, fine, they can call, or not. Their choice.
If a shop does not do calls, then they should really change the button text appropriately (we should have Price Not Available), and it should still go to AAQ if clicked.
I don't see any need to change the AAQ format based on source click.

**Comment by scottcwilson** [comment]
He means the contact details for the store owner, not for the customer.

**Comment by torvista** [comment]
Ok, just to clarify...
in the admin
STORE_NAME_ADDRESS: is titled "Store Address and Phone" and described as Store Name, address and phone. Where used, as in AAQ, this constant is displayed.
I did not have a phone in there.

I was expecting this to be used:
STORE_TELEPHONE_CUSTSERVICE.

Between these two constants and STORE_NAME, STORE_OWNER there is some semantic overlap and possibly a case for rationalisation at some point...

**Comment by papanco** [comment]
> 
> 
> > AAQ page there are already the contact details including the telephone number:
> 
> I don't see the telephone number.
> 
> Anyway, not all shops want/can handle telephone enquiries, especially damned Whatsapp.
> If a shop is happy with calls, the number should already be prominent on the page, so Call for Price invites a call. If the user clicks on it and they see the store details with a phone number, fine, they can call, or not. Their choice.
> If a shop does not do calls, then they should really change the button text appropriately (we should have Price Not Available), and it should still go to AAQ if clicked.
> I don't see any need to change the AAQ format based on source click.

I don't want to create confusion, I just try to improve the usability of the cart: if the customer finds everything easily, he is more likely to place an order and the damned WhatsApp is now one of the main means of communication for millennials!
The price request function has long been present in Zen Cart and although "ancient" it can be used to convert questions into orders!

**Comment by torvista** [comment]
> damned WhatsApp is now one of the main means of communication for millennials!
Yes, but impossible to manage in a businesslike manner. A necessary evil I guess.

**Comment by mc12345678** [comment]
The extra code I'm talking about is more in line with making it possible to add changes to help the store owner help the customer... E.g. price related questions (as being clicked on through call for a price or whatever words are used) could have a different email title than the standard ask a question type message, or it could be sent to a different individual regardless the selected dropdown, or it could have something else inserted into the email body, etc... The idea is to make information available for someone to easily add onto instead of having to ask in a later version for it to be added. As one to consider adding the functionality through simple change of the associated link (with possibility of changing from `$_GET` (link) to `$_POST` (form)), wanted to consider the possibilities of other capabilities and what, if anything, could further be modernized.

Like for example, I just realized that there could be an ajax observer that could identify when one or the other link was clicked to take an action to store information in a `$_SESSION` that would then be available upon arrival to the Ask a Question Page where it could be parsed/acted upon... At least for more modern ZC versions about which we are discussing...


papanco, I do believe that all in the discussion are trying to ensure customer usability even if also pushing back from another direction, the intent can be seen.  That said, the specific application WhatsApp has its own issues and is something that can be added as desired at the store/owner level.  For the most part development is about making it possible to install/have such an application as compared to actually inserting as part of the base distribution...

**Comment by scottcwilson** [comment]
Suggested solution: add a notifier at the end of zen_get_buy_now_button - or perhaps in the switch block in the product_is_call case) so that storeowners can override the use of CONTACT_US.

**Comment by papanco** [comment]
I thought of integrating a code like this on the product page:
<a href="https://wa.me/<?php echo "mywhatsappnumber" ?>?text=I'm%20interested%20in <?php echo "$product_name"; ?></a>
I recently arrived on the Zen cart and I have to get used to the code ...

**Comment by drbyte** [comment]
> I thought of integrating a code like this on the product page:
> ![code](https://user-images.githubusercontent.com/41792764/80739820-65675180-8b17-11ea-98bf-fd97e17d1a81.jpg)

You certainly can do that, directly in the template file.

**Comment by scottcwilson** [comment]
Switching from Contact Us to Ask A Question (which prefills the email with product information) is certainly an improvement and easy enough to do.  PR'ed.
