### ISSUE TITLE
Installer - change default db name in developer mode?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3354]
While preparing a minor PR regarding DEVELOPER_MODE....
I seem to be doing many repeated installs for testing, and at the moment, if no configure is defined/its a new install, the suggested name is zencart.
While thatmay be fine for a user, that's not informative enough for me, already having multiple installs in a db, and so was thinking that if in developer mode, it would be better to include the version, as shown below?
![Clipboard01](https://user-images.githubusercontent.com/4391026/80385135-fdf69b00-88a5-11ea-8a6f-2f5b75a5bb3a.gif)

**Comment by mc12345678** [comment]
Would that necessarily be "enough"? 

One side I can see where a flag such as `DEVELOPER_MODE` might encourage things being presented a differently, but what about when developing to see differences between databases associated with multiple installs at the "current" version? Wouldn't the Database Name field still need to be touched/edited?

Further, when at this point in the process the database has already been created hasn't it? Therefore the name had already been selected from within the desired database tool and may not match up to this preselected text...

So, is the thought that instead of the ZC software predetermining a database name, are you looking at including a "field" (constant) to support auto-populating the field such as would exist if a pre-existing `includes/configure.php` or `admin/includes/configure,php` (as applicable) was present? E.g., by actually having the file there already? Or is this back to the use of the `includes/local/configure.php` file situation during install/upgrade?

BTW, asking questions to support development of the solution and to understand better. :)

**Comment by torvista** [comment]
If there is a configure existing, it uses the values from that file.
If not, it uses fallback values, like "zencart" for the db name.
While personally I use a relevant db name for each upgrade (ie change to shop_156, shop_157 etc.), suggesting to users "zencart" is not a problem for a new install.
I am proposing a fallback to a more detailed name when in developer mode.
In the end, I feel the idea of developer mode (and the two constants to allow zc_install and "admin")  allow a developer to click through the install as fast as possible, check and change, and do it again, and again, with as little typing as possible.

I've probably spent more time on this already than 50 installs...but anyway, once I discovered the developer mode I was wondering what else it could do to save us those previous seconds re-typing things!

**Comment by drbyte** [comment]
I'd support adding the digits only (ie: `1.5.7-alpha` becomes `157`)

I'm reluctant to change the behaviour more than that because I'm used to just tabbing into that field, pressing End and typing the digits of the version I know I'm working with.
Adding non-numeric characters will make my usual workflow slower, not faster.

Interesting note:
While on some OS's `zencart_1.5.7-alpha` is a "semi-" valid database name, on the filesystem it escapes the dots and hyphens `zencart_1@002e5@002e7@002dalpha`. That's always confusing when trying to understand what's going on there. Better to avoid characters that need escaping.
Granted, on some multitenant sytems it's common to use `-` if generating database names dynamically and using uuid naming patterns. Still, at the filesystem level those `-` are translated to `@002d`, which is very hard to quickly interpret visually.

**Comment by scottcwilson** [comment]
If you're going to do this, how about calling a function?

if (function_exists('dev-set_db_name')) {  ... } 

or something like that?  I'm sure everyone has their own conventions for managing these things.

**Comment by drbyte** [comment]
Seriously?

**Comment by scottcwilson** [comment]
Come come now Mr. Bond.  You enjoy this as much as I do.

**Comment by torvista** [comment]
A function? Why?

**Comment by scottcwilson** [comment]
Because different people want different things.  I want the name to be demo_<versionname>.  So 156 database is demo_156.

**Comment by torvista** [comment]
> I'd support adding the digits only (ie: 1.5.7-alpha becomes 157
So to use the version constants, it needs something to remove the dots then strip the first non-numeric onwards?
