### ISSUE TITLE
zencart-develop: addition of new language does not duplicate product data

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3384]
I can't even find where this is done, or I'd do it myself.
Another language pack to use for testing:
https://github.com/torvista/Zen-Cart-Develop-Spanish-Language-Pack

**Comment by mc12345678** [comment]
Primarily (in this is done in `admin/languages.php`; however, there is an interesting caveat that might be causing some trouble? It uses the current `$_SESSION['languages_id']` as the source for the new database language records... So... If you happen to have an admin language that is different than the store front and as a result a `languages_id` that doesn't yet actually have data (because the language pack is being added) then the result is that the new language ends up with nothing being copied over... Another possibility is that in executing this section of the code that `$_SESSION['languages_id']` is either not set or set to 0? If that were so, then there would be nothing selected as a source item....

Oh wait, this is about the develop branch where there has been a lot of changes made in processing.  Looks like there isn't really an "insert"/"install" language path... It just detects the language and carries on from what I can see...  I'm looking basically at: https://github.com/zencart/zencart/blob/develop/app/library/zencart/Translator/src/LanguageLoader.php

This appears to be where the language information is loaded along with the Translator.php file which seems to do the loading of the actual content.  The first file though does not appear to touch the database in its "investigation" of the language(s).  Just not seeing where there is any feedback to `TABLE_LANGUAGES`, though I'm also looking directly at code and don't have the software installed to possibly use the developer's tool kit to find anything that identifies relationships between things... :/

**Comment by mc12345678** [comment]
Upon further consideration, perhaps that portion of the software should after loading the languages perform a check against the database for each of the languages and if it doesn't yet exist in the languages table, to then do what the old languages admin did?

Only thing I see about that is that each page load would result in performing that check, but perhaps the "cost" of operation... The difference being that unless you see a widget associated with languages, then that would be the way it would be done... Without some sort of "admin" control though, each language would just get auto-installed upon discovery...

**Comment by torvista** [comment]
I have to day I don't follow any of that, in relation to the issue.
A new language can be installed, but part of that process should be duplication of the product data fields for that new language. That does not happen.
So, since there is no admin/languages.php file and I can't find anything relevant to "languages", I don't know if it's broken or was never implemented.

**Comment by torvista** [comment]
In any case I duplicated them with sql, that'll do for my use.

Still, I would be interested to know where this is done/not done/why I am incapable of finding it!

**Comment by mc12345678** [comment]
From what I see, "installation" occurs by loading the language fileset into the appropriate language folder... Further to that described is that there currently is no admin "languages" handler like there was in previous versions. As such, to align with your offer to "do it yourself", the location at which to capture the need to do the copy from one language to the new one is in the file identified where perhaps some handler is called to perform the check of the language/duplication.

In other words, without specifically searching the installed fileset for where `TABLE_LANGUAGES` is updated to recognize a new language, there is nothing currently present that recognizes that the **new** language has been *added* and therefore an operation be taken to prepopulate the content in the database. 

I thought I understood some of the process to use fallback methods to default to something like a primary language define, but that may only be true within the given language not from one language to another.

**Comment by torvista** [comment]
Even after duplicating the product/category info, if the shop language is not english, checkout bounces to the account edit address page which is broken.
Too many issues to fix with this, so I guess I'll have to try and port the code assuming it was working at the time.

**Comment by mc12345678** [comment]
I have my guesses about the why not yet done, which to me is to offer some sort of new code processing which effectively works with a given database (new or updated) and then fill in handlers/additional processing where necessary. I mean, the way the languages are being identified is actually kind of interesting. Instead of waiting on some admin action to take place and insert the language, it is based on the presence of files. Not sure if it was a sort of quick fix to offer support/interface or is more of an expected final result, but the whole thing is/was a work in progress with the idea of new development and interface in mind. Seems it was somewhat being built from scratch.

**Comment by torvista** [comment]
I found it does not auto detect a new language: I still had to add it through the admin.

**Comment by mc12345678** [comment]
Makes sense based on what was seen, found, and not found. Indication then is that there are two independent "systems" at play. A preload of data associated to language files that are used/shown only when the database recognizes the existence of the language. 

I do believe though that in a previous comment in one of the issues you were a part of that the development branch is/was somewhat abandoned that has improvements desired to be pulled into future versions though. (I'm sure a lot of work has already been done that is desired to be salvaged.)
