### ISSUE TITLE
To Explore: Replace jAlert with Bootstrap modal

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#3404]
Is there anything in jAlert that can't be done with just Bootstrap's modal?
Specifically any functionality we're using in the keepalive tool that wouldn't be easily converted?

I think the pro's of this are:
- remove a few files from the distro
- use same styling as Admin, for consistency
- perhaps easier debugging because it's all based on one framework, not added plugins

con's:
- might lose a tiny bit of functionality? maybe not?
- have to manually create the html template jalert provides into a bs modal (very small task)

**Comment by mc12345678** [comment]
Functionality that seems to be in place and useful:
- If have been logged out because of a time out, selecting the button to login again attempts to return the user back to the same page they were on, even though this can also be a page of attempt to set data that was supposedly passed (but now lost as a result of the login cycle).
- Retaining and extending the session if acknowledged before the timeout has occurred assuming any cookie update also happens in appropriate time.
- Ability to cause the webpage tab to "flash" and/or come into focus when the timeout window is popped up/displayed (good/bad depending on perspective, but editable supposedly).
- Window appears or can be made to appear in an appropriate view without having to scroll through the screen to find the button. At one point I had to modify the code to make the window appear vertically mid screen (viewable area) instead of mid window (possibly scroll somewhere).

Don't know the answer to potential loss of any of that without knowing the effects/operation of the Bootstrap's modal. Also may have missed something of functionality.

**Comment by proseLA** [comment]
i love the functionality of jAlert; but i hated debugging it.  i'm reminded of #2083 which i'm not sure was ever figured out.

and perhaps what i loved was the functionality of the keepalive module itself as opposed to jAlert.

**Comment by drbyte** [comment]
> i'm reminded of #2083 which i'm not sure was ever figured out.

That's precisely why I'm considering this change.

> and perhaps what i loved was the functionality of the keepalive module itself as opposed to jAlert.

Ya, there's no plan to change the keepalive functionality (save for whatever jAlert did that BS can't do)

**Comment by drbyte** [comment]
If someone wants to tackle this, I'd be happy to review a PR.

It'd be nice to embrace the consistency of display, and drop one dependency. But the dependency is so tiny I'm not all that bothered about its presence, especially since it's designed to work directly with the jTimeout script so well.
