### ISSUE TITLE
Auto repair who's online table?

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3423]
This happens a few times a year across my few dozen clients: 

```
[05-May-2020 18:41:56 America/Denver] PHP Fatal error:  145:Table './sitedb/zc_whos_online' is marked as crashed and should be repaired :: delete from zc_whos_online^M
          where time_last_click < '1588724816' ==> (as called by) /home/site/public_html/shop/includes/functions/whos_online.php on line 56 <== in /home/site/public_html/shop/includes/classes/db/mysql/query_factory.php on line 167
```

It would seem that we could detect this condition and auto repair it.  True?

**Comment by drbyte** [comment]
Can you test whether this works in your case?

https://github.com/zencart/zencart/pull/3424/commits/4593e133645c32c856dd2bd85a80a5326ce1f945
(could apply it to catalog-side just as easily)
Might need to catch a different exception, although this just uses the top-level one that things will bubble up to.

**Comment by scottcwilson** [comment]
Can you put in catalog side logic, because it was the catalog that was unavailable.

**Comment by drbyte** [comment]
Yes it could be put catalog-side. Same logic wrapped around the catalog-side query.

But I'm slightly less inclined to put repair operation catalog-side because of race conditions.
I was thinking that if the Admin whos-online page automatically checked for and did the repair, then the storeowner has an immediate way to go "fix" it if a problem occurs.

Granted I suppose the broken table is a sort of race condition on its own.

**Comment by scottcwilson** [comment]
Catalog side failure with this table is what generates the client-in-a-panic phone call. :) Not so worried about the admin.

**Comment by drbyte** [comment]
The code I was trying doesn't work, so I removed it.

If someone has code that works to address this, please re-open the discussion.
