### ISSUE TITLE
unused function in products class

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3426]
it seems that the `products_name` function in the products class is not used in the base ZC (157).

it does seem very similar to the lookups function `zen_get_products_name`.

would it not make more sense to use the function within the class?

i bring this up as i have sites that redefine what a name is based on other attributes associated with the product id.  it would be nice to be able to extend the products class and then redefine what the function does.  isn't the use of lookups function a bit of a crutch?  or am i off-base here?

**Comment by lat9** [comment]
FWIW, it's more 'standard' practice to make use of the class within the function.  That's similar to the [`date_diff`](https://www.php.net/manual/en/function.date-diff.php) PHP function, which is an alias of ` DateTime::diff()`.

**Comment by drbyte** [comment]
Using classes instead of lookup functions is what v2 was all about. Way more efficient, easier to extend, easier to upgrade, etc.

But everyone said they don't want all the pain of such a conversion.

**Comment by proseLA** [comment]
perhaps we can say the overwhelming consensus as opposed to everyone?

it looking at it closer, i can not even find any uses of of the product class at all.  unless i am missing something.

perhaps we can take smaller steps to get to the ideal of v2 and work towards getting more folks on board?  i think ZC should have a functioning product class.  nothing wrong with leaving the lookup functions for those that still want to use them.

**Comment by drbyte** [comment]
> it looking at it closer, i can not even find any uses of of the product class at all. unless i am missing something.

You are correct.

> perhaps we can take smaller steps to get to the ideal of v2 and work towards getting more folks on board? 

Depends what "smaller" means, in terms of what "upgrade pain" people will accept. Again, most of the pain is in areas of code that are often-customized, whether DIY or by plugins.

> i think ZC should have a functioning product class. 

Agreed. It's an incredibly complex class to build. I've done about 5 variations of it over the years. In truth it ends up being multiple classes because of all the things a product can consist of.
Plus the shopping-cart class needs to interact with it extensively. And updating that is gonna make upgraders cringe.

> nothing wrong with leaving the lookup functions for those that still want to use them.

Agreed. Rewriting them as compatibility stubs "into" the class functionality may maintain more consistency than leaving them alone.

**Comment by proseLA** [comment]
as someone who will need to do a few upgrades coming up, i am already cringing.  i think this comment was attempting to be pro-active going forward for future updates.

yeah, i looked at the shopping cart class and it seemed that is has so much of the (lack of a ) product class coded into it.  at some point, i will look closer.  

5 variations over the years?  that sucks not being able to get any variation merged.  i've done my share of coding over the years that never saw the light of day.
