### ISSUE TITLE
Missing label for navMainSearch

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3467]
Working on trying to get 1.5.7 more liked by Lighthouse (Developer tool for Chrome - aka Google Lighthouse for Firefox) and am unable to figure out the way to get a label on the navMainSearch.

Being created from several sources, I have been unable to figure out where to place the label tag or would do a PR.

Any suggestions for a fix?

**Comment by drbyte** [comment]
Question: what's the reason for wanting to put a label on it?

**Comment by dbltoe** [comment]
It lowers the accessibility score.  Contrast, some link names, and this lack of label takes accessibility out of the Green in Chrome's lighthouse.
It's the only one I find without the label.

**Comment by wiztechinc** [comment]
Isn't it the form that needs a name/label? buttons are a whole 'nother thing.

**Comment by dbltoe** [comment]
It is the navMainSearch form.

**Comment by wiztechinc** [comment]
have you found a form with a name? Parameters for form? I haven't looked closely but if a label/name cannot be added to any form, that's the problem not one form. I'm not digging into this deeper right now as I was just checking email on the run but accessibility probably needs massive work across the board. And since these kind of changes may well be template based, I'm thinking not a good idea to open that particular can of worms in 1.5.7. Perhaps a deep look in 1.5.8? 

My 508 compliance chops are rusty at this moment but have had to obey such in the past. So willing to offer to look at this.

**Comment by dbltoe** [comment]
I've worked with 508 since it came out in '98 but, not able to find the spot to put the label as it is generated in several files

**Comment by drbyte** [comment]
How about using `aria-label` in `tpl_search_header.php`:

```diff
-$content .= zen_draw_input_field('keyword', '', 'size="6" maxlength="30" style="width: 100px" placeholder="' . HEADER_SEARCH_DEFAULT_TEXT . '" ');
+$content .= zen_draw_input_field('keyword', '', 'size="6" maxlength="30" style="width: 100px" placeholder="' . HEADER_SEARCH_DEFAULT_TEXT . '" aria-label="' . HEADER_SEARCH_DEFAULT_TEXT . '"');
```

**Comment by dbltoe** [comment]
I may have been incorrect as it says it needs a name (id?) for <input type="text" name="keyword" size="6" maxlength="30" style="width: 100px" placeholder="Enter search keywords here">

https://web.dev/label/?utm_source=lighthouse&utm_medium=lr

**Comment by drbyte** [comment]
If you use a `label` tag with an `input` then yes you need to link them using an `id`.

But if the UI doesn't actually need a `label`, the `aria-label` attribute is a suitable substitute for adding context for accessibility and assistive devices..

**Comment by drbyte** [comment]
@dbltoe I'm hoping this isn't at cross-purposes with work you were doing. I've started #3470 in hopes that we can determine whether anything further is needed catalog-side.
Your thoughts are welcome!
