### ISSUE TITLE
Load-times for JQuery and Font-Awesome

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3506]
Here is the latest Lighthouse report on the current merge front page with a store name entered.  If we could just do something about JQuery (350ms) and font-awesome (270ms) of load time.......

What an accomplishment if we make 100 across the board.
![Lighthouse Report Viewer](https://user-images.githubusercontent.com/5122886/82425432-1fcde280-9a4c-11ea-89c2-83e7ab4f42ef.png)

**Comment by drbyte** [comment]
No plans for that at this time.

Self-hosting of those assets, instead of CDN might push it up from 99 to 100.
Or use lighter-weight alternatives.
That's the sort of thing a site owner can do themselves if they are feeling pedantic about it.

Practically speaking, once the asset is loaded the first time it is cached by the browser, so the performance hit is nil in terms of remote loading.

**Comment by scottcwilson** [comment]
Nevertheless, this is really exciting data - thanks for posting.
