### ISSUE TITLE
Concern about template-customization instructions in What's New Docs

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3512]
Am I the only one that has a problem with lines 96 thru 130 of docs/whatsnew_1.5.7.html?

Just saw this after a test install.  Honestly, I haven't read it in ages as we don't always do the "standard" steps of upgrade/install.

And it is NOT because of our color change mod for the responsive_classic template.

Why would anyone want to waste time developing a template that is, first of all, not responsive and as old as it is.

I recommend to everyone to load ZC, clone (should be in the core) the responsive_classic to a personal template, (optional - add color change mod and clone to personal), and start developing.

With the changes to 1.5.7, they will have a template that is far superior to anything in template_default or the dreaded "Monsters" out there.

With the basic steps above, they have BOTH template_default AND the responsive_classic untouched and available as troubleshooting tools.

IF the color change mod is added, there is an extra template in between the responsive_classic and their final your_template as an extra troubleshooting step.  Rather than the "what does it do in classic?" we should now be asking "What does it do when you go to responsive_classic?"

I think these instructions are just making too much unneeded work for the store owner with no real gain from the process.

**Comment by scottcwilson** [comment]
I see your point.  I also want to embed as little "upgrading" content with the product as possible; I want people to go to the docs site, which is not tied to a release and gets updated much more frequently. 

How about: 

Zen Cart now contains a newer "responsive_classic" template, which performs well on mobile devices such as phones and tablets.  If you are upgrading an older site, we recommend that you use *this* template (rather than template_default or any older non-responsive template) as the starting point for your upgraded site.

**Comment by dbltoe** [comment]
That works for me.  Wish we could have clone in the core so we could advise them to clone before moving on.  It's good advice whether using T_D, R_C, or TM.

**Comment by drbyte** [comment]
In my experience the "clone" plugin adds a ton of cruft that I have to then go and get rid of. Not a fan.

**Comment by scottcwilson** [comment]
We'll go with the simpler wording for the product-embedded documentation for now.
