### ISSUE TITLE
Product update after timeout during preview zeros fields

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3513]
Using zc157, current alpha (note that the issue's also present in zc156, possibly earlier).

In the admin (site's set up with the demo products), navigate to edit a product (I chose "Matrox G200 MMS", pID=1).  Click the "Preview" button and wait until the timeout jQuery script indicates that the session's timed out.

Click the "Log in again" button, log in and you're taken back to the product's "Preview".  Clicking "Update" at this time wipes various fields within the product's definition.

Here's the phpMyAdmin view of that product's original definition:
![image](https://user-images.githubusercontent.com/2685585/82561459-6fdaa100-9b41-11ea-8109-5b426a8faa6e.png)

... and here's that view after clicking that "Update" button:
![image](https://user-images.githubusercontent.com/2685585/82561395-4f124b80-9b41-11ea-88d4-4f194cca22c5.png)

The 'update' action has set the `products_type`, `products_price`, `products_quantity`, `products_status` (and others) to 0 and has wiped the product's model number to an empty string.

**Comment by drbyte** [comment]
I'll call this a bug, but it's a complicated one to "fix". As you say, it's been around forever.

It's because the Preview screen relies on POSTed data from the last click to the page, and the timeout/login step loses that data. You can trigger the same by manually visiting the preview page without POSTing any data to it.

Note that the preview IS showing the blanked-out/zeroed values. The user clicking the Save is merely confirming that they agree with the changes presented.

Probable fix, in shorter term:
- force the Preview page to abort if it's visited directly after login; reminder: this will lose all updates that were being previewed ... but everywhere else in Admin all updates are lost if not saved before a timeout, so this is at least consistent with everywhere, and not unexpectedly destructive.

Longer-term options:
- remove the Preview step altogether and just immediately fire the Update to store all edits  (caveat: dealing with uploaded images will be a problem: that's why the preview page exists)
- revamp entire Admin to cache edits to LocalStorage, divorce the product-image-upload process into a different stage, etc. These would require extensive dependence on javascript.

**Comment by torvista** [comment]
Can the Update not abort if product_type type_id == 0?

**Comment by drbyte** [comment]
I've submitted a proposed PR: #3514 

I didn't check whether reducing the tests to just look for POST['product_type'] or equiv. That could be explored too.

**Comment by mc12345678** [comment]
> Longer-term options:
>
> - remove the Preview step altogether and just immediately fire the Update to store all edits (caveat: dealing with uploaded images will be a problem: that's why the preview page exists)

Considering that entry of information into each field (currently) does not seem to affect the session (though I can't say that I have sat around to test that theory either) to ensure that upon next action a timeout doesn't occur, I currently use the preview option to temporarily save information allowing me to go (immediately) back and continue editing knowing that I have not committed the information to the database.  Further, if I *am* on a product's "preview" page and a timeout has occurred, then I am also able to use the browser's CSS controls to remove the backdrop color as necessary to retrieve information from such a stale situation.

My thing is that want to be sure that conditions do not arise where entered data be lost in the process because of session expiration that went undetected and now page content can not be retrieved by use of a browser's back feature.

**Comment by drbyte** [comment]
@mc12345678 you specifically quoted the option of skipping preview altogether. 
If we skip that step altogether, doesn't it accomplish the same end goal? ie: there'd be nothing "not saved" because it would indeed save immediately. No intermediate step to timeout on.

**Comment by mc12345678** [comment]
> @mc12345678 you specifically quoted the option of skipping preview altogether.
If we skip that step altogether, doesn't it accomplish the same end goal? ie: there'd be nothing "not saved" because it would indeed save immediately. No intermediate step to timeout on.

I did specifically focus on the issue of the intermediate step. As the intermediate step is available (maybe not necessary to be a required capability) and can temporarily store the information (for admin view/review) without affecting the customer/live site...

A real life example: I am working on a change to various aspects of the record, but I know I have modified the description even away from whatever pre-typed/copy-and-pasted content.  I wish to let another review it (in my case someone who happens to be in room, but not at the computer screen), so in waiting for them I move to the preview screen where the data is temporarily stored, I can then either commit it or I can go back to the previous screen.  So long as I haven't gotten my review/approval, I'm not actually ready to commit it to the store.

I mean, possibly splitting hairs in that it may be possible to store the record, send the link to a separate person to review, then either modify or leave it alone as applicable, but by the content becoming available store side, it is also available for others to screen capture or reference as "fact", but in the idea of having an "intermediate" location to load (even loading a secondary popup screen would effectively maintain the session at intervals) the data remains easily accessible, unsaved to the store, and the session remains alive to support whatever final state is to come of the data (stored, modified, or restored).

**Comment by drbyte** [comment]
I understand the "use case" of using a "preview".
I don't have a sense of how "important" it is in the workflow of a Zen Cart store.
Especially given the fact that the "preview" currently offered looks almost nothing like the actual storefront representation.

I've always experienced the ZC "preview" screen as a waste of extra clicks. Pretty much every other platform saves changes immediately, making them live on the storefront immediately.

For the real-life-example you quoted, I can see where one is more likely to use the built-in HTML editor to see the visual changes right there while editing, instead of needing a separate "preview" screen.

I'm 90% convinced to remove the "preview" feature completely. 
I'm still seeking compelling reasons for keeping it.

**Comment by wiztechinc** [comment]
Personally I never ever look at the “preview” because it looks nothing like the actual page. I proofread before I get to it.  Only one or two customers have ever commented on it, years ago when the image was always mangled. It can be confusing and it’s not rare for folks to not follow thru because they forget or get interrupted before actually committing changes. I’ve even done that myself. So I’m completely in favor of it being eliminated as I see no reason to keep it.
