### ISSUE TITLE
Improvement: remove need for update_product.php in music type

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#3551]
Since we now have a notifier for adding extra date to the products database table, in 
"admin/includes/modules/update_product.php". We can delete the file from the music folder, and add the changes to an observer file.
This removes the need for updating multiple almost identical files, and provide an example file for users that need to create their own observer files.

**Comment by scottcwilson** [comment]
OR ... we could just get rid of product music so we don't have to keep maintaining this code.  See #2691

**Comment by lat9** [comment]
Unfortunately, it's not as easy as migrating the additional table-updates for the `product_music` type, since it doesn't use a `manufacturers_id` which would result in a PHP 8.0+ PHP Notice/Warning/Error for that missing $_POST field.

**Comment by lat9** [comment]
PR forthcoming, but I'll document here what's been done:

- Added an auto-loaded 'product_music' observer which monitors notifications and enables that product-type to reuse the following 'base' /admin/includes/modules files.  Each of these files is 'stubbed-out' in /admin/includes/modules/product_music to ensure that duplication of processing doesn't occur on an upgrade:
    - update_product.php
    - copy_product.php
    - copy_product_confirm.php
    - delete_product_confirm.php
- Added notifier to /admin/includes/modules/update_product.php to indicate that the update's started.  This enables the `product_music`'s auto-loaded observer to inject that missing `$_POST['manufacturers_id']` which enables that product type to reuse the 'base' product update/insert processing.
- Each of the following /admin/modules/product_music files has been updated to simply `require` the base 'product' handler's version, since the handling was unchanged for a 'product_music' file:
    - collect_info_meta_tags.php
    - preview_info.php
    - preview_info_meta_tags.php
