### ISSUE TITLE
Partial Blank Page WhosOnline.php

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#3557]
[03-Jun-2020 02:35:26 UTC] Request URI: /jetmar/, IP address: ************
--> PHP Fatal error: Uncaught Error: Call to a member function format() on null in /******/includes/classes/WhosOnline.php:349
Stack trace:
#0 /******/includes/classes/WhosOnline.php(153): WhosOnline->inspectSessionCart('d9fb7f43ba21c52...', 'securityToken|s...')
#1 /******/includes/classes/WhosOnline.php(213): WhosOnline->retrieve()
#2 /******/includes/modules/dashboard_widgets/WhosOnlineDashboardWidget.php(16): WhosOnline->getStats()
#3 /******/index_dashboard.php(75): include('/home/*-*-*-*-*/...')
#4 /******/home.php(25): require('/home/*/*/*//...')
#5 /******/index.php(11): require('/home/*-*-*-*-/...')
#6 {main}
thrown in /******/includes/classes/WhosOnline.php on line 349.

I believe the culprit is line 364 in newer and 361 in previous.  Some time back the line was changed to remove the` => $value` it is back and might be the cause of the problem.  Reverted to previous and back to go.

**Comment by drbyte** [comment]
> --> PHP Fatal error: Uncaught Error: Call to a member function format() on null in /******/includes/classes/WhosOnline.php:349******

In that line `->format()` is being called against `$GLOBALS['currencies']` which refers to `$currencies` in the global scope

In the main `/admin/whos_online.php` file this is instantiated right at the top:
https://github.com/zencart/zencart/blob/3d6460ec760760b077c9ffe0a04bdbf8790b1b12/admin/whos_online.php#L13-L14

But your stack trace shows that you're encountering this in the context of the dashboard widget. The dashboard and lots of other admin pages don't initialize the `$currencies` object because they don't use it. But, for the sake of the widgets I've added it in https://github.com/zencart/zencart/commit/c5b4f4eaa73226b1e75c85e72f101c65349bb6b8
Making that change should resolve the error you were seeing.
