### ISSUE TITLE
Higher priority notices intermixed with lower priority ones

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3636]
Looking at myDEBUG-adm-20200630-165120-000758-warning.log: 

[30-Jun-2020 16:51:20 America/New_York] PHP Fatal error:  Uncaught Error: Call to a member function read() on boolean in /Users/scott/Sites/site/admin/includes/functions/general.php:3157
Stack trace:
#0 /Users/scott/Sites/site/admin/categories.php(443): zen_build_subdirectories_array('/Users/scott/Si...')
#1 /Users/scott/Sites/site/admin/index.php(11): require('/Users/scott/Si...')
#2 {main}
  thrown in /Users/scott/Sites/site/admin/includes/functions/general.php on line 3157

**Comment by lat9** [comment]
Yep, that'll happen for those **fatal** errors.  I've looked fairly deeply into PHP's error-handling and don't believe that there's any way to circumvent that.

**Comment by scottcwilson** [comment]
Oh ok.  It just could be misleading since the filename is warning.

**Comment by lat9** [comment]
Agreed, but those fatal errors ... are **_fatal_**, so they do a `cease-and-desist-order` on any additional processing.

**Comment by drbyte** [comment]
Ya, once a fatal error is triggered it can only bubble execution up to already-configured listening error-handling processes on the way to final exit.
I think the only other option at that point is to have already-registered additional handlers listening in order to take action in a round-robin loop.
