### ISSUE TITLE
Messagestack $_SESSION content gets wiped out

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3740]
The 1.5.7 changes to the messagestack class wipe out the data that is stored in $_SESSION['messageToStack'].

This report 

https://www.zen-cart.com/showthread.php?226969-Warning-message-not-showing-for-not-checking-quot-terms-and-conditions-quot-box-on-checkout

came in today.  Restoring the messageStack class constructor and size() functions fixes it, but these changes were presumably done for a reason so I want the folks who did them to weigh in.  @lat9 and @zcwilt ?

**Comment by lat9** [comment]
I'm on it.

**Comment by lat9** [comment]
That detection needs to be moved back to the class' `output` method (I've no idea why I thought it would be a good idea to move it to the `size` method).  The issue is that some headers', notably that for the `checkout_confirmation` page, check a stack's `size` to make decisions.

I'll be moving that clean-up back to the output (presumed template) method.

**Comment by lat9** [comment]
Actually ... the issue was a premature reset of the session-based messages.  Moved that to the `output` method, since that's indicative of the page-load having entered the rendering phase (no more page-redirects).
