### ISSUE TITLE
1.5.8 ... is that version-naming appropriate?

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3765]
There's a lot of **_infrastructure_** change going on in the `v158` branch, making me think that the current version number is not indicative of the level of change.

**Comment by drbyte** [comment]
What are you suggesting would be appropriate?

There are those who would say we can't ever call something `1.6` or `2.0` because those numbers have been tainted.
Jumping to `3.0` sounds too major.

There are no plans for 1.5.8 to have a "new template" (maybe a later version though), but if the template doesn't change then a huge leap doesn't feel appropriate.

**Comment by lat9** [comment]
I was thinking something akin to `1.7` or `1.8` (skipping 1.6 for the above reason).  It just seems that sticking with a `1.5` major version has the implication that the change isn't big (although the current branch is a _very different_ beastie than its predecessors).

**Comment by scottcwilson** [comment]
Changing the version number after work has begun seems like a lot of pain for minor benefit.  As long as 1.5.8 is mostly backwards compatible, I'd prefer that we not spend our limited time on changes like this.
