### ISSUE TITLE
New boolean define PRODUCT_THROWS_200_WHEN_DISABLED does not use quoted values

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3789]
References to this value in the following files: 

./includes/functions/functions_products.php
./includes/modules/pages/product_free_shipping_info/main_template_vars.php
./includes/modules/pages/document_general_info/main_template_vars.php
./includes/modules/pages/document_product_info/main_template_vars.php
./includes/modules/pages/product_music_info/main_template_vars.php
./includes/modules/pages/product_info/main_template_vars.php

compare to `true` rather than `"true"` as is traditionally done for other defined constants.

This could be confusing.

**Comment by drbyte** [comment]
Use of boolean was intentional for this. It's not a configuration switch (which have heretofore required strings). It's an optional and technically undocumented override one could add.

Using boolean words as strings is very often misinterpreted. Boolean is very clear.

Aside: in hindsight I think the use of a constant here was ill-conceived. I wish I'd leaned towards a notifier hook instead, so that the logic could be product-specific.

**Comment by scottcwilson** [comment]
Very good - closing then, but please document with an example of how to configure this.  (Or just make a note here and I'll add it to the documentation.)

**Comment by drbyte** [comment]
Update: Given a notifier event does already fire, I'm inclined to leave this constant undocumented, in favor of using the observer instead.

**Comment by scottcwilson** [comment]
Isn't an observer kind of storeowner unfriendly?  What about a flag instead in the Admin > Configuration > Stock area? 

If you're set on using the observer, can you add a quick note to (say) /user/products/products_misc.md telling people how to enable this behavior?  It's completely undocumented right now.  I just stumbled on it trying to answer Steve's question.

**Comment by mc12345678** [comment]
The way I have read the code that uses/supports `PRODUCT_THROWS_200_WHEN_DISABLED` is that its use must be very purposefully implemented... If just the constant is defined, then a "disabled" product becomes visible and a 200 is thrown. To have the disabled product "hidden" then requires addition action in advance of the code at: https://github.com/zencart/zencart/blob/cff05fe30df4938e9053f5d23690bb4c975a3a80/includes/modules/pages/product_info/main_template_vars.php#L21

That additional action being in the form of code intended to at least identify that the product is not to be displayed if the disabled product is to return a 200 code. Otherwise, if `PRODUCT_THROWS_200_WHEN_DISABLED` is the only "modification" made where it is set `===true`, then `$product_not_found` would be set to `false` for a disabled product in the above line, but  `true` for a product that does not exist in the database in the same above line. With `$product_not_found` set to false (product exists but is disabled) and the only other change implemented to the site is defining `PRODUCT_THROWS_200_WHEN_DISABLED` with `define('PRODUCT_THROWS_200_WHEN_DISABLED', true);` then the product will be displayed even though its status is disabled.  

By going a step further to "filter" the data based on whatever criteria is desired, whether it is stock quantity, logged in status, group of which the person is a part, other product in the cart, etc... the condition of displaying the product can be controlled, but with it displayed if nothing else is done to establish `$product_info->EOF == true`. 

I would say that ideally it seems that the additional "control" may be implemented within `includes/modules/pages/PRODUCT_INFO_PAGE/main_template_vars.php` so that the necessary values are controlled as close as possible to the usage of those values. They could also be modified at the end of `includes/modules/pages/PRODUCT_INFO_PAGE/header_php.php` with the chance of being modified later by some other code. Or as suggested as far back as within: `zen_product_set_header_response`.  

That said, there is something therein that doesn't make a lot of sense to me, `$products_status` is set in there as a global value.  I don't see though where that value is used in the immediate included software.  Instead, `$product_info->fields['products_status']` associated results are used and unfortunately the function `zen_product_set_header_response($product_id, $product_info = null)` doesn't support modifying that data. Any observer monitoring the included notifier would have to "guess" at the variable type/name to be modified (function doesn't require `$product_info` to be passed but to be something that resembles that type of variable. Even if the second parameter of the function were made mutable (`&$product_info`), the notifier that is within that function passes the fields of the variable as an immutable array, so still doesn't provide the maximum benefit... 

Thus again, going back to my earlier statement that to control the "visibility" of the product when using `PRODUCT_THROWS_200_WHEN_DISABLED` requires a bit more purposeful code with likely at least two notifiers used to control the situation such that a disabled product that is to return a 200 html response but not be displayed arrange to have `$product_info->EOF == true` within `includes/modules/pages/PRODUCT_INFO_PAGE/main_template_vars.php`.
