### ISSUE TITLE
Suggestion: Admin page widget RecentOrdersDashboardWidget.php attribute query changes 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3794]
As raised in 
https://www.zen-cart.com/showthread.php?227011-Slow-admin-home-page-load

**Comment by drbyte** [comment]
Thanks for transferring the concern here. 

But is ”should not query” an accurate description, and outcome?

Excluding the attributes makes the data useless in stores that use them heavily, doesn’t it?

**Comment by scottcwilson** [comment]
Perhaps the behavior could be switchable.  Title updated.

**Comment by scottcwilson** [comment]
Alternately, perhaps the attribute query could be done in real time when the bubble is clicked.   Even this could be optional, of course.

**Comment by JSWebSteve** [comment]
> Excluding the attributes makes the data useless in stores that use them heavily, doesn’t it?

I'm not sure I would agree with this comment.

Surely the purpose of the bubble is to give a quick glance look at what an order contains. Nobody is going to pick and pack an order based on the content of that little bubble.
The site that the issue was identified on uses attributes for many of their products and the general product info in the bubble is sufficient to give a brief overview of the order content.

**Comment by JSWebSteve** [comment]
> Alternately, perhaps the attribute query could be done in real time when the bubble is clicked. Even this could be optional, of course.

This seems like a sensible solution as it will limit the query to a single order.
