### ISSUE TITLE
bug in also purchased products.

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3805]
https://github.com/zencart/zencart/blob/89621e6e8cc96dfdaa202655026737174195f168/includes/modules/also_purchased_products.php#L15

see:
https://www.zen-cart.com/showthread.php?227029-Customers-who-bought-this-product-also-purchased-doesn-t-show-any-products

i have confirmed.  but i do not have the solution at this hour.

**Comment by scottcwilson** [comment]
The forum poster's remark appears correct- includes/modules/also_purchased_products.php line 15 is missing the final parm - should be 

`  $also_purchased_products = $db->ExecuteRandomMulti(sprintf(SQL_ALSO_PURCHASED, (int)$_GET['products_id'], (int)$_GET['products_id'], (int)MAX_DISPLAY_ALSO_PURCHASED), (int)MAX_DISPLAY_ALSO_PURCHASED);
`
otherwise `$zf_limit` = 0 by default in ExecuteRandomMulti

**Comment by proseLA** [comment]
problem started here:

https://github.com/zencart/zencart/commit/e048dd76a4c

added an element to the ```sprintf``` and "stole" it from the ```ExecuteRandomMulti```

it seems redundant to have the ```MAX_DISPLAY_ALSO_PURCHASED``` in both places.  i think it can probably be removed from the define.

**Comment by scottcwilson** [comment]
Agreed.

**Comment by scottcwilson** [comment]
> it seems redundant to have the MAX_DISPLAY_ALSO_PURCHASED in both places. i think it can probably be removed from the define.

Indeed, the presence of LIMIT in the query is a bug.  The query should return a large dataset and pluck `$zf_limit` (parameter 2) items from it - using LIMIT on the query means the same items will be retrieved every time, except in different order.
