### ISSUE TITLE
Feature? More attention for Popular/Bestselling products

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#3867]
One thing I often see asked is "how do I draw attention to popular products" (usually they mean "automatically", hands-off).

The challenge is that everyone's interpretation of "popular" is different. 
It could be "best reviews". 
It could be "most sold" (this week, this month). 
It could be "according to something I heard on social media" (ie: any whim of the marketplace or the customer/storeowner's favorite blogger). 
It could be a certain singular attribute of a product.
... etc

So, using software to do "automatic aggregation" such as relying on sales "numbers", or "number of 5-star reviews" is probably not the best approach. 

Instead, I wonder if it may be as simple as using existing capabilities but documenting a few approaches that can be used?  

eg:
- "featured" products tagging
- "banners" to draw attention
- "link products to a Popular category" which is then positioned at the top of the categories sidebox
- using an ez-page or the `define_main_page` for more freeform text with links

What other approaches have you seen?  Or are you using yourself?

Is there a need for more in-app tooling? What sort?

**Comment by wiztechinc** [comment]
Most of the time I tell small business clients to target specific products, i.e., use featured products. But what I also allow the featured products (all centerboxes) to be moved to the top of the home page when desired. Moving them to the top puts them "above the fold" per se. But I also remove (display:none) the title of the centerbox in that case. I also suggest only one row of them. Sometimes more is just too much no matter where they are displayed. But really having the featured products at the bottom of the page is very sales inefficient. A sidebox can help but it has its own disadvantages, space, numbers, or one at a time presentation).

The best sellers sidebox is a bit unwieldy - with a numbered list, it doesn't fit that well. And the box can be long and take up a lot of vertical space. But I have used a best sellers centerbox. I would recommend that as a default zc feature - even more than the new products box.  A best sellers page (with categories box link like all, featured, specials) would be a great assist with what really is a handy but not well used feature. The biggest drawback is that on a site that doesn't sell much, the best sellers may be skewed and not representative of what the owner wants to sell or actually can sell with a higher sales volume.

So many folks don't run specials and add few to no new products in a month. Then of course most who display the new products have never curtailed by date and are showing a random selection of products listed as new that their customers may well be aware have been on the site for years! 

Most don't use banners - one has to have either graphic design skills or html skills for the banners and it's more than most small businesses can do or afford to do. Perhaps for some it's because they don't realize how or if this can be done. With responsive though, this is very tricky for most to even consider. 

Discussion of how to manage the categories links is always necessary - many don't realize how to sort and only find out when they ask me to move something that it's possible. Then they have 20 or  even 30 categories with a zero sort number. A lot of work to correct that situation. I wish there was an easy way to do that.

As most of my clients are very small businesses, part of this may not be so for larger clients but my larger clients may also have more money to spend on their website and thus have more custom or additional options. But many of the things I mentioned also apply to them.

So yes, some discussion, guidance is necessary.

**Comment by dbltoe** [comment]
>Discussion of how to manage the categories links is always necessary - many don't realize how to sort and only find out when they ask me to move something that it's possible. Then they have 20 or  even 30 categories with a zero sort number. A lot of work to correct that situation. I wish there was an easy way to do that.

Quick Updates works for that. 👍

**Comment by wiztechinc** [comment]
> Quick Updates works for that. 👍
without installing a mod.....

**Comment by mc12345678** [comment]
> Discussion of how to manage the categories links is always necessary - many don't realize how to sort and only find out when they ask me to move something that it's possible. Then they have 20 or even 30 categories with a zero sort number. A lot of work to correct that situation. I wish there was an easy way to do that.

Could run a SQL query:
````
UPDATE categories TOne INNER JOIN ( SELECT t.categories_id, t.categories_name, @rowNumber := @rowNumber + 10 as rn FROM (SELECT t1.categories_id, t2.categories_name, t2.language_id FROM DB_PREFIXcategories t1 LEFT JOIN DB_PREFIXcategories_description t2 ON t1.categories_id = t2.categories_id ORDER BY t2.language_id ASC, t2.categories_name ASC ) AS t CROSS JOIN (SELECT @rowNumber :=0) as var) AS r ON TOne.categories_id = r.categories_id SET TOne.sort_order = r.rn;
````

Which sorts the categories alphabetically in intervals of 10. Note that if executing within the `Install SQL Patches` tool, that will need to update/replace the value of `DB_PREFIX` with the actual `DB_PREFIX` for the database as found in `includes/configure.php` & `admin/includes/configure.php`. If that is '' (`define('DB_PREFIX', '');`), then simply remove DB_PREFIX from the above...

**Comment by wiztechinc** [comment]
Thanks!  I'll stick that into my saved queries file!
