### ISSUE TITLE
Updates to multiple admin pages

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#3928]
I am making updates to multiple admin pages. Each page will have it's own PR, but since the changes are fairly common acros all the pages, I am using this issue as as placeholder for the changes.

- Removing braces from include and require lines
- Update status icons from images to font-awesome icons
- Replace info- and current arrow images for font-awesome icon buttons
- Remove quotes on integers in queries
- Replace ```$_GET['page']``` with ```$currentPage```
- Make sql queries uppercase
- unify the seach box feature on pages where it is used. (idea for future update: put this in a function or class to prevent repetitive coding)
- Edit page replace labels with plain text where multiple inputs are used for 1 label
- Add id's to input fields
- Sorting drop-down remembers current selection
- Type casting multiple variables
- Replace Spiffycalender with datePicker

references to this issue will be made in the PR's

**Comment by Zen4All** [comment]
That;s what my plan is.
There may of-course still be add-ons that use Spiffy, so maybe leave spiffy in 1.5.8 as deprecated, and remove completely by 1.5.9?

**Comment by drbyte** [comment]
> * Edit page replace labels with plain text where multiple inputs are used for 1 label

Can you explain this further?

**Comment by Zen4All** [comment]
Object like multi language inputs, and radio fields are not allowed to have a label with a ```for=""``` attribute. So these label neet to be converted to something that looks like a label, but is a ```<div>``` or a ```<p>```.
This was already done on pages like collect_info, I think by @zcadditions.

**Comment by mc12345678** [comment]
Realize this is closed.

Noting that in some of the updates, the following code "template" has been removed:
````php
// Split Page
// reset page when page is unknown
                  if ((!isset($_GET['page']) or $_GET['page'] == '' or $_GET['page'] == '1') && !empty($_GET['IDParameter'])) {
                    $check_page = $db->Execute($zones_query_raw);
                    $check_count = 1;
                    if ($check_page->RecordCount() > MAX_DISPLAY_SEARCH_RESULTS) {
                      foreach ($check_page as $item) {
                        if ($item['association_id'] == $_GET['IDParameter']) {
                          break;
                        }
                        $check_count++;
                      }
                      $_GET['page'] = round((($check_count / MAX_DISPLAY_SEARCH_RESULTS) + (fmod_round($check_count, MAX_DISPLAY_SEARCH_RESULTS) != 0 ? .5 : 0)), 0);
                    } else {
                      $_GET['page'] = 1;
                    }
                  }
````
And in some cases it remained.

This code snippet (although it needs revision to fully function correctly) has previously appeared to allow arriving at these pages with just the associated `IDParameter` being identified allowing the code to determine on what page that particular item would be found (if present) or to then show the last page of results if the `IDParameter` was not present or was `falsey`.

This has "recently" been somewhat discussed at: https://www.zen-cart.com/showthread.php?228475-Featured-Products-choosing-deleting-of-10th-item-on-first-page-error-bug

While the intent was to remove `$_GET['page']` type parameters in place of `$currentPage` it doesn't appear that was fully performed/the feature of the above code considered. E.g. appears that there is more to be done in these code "sections" to align with the OP about removing the `$_GET['page']` like parameters and to retain the feature that has been present (and appears may have been broken) at least as far back as ZC 1.5.0 for some of the pages. At some point in ZC 1.5.8 the method `findPage` has been added to the admin's `splitPageResults` class to support finding the page. That method may also/otherwise be appropriate to use in place of the insides of the above code snippet.
