### ISSUE TITLE
Option Value Sorter - Update Attribute Sort Order not working 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#3947]
Go to Admin > Catalog > Option Value Sorter  and look below the dropdown list of option names. 

You see two dropdowns: For a Product and For a Category. 

The "For a Category" list is empty.

**Comment by proseLA** [comment]
i do not really understand why there is an option value sorter for category, but i do remember looking at this issue, and not really understanding it too well...  

https://github.com/zencart/zencart/pull/3895

**Comment by scottcwilson** [comment]
Scenario: you have two options (Extra Large and Extra Wide), created in that order.  They show up on the product info page in that order.

Then you decide you want Extra Wide to be first.  This option is only used on category 12.  

That's when you would use it.  Fix the 2 option sort orders, select Category 12, select option name, update. 

(Alternately, you could update it on all products or just a single product.)

**Comment by scottcwilson** [comment]
Having said that, I don't believe the category option actually worked in 1.5.6 either; it just had a populated dropdown. :(

**Comment by mc12345678** [comment]
> Scenario: you have two options (Extra Large and Extra Wide), created in that order. They show up on the product info page in that order.

> Then you decide you want Extra Wide to be first. This option is only used on category 12.

> That's when you would use it. Fix the 2 option sort orders, select Category 12, select option name, update.

> (Alternately, you could update it on all products or just a single product.)

Okay, but where's any of the assistance to know what is associated with what? I'm not seeing any changes made to the other areas/dropdowns (in 1.5.7) when selecting any of the existing dropdown options... It appears as if say the Version Option Name appears in all product and all categories... Can't be true and isn't.

Ughh and why is the products_id not associated with the product list dropdown?  There's no requirement for product names to be unique, so why isn't there distinguishing info? (Sorry, I'll take that up at another more appropriate location).

**Comment by scottcwilson** [comment]
I'm not positive what you're saying, but to understand the issue better, do this: on a 1.5.6 site, go to Admin > Catalog > Option Value Sorter.   Observe that the "For a Category" list is fully populated with all categories. 

It should also be that way in 1.5.7/1.5.8 but instead it's an empty dropdown.

**Comment by mc12345678** [comment]
@proseLA provided the currently proposed solution to the "empty" category listing.

What I'm saying is that once that fix is applied, accessing this options_values screen provides a dropdown to select any of the option names that are to have the option values sequenced, a listing of all product and a listing of all categories.,, These are in no way "related" to each other.. Selecting an option name doesn't adjust the options displayed in the product list nor the categories list. Selecting a product doesn't change the option name list or the category list and selecting a category doesn't modify either of the other two. 

While reviewing those three lists, I realized that I had a copy of one of the products and had removed the excess (Duplicate) or whatever it is now and so two product showed up next to each other with the same name. If I had really wanted to copy/apply/or whatever the option values to one or the other I wouldn't be able to tell which was which because there is no number sign with the products id or any other unique identifier...

**Comment by scottcwilson** [comment]
OK so this is really a dup of #3891.  Closing. 

@mc12345678 If you get into this situation, do a View Source (or Inspect in Chome) of the drop down and you'll see the id of the each product in the list.  The higher id is the newer (copied) one, obviously.   But the better approach is not to remove [DUPLICATE] until you think of a proper title for the copied product.

**Comment by mc12345678** [comment]
> If you get into this situation, do a View Source (or Inspect in Chome) of the drop down and you'll see the id of the each product in the list. The higher id is the newer (copied) one, obviously. But the better approach is not to remove [DUPLICATE] until you think of a proper title for the copied product.

I wrote this from the perspective of a user that is simply trying to use the software... Not as someone that understands what data is pushed to the browser to support record entry and modification... Remember this software needs to remain usable for entry level and not require some "magic" to figure out what should really be simple. I'm glad that an aspect of [DUPLICATE] was addressed, though heaven forbid someone copy a copy of a copy in order to "quickly" populate their store or... copy the original again and again and again,.. There goes the "unique" name as all one off copies of the original will each have the same "duplicate" (or whatever the text has become) additional name.  So if 5 copies are made, then instead of 6 items having all the same name, 5 of them will have the same name (if initially not too long) and one of them will be unique (or all 6 could be the same if the initial name is too long).

Anyways, this has all gotten buried including the discussion of how the multiple "selection" items have no functional relationship to each other among the other issues.
