### ISSUE TITLE
"Unused" definitions that were removed are (er) "Used".

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3975]
[This](https://github.com/zencart/zencart/commit/bcd724e495cdf37bbdd145ca4412991235c27266#diff-ebcabc3e36c1db4c3002f506c1f877f4) commit removed the DATE_FORMAT_SHORT and DATE_TIME_FORMAT from the primary language file (e.g. english.php) which, as identified in [this](https://www.zen-cart.com/showthread.php?227224-shipstation-no-longer-importing-orders-after-upgrade&p=1373223#post1373223) Zen Cart forum posting, _are_ used by plugins (like ShipStation).

**Comment by drbyte** [comment]
Question: for the way shipstation is using this, does it really need to rely on a constant in Zen Cart? ie: is it critical that it know something about Zen Cart in order to do what it's doing in this part of the code? Or does shipstation's processing actually need/expect a certain format (which "coincidentally" matched what Zen Cart had in that constant) and therefore it would be more sensible to hard-code the expected format instead of using any constants in Zen Cart anyway?

**Comment by lat9** [comment]
Answer: It probably didn't need to rely on a Zen Cart constant when written in 2011, but this unneeded change has broken a relatively simple plugin that's worked for ages.  That also makes me wonder what other plugins are making use of these constants.

**Comment by scottcwilson** [comment]
This ticket should be closed.  Plugins should define their own constants and/or stay up to date.  I'm also confused about why you're making a big deal out of this, since it takes about 10 seconds to debug problems like this.  There's a debug log created when an undefined constant is referenced in code; work backwards. 

Cleaning up cruft from the code base is not an unneeded change; it's part of keeping Zen Cart relevant and attracting people to work on the platform.  People who will hopefully update their plugins more than once every ten years.

**Comment by drbyte** [comment]
In chatting with @zcwilt I think we're on the same page with cleaning up some of these older unused things, particularly regarding dates where their existence leads to confusion about what is officially supported and maintained vs not.

In the case of these date constants perhaps simply documenting their removal in the docs site is enough so that plugin authors have a place to reference the change. They could then choose to define a constant if they really want one or hard-code their own expected/required date format in their own code.

**Comment by scottcwilson** [comment]
> In the case of these date constants perhaps simply documenting their removal in the docs site is enough so that plugin authors have a place to reference the change.

Done - https://docs.zen-cart.com/user/upgrading/release_specific_upgrade_considerations/
