### ISSUE TITLE
[Feature] Child Template

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4015]
WordPress has this notion of a Child Theme where you only customize the stuff you want to change and get everything else from the regular theme directory, which can be updated with bug fixes, etc.

It would not be hard to do this for Zen Cart.   If approved I'd be happy to add it.  The first use case would be a child theme for Responsive Classic, which could perhaps be provided as a plugin after the release of 1.5.8.

**Comment by drbyte** [comment]
> where you only customize the stuff you want to change and get everything else from the regular theme directory

Must be pointed out:
Responsive Classic is already a "child theme" in this sense, with template_default being the "regular theme directory".

**Comment by drbyte** [comment]
Before writing code, how do you envision it working? There's not enough detail in your first post to respond to "if approved...".

Many questions arise, including this brief incomplete list:

What "kind" of "customizations" are you trying to support? Just CSS? That's easy today.
How many layers of inheritance do you envisioning supporting? Why?
How would you combine javascript files that duplicate each other, incorrectly replacing newer versions with older versions?
How would you combine CSS directives that the child wants to bypass in its parent?
How would you deal with plugins that say "put these files in your template directory" when really they belong in the parent? 
What would you call the "parent" when it's not really the parent because it's a child of template_default?
How would files outside the `/includes/templates` directory be handled, such as modules and language files? (Particularly wishing to avoid multiple nested levels of new override directories.)

**Comment by drbyte** [comment]
More importantly: 
What's the real-world-use-case that drove you to post this in the first place? What were the very specific technical problems that were being encountered? 
Particularly, what files did you need to replace/update that were problematic and thus drove enough frustration to make a post?
The background behind every feature request is way more important than the request itself. I'd rather see those details before seeing anything about implementation ideas for the "how".

**Comment by scottcwilson** [comment]
This would be for code files; css and JS would still have to be replicated.  The spirit of this idea is to allow people to modify just the code files needed. 

The problem it solves is having people copy responsive_classic and then never merge back in the changes.

**Comment by barco57** [comment]
The only use case I can come up with off the top of my head is where you might want child templates of "your template" to change the look of the site seasonally, so mostly CSS changes in the children. 
So for most of the year, you just use responsive_classic (or a clone of responsive classic (before dbltoe comes in to remind us of that plugin)), and then you would have children named, responsive_classic-christmas, responsive_classic-easter, etc. Now I know some will say just make multiple clones and edit the clones for those holidays, seems reasonable until you remember the clones bring EVERYTHING, you may not want everything, as you move from default to responsive classic to children you want less in each. Add a plugin to the responsive classic and you now have to add it to every clone,.. if using a children method and the children are lightweight than you possibly won't have to address the plugin in the children. 

I would personally extend this as it is something I have on the back burner that I have been thinking about for years and children would take us partway there. A store owner may want to "rearrange" some stuff for Christmas, change the order of centerboxes on the homepage, increase the number of items in those centerboxes, switch out text on the homepage, etc... So I think it would be brilliant if in the children's template folder there would be files that could override layout config settings. Nothing worse than switching a template and then having to go fiddle with all of those config switches drbyte hates so much and then having to switch them back when the holiday is over and you switch back to the "normal" template

just my two cents and if you take a drink every time you see the word children in this thread it will make you feel better...lol

**Comment by scottcwilson** [comment]
> Particularly, what files did you need to replace/update that were problematic and thus drove enough frustration to make a post?

I think the approach I am suggesting would make it easier for people to stay up to date.

>Responsive Classic is already a "child theme" in this sense, with template_default being the "regular theme directory".

Agreed - so an alternate approach would be to overrwrite the contents of template_default with what's in responsive_classic, so the latter would become the "real" base.

**Comment by barco57** [comment]
> so an alternate approach would be to overrwrite the contents of template_default with what's in responsive_classic, so the latter would become the "real" base.
if I am understanding you correctly then ummm, no.

**Comment by scottcwilson** [comment]
Can you elaborate on your reasoning?  I am suggesting this because desktop only templates make no sense anymore.  What's the counterargument?

**Comment by barco57** [comment]
so you are saying responsive_classic files should replace template_default files, basically making resposive_classic the base for all things, unless you override absolutely everything in a template to get away from responsive classic?

Let me lay my bias out on the table. I hate (it is a strong word but I couldn't think of another I would use in polite company) responsive classic, am I forced to use it, sure, and I hold my nose the whole time. Where is my poop emoji when I need it.....

**Comment by drbyte** [comment]
> people copy responsive_classic and then never merge back in the changes

True. There's all kinds of things they never merge back in until something breaks.

> overrwrite the contents of template_default with what's in responsive_classic

I knew that would come up. :(  I actually expected it to be said sooner than this.

> What's the counterargument?

IMO the counter-argument is that responsive_classic uses the wonky MobileDetect stuff to determine mobile mode, instead of being truly responsive. That and other bloat it introduced that I wish we'd done differently.

> that could override layout config settings

I'm toying with ripping out the defaults for those and creating a json field in a template-related table to store template-specific configs for those. It's a lotta work, and a lotta admin ui dev, and a pain to make backward-compatible with existing templates. But it would reduce a lot of the pain of settings being suddenly wrong when switching between templates.
But this is a serious digression from the topic at hand.

**Comment by drbyte** [comment]
I'd like to envision more clearly what overrides a "child template" would have in this context. 

I'd prefer real examples, not contrived/theoretical.

And, while I don't want a rabbit trail, for completeness I should ask: how would it differ from the `/shared` template tier that was experimented with in v160-alpha? I'm pretty sure you're not talking about the same thing, but would like to know the intersection of the two.

**Comment by barco57** [comment]
> wonky MobileDetect stuff to determine mobile mode

yes, mobile detect can be tossed to the curb

> I'm toying with ripping out the defaults for those and creating a json field in a template-related table to store template-specific configs for those. It's a lotta work, and a lotta admin ui dev, and a pain to make backward-compatible with existing templates. But it would reduce a lot of the pain of settings being suddenly wrong when switching between templates.

Yes, please. Draw a line in the sand and don't worry about backward-compatible.

**Comment by scottcwilson** [comment]
> And, while I don't want a rabbit trail, for completeness I should ask: how would it differ from the `/shared` template tier that was experimented with in v160-alpha? I'm pretty sure you're not talking about the same thing, but would like to know the intersection of the two.

Shared was another idea for multiple templates.   Different.

**Comment by scottcwilson** [comment]
> I'd like to envision more clearly what overrides a "child template" would have in this context.

Consider the following workflow: 
- Create template rc_child (child of responsive_classic.  (This creates includes/templates/rc_child/template_info.php)

You then create the following customizations: 
- includes/templates/rc_child/css/stylesheet.css 
- includes/languages/rc_child/english.php 
- includes/languages/english/rc_child/index.php

of course, instead of basing your template on responsive classic, it could be some other template - the principle is the same. 

If there's an update to the template, you drop it in and only need to worry about merging files you have changed.

**Comment by Zen4All** [comment]
> > And, while I don't want a rabbit trail, for completeness I should ask: how would it differ from the `/shared` template tier that was experimented with in v160-alpha? I'm pretty sure you're not talking about the same thing, but would like to know the intersection of the two.
> 
> Shared was another idea for multiple templates. Different.

Liked it, and backported to several 1.5.x projects

**Comment by lankeeyankee** [comment]
> Yes, please. Draw a line in the sand and don't worry about backward-compatible.

This!!

**Comment by mc12345678** [comment]
>> Particularly, what files did you need to replace/update that were problematic and thus drove enough frustration to make a post?

> I think the approach I am suggesting would make it easier for people to stay up to date.

As to the staying up-to-date, I'm not really seeing anything above that improves on that. In fact now there are possibly two files that need to be updated, the parent and the child. I see that it would be easier to update if there was a way to more easily align the template override files with the default/parent files.  Right now this is or can be done mostly folder-by-folder rather than template-to-template. I've found a way around that, but I also see that too often individuals are recommended in the forum to ditch their old template and either start anew or with something newer. Statement is made for various reasons whether legitimate or not, but it partially surprises me that keeping a template up-to-date is being identified as I see it as pretty much the primary concern. I'm glad to see it, but surprised.

I do also get the "seasonal" template, I tried that early on in my working with Zen Cart and thought I had it all figured out, but then too came the "plugins" part of ensuring everything was everywhere it needed to be, worked pretty well for the year used, but haven't done that again since. It *was* a full different template rather than just say a color change. Would be willing to revisit the idea of seasonal templating, preferably I guess with minimal file adjustment.

**Comment by scottcwilson** [comment]
> As to the staying up-to-date, I'm not really seeing anything above that improves on that.

It helps because you only copy the files you change, rather than ALL of them.  So on the next upgrade, if a file you haven't changed is fixed, you get the fix without needing to do any merging or copying.

**Comment by drbyte** [comment]
I'd forgotten to ask this earlier:

Would it make sense to think in terms of "parent" instead of "child"? 
eg: "this template, which is set as Current, names its 'parent' as XYZ template, so lookups go there first before template_default"?

Or is that what you had in mind but just hadn't stated it that way?

A question arises then: to what degree does any version-control become crucial when naming the parent?

**Comment by scottcwilson** [comment]
I used the nomenclature that WordPress uses.  That's all.

**Comment by drbyte** [comment]
> A question arises then: to what degree does any version-control become crucial when naming the parent?

**Comment by scottcwilson** [comment]
Parent is always the latest and greatest.  Child is where merging needs to be done to pull in changes.
