### ISSUE TITLE
1.5.7: getPluginRelativeDirectory returns wrong relative path

### ISSUE THREAD

**Issue by jadebox** [zencart/zencart#4023]
The value returned by the getPluginRelativeDirectory method in includes/classes/FileSystem.php is incorrect if ZenCart is not installed in the "root" folder.  

I fixed it (on my site) by changing the method to:

` public function getPluginRelativeDirectory($pluginKey)`
`    {`
`        if (!isset($this->installedPlugins[$pluginKey])) {`
`            return null;`
`        }`
`        $version = $this->installedPlugins[$pluginKey]['version'];`
`        $relativePath = 'zc_plugins/' . $pluginKey . '/' . $version . '/';`
`        if (DIR_WS_CATALOG != '') $relativePath = DIR_WS_CATALOG . '/' . $relativePath;`
`        return $relativePath;`
`    }`

It fixes the issue I ran into (css not loading for the plug in), But it doesn't seem right ....

All the other methods use DIR_FS_CATALOG. So they all deal with file system paths as you would expect for a class named FileSystem.`  But, this method is used to produce the URL to assets like the plug-in's css file.

**Comment by proseLA** [comment]
sorry, i do not agree.  the function, `getPluginRelativeDirectory`  returns the "relative" path to the root of the install.  

it is entirely possible that the return value is used incorrectly further down the line. 

if i were to:

`print_r($fs->getPluginRelativeDirectory('shipAdmin'));`

returns:

`/zc_plugins/shipAdmin/1.0.0/`

seems pretty relative to me.

i have had some problems loading `.js` files; so the idea that you are having problems loading `css` files seems more than plausible.  but this properly named function, does what it is named to do.  IMO.

best.

**Comment by scottcwilson** [comment]
I agree with @proseLA.

**Comment by mc12345678** [comment]
> `if (DIR_WS_CATALOG != '') $relativePath = DIR_WS_CATALOG . '/' . $relativePath;`

Wouldn't quite be right for others ***not*** having the store in a web-facing sub-directory (i.e. stores installed to the root of the domain)... A site that is installed to the root of the domain is expected to have `define('DIR_WS_CATALOG', '/');` which would assign/reassign `$relativePath` to include that slash and become `'//' . $relativePath;`

If something like this were incorporated for some reason (relative from the root of the store (suggested by OP) versus relative to get to the root of the store (in a way provided)) then the test of application would need to be something else, though would question why test anything and not just apply universally: `$relativePath = DIR_WS_CATALOG . $relativePath;` as an action somewhere in there. Again... That is *if* the existing string is later found/determined to be incorrect or need revision.  

An issue I see though too is that with the existing "relative path" response, using it with an existing define, such as DIR_WS_CATALOG or any such DIR_WS_XXXX define, would also result in that duplication of the slash, whereas if no such use is incorporated then as identified/determined, the path would be off of the domain instead of the subdirectory. If the intention was to remove this relative path from the current full path, then the slash would need to be added back in to reference whatever is at the root of the directory or subsequent path...

**Comment by zcwilt** [comment]
As others have pointed out, this method does exactly what it is meant to do, and I don't think it needs changing.

That said, OP @jadebox may still have a problem to solve, that current plugin system code is not addressing.

**Comment by mc12345678** [comment]
In part I still disagree, though I am interested to know what is an intended use of the output of the method `getPluginRelativeDirectory`? I'm not seeing how it formatted the way it is that it would reasonably be used.

**Comment by drbyte** [comment]
Closed by #4039
