### ISSUE TITLE
Plugin Manager Question: Multiple plugins using common processing

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4029]
A number of my current plugins use some [common processing](https://github.com/lat9/vinos_common) to ensure that their required notifiers are available.  Is this going to work with the zc157+ plugin-manager?

Along the same vein, what if a plugin provides a function (think, although it's now in the zc158 core, `zen_cfg_read_only`) that's also used/distributed by another?  Is that going to result in a PHP error due to a function that's already defined?

**Comment by drbyte** [comment]
We haven't incorporated anything like this in the `zc_plugins` feature yet.

Adding shared packages, whether namespaced or not, is a huge complex challenge for projects like Zen Cart where people resist staying current with core code and want to still add things willy nilly to their sites.  It's even more complicated when people (storeowners, plugin authors, anyone) want to add packages that have shared dependencies on other packages ala `composer`. While `composer` is great, it requires regular refreshing of all packages in order to incorporate updates and maintain compatibility with other inter-related packages ... which is something that's impossible to control or support well with an open source "complete system" like Zen Cart. Not only because it's procedural code, but also because most end-users have very limited technical skill, and almost zero command-line skill/comprehension. Modern web dev requires more and more command-line skill to keep current.

I'm thrilled that you're namespacing your own utilities! Co-integrating them across `zc_plugins` is definitely going to introduce some challenges we need to collaboratively sort out.

Tagging @zcwilt for comment, as I know he's worked on these concepts more than I have.

**Comment by lat9** [comment]
Thanks for the detailed response, @drbyte.  I'm just trying to work through some of the potential integration hiccups before I start looking to convert some of my plugins to `zc_plugins`.

**Comment by zcwilt** [comment]
As @drbyte said there isn't currently any support for common libraries etc yet for plugins. 
Something that was in the original code, but not committed was the ability run pre-install checks, 
e.g. to check if a specific php extension was installed and more relevant, if a specific zc plugin, or function or class was available.
This will come in v158 once I get time to finish off catalog side plugin support.

**Comment by scottcwilson** [comment]
The same problem exists with classic plugins - you'd have to ifndef any function that might be defined by another plugin.
