### ISSUE TITLE
[Proposal] Replace httpClient with Guzzle package

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#407]
Replacing httpClient (used by ups and usps and various older shipping modules) with Guzzle requires either rewriting those modules, or writing an interface to bridge httpClient to Guzzle.

Switching to Guzzle allows the 3rd-party module to be kept up-to-date instead of unmaintained like the httpClient code has been.

UPS Module for testing: https://www.zen-cart.com/downloads.php?do=file&id=1293

**Comment by drbyte** [comment]
Note: for PHP packages that are being distributed with core code, Zen Cart is currently using `/includes/library` instead of `/vendors` ... so you'll want to put the GuzzleHttp files there ... and not touch composer.json

**Comment by BlackGh0st** [comment]
Just looked into this, I think a Interface won't do the job for you, since all attributes and methodes got public access. But I would suggest to use the existing one as an adapter and initiate the guzzle instance there - may be it would be even better to declare the whole guzzle-http client as a psr7 instance - which will force you to the psr7 interface.
