### ISSUE TITLE
Specials: Add by selection is now including linked products

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4077]
![Clipboard01](https://user-images.githubusercontent.com/4391026/98873805-4dcf3500-2479-11eb-8042-82680dcddac9.gif)

**Comment by torvista** [comment]
zen_draw_products_pulldown
is missing an else to this clause for !$show_current_category that was in use in the previous version of this function. 

```
$condition = '';

    if ($show_current_category) {
        // only show $current_categories_id
        $condition = " AND ptc.categories_id = " . (int)$current_category_id;
    }
```
previous version
```
} else {
        $sql = "SELECT p.products_id, pd.products_name, p.products_sort_order, p.products_price, p.products_model
                FROM " . TABLE_PRODUCTS . " p
                LEFT JOIN " . TABLE_PRODUCTS_DESCRIPTION . " pd USING (products_id)
                WHERE pd.language_id = " . (int)$_SESSION['languages_id'] .
            $order_by;
    }
```

**Comment by torvista** [comment]
While I don't know why this function was refactored (for a shopfront aspect?), maybe this is more evidence that this function should be different for admin use: https://github.com/zencart/zencart/issues/4066

**Comment by proseLA** [comment]
> zen_draw_products_pulldown

@torvista i think i have asked before.  i will ask again.  can you please use permalinks to the code you are talking about?  are we talking v158 v v157?  or v157 v v156?  trying to track down what you are talking about would be so much easier for those of us affected by the changes that you make or are proposing to make. 

the function you described above does not exist.  i get it, its a typo; we all make them.

but i do not want to spend any extra time trying to figure out what you are talking about.  someone made the change for some reason.  whoever made the change, it is very difficult to find unless you can provide the permalinks to the code you are talking about.  

is this too much to ask?

respectfully.

**Comment by torvista** [comment]
1. Version
I don't see anyone mentioning version in their comments. Is it not assumed all issues refer to the currently-unreleased version, in this case branch 158 unless specified otherwise? Should the version always be mentioned in the text?

2. function name incorrect.
Guilty as charged. Should be function zen_draw_products_pull_down 

3. Permalink
Like this?
https://github.com/zencart/zencart/blob/v158/includes/functions/functions_categories.php

I seem to annoy you more than "necessary", it's not intentional, only trying to feed back stuff I find/fix on my upgrade...I'm not a pro. developer.

**Comment by mc12345678** [comment]
3. permalink... When navigating the file within github (literally here on this site), after making a selection of code, when clicking the "three dots" that appear adjacent to the selection, a dropdown is provided that offers Copy Permalink... 

Such a copy for this code section would result in: https://github.com/zencart/zencart/blob/0aaa10e342b9546fc6387636ac39d32f2afa77ab/includes/functions/functions_categories.php#L349-L354

Unfortunately, that permalink doesn't exactly identify a version number, but there are some ways to navigate around/investigate the file, etc to *try* to figure out where in the history of the code this is... Further though, such a permalink doesn't ensure that the code will/is actually within the final distribution of the software as rearrangements could occur that move/remove the commit from the final distribution..

1. Ehh, kind of? Depends on what is being reported/discussed... Any information of whatever situation is always helpful, including such things as found in *this* version, not tested in *this* version, etc... 

2. As far as the function name? Ehhh.. I think that perhaps there is some other stress going on that has brought on the response... I say this from my own perspective of me being snippy sometimes recently. :) 

If anything, I'm curious where on the catalog side this function is being used? There doesn't appear to be anything within a default Zen Cart install that uses the function on the catalog side. As such, it seems to me that yet another conditional parameter could be added to address this "sort/display" feature... Perhaps providing the desired "primary" key where within the function a list of items to be displayed is populated (with possible notifier override/addition) and that in using an array that the first item of the array is the parameter provided (or some chosen default if none is provided) then to cycle through that array to add the parameter(s) not yet addressed.... Just a thought...

**Comment by torvista** [comment]
> permalink... When navigating the file within github (literally here on this site), after making a selection of code, when clicking the "three dots" that appear adjacent to the selection, a dropdown is provided that offers Copy Permalink...

Not exactly, you click the line number to get the 3-dots menu, hover over the final line number and click shift, then select permalink from the 3-dots menu. But that's great, I see why everyone should use it!!

I don't want to confuse two issues here.
1) Format...that I have started going on about elsewhere.https://github.com/zencart/zencart/issues/4066
2) Returned values....
previously (156) these results on specials were returned as a distinct list of products (as $show_current_category is not set)

https://github.com/zencart/zencart/blob/e60c81b6dbac7b1a61fb891397fe20de7b02c623/admin/includes/functions/general.php#L292-L308

Now for 157/8

https://github.com/zencart/zencart/blob/0aaa10e342b9546fc6387636ac39d32f2afa77ab/includes/functions/functions_categories.php#L343-L354

it returns all products and their linked instances as the clause for !$show_current_category is missing.

**Comment by mc12345678** [comment]
Hmm.. Perhaps something like:

````diff
    $sql = "SELECT p.products_id, pd.products_name, p.products_sort_order, p.products_price, p.products_model, ptc.categories_id
                FROM " . TABLE_PRODUCTS . " p
-                LEFT JOIN " . TABLE_PRODUCTS_TO_CATEGORIES . " ptc USING (products_id)
                LEFT JOIN " . TABLE_PRODUCTS_DESCRIPTION . " pd USING (products_id)
+                :add_tables:
                WHERE pd.language_id = " . (int)$_SESSION['languages_id'];


    $condition = '';
+    $add_tables = '';

    if ($show_current_category) {
        // only show $current_categories_id
+        $add_tables = "LEFT JOIN " . TABLE_PRODUCTS_TO_CATEGORIES . " ptc USING (products_id)";
        $condition = " AND ptc.categories_id = " . (int)$current_category_id;
    }
+    $sql = $db->bindVars($sql, ':add_tables:', $add_tables, 'stringIgnoreNull');
````
It does look like the refactor didn't quite come to the same end product as the original query(ies).

**Comment by proseLA** [comment]
> 1. Version
>   Should the version always be mentioned in the text?

yes.  always. please.

> 2. function name incorrect.
>    Guilty as charged. Should be function zen_draw_products_pull_down

not about guilt v innocence.  i look for a function based on the name.  you post the wrong name, it makes any reviewers job more difficult.

> 3. Permalink
>  But that's great, I see why everyone should use it!!

please.  you are welcome.

> I seem to annoy you more than "necessary", it's not intentional, only trying to feed back stuff I find/fix on my upgrade...I'm not a pro. developer.

don't feel special.  nothing to do with you.  you have enough PRs in this repo that you can not use excuses of not being a pro developer.  IMO.

in addition, this is not an upgrade.  you are pointing out a difference in search results for v158.  which is unreleased.  which is something that someone in development does.   finding these differences is GREAT.

i initially called it a bug.  i am not sure.  the question is whether the new inclusion of linked products was intentional or not.

> Now for 157/8
> 
untrue. 

this is the released version of v157a. 

https://github.com/zencart/zencart/blob/1c039c5d2e43558e4ee0b312c2b3816346144ec4/admin/includes/functions/general.php#L260-L276

the results are the same as v156.  or are they not?

i took the time to verify that the search results are different in v158 v 157a; the question remains as to whether that was intentional or not.

**Comment by torvista** [comment]
`the results are the same as v156. or are they not?`
Right again, sorry, I got mixed up with the code in my frankensite.

so, the question remains over the refactoring.

**Comment by proseLA** [comment]
@drbyte the refactor has produced different result set; pretty clearly defined by @mc12345678 comment above.

intentional or not?  looks like from #3683

**Comment by mc12345678** [comment]
FYI, I'll also note that my choice of sequence for the additional `:add_tables:` was both purposeful and haphazard... My thought was that the content/replacement lookup could be modified to be an `INNER JOIN` instead of a `LEFT JOIN` thinking that it may make a difference whether the table(s) were placed at the end of the existing `LEFT JOIN` chain versus along the original path...

E.g. if one wanted to use/include an `INNER JOIN` then it seems it may visually make sense possibly following the existing `LEFT JOIN`, though I don't see that it would make a resulting difference... So if there is any "concern" about the sequence as I have presented, I am not stuck on it and it can be revised/debated... :)

**Comment by proseLA** [comment]
@mc12345678 i have no strong opinion on inner v left join.  nor do i have strong opinion on linked products in general; as my few ZC clients rarely use them.

i think the point, i'm trying to make, is the need to be clear, concise and accurate when posting or doing a PR in this repo.  i'm trying to be a bit more pro-active in code review so that the code base improves for everyone and does not deteriorate.

this change was a good find on the part of @torvista, and i'm hopeful that in the future he will be more concise and accurate in his postings.
