### ISSUE TITLE
Add an email address for TECHNICAL_CONTACT 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4127]
Emails sent when there is an issue go to STORE_OWNER, which may not be a good choice; the store owner may not be able to do anything useful with a problem report.  Having an additional email defined for technical issues would allow multiple points of contact in a problem situation. 

Changes needed:  
- add email to default database script
- add email to upgrade script 
- look for opportunities to use this additional email.

**Comment by drbyte** [comment]
> look for opportunities to use this additional email

I'm trying to think of use-cases.

Usually when something goes wrong it's related to business issues that the storeowner has expertise or responsibility around ... such as customer payment failures, settings getting changed by an unauthorized administrator, etc.

Emails aren't sent when technical problems occur. To some degree this is intentional, because if there's a flood of application errors the last thing you want is a flood of emails that gets the server flagged as spamming. And if there's an email system failure you don't want an endless loop of trying to email about the email failure.

I imagine you bumped into a specific use-case that prompted this Issue?

**Comment by scottcwilson** [comment]
Consider a cURL error in a shipping or payment module that interacts with a remote system.  Right now some of them have an "email" setting for logging, but it emails to STORE_OWNER.

**Comment by drbyte** [comment]
I'm open to the idea of adding a config for `TECHNICAL_CONTACT_EMAIL_ADDRESS`.

But ... what if the storeowner leaves/makes it blank?

I don't want to add a bunch of complexity to every place where it's used to check "if defined then use it; else use something else..."

**Comment by torvista** [comment]
I need to imagine being a store owner with a tech minion looking after things....but I would still want to know what is not working...forwarding emails to the minion feels preferable to not knowing about the problems by emails going direct, and is part of store management/ownership.
