### ISSUE TITLE
does zen_not_null work as intended?

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4145]
in looking at something else, i decided to explore `zen_not_null`.  i used the following code:
```
        $sql = "SELECT * from " . TABLE_PRODUCTS;
	$test = $db->Execute($sql);

	if (is_a($test, 'queryFactoryResult')) {
		echo "-------->" . 'query factory result' . "<---------<br>";
	}
	if (zen_not_null($test)) {
		echo "-------->" . 'zen not null' . "<---------<br>";
	}
	echo "---Result----->" . count($test->result) . "<---------<br>";
	echo "---RecordCount----->" . $test->RecordCount() . "<---------<br>";
```

the results of said test are:
```
-------->query factory result<---------
---Result----->0<---------
---RecordCount----->19559<---------
```
so `$test` which is a query factory result, and has records, the function `zen_not_null` comes back as false, which means the `$test` is null.

is this the intended behavior?

**Comment by drbyte** [comment]
Interesting.

Since queryFactoryResult is a `Countable` object I find myself almost never using `zen_not_null` anymore. Instead I use `empty()`.

The test for queryFactoryResult was added into zen_not_null before it became a Countable, because it would give strange results without that test.

That said, perhaps a better rewrite of zen_not_null would include:
```diff
-   if (is_array($value)) {
+   if (is_countable($value)) {
      return count($value) > 0;
    }
-    if (is_a($value, 'queryFactoryResult')) {
-      return count($value->result) > 0;
-    }
```

**Comment by proseLA** [comment]
i would think so.

personally, i rarely use it.  i used it 3 times in 1 plugin, and in fact, the next rewrite of that plugin removes it.  i find myself using the coalesce operator `??` all the time now; as i no longer worry about php versions less than 7.  

i started exploring it, as i was reviewing the code in #4144 and was thinking lines 25 & 26 might be combined into something like:
```
if (($cPath ?? 0) > 0) {
```
but if being a part of 1.5.7, that would not work due to php 5.6 requirements.

in any event, this is zen-cart, and any function that starts with `zen_` should work as there are numerous uses of it throughout the repo.

i'll do a PR.

**Comment by drbyte** [comment]
Turns out 1.5.8 already had switched to checking for Countable.
I've [updated it](https://github.com/zencart/zencart/commit/bd8af74c3ebd966f28ca12879f250d57e5635d4d) to use is_countable so that it's slightly more generic.

**Comment by proseLA** [comment]
after i posted, and when i was away from my computer, i thought i should have checked 1.5.8.  but i still think its worthy of fixing if there is another 1.5.7 letter release...

**Comment by drbyte** [comment]
I think for 157 the issue is that it shouldn't be counting `$value->result` but rather just `$value`.

eg:
> 	echo "---Result----->" . count($test->result) . "<---------<br>";

Probably `count($test)` would give the same as `$test->RecordCount()`, right?

**Comment by drbyte** [comment]
But I'm surprised that this hasn't caused all kinds of issues over the years ..... hmmm...

**Comment by proseLA** [comment]
under 157 using php 7.4.13 or php 8.0, both of those aforementioned give the same results, ie `count($test)` and `$test->RecordCount()`.

i'm surprised as well, although its possible that people are not using the function for query results.  frankly, i looked at this for a long time prior to posting, as it does seem curious how this would not have caused problems.

**Comment by drbyte** [comment]
Turns out it's not used for query results anywhere that I can find.

That said, for 158 I've converted most to `!empty` instead.

**Comment by mc12345678** [comment]
Although this is not centered around the query aspect of zen_not_null, but a concern about it came up while reviewing its use and some code that was posted on the forum to resolve an issue. 
I was just about to create a new github issue seen with this function if/when it is used in PHP 8.0 where `$value = 0`, then the function gives a result different than the same under PHP < 8.0.  It seems that the point is to use this for strings, but there doesn't seem to be anything that "forces" that and as a result if/when used will give a different answer under PHP 8.0 than it did/does under older PHP versions...

I'm not yet fully confident of this solution, but the issue comes around the test `$value != 'NULL'`.  Guess could change the last line as such:
````diff
- return trim($value) !== '' && $value != 'NULL';
+ return trim($value) !== '' && (is_string($value) ? $value != 'NULL' : !empty($value));
````
This was discovered by running the following code using php 7.4.13 and 8.0:
````php
require 'includes/application_top.php';

$testarray = [0, '0', 'false', false];
foreach ($testarray as $testval) {
    echo (zen_not_null($testval) ? 'full' : 'empty');
    echo PHP_EOL;
}
````
First I tried in PHP 7.4.13 where I get:

value | PHP 7.4.13 | PHP 8.0.0
------ | ------------ | ----------
0 | empty | full
'0' | full | full
'false' | full | full
false | empty | empty

Notice how the first "value" response changed the integer of 0 from an "empty" (false from zen_not_null) to "full" (true from zen_not_null). This appears to be a result of how '$value != 'NULL'' is evaluated...  When $value is an integer it appears that the comparison is now different which is explained in the PHP manual: https://www.php.net/manual/en/migration80.incompatible.php for String to Number Comparisons... So, if this zen_not_null is to continue to operate as previously considered, then may need to revise the last line of code in some way to do that evaluation differently? Possibly as described above, or perhaps something else?

BTW, while the function has been moved to a `functions_string` file, I wouldn't expect that the new location would necessarily translate to some sort of necessity of using the function against strings "only"...

**Comment by drbyte** [comment]
Thanks for this.

The `!= 'NULL'` is intended to relate to a string of uppercase letters forming `'NULL'`.
Thus [changing `!=` to `!==`](https://github.com/zencart/zencart/commit/a22cbcc9cef43047ac764d81a9fe1660c24e2adf) adds the specificity which yields consistent results in both PHP7 and PHP8

The `zen_not_null` function is intentionally not testing for whether `0` evaluates to 0 or boolean false, so I prefer not to include testing for `empty()`.

**Comment by mc12345678** [comment]
> Thus changing != to !== adds the specificity which yields consistent results in both PHP7 and PHP8

True, but that functions differently than in previous ZC versions...

Where old and new are identified below, old `!=`, new `!==` .

value | old PHP <= 7.4.13 | old PHP 8.0.0 | new PHP <= 7.4.13 | new PHP 8.0.0
-- | -- | -- | -- | --
0 | empty | full | full | full
'0' | full | full | full | full
'false' | full | full | full | full
false | empty | empty | empty | empty

If going to go that route, then may need a heavy disclaimer about the use of `zen_not_null`... BTW, I've actually been stepping away from the use of this function because of its seemingly inconsistent results depending on the data type. In my previous above tests, I also used/compared against the older version of `zen_not_null`

**Comment by drbyte** [comment]
> BTW, I've actually been stepping away from the use of this function 

I agree.
So is v1.5.8: https://github.com/zencart/zencart/commit/3f13e22bd98fadff3516d3c44428c59367523bc3

I've left it only for searches, prices, and dates. 
(Dates don't really need it, but I've oft contemplated using it to check for 0000 and 0001 dates)

Other than cases where we actually need to accommodate a `0` or `'0'` I prefer to use `empty()`.

**Comment by drbyte** [comment]
@mc12345678 One thing to note when considering refactoring of code: 
Zen Cart's current query_factory use of the `mysqli` client (ZC v1.5.2 to at least v1.5.8 currently in dev) brings back all database data as strings, regardless of field type in the actual database. 
(So did versions prior to v1.5.2 where the `mysql` client was used.)

Thus an integer field in the database containing a `0` value will still be treated in Zen Cart as a string: `'0'`. 
(Unless of course if one type-casts it to int subsequent to the queryResult being returned.)

Similarly, but for different reasons, all $_POST and $_GET data is received as strings. So a $_POST value will never be `0`: it will always be a string: `'0'`
