### ISSUE TITLE
zen_mail_archive_write does not process/store $error_msgs

### ISSUE THREAD

**Issue by mc12345678** [zencart/zencart#4150]
**Is your feature request related to a problem? Please describe.**

While trying to track down why frequently/periodically receiving the following error in a mostly Zen Cart 1.5.6c+ site operating on PHP 7.2:
--> PHP Notice: Email Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting<br /> in /path/includes/functions/functions_email.php on line 377.

In the section of code just before, the following code is called:
````php
      if (EMAIL_ARCHIVE == 'true'  && $module != 'password_forgotten_admin' && $module != 'cc_middle_digs' && $module != 'no_archive') {
        zen_mail_archive_write($to_name, $to_email_address, $from_email_name, $from_email_address, $email_subject, $email_html, $text, $module, $ErrorInfo );
      } // endif archiving
````
and then following this to the associated function, the variable `$ErrorInfo` is passed into the function, is treated for potentially adding to the database, but is not included in the database call:
````php
    $db->Execute("insert into " . TABLE_EMAIL_ARCHIVE . "
                  (email_to_name, email_to_address, email_from_name, email_from_address, email_subject, email_html, email_text, date_sent, module)
                  values ('" . zen_db_input($to_name) . "',
                          '" . zen_db_input($to_email_address) . "',
                          '" . zen_db_input($from_email_name) . "',
                          '" . zen_db_input($from_email_address) . "',
                          '" . zen_db_input($email_subject) . "',
                          '" . zen_db_input($email_html) . "',
                          '" . zen_db_input($email_text) . "',
                          now() ,
                          '" . zen_db_input($module) . "')");
````
The above is the same even in ZC 1.5.7b (https://github.com/zencart/zencart/blob/f16f54efa9fd0af3a6ae5bd4f6475d9ce5c25e53/includes/functions/functions_email.php#L422-L432)
and ZC 1.5.8:
https://github.com/zencart/zencart/blob/08642cb289c4e3351929d652170c7dfc4c9c2b38/includes/functions/functions_email.php#L430-L440

Thinking that may be of "benefit" to store the `$error_msgs` variable; however, for some reason it wasn't incorporated already, I presume for a "valid" reason. I notice though that the variable is not identified in the header docs for the function. Sure there is a step that follows that logs the error; however, it almost seems like having the error directly associated with the message in question would be of a little more assistance.  For me to track down at least a portion of the issue, I had to match the time stamp of the above error message with the message that was sent at that time (as message archiving was active). Would think that the table could be altered to add an additional field that has a default value of an empty string or even null if necessary and to log that error message as a field in the data table `email_archive`.

Then possibly in the email archive manager, could display the error message somewhat separately from the rest of the information so that it would be viewable, but not likely to be "passed" on when attempting to resend the message.

The idea is to be better able to track down the cause of an email error where that information is available instead of having to pull individual pieces of information together, again not sure if there was a purposed reason to exclude the logging of the error messages. If so, then may recommend more information to be added to the code comments about why it was excluded or some other guidance.

**Comment by scottcwilson** [comment]
Interesting idea but it only works if email archiving is enabled.  What about creating a second error log with the $ErrorInfo data so it doesn't get lost?

**Comment by drbyte** [comment]
IIRC the reason for excluding the error from db logging was mainly that the error wasn't useful for those viewing the archives for the purpose of seeing what messages were sent (which was the primary reason for the optional archive feature being added .... not troubleshooting)

Also, when exploring what errors would be passed, the logs at that time always had the same message repeated: 
"`SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting`"
... which is incredibly verbose.
(Aside: the verbose message including the github link comes from the PHPMailer package itself, who added the link intentionally since `SMTP connect() failed.` is by far the most common problem people encounter.)

I'm open to the idea of adding another column to the email_archive table to track the error_msgs value. Go ahead with a PR to v158.

To Scott's point, we could explore overriding the "is archiving enabled" flag and always archive messages which encounter an error, including the error message.
