### ISSUE TITLE
[157] zen_image with empty width and height results in 0 x 0 img tag

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4212]
**Describe the bug**
The `zen_image` function (present in /includes/functions/html_output.php) currently produces an image tag with `width="0" height="0"` when the `$width` and `$height` parameters are either not supplied or supplied as empty strings.

From the reading of the code, having those parameters 'empty' should result in a fully-sized image if **_Images :: Calculate Image Size_** is set to 'true' ... falling back to the SMALL_IMAGE_WIDTH and SMALL_IMAGE_HEIGHT for on-site images.

The issue appears to be the use of the `zen_not_null` function, which returns `(bool)true` for a values of `(int)0`.

**Version**
Zen Cart version: 157b
PHP version: 7.3
MySQL version: n/a
Plugins that may be related: n/a
What older/newer versions were also tested? None

**To Reproduce**
With a site that has zc157b installed with the demo products, run the following mini-script to see the error:
```php
<?php
require 'includes/application_top.php';

$image = zen_image(DIR_WS_IMAGES . 'sooty.jpg', 'Test');

echo htmlspecialchars($image) . '<br>';
echo $image;

require DIR_WS_INCLUDES . 'application_bottom.php';
```

**Expected behavior**
The function's output should create a viewable image, given the inputs.

**Screenshots**
![image](https://user-images.githubusercontent.com/2685585/108072277-b27bcc00-7034-11eb-9851-4ebf8aefc64c.png)

**Comment by mc12345678** [comment]
How though is `zen_not_null` being provided `(int)0`?

if no parameters are provided, as shown above, then the default is `''` an empty string. The next "treatment" of either `$width` or `$height` is above that where:
````php
    // Convert width/height to int for proper validation.
    // intval() used to support compatibility with plugins like image-handler
    $width = empty($width) ? $width : (int)$width;
    $height = empty($height) ? $height : (int)$height;
````
Which, in this case, an empty quote would evaluate as true and therefore remain still an empty quote.
And then when that is presented to `zen_not_null` the last evaluation in the function would be the one responsible for the returned value:
````php
    return trim($value) !== '' && $value != 'NULL';
````
where the first evaluation (`trim($value) !== ''`) would be false, stop processing and return false...

It seems more likely that there is an issue with the image based on the writeup of the operation of `getimagesize`, specifically the first part of the Return Values: https://www.php.net/manual/en/function.getimagesize.php
> Note:
>
> Some formats may contain no image or may contain multiple images. In these cases, getimagesize() might not be able to properly determine the image size. getimagesize() **will return zero for width and height** in these cases.

I used the above suggested code and then even duplicated the assignment with a different image (`'small_00.jpg'`), both provided non-zero results for height and width. `PROPORTIONAL_IMAGES_STATUS` === '1', `CONFIG_CALCULATE_IMAGE_SIZE` === 'true'. Tested first on PHP 7.4.14 and then backed down to 7.3.26.

There's no `handle_image` function? No observer for `NOTIFY_OPTIMIZE_IMAGE`?

**Comment by drbyte** [comment]
> ```
> <?php
> require 'includes/application_top.php';
> 
> $image = zen_image(DIR_WS_IMAGES . 'sooty.jpg', 'Test');
> 
> echo htmlspecialchars($image) . '<br>';
> echo $image;
> 
> require DIR_WS_INCLUDES . 'application_bottom.php';
> ```

On PHP 7.4.15 I get the following:

<img width="540" alt="Screen Shot 2021-02-17 at 9 08 49 PM" src="https://user-images.githubusercontent.com/404472/108294803-924b2a80-7164-11eb-88cf-013797000d4d.png">

... which leads me to wonder if there's something environmental causing the symptoms reported.

**Comment by mc12345678** [comment]
Well, there is the strong possibility that an image has been presented where one of the dimensions is assigned the integer value `0`. Under ZC 1.5.8 (and the revised version of `zen_not_null`), the response ***is*** opposite from what it was not that long ago... As such, and because of the "sensitive" nature of this portion of the `zen_image` and `zen_image_OLD` code, I would instead suggest adding to the evaluation that has been modified a strict test that the associated height/width is not equal to 0:
````diff
-        if (empty($width) && zen_not_null($height)) {
+        if (empty($width) && zen_not_null($height) && $height !== 0) {
          $ratio = $height / $image_size[1];
          $width = $image_size[0] * $ratio;
-        } elseif (zen_not_null($width) && empty($height)) {
+        } elseif (zen_not_null($width) && $width !== 0 && empty($height)) {
          $ratio = $width / $image_size[0];
          $height = $image_size[1] * $ratio;
        } elseif (empty($width) && empty($height)) {
          $width = $image_size[0];
          $height = $image_size[1];
        }
      } elseif (IMAGE_REQUIRED == 'false') {
        return false;
      }
    }




-    if (zen_not_null($width) && zen_not_null($height) && file_exists($src)) {
+    if (zen_not_null($width) && $width !== 0 && zen_not_null($height) && $height !== 0 && file_exists($src)) {
````

It appears that ultimately that before the change to a strict evaluation against the empty quote that if one of the dimensions was `0` then that dimension was to be "adjusted". The above would be backwards compatible, though "unnecessary" in older php/Zen Cart versions.

**Comment by mc12345678** [comment]
> ... which leads me to wonder if there's something environmental causing the symptoms reported.

If look at the above history, see that there is some work done in ZC 1.5.8 (or not yet officially released 1.5.7c) to address the/a problem. That is/would be where the zen_not_null fed a `0` issue first really comes to light or if PHP 8.x+ as I identified earlier/elsewhere in github.  When that happens, the `zen_not_null(0)` changes behavior (reverses) from its original/current boolean value. Because it appears to only occur for the integer value of `0`, Therefore for the function to operate like it used to the addition of an "outside" comparison would resolve the situation in this case.  Previously I had suggested an internal comparison/check within `zen_not_null` that if the value was an integer to evaluate it against `0` or something similar. 

My previous discussion on the upcoming changes to `zen_not_null` starts here: https://github.com/zencart/zencart/issues/4145#issuecomment-751158215

**Comment by drbyte** [comment]
But ... the issue being discussed here has nothing to do with PHP 8, insomuch as the OP stated PHP 7.3 ...

**Comment by lat9** [comment]
@mc12345678, you're making this way more complex than it needs to be with all the specific checks for (int)0.  

In my installation, I do have IH-5 installed (but disabled).  After inspection, it appears that the `$width` and `$height` parameters are returned as `intval` values, that's where the `(int)0`'s are coming from.   We can either close this issue and I'll address a change to IH, or accept my proposed use of `!empty` instead of `zen_not_null` to correct the interoperational issue.

**Comment by drbyte** [comment]
I'll re-review the PRs again.

In the meantime, note that `intval()` is a CPU-intensive function that's unnecessary when `(int)` can be used instead. (Same with `strval()` etc)

**Comment by lat9** [comment]
> 
> 
> I'll re-review the PRs again.
> 
> In the meantime, note that `intval()` is a CPU-intensive function that's unnecessary when `(int)` can be used instead. (Same with `strval()` etc)

Understood.  I'm not sure why the original `handle_image` function felt the need to make changes to the inputs when Image Handler, itself, is disabled.  It's been like that since at least IH v4.3.4 (ca. 2015).
