### ISSUE TITLE
Products URL in product edit asks for a URL even when one present

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4234]
**Describe the bug**
When editing a product you get a prompt for a URL even when one is already present. 

**Version**
Zen Cart version:  <strike>157</strike> 158

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
Edit a product with a URL setting.  When you click preview you will see the message.

**Expected behavior**
No prompt if URL has been entered. 

**Screenshots**
![Screen Shot 2021-03-07 at 10 31 12 AM](https://user-images.githubusercontent.com/4391638/110245342-a9459700-7f30-11eb-8f69-5e60a9a78f62.jpg)

**Comment by torvista** [comment]
https://github.com/zencart/zencart/commit/4717032046d64e92ff5a71552b019636ef3fc8f5#commitcomment-45816827

**Comment by scottcwilson** [comment]
Great!  Thanks.

**Comment by drbyte** [comment]
Dilemma:
- `type="url"` provides validation; of course this is also the problem here since ZC has always wanted no `protocol` in this field
- using `inputtype="url"` helps with mobile browsers by enabling a URL-friendly keyboard, but isn't well supported
- I suspect the reason ZC prefers no protocol be supplied is because historical support for https vs http was flaky in the past (it's not such a problem nowadays)
- Changing to accept a protocol so type="url" can remain and provide validation would still require storeowners to manually fix this entry upon first edit
- Changing to accept a protocol would also require updating all entries already in the database ... but there's no sane way to know whether those should be set to http vs https in an automated fashion

**Comment by scottcwilson** [comment]
Oh I quite agree.  This is a pickle.  If it was easy I would have PRed it already. :)

**Comment by drbyte** [comment]
For storeowners needing a quick fix, the patch is easy: remove the `, 'url'` part at the end of those lines in each of the product type files for product types they use.

**Comment by scottcwilson** [comment]
sorry there was a typo in the first version of the description - this is an issue in 1.5.8 only.

**Comment by scottcwilson** [comment]
(so there are no affected storeowners)

**Comment by drbyte** [comment]
Okay, I guess the simplest is to revert to using `inputtype="url"`.

I must slap myself on the wrists for not explaining why I changed it in the original commit where I made the change.

**Comment by torvista** [comment]
> inputtype

I don't find any reference for this html attribute...only in android.
