### ISSUE TITLE
products to categories: PHP Fatal error Column 'products_id' in from clause is ambiguous

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4249]
ZC158, strict reporting

Enter page, select a category with products:

> 1052 Column 'products_id' in from clause is ambiguous
> in:
> [SELECT ptc.* FROM products_to_categories ptc LEFT JOIN products_description pd ON (p.products_id = pd.products_id AND pd.language_id = 1) INNER JOIN products p USING (products_id) WHERE ptc.categories_id = 8 ORDER BY p.products_model]

The only bit I see that is ambiguous/without a table prefix is in the USING, but whatever prefix I use gives a mysql syntax error.

https://github.com/zencart/zencart/blob/f6f32681cfe4a0cf17e218f707a168446e3d796b/admin/products_to_categories.php#L59-L65

While this query is up for being simplified, I'd still like to understand what the problem is.

**Comment by scottcwilson** [comment]
Try changing `p USING (products_id) ` to `p USING (pd.products_id) `

**Comment by torvista** [comment]
Tried all those options, blindly. Then after research, that makes no sense, as USING is exactly for that, to use a column name that is identical between the tables.

**Comment by torvista** [comment]
Suggested easy fix in https://github.com/zencart/zencart/pull/4251

**Comment by mc12345678** [comment]
Isn't the ambiguous part, this portion of the query?:
> SELECT ptc.* FROM products_to_categories ptc LEFT JOIN products_description pd ON (**p**.products_id = pd.products_id AND pd.language_id = 1) 

Where pd is left joined to ptc but and by referencing p which isn't yet a part of the join?

Thus perhaps the "better" consideration (when only considering the original query) being this untested query:
> SELECT ptc.* FROM products_to_categories ptc LEFT JOIN products_description pd ON (**ptc**.products_id = pd.products_id AND pd.language_id = 1) INNER JOIN products p USING (products_id) WHERE ptc.categories_id = 8 ORDER BY p.products_model

**Comment by torvista** [comment]
Seems not...
> 1052 Column 'products_id' in from clause is ambiguous
> in:
> [SELECT ptc.* FROM products_to_categories ptc LEFT JOIN products_description pd ON (ptc.products_id = pd.products_id AND pd.language_id = 1) INNER JOIN products p USING (products_id) WHERE ptc.categories_id = 4 ORDER BY p.products_model]
> If you were entering information, press the BACK button in your browser and re-check the information you had entered to be sure you entered valid data.

**Comment by mc12345678** [comment]
Okay, what about if the `USING` portion were more "specific" (ptc.products_id)? Again using the relatively original query:
> SELECT ptc.* FROM products_to_categories ptc LEFT JOIN products_description pd ON (p.products_id = pd.products_id AND pd.language_id = 1) INNER JOIN products p USING (ptc.products_id) WHERE ptc.categories_id = 8 ORDER BY p.products_model

I was doing some research/reading and at one point in time, this type of error was a part of MySQL, but then was supposedly worked out (to some extent). Others have pointed at the need for more specificity; however, the idea of `USING` appears to be as described, that it should be possible to be "generic". Other solutions basically removed the `USING` and instead used an `ON (x.z = y.z)` style.

If the above didn't work then I would suggest trying the combination of my two suggestions. Sorry that I don't seem to be able to test these myself.

**Comment by torvista** [comment]
Using a specific column for Using, is not allowed:

> 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.products_id) WHERE ptc.categories_id = 4 ORDER BY p.pro' at line 4
> in:
> [SELECT ptc.* FROM products_to_categories ptc LEFT JOIN products_description pd ON (p.products_id = pd.products_id AND pd.language_id = 1) INNER JOIN products p USING (ptc.products_id) WHERE ptc.categories_id = 4 ORDER BY p.products_model]
> If you were entering information, press the BACK button in your browser and re-check the information you had entered to be sure you entered valid data.
-----------------------------------
Swapping Using for ON:

```
    $sql = "SELECT ptc.*
            FROM " . TABLE_PRODUCTS_TO_CATEGORIES . " ptc
            LEFT JOIN " . TABLE_PRODUCTS_DESCRIPTION . " pd ON (p.products_id = pd.products_id AND pd.language_id = " . (int)$_SESSION['languages_id'] . ")
            INNER JOIN " . TABLE_PRODUCTS . " p ON (p.products_id = ptc.products_id)
            WHERE ptc.categories_id = " . $current_category_id . "
            ORDER BY p.products_model"; // Order By determines which product is pre-selected in the list when a new category is viewed
```

> 1054 Unknown column 'p.products_id' in 'on clause'
> in:
> [SELECT ptc.* FROM products_to_categories ptc LEFT JOIN products_description pd ON (p.products_id = pd.products_id AND pd.language_id = 1) INNER JOIN products p ON (p.products_id = ptc.products_id) WHERE ptc.categories_id = 4 ORDER BY p.products_model]
> If you were entering information, press the BACK button in your browser and re-check the information you had entered to be sure you entered valid data.
------------------------------------------

BUT, after thinking slightly more than usual, this works:

```
    $sql = "SELECT ptc.*
            FROM " . TABLE_PRODUCTS_TO_CATEGORIES . " ptc
            LEFT JOIN " . TABLE_PRODUCTS_DESCRIPTION . " pd ON (pd.products_id = ptc.products_id AND pd.language_id = " . (int)$_SESSION['languages_id'] . ")
            INNER JOIN " . TABLE_PRODUCTS . " p ON (p.products_id = ptc.products_id)
            WHERE ptc.categories_id = " . $current_category_id . "
            ORDER BY p.products_model"; // Order By determines which product is pre-selected in the list when a new category is viewed
```
------------------------------------------
Then while on a roll, I thought a bit more... "wtf would you want ALL the rows from ptc?" As per a LEFT join.
Surely INNER would be the appropriate join here.
```
    $sql = "SELECT ptc.*
            FROM " . TABLE_PRODUCTS_TO_CATEGORIES . " ptc
            INNER JOIN " . TABLE_PRODUCTS_DESCRIPTION . " pd ON (pd.products_id = ptc.products_id AND pd.language_id = " . (int)$_SESSION['languages_id'] . ")
            INNER JOIN " . TABLE_PRODUCTS . " p ON (p.products_id = ptc.products_id)
            WHERE ptc.categories_id = " . $current_category_id . "
            ORDER BY p.products_model"; // Order By determines which product is pre-selected in the list when a new category is viewed
```

So completing this exercise, thanks for the input...
the PR that I did above, is, I think, still valid.

**Comment by mc12345678** [comment]
By changing the `LEFT JOIN` to an `INNER JOIN` and therefore "removing" all of the `ptc` rows that contain data pertinent to the `WHERE`, there's a couple of things that happen here. The existence of records in `ptc` that either shouldn't exist or where a matching products description doesn't exist for the associated language are not shown/made available.  This can be a problem if the tools for which this query is being execute effectively prevent access to those records.

The existence of additional records in `ptc` by itself is troublesome as one would question how that came to exist or what didn't remove the matching record when some other action occurred. A missing product description may also be troubling, but what mandates the existence of a product description for each language being used to access the data? For example, what if the admin uses a language that is not supported by the catalog? Wouldn't this sort of listing of product that only have a matching product description in the language being used cause no results? Sure, such usage may also be "cumbersome" to some, but the products_id would still be present and that may be the only tool that the store owner uses/needs in order to use the results of this query. That said...

What I find interesting though, is that the function chosen to be used (not equivalent to the above reworkings of queries) actually opens the possibility of more returned data than the existing (when properly formed). It also provides more results than the one in the previous post... In other words, the suggested revision of using `zen_get_linked_products_for_category` will return all `products_id` from `ptc` even if such product is not in the products table... In that regards, the discussion of the proper format for the above sql statement is now moot. The query result can still support identification of a database problem if one exists, though will rarely see that issue in this usage because of sorting and retrieval of a single record. 

Thanks for the "entertainment". :)
