### ISSUE TITLE
Upgrade to Font-Awesome 5 in 1.5.8? 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4250]
Seems like a good idea - any objections?

**Comment by drbyte** [comment]
I'm not opposed to it.

Catalog-side it's only used in maybe 20 spots across a half dozen files in responsive_classic.
Admin-side it's used extensively though, so will touch a lot of files.

I guess the people who begrudge that FA was embraced "at all" in the admin will likely begrudge the syntax change that FA5 requires.

**Comment by Zen4All** [comment]
Is there a good reason to upgrade? I like to use FA, but I do not see a reason to upgrade. FA 5 has many restrictions that FA 4 does not have. If it is because FA4 is no longer supported by FA, than we could switch to [Fork Awsome](https://forkaweso.me/Fork-Awesome/). This is a well maintained for of FA, with the same syntax as FA. As a bonus Fork Awesome adds new icons.

**Comment by scottcwilson** [comment]
I'm not strong on this, I was just annoyed when an icon I wanted to use wasn't available in the older version.  There are no security issues and this can certainly wait.

**Comment by drbyte** [comment]
I was concerned about whether all of FA4's icons were available in the free offerings of FA5, but for the things Zen Cart uses it didn't seem like it would be problematic.

> FA 5 has many restrictions that FA 4 does not have.

Can you elaborate?

**Comment by proseLA** [comment]
i am hesitant to weigh in on this....  but....

i have no strong feeling on FA4 v FA5.  but it would be nice to have a little more direction on the use of icons and replacing images with icons on the admin pages chosen by the team.  i know i looked at this at 1 point, and i was unclear if the direction was to use the FA icons or the glyphicons included with bootstrap.  i was ready to do a PR, but i bailed...

i look at the banners page, for example, and i really like the use of the fa icons there, but i'm not a fan of the in-line styling.  i think its preferable to create a class in a style sheet and make it available for other uses or for store admins to override with their own css sheet.  

for my clients i have changed the configuration script to make use of bootstrap glyphicons, which to me look much better that the image gifs.  i ended up liking them more than the FA icons, but it was close.

i am not sure if a direction has been chosen to have more consistent formatting on the admin pages, and if so what it is, or if it is posted anywhere, or if it is worth wild to start doing PRs....  but it would be nice to get rid of the images and have a more consistent look across the admin pages...  i would have no problem tackling some of it, but a little direction could go a long way...

apologize if this is thread drift, it seems close...

bootstrap glyphicon on configuration page:

![image](https://user-images.githubusercontent.com/1095136/112419290-66354300-8ce8-11eb-9259-4cf9f9c911de.png)

**Comment by drbyte** [comment]
@proseLA 
Since you mention "glyphicons", I assume you're referring to the glyphicons "halflings" v1.9 series that come with Bootstrap 3.4.1 currently in use in the Admin.
I originally avoided implementing glyphicons in core, in favor of font-awesome, because FA's integration was less verbose and the selection was better (at the time). (It was a tough call because it meant distributing unused assets for the sake of consistency and to retain support any use of glyphicons that might be required if someone added a 3rd party BS3 feature expecting glyph stuff to be present.)

In Bootstrap 4 they [dropped the Glyphicons](https://getbootstrap.com/docs/4.6/migration/#components).
[They suggest alternative icon options](https://getbootstrap.com/docs/4.6/extend/icons/) which include Font-Awesome
... or their own separate icons project at https://icons.getbootstrap.com/#icons
Looks like it can integrate almost the same way as font-awesome, but there's no 1:1 mapping between icon names across multiple icon projects such that we could write a function to make the choice a seamless integration requiring zero template changes if one wanted to swap out one project for another.

So IMO going to glyphicons seems the wrong direction at this point.
That said, I get your point about wanting more consistent iconography (instead of images).

**Comment by drbyte** [comment]
> i am not sure if a direction has been chosen to have more consistent formatting on the admin pages, and if so what it is, or if it is posted anywhere

No, nothing has been decided or posted yet.

**Comment by brittainmark** [comment]
Font-Awsome 6 is now available, should that be considered if upgrade to happen.

**Comment by scottcwilson** [comment]
Closing issue due to lack of interest and activity.
