### ISSUE TITLE
attributes_controller: use of zen_get_linked_products_for_category

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4252]
The second parameter in these function calls is "first_only = true"
Should this not be just "true"?
https://github.com/zencart/zencart/blob/f6f32681cfe4a0cf17e218f707a168446e3d796b/admin/attributes_controller.php#L85-L100

**Comment by drbyte** [comment]
> The second parameter in these function calls is "first_only = true"
> Should this not be just "true"?

That was intentional. It's inline documentation.
When a parameter is only true/false it's hard to know what it means without going to the called function to determine what parameters are accepted. 

Admittedly I've only used it in a few places thus far, but that was the reason behind it.

Just leave it alone.
