### ISSUE TITLE
products to categories: updating categories, update form POST variables exceed max_input_var limit

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4253]
ZC158
![Clipboard02](https://user-images.githubusercontent.com/4391026/111083084-f1a21d80-850b-11eb-9f2a-74b3dc7d90f0.gif)

Yes I do indeed have that many categories, since they are Bike->Model->Year structure.

I added that warning, intending to persue the issue when the dust settled on this file.

So, in the scenario that I want to link a product to all those categories (since it is a generic product), only the initial chunk of selected categories up to the server limit will be processed.

So, what would be an alternative to sending these selected catagories as POST variables and so avoid this server limit?

**Comment by scottcwilson** [comment]
Maybe generic products which apply universally should be handled differently.  Put them in a specific category, then build a centerbox to display items from that category and put that centerbox on all your pages.

**Comment by torvista** [comment]
I don't think so. A category (bike-model-year) contains a lot of products in the list....many specific and even more generic. They really need to be all listed.

**Comment by drbyte** [comment]
> what would be an alternative to sending these selected catagories as POST variables and so avoid this server limit?

Additional alternatives, beyond the one Scott offered which you didn't like, include:

- link via external means, such as tools like EasyPopulate or dbIO
- manual database queries
- write another feature into your admin that lets you tick a box to link to all of that subcat's subcats instead of selecting each subcat individually
- change your PHP configuration to allow more than 1000
- rewrite the whole thing to use javascript and simply pass a massive json string

**Comment by torvista** [comment]
> write another feature into your admin that lets you tick a box to link to all of that subcat's subcats instead of selecting each subcat individually

Seems the most efficient.
Thanks.

**Comment by scottcwilson** [comment]
Can this issue be closed?
