### ISSUE TITLE
Country name United States Minor Outlying Islands too long 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4257]
The customers_country, delivery_country and billing_country fields are too short to contain the name "United States Minor Outlying Islands."  

I'd be happy to fix this but want to confirm the core team's preference before moving forward:

- extend these fields in the orders table
- abbreviate this string to "US Minor Outlying Islands"

**Comment by drbyte** [comment]
Tough to decide, given that Fedex, UPS, PayPal all seem to have no listing for it.

Does USPS give it a name? I'm not seeing any mention in either domestic or international docs, but I could be missing something. Surely they have something?

The only "official"-looking thing is IS0-3166-1 which names it as `UM`, like we do.
Shortening it by abbreviating "United States" to "US" makes it harder to find (not badly alphabetically, but visually confusing). Always more convenient to shorten the end of something rather than its beginning when it shares similarity with those around it. But there's no official shorter name for it as far as I can tell.

There are 4 entries that are longer than the 32 length supported in the orders table. Of those 4 two could probably be shortened to their familiar name; the other two are harder to shorten.

I guess the best fix is to stretch those 3 fields to varchar 44 instead of 32.

**Comment by scottcwilson** [comment]
ok please assign to me and I'll do it ASAP. I agree this is the right choice.

**Comment by lat9** [comment]
What would extending to varchar(64) do to the database size, given that anything in the varchar(33) to varchar(64) would have the same overhead, right?

**Comment by proseLA** [comment]
is there a reason why the orders table stores the country name as opposed to one of the iso_codes from the countries table?  the country name field in that table is already set to 64.

**Comment by drbyte** [comment]
> What would extending to varchar(64) do to the database size, given that anything in the varchar(33) to varchar(64) would have the same overhead, right?

Same overhead

**Comment by drbyte** [comment]
> is there a reason why the orders table stores the country name as opposed to one of the iso_codes from the countries table? the country name field in that table is already set to 64.

I think it's just always been that way. Probably inherited from osC.

The orders table is intended to "canonize" an order's information, independent of whatever else changes in customers/addressbooks/products/etc. 
I wouldn't care whether it was the ISO code or the full spelled out country name.
My personal preference would be the ISO since IMO the postal service prefers that too.

We couldn't just switch what we store in that field; we'd need to use a different field name, and then write code to use it .... and of course then all the unfortunate complexities of needing to write fallbacks in order to read old data, both for old databases and for outdated plugins that don't honor the change.

**Comment by scottcwilson** [comment]
I think the theory is to keep orders (which are past history) independent of current changes to the database.   It's the same principle behind putting the entire address (customer, shipping,  billing) vs just pointing to an index in the address table.

**Comment by proseLA** [comment]
> I think the theory is to keep orders (which are past history) independent of current changes to the database. It's the same principle behind putting the entire address (customer, shipping, billing) vs just pointing to an index in the address table.

customers move all the time.  ISO codes do not.  apparently once assigned, if said country is deleted, ISO reserves the code for another 50 years...

i get it.  very difficult to clean up and transition the old into the new...

for shipping integrations, i believe UPS and FedEx both use the iso code 2.

**Comment by scottcwilson** [comment]
ISO codes are not used in addresses.  The address table field for a country is an index - an integer which is an offset into another table, the countries table.
