### ISSUE TITLE
 STORE_ZONE (My Store :: Store Zone), unchangeable if STORE_COUNTRY doesn't have zones

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4293]
The setting `My Store :: Store Zone` isn't changeable if the country identified in `My Store :: Store Country` doesn't have zones.

**Version**
Zen Cart version: zc157c/zc158 ... probably earlier, too

**To Reproduce**
1. Navigate to the admin's `Configuration :: My Store`.
2. Change "Store Country" to a country that doesn't have zones, e.g. Uruguay.
3. Attempt to change the "Store Zone".  You can't, since what is displayed is an empty/unselectable dropdown.
![image](https://user-images.githubusercontent.com/2685585/115021095-85f3fd00-9e89-11eb-8d56-012bb55e03ba.png)

**Expected behavior**
You should be able to enter the store's zone-name.

**Comment by drbyte** [comment]
Zen Cart's internals currently require Store Zone to match a geo-zone that's linked to a country (ie: a record in the `zones` table), or be blank/zero.
Linking it to a user-defined "Zone Definition" (ie: a record in the `geo_zones` table) won't work with the internals that reference the STORE_ZONE value.

I guess if your point is that "if it's already set to a zone in another country and you want to blank-it-out because you're changing to a country without zones" (which is relatively rare to do in production), then the zen_cfg_pull_down_zone_list might be able to be altered to insert a 0-None record at the top of the list (gotta check for side-effects of that).

**Comment by lat9** [comment]
That sounds like a great solution, @drbyte.  The 'blankness' in the name of the only available selection threw me off.

**Comment by drbyte** [comment]
How often does one change their store's country from one that has defined zones to one that doesn't? And why?

**Comment by lat9** [comment]
> 
> 
> How often does one change their store's country from one that has defined zones to one that doesn't? And why?

The first time the store is installed, since the default country is `United States` and the default zone is `Florida`, if the current country (like `Costa Rica`) doesn't have defined zones.

**Comment by drbyte** [comment]
Thanks. Good point.
