### ISSUE TITLE
ZC158, admin, category-product listing search: not finding text in category description

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4343]
I doubt this is by design so it appears to be a bug.
I just put xyz in a category description and it did not get found.

**Comment by proseLA** [comment]
https://github.com/zencart/zencart/blob/bf85f1ea4a2ab56701203ca8669736b8d42482a4/admin/category_product_listing.php#L524-L535

currently not searching the cat description.

if you wanted the category description to be used as part of the search, you could replace lines 530 and 531 with:

```
                 $keyword_search_fields = [
                      'cd.categories_name',
                      'cd.categories_description',
                  ];
                  $sql .= ' WHERE ' . substr(zen_build_keyword_where_clause($keyword_search_fields, trim($keywords)), 4);

```

i'm sure that would work.  makes me think that i should improve on that function by including a var to indicate whether the clause should start with a `WHERE` or an `AND`.  currently right now, it comes back with an `AND` which is why there is a need for the substr.
