### ISSUE TITLE
Change STORE_DB_TRANSACTIONS

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4369]
1.5.8 includes/classes/db/mysql/query_factory.php" line 715 of 958 is 

            if (STORE_DB_TRANSACTIONS == 'backtrace') {

but STORE_DB_TRANSACTIONS is a boolean.  Should we add a new config?  Create a local variable in configure.php? 

(Same issue is in prior versions of this file, in 1.5.7 and 1.5.6.)

**Comment by proseLA** [comment]
please do not say any configuration value is boolean.  

i would add the value into the existing configuration.

**Comment by drbyte** [comment]
1. Correct: `STORE_DB_TRANSACTIONS` is NOT a boolean. It is a string, even if that string looks like a boolean-ish value.

2. No, we should not add a new config.

**Comment by scottcwilson** [comment]
It's a string with the possible values 'true' or 'false' - not 'backtrace'.  Do you want to modify the set function for STORE_DB_TRANSACTIONS to include backtrace?

**Comment by drbyte** [comment]
It's been intentionally left as an undocumented feature, since it throws a lot more sensitive data into the logs.
Of course, overriding such constants for temporary developer use has to be done via extra_configures, and will likely trigger some "already defined" warnings, the amount of those is mitigated.
