### ISSUE TITLE
PHP notices after a product has been automatically removed from cart

### ISSUE THREAD

**Issue by marco-pm** [zencart/zencart#4487]
ZC version 1.5.7c

On `shopping_cart.php`'s `get_products()` function, if `$check_for_valid_cart == true` and a product that the customer had in cart has meanwhile been disabled, it is removed (with `$this->remove($products_id)`).
However, later on in the same function the product is still being accessed (with `$this->contents[$products_id]`), generating these notices:

```
PHP Notice:  Undefined index: 601:b98d8dcd0327937e0978898c56a40fac in /var/www/html/includes/classes/shopping_cart.php on line 1318
PHP Notice:  Trying to access array offset on value of type null in /var/www/html/includes/classes/shopping_cart.php on line 1318
PHP Notice:  Undefined index: 601:b98d8dcd0327937e0978898c56a40fac in /var/www/html/includes/classes/shopping_cart.php on line 934
PHP Notice:  Trying to access array offset on value of type null in /var/www/html/includes/classes/shopping_cart.php on line 934
```

I would therefore add a check like `if (isset($this->contents[$products_id]))` before line 1305.

**Comment by mc12345678** [comment]
Shouldn't the code just cycle back to check/process the next product?

I would think that would add a `continue;` after the `$this->remove($products_id);`

I suggest that because, when the product is identified as being disabled during this processing, error handling is performed within that check, the product is removed and there seems to be no further need to attempt to add/collect information about the disabled product and therefore should just move along to the next product.

Anyone see a need to continue down the execution to attempt to add the "removed" product to the array of product being returned? E.g., is there some level of "handling" expected based on the quantity now being zero as a result of its removal?

**Comment by marco-pm** [comment]
I agree with @mc12345678, `continue` does the trick.

On the v158 branch a  `break` was added instead, but it's likely a mistake (that way all the next products in the cart won't even be returned by the function), so I changed it with `continue` .

**Comment by scottcwilson** [comment]
Thanks guys!
