### ISSUE TITLE
Consolidate functions in jscript_addr_pulldowns.php

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4488]
At least some of these files are exact dups.  We should consolidate this code to a single place and reuse it so fixes don't have to be done multiple times. 

includes/modules/pages/checkout_payment_address/jscript_addr_pulldowns.php
includes/modules/pages/create_account/jscript_addr_pulldowns.php
includes/modules/pages/popup_shipping_estimator/jscript_addr_pulldowns.php
includes/modules/pages/checkout_shipping_address/jscript_addr_pulldowns.php
includes/modules/pages/login/jscript_addr_pulldowns.php
includes/modules/pages/address_book_process/jscript_addr_pulldowns.php

**Comment by torvista** [comment]
Previously I had stubs in those places to include a single file from /templates/shared/form_checks
Not done it in my current site, but it should be done.

Seems it was done in a parallel universe.

https://github.com/zencart/zencart/issues/2604
https://github.com/zencart/zencart/pull/999
https://github.com/zencart/zencart/issues/574

**Comment by scottcwilson** [comment]
Ah done in 2.0.  We need to pull this change back to 1.5.x series.

**Comment by lat9** [comment]
Sounds like a good time to convert that javascript to be jQuery-based as well.

**Comment by lat9** [comment]
Does anyone know of a plugin (or other customization) that uses the built-in processing for **_multiple_** address pulldowns on a single page?  I'm guessing **not**, since the `#stBreak`, `#stateLabel` and `#stText` are all (er) unique HTML `id=` references.

I'm just wondering why the current javascript goes for the country/state dropdowns by their name instead of their `id=` attribute.

**Comment by scottcwilson** [comment]
Not AFAIK.  I think even if you had a plugin that allowed shipping different parts of an order to different addresses, it would still use entries from your address book, so it wouldn't be necessary to have two address forms on one page.

**Comment by lat9** [comment]
There's that for review.  Essentially:
1. Moved common processing to `/includes/templates/template_default/jscript/zen_addr_pulldowns.php`.
2. All page-specific `jscript_addr_pulldowns.php` now simply require the above script.
3. Page-specific `on_load_main.js` files updated to remove the `update_zone` function call.  For non-`login` page versions, those are replaced with `javascript:void(0);` calls so that there's still a file to overwrite the no-longer-needed-or-wanted call to `update_zone`.
4. The `shipping_estimator` has been updated to remove its code-based inclusion of the above onload component.

**Comment by torvista** [comment]
Anyone tried this out?...it's likely to get merged if it does what it says on the tin?
I am keen, but have no time to implement/try it at the moment.

**Comment by lat9** [comment]
I'll look at migrating those changes to zc158, but would appreciate some third-party validation that the zc157 changes do what I 'think' they do!

**Comment by scottcwilson** [comment]
Tested in 1.5.7 and seems solid.

**Comment by scottcwilson** [comment]
Please create PR for 1.5.8 when you can.

**Comment by lat9** [comment]
PR (finally) created; reviews appreciated.

**Comment by proseLA** [comment]
when i have some more time, i will test it out.  but i am TOTALLY a fan of this PR.

while we are here, and i apologize if this thread drift, i am personally a fan of NOT using the `zone_id` for the pulldowns.  using `zone_code` makes a TON more sense, and it makes integration with 3rd party address verification services so MUCH easier.

given that the `zone_code` along with the country, makes for a unique key (and we only look at zones as part of a country), i would see no problem doing it with that approach.  

i am NOT advocating for changing what we store in the database.  just the option code used in the pulldown.

my 2 cents.
