### ISSUE TITLE
Add search to Option Name Manager, Option Value Manager 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#4549]
I'd like to extend the search capability added by #4530.

**Comment by proseLA** [comment]
@scottcwilson i am not exactly sure what you are asking here.  forgive me, but my foo on option name manager and option value manager is not so strong.  

both of these scripts seem to start with an option name and then create a list of products or categories.  how would you see the searching capability that we implemented be used in this context?

**Comment by scottcwilson** [comment]
Stores that use attributes heavily can have dozens of pages of Names and/or Values. It would be nice to be able to drill in, for example, to see all values associated with a particular name on Option Value manager.

**Comment by proseLA** [comment]
just so we are clear, you are initially talking about the `set_filter` pulldown on the option value manager?  that gets constructed here:

https://github.com/zencart/zencart/blob/64e09214fd5341622ebf55a2fd22c595b146f7cb/admin/options_values_manager.php#L619

this is **VERY** far removed from the PR quoted above.  i created an abstract class called `pulldown` and then extended that class to create 2 new classes, `productPulldown` and `categoryPulldown`.  both of those new classes can make use of the search capability referenced in #4530.  if you wanted the `set_filter` pulldown to make use of searching, one would need to create a new class for the option value pulldown or alternatively build the searching into the existing construction of the pulldown.

considering the existing script to be over 1000 lines, i would be more inclined to do the first rather than the 2nd.  

however, as you can see from the blame, i have never been involved in this script.  and as my experience is rather limited, i am hesitant to do big changes to it with my limited experience.

**Comment by scottcwilson** [comment]
LOL for some reason I had forgotten that this had been addressed by the dropdown already.  Never mind!
