### ISSUE TITLE
ZC158, direct inclusion of pre-ZC158-style language files

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4582]
https://github.com/zencart/zencart/blob/580028276f6885dcb97d6c662f615d6e0b1803ff/includes/modules/shipping_estimator.php#L185
causes php warning

similar calls using zen_get_file_directory and hard-coded filenames are in
functions/audience.php
init-ipn_postcfg.php
tpl_ec_button
paypalwpp.php

**Comment by scottcwilson** [comment]
This is correctly fixed in `includes/classes/shipping.php`.  

Todo: 

- [ ] includes/init_includes/init_ipn_postcfg.php
- [ ] includes/functions/audience.php
- [ ] includes/modules/payment/paypalwpp.php
- [ ] includes/modules/payment/paypal/tpl_ec_button.php
- [ ] includes/modules/shipping_estimator.php

**Comment by scottcwilson** [comment]
It's a big block of code so rather than duplicate it, I'm turning it into a function that can be reused.

**Comment by scottcwilson** [comment]
We could also update files that use the big block of code: 

includes/classes/shipping.php 
includes/classes/payment.php

**Comment by scottcwilson** [comment]
I believe this ticket can be closed when #4595 is merged.
