### ISSUE TITLE
problem with the orders page.

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4728]
as reported here:

https://github.com/proseLA/square_webPay/issues/17

there seems to be an issue on the orders page if the payment module used is uninstalled or somehow out of date.

i think a potential solution is to change this line:

https://github.com/zencart/zencart/blob/33cd10a3efed243071f0e5bd44b4b7835e4f46d6/admin/orders.php#L736

to:
```
if (isset($module) && (is_object($module) && method_exists($module, 'admin_notification')) && $module->enabled) {
```

thoughts?

i suppose one could also do it in the `admin_notification` method of the payment module; but with square being sunsetted, i think it would behoove us to do it in the orders script.

**Comment by dbltoe** [comment]
Just throwing this out there for thought.

Is Square really being sunsetted or are we just using a different method of communication to get to our existing Web Application in Square?

As I noted in https://github.com/proseLA/square_webPay/issues/17, all the order information remains relevant and, if the payment code is changed from square to squarewebPay in the database, all pertinent data is retrieved correctly from the old orders done in Square.

Just FYI for the whole picture.

**Comment by dbltoe** [comment]
Just another FYI tidbit.

Square does not allow the deletion of a Web Application.  That means the data will remain relevant and retrievable until they make a change.

One solution done by a customer was to create a second Square Web Application and tie it to the old Square Module and utilizing the redirect URL of square_handler.php.  This was done as they only have one location.  Both Web Applications will point to the same (main) location.  This way the token can be updated.  They set the actual use to False so as to not have two Credit Card options listed.

As stated in the original mod's readme, a corn could be established to run the square_handler.php and keep it active BUT, what happens when Square turns off that method of processing/contact?

**Comment by lat9** [comment]
> Is Square really being sunsetted or are we just using a different method of communication to get to our existing Web Application in Square?
> 

That's the thought; see #4725.

**Comment by barco57** [comment]
You can "disconnect" existing web applications in the square interface

**Comment by proseLA** [comment]
i think this is an oversight on our part.

i am not a fan of changing things in the database.  obviously every store owner can do what they want.  but there is no guarantee that store owners will use the same web application for the 2 different payment modules.

i will address this issue for the `square_webPay` module; but i am not a fan of code generating fatal errors in this manner.  it should be addressed programmatically IMO.  not keeping up with refreshing of tokens should not cause a fatal error.  nor should looking at a historical order that makes use of a payment module one is no longer using.  but that is exactly what is happening.

**Comment by scottcwilson** [comment]
@proseLA your change makes sense. Please PR.
