### ISSUE TITLE
ZC158: Shipping Estimator layout errors with consolidated javascript address pulldown.

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4792]
Shipping/Packaging->Shipping Estimator Display Settings for Shopping Cart = 2  Display as listing on Shopping Cart page
Customer Details->State - Always display as pulldown? true

Put an item in the cart.

1) Choose a country with zones: United States.

![2022 05 10 Shipping Estimator 1](https://user-images.githubusercontent.com/4391026/167673997-49cf88b9-8aac-4d92-878b-5517de3fb91b.gif)

SHOWN State as dropdown: "zoneLabel" (label), "stateZone" (dropdown)  . Correct.
HIDDEN State as text input: "stateLabel" (label, which has no text!), "state" (text input) . Correct.

This **appears** to be correct visually, but also hidden is the "stBreak" linebreak which is part of the **dropdown** group which may/may not be shown dependant on the admin switch ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN.

2) Change country to a one with no zones defined, like Afghanistan.
![2022 05 10 Shipping Estimator 2](https://user-images.githubusercontent.com/4391026/167674054-7858e047-c4e8-41d4-9d39-f7125f1fd641.gif)
The original label "zoneLabel" for the dropdown is still shown. Incorrect, apparently.
The dropdown field is hidden. Correct.
The dropdown linebreak "stBreak" is shown, causing the text field to be misaligned with the (dropdown) label. Incorrect.
The label for the input field is shown. But it has no text. Incorrect.
The input field is shown. Correct.

So, some food for thought there.
 
ps. Does 
`<a name="view"></a>`
serve any purpose?

**Comment by lat9** [comment]
Unfortunately, there are more issues than those that @torvista identified, which affect **all** uses of the `zen_addr_pulldowns.php` script.

1. If none of the enabled countries for the site include zones, a jQuery error is issued since the `country_zones` array is created only for that case.
2. The initialization for use on address-input pages is incorrect, requiring a page-refresh to display the state dropdowns if the default country has zones.
3. The script should 'quick-return' if a store has `Configuration :: Customer Details :: State` set to 'false' (`ACCOUNT_STATE`), since there's nothing to be done.
4. The inclusion of a `&nbsp;` outside of any HTML tag for the `stateZone` dropdown, e.g.
```
      if (!empty(ENTRY_STATE_TEXT)) echo '&nbsp;<span class="alert">' . ENTRY_STATE_TEXT . '</span>';
```
will result in a slightly-off display of the state's input field when a country does not have zones
![image](https://user-images.githubusercontent.com/2685585/168043541-d7e7c20e-b2f0-42d5-8e1b-75f355084632.png)

FWIW, I've searched and have found no solution to optionally hide that whitespace only when the state-input is needed.

In answer to the question regarding the `<a name="view"></a>` tag, it serves no purpose that I can see but it's also harmless.

**Comment by torvista** [comment]
Does it not simplify things to just reload the page on a change of country (having the country selector as the first item or making all form inputs sticky)?  
I implemented that from day one, mainly due to having less-than-zero javascript skills at the time, but also to set up various country-specific checks on form inputs.

**Comment by lat9** [comment]
> Does it not simplify things to just reload the page on a change of country (having the country selector as the first item or making all form inputs sticky)? I implemented that from day one, mainly due to having less-than-zero javascript skills at the time, but also to set up various country-specific checks on form inputs.

It doesn't make things simpler, as that change would affect the processing of multiple pages, which is why the consolidated processing was created in the first place.  Any entered data would be posted back and would need to be reinstated in the various forms on the page's refresh.

**Comment by torvista** [comment]
> Any entered data would be posted back and would need to be reinstated in the various forms on the page's refresh.

That's why I have the country select as the **first** form item on a page, so no other data has been entered yet that could be lost.  
Anyway I also made all the forms input fields reinstated too, belt and braces. I hate forms that lose inputs!

**Comment by lat9** [comment]
Noting that having the country-select as the first form-field doesn't prevent someone from entering other information before they realize that they've not selected the correct country.

**Comment by torvista** [comment]
Yep, that's why forms should be sticky too!

**Comment by torvista** [comment]
> In answer to the question regarding the 
`<a name="view"></a> `
tag, it serves no purpose that I can see but it's also harmless.

It's deprecated/obsolete though.

**Comment by lat9** [comment]
> > In answer to the question regarding the
> > `<a name="view"></a> `
> > tag, it serves no purpose that I can see but it's also harmless.
> 
> name is deprecated/obsolete though.

OK, but that change has nothing to do with this current issue.  A separate issue and/or PR is welcomed.
