### ISSUE TITLE
admin/orders.php: PHP Warning issued if payment-module removed or enable/zone settings changed post order placement.

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4840]
ZC158, php 8.1
Make an order using moneyorder, with default settings/no zone restriction on the module.
Set a zone restriction on the moneyorder payment module.
View the previous order in the admin: get debug for line 48: $order->billing['zone_id'] which is not set.
https://github.com/zencart/zencart/blob/1a602a33c3d8a14772be3127b569dc85be77b3d5/includes/modules/payment/moneyorder.php#L41-L53

The difference between zone restriction or not, is that $order->billing['country']['id'] is set for a zone restriction.

**Comment by scottcwilson** [comment]
If you fix this by adding a !empty check on line 48 does the restriction actually work (i.e. does the payment module show up or not according to the customer's zone)?  I had some issues with this logic that I documented in #4476 (shipping not payment but likely the same problem).

**Comment by torvista** [comment]
Changing line 48 to
```
          } elseif (!empty($order->billing['zone_id']) && ($check->fields['zone_id'] === $order->billing['zone_id'])) {
```
prevents the error log and the zone restriction works...on a vanilla shop with one order and zone, and on the limited tests I've done on my shop.
But I'm not convinced this is the solution.

The background to this is that the error is triggered by changing the status of a moneyorder order in the admin.
Part of the update_order action in admin/orders includes initiating the payment module object to subsequently use the _doStatusUpdate method (which I don't find anywhere).
```
if (method_exists($module, '_doStatusUpdate')) {
            $response = $module->_doStatusUpdate($oID, $status, $comments, $customer_notified, $order->info['orders_status']);
          }
```
The error referenced in this thread comes from the instantiation of that payment object when method update_status is run as part of _construct.
Perhaps a review is required of the order object to include that missing zone_id in the billing array?

**Comment by lat9** [comment]
While I'm not able to reproduce the issue with the originally-posted instructions, I'll note that `$order->billing['zone_id']` (ditto for the delivery array) is not set during an order-query (as used in the admin processing); it's only set during the cart-to-order processing during storefront checkout.

**Comment by torvista** [comment]
My original post was incorrect, it manifests when you **change** the order status..

**Comment by lat9** [comment]
> While I'm not able to reproduce the issue with the originally-posted instructions, I'll note that `$order->billing['zone_id']` (ditto for the delivery array) is not set during an order-query (as used in the admin processing); it's only set during the cart-to-order processing during storefront checkout.

... and that's the root-cause of this issue.  Noting that the `update_status` method of all distributed payment methods (thus, likely all others) will experience the same 'missing' array key.

**Comment by lat9** [comment]
While the change that I'm working on will address the PHP Warning, it's important to note that a change in a payment method's zone restriction while there are orders pending or awaiting an update is going to result in 'wonky' results if the order was billed to a zone not covered by the updated zone-restriction.  That is, the payment method is going to determine that it's not valid for the placed order's billto zone and disable itself.  _Sigh_.  That's especially bad for payment methods that support after-purchase actions (like refunds) because those after-purchase actions will no longer be available.

The only way to circumvent those conditions is to have `/admin/orders.php` , for each spot where the order's payment method is instantiated:
1. Save the current value for `$order->billing['country']['id']`.
2. `unset` `$orders->billing['country']['id']`.  The presence of that field is something that a payment module 'looks for' in determining whether it needs to perform its `update_status` processing.
3. Instantiate the payment method, since `update_status` is _presumed_ to run during the class construction.
4. Restore `$order->billing'[country']['id']` to the previously saved value.

While that's possible, it feels like a bunch of non-intuitive code to deal with a corner-case.  Other opinions and/or solutions welcomed.

**Comment by torvista** [comment]
> the payment method is going to determine that it's not valid for the placed order's billto zone and disable itself.
I assume this bug has been around forever and no-one else has noticed the effect of a module being disabled: not worth the effort to cover it.
However perhaps an admin error message to point out the fact, at that fail point ("line 48") would suffice to satisfy internal quality-control standards.

**Comment by lat9** [comment]
> > the payment method is going to determine that it's not valid for the placed order's billto zone and disable itself.
> 
> I assume this bug has been around forever and no-one else has noticed the effect of a module being disabled: not worth the effort to cover it 100%. However perhaps an admin error message to point out the fact, at that fail point ("line 48") would suffice to satisfy internal quality-control standards.

It's just that any change to a payment module's `update_status` method is going to affect **_all_** built-in payment methods as well as those cloned from the built-ins and any totally new methods.  I'll look for spots where `/admin/orders.php` can detect errant conditions and issue a warning to the site's admin when an order's details are displayed.
