### ISSUE TITLE
zc158: debug for duplicating a product with products_date_available default/null 

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4963]
php 8.1.7, strict reporting

Admin->Product listing->Copy-Duplicate a product.

If it has never has had date_available set, products_date_available is null and causes this debug

> --> PHP Deprecated: mysqli_real_escape_string(): Passing null to parameter #2 ($string) of type string is deprecated in \includes\classes\db\mysql\query_factory.php on line 175.

but it comes from this call
https://github.com/zencart/zencart/blob/0544f29edac64242e286690f0c9d042cf7baebb8/admin/includes/modules/copy_product_confirm.php#L69

Perhaps this default should be changed from null to now/the inserted date?

Additionally if the source product has a date set for this field, that is copied too. Does that make sense?

**Comment by lat9** [comment]
Noting that the same deprecation is raised during storefront processing when an order is placed for an attributed product that doesn't have any quantity-discounts applied (think the demo product "A Bug's Life "Multi Pak" Special 2003 Collectors Edition"), since `products_attributes::attributes_qty_prices` and `products_attributes::attributes_qty_prices_onetime` are also (by default) NULL:
```
[01-Jul-2022 10:35:14 America/New_York] Request URI: /zc158/index.php?main_page=checkout_process, IP address: 127.0.0.1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php(175): mysqli_real_escape_string()
#2 C:\xampp\htdocs\zc158\includes\functions\database.php(104): queryFactory->prepare_input()
#3 C:\xampp\htdocs\zc158\includes\classes\order.php(1079): zen_db_perform()
#4 C:\xampp\htdocs\zc158\includes\modules\checkout_process.php(99): order->create_add_products()
#5 C:\xampp\htdocs\zc158\includes\modules\pages\checkout_process\header_php.php(14): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\zc158\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Deprecated: mysqli_real_escape_string(): Passing null to parameter #2 ($string) of type string is deprecated in C:\xampp\htdocs\zc158\includes\classes\db\mysql\query_factory.php on line 175.
```
I'm wondering whether it's better to review/change some of the database defaults from `NULL` to an empty string or to burden the `query_factory` class with a conditional check to ensure that any value supplied is, in fact, a string ... tending towards the former, but open to suggestions.

For the second question/comment in the original issue's posting, I don't think it makes sense.

**Comment by scottcwilson** [comment]
> Additionally if the source product has a date set for this field, that is copied too. Does that make sense?

Some people will want this and others won't.   I *kind of* think it should since you did say "copy," but I'm not strong on this.
Obviously fields like `products_date_added` and `products_last_modified` should not be copied but I think others should.

If you decide not to copy, let's build an exception list here:
https://docs.zen-cart.com/user/products/product_management_admin/#copying-a-product

so that it's clearly documented.

**Comment by torvista** [comment]
After uprating my production site to php 8.1 for a couple of days before going back to 8.0,  I've been all this rainy afternoon reviewing the debugs, all are associated with passing null to php functions.
I think fixing these at source by reviewing the db null defaults may be a better time investment, as I imagine this tightening of null-to-functions will only get wider with subsequent php versions.

**Comment by torvista** [comment]
Although pedantically duplicate should mean duplicate, in reality duplicating a product is when you want a new product that is very similar to an existing one. But it will always end up being a different product. So while description, name, meta-data etc. will require slight changes, the date fields are not related to the source product and should not be copied, in my opinion.

**Comment by scottcwilson** [comment]
Acme Industries is releasing two new products on 09-01-22.  You create the first one and set date available.  Then you copy that product.  Why wasn't date available set?   What kind of a copy is this anyway?

**Comment by torvista** [comment]
Returning to the theme. 
PR for changing db default?
products_date_added
products_date_available
products_last_modified
to empty string or 0001-01-01 00:00:00

**Comment by scottcwilson** [comment]
> I'm wondering whether it's better to review/change some of the database defaults from NULL to an empty string
I would prefer not to do this change.  There's lots of code out there that handles the current schema.  If we need to add checks, let's add checks.

**Comment by lat9** [comment]
PR just created addresses the deprecation logged, but doesn't address the whether/not to copy the associated date.
