### ISSUE TITLE
Release Page Still has 1.5.7 PDF

### ISSUE THREAD

**Issue by dbltoe** [zencart/zencart#5321]
https://docs.zen-cart.com/release/ still has a link to the 1.5.7 PDF

**Comment by scottcwilson** [comment]
Thanks for spotting that.

**Comment by scottcwilson** [comment]
OK long story short: 

- I was hoping to keep the implementation guide with the rest of the online docs but PCI requires it to be distributed with the product. 

- We're really trying to reduce duplication in the product because it's an endless source of problems as things get out of sync since there are two sources of truth.  For this reason, I removed the .pdf from the online docs.  The updated 158 pdf will be built into the next patch release of 1.5.8; for now, you can pull it from Github:
https://github.com/zencart/zencart/blob/v158/docs/implementation-guide-v158.pdf  

- Moving forward, updating the PDF and getting it into the build is part of the documented build process, so hopefully it won't be missed again.
