### ISSUE TITLE
PHP8.2 utf8_encode and utf8_decode are deprecated

### ISSUE THREAD

**Issue by brittainmark** [zencart/zencart#5387]
**Describe the bug**
If PHP 8.2 is used and the CHARSET is not UTF-8 a depreciation error `This function has been DEPRECATED as of PHP 8.2.0. Relying on this function is highly discouraged.` will be raised in ajax.php and includes/functions/function_strings.php

**Version**
Zen Cart version: 1.5.8
PHP version: 8.2

**Additional context**
`utf8_encode` could be replaced with `iconv` to perform the necessary conversion. Assuming a conversion is necessary at all.
Additionally, does ajax.php need its own copy of the function?

**Comment by lat9** [comment]
Does anyone have a clue as to whether the various language translations are now `utf-8` instead of `iso-8859-1`?  I'll note that the last time the base Zen Cart /includes/languages/english.php was `iso-8859-1` was in zc139h (2010-10-31).

Perhaps it's time to simply drop the `utf8_encode_recurse` function.

**Comment by torvista** [comment]
This error cropped up multiple times in CEON URI, I removed all uses of the function as it occured without noting any difference.
The spanish language pack has long been utf-8. The "rest" are in unknown states of decomposition/use/maintenance.

**Comment by brittainmark** [comment]
There was a new Japanese language pack posted recently, had a quick look it appears to be UTF8 encoded.

I remember reading that the preferred solution was to remove it, as @torvista did.

**Comment by scottcwilson** [comment]
> Date in admin header was mixed up by a conversion to utf8 for Windows only. Problem is that it was already utf8.

I see that line in `admin/includes/header.php` is still there... thought we had gotten rid of that ... if a Windows person could go through and clean this up, that would be great.

**Comment by piloujp** [comment]
> > Date in admin header was mixed up by a conversion to utf8 for Windows only. Problem is that it was already utf8.
> 
> I see that line in `admin/includes/header.php` is still there... thought we had gotten rid of that ... if a Windows person could go through and clean this up, that would be great.

What I first did was adding a test to check if string is utf8 or not. But I had to add a new function for that. Now I am testing without any conversion or test at all and there is no problem at all even with an old Windows 7.
As long as the browser support utf8, which is nearly all at this time, there should be no problem on client side. On Server side I am not sure. Win Server 2019: no problem, Win Server 2008: no good, and in between I don't know.
All in all I think this Windows test can be dropped without regret.
Ligne 203 in admin\includes\header.php can be change from:
`echo((strtoupper(substr(PHP_OS, 0, 3)) == 'WIN') ? iconv('ISO-8859-1', 'UTF-8', $zcDate->output(ADMIN_NAV_DATE_TIME_FORMAT, time())) : $zcDate->output(ADMIN_NAV_DATE_TIME_FORMAT, time())); //windows does not "do" UTF-8...so a manual conversion is necessary`
to:
`echo $zcDate->output(ADMIN_NAV_DATE_TIME_FORMAT, time());`

**Comment by scottcwilson** [comment]
Can you PR this change?

**Comment by piloujp** [comment]
Hi Scoot,

 

I already pm this on Zencart forum but if you prefer on Github here is a
copy:

Line 203 in admin\includes\header.php can be change from:

Code:

echo((strtoupper(substr(PHP_OS, 0, 3)) == 'WIN') ? iconv('ISO-8859-1',
'UTF-8', $zcDate->output(ADMIN_NAV_DATE_TIME_FORMAT, time())) :
$zcDate->output(ADMIN_NAV_DATE_TIME_FORMAT, time())); //windows does not
"do" UTF-8...so a manual conversion is necessary

to:

echo $zcDate->output(ADMIN_NAV_DATE_TIME_FORMAT, time());

 

Pierre

**Comment by torvista** [comment]
Just got bugged by this in function zen_date_long.
I can remove all instances of it in one PR....

**Comment by lat9** [comment]
> Just got bugged by this in function zen_date_long. I can remove all instances of it in one PR....?

"Bugged" ... in what way?  I'll note that the function's been around forever, and it's quite likely that add-on plugins are making use of it.

**Comment by scottcwilson** [comment]
I think he means the PHP_OS check and subsequent call to `utf8_encode`.

**Comment by torvista** [comment]
Correct.

**Comment by lat9** [comment]
Why not just remove the usage (those 2 spots) of `utf8_encode`?  Any site that's running on zc158+ and is still using a `latin1`/ASCII encoding is going to have additional issues.

**Comment by brittainmark** [comment]
> Why not just remove the usage (those 2 spots) of `utf8_encode`? Any site that's running on zc158+ and is still using a `latin1`/ASCII encoding is going to have additional issues.

That was my original thought, too! Did not expect it to cause this much debate.

**Comment by torvista** [comment]
Since I entered the ZC world I seemed to come up against utf-8/encoding issues for the first time. Maybe as I have a spanish site, leading to spanish accents in products, customer/order details and working locally on Windows.
Not seen any new ones for a very long time.
I think the doubt is if all instances of utf8-encode can be removed, and of the miniscule pool of developers here, only the piloujp is likely to see side effects as the rest will be mainly handling non-accented product and customer names. So the testing is a problem.

Anyway, out of laziness I've removed all the (few) instances of utf8_encode in core code too, see if the sky falls in....meanwhile the two obvious ones can be purged now.

**Comment by piloujp** [comment]
Well Torvista, actually I think you won't have any trouble and me neither if I remove everything like you did. We are using utf8 systems and settings, we don't need conversion to utf8 as everything is already utf8. Problems would be for pure ASCII systems that could not deal with utf8, or would it be? Pure ASCII system only produces ASCII. The only conversion needed would be when importing data from another system or files. Then a conversion utf8 (or whatever encoding) to ASCII is necessary. 
It made me wonder why are there conversions to utf8 in Zen Cart?
Actually I remembered that before utf8 I had my shop in 3 languages, English, French and Japanese. English and French were using ASCII (ISO-8859-1)  and Japanese SHIFT-JIS. Displaying everything correctly in admin side was only possible using SHIFT-JIS meaning I had to use a fully converted Japanese Zen-Cart.
At this time conversion function would have been nice and it is probably when utf8 appeared that they were implemented. If I am right these conversions are there for non-utf8, non-ASCII systems allowing partial use of utf8 on server side while client side is still using local charset in case browser do not support utf8. Actually it is what I did for a while with database and few files only in utf8 but charset set to SHIFT-JIS.
Anybody has an idea why they are there? utf8_encode can easily be replaced by iconv or perhaps better mb_convert_encoding but is there some usefulness in these conversions? Looking at the code I can't tell.

**Comment by lat9** [comment]
IIRC, the use of `utf8_encode` began with zc155, which is where the built-in AJAX handling 'recognized' that JSON arrays could be returned.

JSON required that the data be utf8 and, since 2016 was still a transition period for sites changing from latin1/iso encodings, it made sense to perform that data conversion.

**Comment by piloujp** [comment]
Thanks for this information. It means conversions might still be needed in some cases.

**Comment by lat9** [comment]
> IIRC, the use of `utf8_encode` began with zc155, which is where the built-in AJAX handling 'recognized' that JSON arrays could be returned.
> 
> JSON required that the data be utf8 and, since 2016 was still a transition period for sites changing from latin1/iso encodings, it made sense to perform that data conversion.

Given that 2016 was (er) **_7 years ago_**, I'm of a mind to just _nuke_ that UTF8 encoding in the main `/ajax.php` handler.  Sites that are still using a latin1 encoding are going to experience more issues than the AJAX returns being wonky.

**Comment by scottcwilson** [comment]
Don't like that.  There will be latin1 sites, and we want to encourage them to upgrade one step at a time.  Converting to utf8 is a pain that will scare them away.

**Comment by torvista** [comment]
Make a release note that latin1 sites need to convert prior to an upgrade/ do a warning on a db upgrade if tables are not already utf-8 or are still mixed?

**Comment by brittainmark** [comment]
Totally agree. Release note and purge.

**Comment by piloujp** [comment]
Is there really some cases where this conversion is needed with Zencart 1.5.8 and above? Database is installed with UTF-8 collation and when upgrading installer could take care of conversion or lat9 conversion tool which makes conversion of all database collation so easy... I really can't see any use for utf8_encode on a new cart version but I may be missing something...

**Comment by torvista** [comment]
Tell them some big lads did it, then ran away. 

Then pass 40+ invoices.

**Comment by brittainmark** [comment]
Maybe we need to leave this for 1.5.9 not a letter release. If Scott has 40 carts on 1.5.8 it would be difficult to justify db change on letter release. 
That being said, it does cause an issue with PHP 8.2. 
Options
1) convert to use iconv for now.
2) put some code to check PHP version and if using PHP 8.2 ignore the conversion
3) build in lat9 conversion to zc_install
4) remove and add check to zc_install with message pointing to [zen cart document convert to uft8](https://docs.zen-cart.com/user/upgrading/convert_to_utf8/)
5) something else!

**Comment by lat9** [comment]
FWIW, I've got a site that I inherited that was upgraded from zc155 to zc158 that has the dreaded mixed-collations (the overall database has a utf8mb4/utf8mb4_general_ci charset/collation):

![image](https://github.com/zencart/zencart/assets/2685585/4ee681c1-01ac-4c2a-85e1-f0e9055f5ce4)

The site's using a CHARSET of `utf-8` and a DB_CHARSET of `utf8mb4`.  Having commented out the various PHP files that do the `utf8_encode` and letting each of those modules "do their thing", I'm not seeing any logs when running PHP 8.2 (especially the Deprecated ones).

I believe that we should be forward-going and simply remove the now-deprecated uses of the `utf8_encode` function since I'm seeing no ill-effects of that removal.

**Comment by scottcwilson** [comment]
Thanks for checking.

**Comment by lat9** [comment]
> Thanks for checking.

If that's agreement, I'll get a PR submitted.

**Comment by scottcwilson** [comment]
We'd better to support PHP 8.2.

**Comment by drbyte** [comment]
Technical notes regarding how we got to the point of using `utf8_encode` in the case of this `ajax.php` file:

Make sure response is utf8, because `json_encode` requires `utf8` content:
https://github.com/zencart/zencart/commit/2ec6449c04a807b7fe332f93f1102fdc9609518f

Make it recursive:
https://github.com/zencart/zencart/pull/654

Refactor to use utf8_encode recursively:
https://github.com/zencart/zencart/pull/684
