### ISSUE TITLE
zen_get_uprid returns a mixed (int|string) value, not a string

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5452]
Having just spent the last hour trying to figure out why my code wasn't working ... a non-attributed product, when added to the cart, results in an (int) value being returned for an 'id' element of the `$_SESSION['cart']->get_products()` returned array.

Since its results can't be counted on as a string, as it's been that way forever, perhaps it's best to just update the function's definition to indicate that it returns `mixed`.

**Comment by mc12345678** [comment]
Something is not correct about the content of this issue. `zen_get_prid` returns an `int` not a string and not mixed. (Yes the comment block description of the function wrongly states a mixed return.) How that factors into the remainder of the discussion is yet to be really figured out because it calls to question what other details were omitted or otherwise urgently glanced over. For example how it matters if the value stored in `$_SESSION['cart']->contents` is a string or an integer, e.g. what type of comparison is being made and must it be made that way? 

The function described in the title: 
https://github.com/zencart/zencart/blob/707e4f51161f11fac04207e5a150f48dad08447a/includes/functions/functions_products.php#L423-L433

**Comment by lat9** [comment]
Sorry, wrong function.

**Comment by mc12345678** [comment]
Ah, so just need to make the following change: 
````diff
-    if (!is_array($params) || empty($params) || strstr($prid, ':')) return $prid;
+    if (!is_array($params) || empty($params) || strstr($prid, ':')) return (string)$prid;
````
As provided at: https://github.com/zencart/zencart/blob/b0b560f603f3b04d3efc3409a36805b7bac7c6aa/includes/functions/functions_products.php#L406

At least in that way, the statement of returning a `string` would be true. Don't know yet impact of other places in the core code.
