### ISSUE TITLE
Can no longer create an admin form that targets a different page with GET request

### ISSUE THREAD

**Issue by neekfenwick** [zencart/zencart#5454]
**Is your feature request related to a problem? Please describe.**
In past Zen Cart releases I've had a form on our admin dashboard that lets us quickly type an order ID and be taken to the Orders page editing that order, i.e.:

```
<?php echo zen_draw_form('orders', FILENAME_ORDERS, '', 'get'); ?>
<input type="hidden" name="action" value="edit">
  <label>Order ID: <input name="oID" type="number"></label>
</form>
```

However, the latest `zen_draw_form()` insists on writing a hidden `input` with `name="cmd"` and `value` taken from the current requests's `$_GET['cmd']`.  The resulting HTML is:

```
<form name="orders" action="https://dev.site/my-admin/index.php?cmd=orders" method="get">
  <input type="hidden" name="cmd" value="home">
  <input type="hidden" name="action" value="edit">
  <label>Order ID: <input name="oID" type="number"></label>
</form>
```

The cmd=orders in the action is overridden by the hidden field's value, and submitting the form takes you to the `home` target instead of `orders`.

It seems that the way `zen_href_link()` and `zen_draw_form()` work in the latest release conflict with each other, because they both try to insert a `cmd` parameter into the request, the one generated by `zen_href_link` in this case is overridden and ignored.

**Describe the solution you'd like**
Ability to generate a form with customised `cmd` value different to the current page.

I wonder what the team think with their deeper knowledge of why and how this feature came about?

**Comment by mc12345678** [comment]
See #3922

**Comment by scottcwilson** [comment]
Change the last parameter of the form from `get` to `post` (or omit it, since post is the default).

**Comment by scottcwilson** [comment]
GET forms are intended for on page filter activity only.  

https://docs.zen-cart.com/dev/code/forms/
https://docs.zen-cart.com/dev/plugins/upgrading_to_1.5/#rewriting-addon-admin-pages-to-use-form-posts-instead-of-gets

**Comment by mc12345678** [comment]
> Change the last parameter of the form from `get` to `post` (or omit it, since post is the default).



> GET forms are intended for on page filter activity only.
> 
> https://docs.zen-cart.com/dev/code/forms/ https://docs.zen-cart.com/dev/plugins/upgrading_to_1.5/#rewriting-addon-admin-pages-to-use-form-posts-instead-of-gets

These replies and the information at the link do not necessitate that the action page be the same as the current page. Per the malleable instruction, the expectation is that the `$_GET` parameters are for filtering. Such can be accomplished by reference to another page (which may or may not offer self filtering on the same parameters), though is not supported in the core code by change or override. 

So why wouldn't the function get modified as suggested in issue #3922?

**Comment by neekfenwick** [comment]
> Change the last parameter of the form from `get` to `post` (or omit it, since post is the default).

I can't do this, this is a form on our admin dashboard that directs the admin user to the orders page with a search pre-set, and that page works with $_GET.

> GET forms are intended for on page filter activity only.

Yes, but that sentence doesn't dictate which page, why not allow navigation to a different page with on page filter activity?

Anyway sorry for the duplicate, it looks like I'm not going to win any arguments here, I'll go back to hardcoding HTML, closing.

**Comment by scottcwilson** [comment]
This might be a US English thing, but for me, the phrase "on page filter activity" means "filter activity on the current page." 

You are the first person to have hit this issue in recent memory.  Your request is intuitively reasonable, and maybe it should be less restrictive, but these changes were done because there's a boatload of code out there written by people who are less skilled than you are that bad guys were able to exploit.  If I had the requirement you have (passing a GET parameter to orders.php from a form), I guess I'd create an intermediate page file that would read the POST parameters and do a redirect - but certainly hand coding the form (while adding the security Token) is not a bad solution. 

Chris felt this was a bug.  Maybe it is - but I (personally) would not be willing to change it at this point.  We have a ton of other issues that are affecting more people, and you have multiple workarounds.  There are a limited number of skilled developers working on the product, and I have to triage issues.

**Comment by neekfenwick** [comment]
Thanks @scottcwilson yeah it's not necessarily a US/Other English issue, just a context issue, the "on page filter activity" implies that the page is filtered but I don't see a need to dictate the source page of the request.  I'm not familiar with the exploits you mention, and can't imagine off the top of my head how enforcing the rules currently in the code would help avoid any exploit, given that the code generates HTML from code in the system, not from inputs, but I have to presume you're correct.

Your suggestion of having an intermediary page, which would be custom code handling the respective parameters, is more complex than simply hardcoding the form without using zen_draw_form in the first place, so I'll stick with my solution, thanks for the tip though.

I'd be interested in what exploits they were :) I appreciate you're digging your heels in for a reason.

**Comment by mc12345678** [comment]
Again revisiting this topic, I too would like to see what exploits were of concern requiring the addition of the cmd parameter in a form preparation function to now require that `GET` style be used only on the same page.  

I mean the commit that added the parameter specifically states that it should have no impact on legacy plugins and that the primary reason for adding the parameter was to support plugins. 

See this commit:  https://github.com/zencart/zencart/commit/ceec52b218238d7925aaf6b59b0a3e2126e62ab4

**Comment by proseLA** [comment]
> **Is your feature request related to a problem? Please describe.** In past Zen Cart releases I've had a form on our admin dashboard that lets us quickly type an order ID and be taken to the Orders page editing that order, i.e.:
> 
> ```
> <?php echo zen_draw_form('orders', FILENAME_ORDERS, '', 'get'); ?>
> <input type="hidden" name="action" value="edit">
>   <label>Order ID: <input name="oID" type="number"></label>
> </form>
> ```
> 
change is hard...  so is javascript...

sorry for the late response.  i too have had this issue.  i solved it as so:

```
<b>Pull Up Order #</b><?= zen_draw_form('input_oid', FILENAME_ORDERS, '', 'get', '', true) . 
zen_draw_input_field('oID', '', 'class="form-control" size="6"') . 
zen_draw_hidden_field('action', 'edit'); ?>
</form>
````
and then loaded a javascript file:

```
var $ = jQuery.noConflict();

$(function ($) {
    $('form[name="input_oid"] > input[name="cmd"]').replaceWith('<input type="hidden" name="cmd" value="orders">');
});
```
the ability to customize the header of the admin to get quickly where you want to go could be better done.  but i feel your pain.

if would be **NICE** if all plugin authors for admin plugins used the admin_html_head.php to make all of their plugins compatible with the latest...

i do other things as well:

![image](https://user-images.githubusercontent.com/1095136/207366917-c90a1f79-ec88-4b3b-a231-1bdd657a9efb.png)

and replace various nodes with javascript as needed.  

hope that helps!

**Comment by proseLA** [comment]
> > and replace various nodes with javascript as needed.
> 
> Good to see others having this problem, and I hope you take this in good humour, but 'fixing' this problem with Javascript is one of the more horrible methods I could think of :) You're doing something identical to my use case, by the look of it .. having a form on one page (probably home?) that targets another (customers or orders) with a GET request to load the page pre-filtered.

good humuor taken...

i do not understand the solution being as horrible as you state.  perhaps you can elaborate...

**Comment by neekfenwick** [comment]
> i do not understand the solution being as horrible as you state. perhaps you can elaborate...

Using JS to alter content that was generated by the backend seems to me to be a poor engineering solution, that's all.  (side note: This is a different situation so JS frameworks that intentionally have the backend generate placeholder nodes for the JS to modify, such as Dojo, in those cases the backend and JS are designed by the same developers to work in tandem.)  If one were in control of the whole system, one would fix the backend so it generated the required output in the first place.  In this case, the 'fix' is to allow the PHP code to generate HTML as required.

Talking purity of code: I'm not sure what your experience of software development is, but you're talking about allowing one system of code controlled by one party (zencart) to produce output, and then using another system of code controlled by a second party (your JS) to modify it.  If either one changes, the result can be broken.  Better to consolidate the requirements of output in one place (zencart).

**Comment by proseLA** [comment]
you are a very welcome addition to the zc community.  

welcome aboard.

**Comment by neekfenwick** [comment]
I did some digging in `gitk` searching for the string `$form .= '<input type="hidden" name="cmd"` and discovered:

In `zen_draw_form`, the addition of a `cmd` hidden field was first done in commit 5c7e04f58, and actually had `cmd` set to `$action`
`+    if (strtolower($method) == 'get') $form .= '<input type="hidden" name="cmd" value="' . $action . '" />';`

branch: remotes/upstream/v2-historic
in response to ISSUE-98
Ian Wilson ian@zen-cart.com 2014-05-17

This was on some old v2-historic branch that does not seem related to today's `v158` branch.  My git-fu is weak here and I don't know exactly why, but it looks like the whole code base was added fresh on another branch so git doesn't think they are related.

Then later, the same author, on a different branch, introduced a similar change, this time with the more complicated logic: https://github.com/zencart/zencart/commit/ceec52b218238d7925aaf6b59b0a3e2126e62ab4#

```
if (strtolower($method) == 'get') {
    $form .= '<input type="hidden" name="cmd" value="' . isset($_GET['cmd']) ? $_GET['cmd'] : 'home' . '">';
}
```

I really don't see any good reason for this, @zcwilt may be able to comment but he didn't reply to DrByte's comment on that commit.  I have experimented with changing the line back to the original `value="' . $action . '"` and it works perfectly, all the admin links work, searching by order id or customer name work, plus you can then have a form on the dashboard that targets another page e.g. `orders`.

@mc12345678 this is a much simpler fix than your larger changes on https://github.com/mc12345678/zc-v1-series/commit/2f98663bf1578aef696ff93402428c9cf27ab5e5 which I had not seen until now. Not sure if I'm wasting my time or have simply found a cleaner way of doing what you were trying to do.  What do you think of my commit at https://github.com/zencart/zencart/compare/v158...neekfenwick:zencart:issue-5454 is this an alternative to yours? I was about to issue it as a PR here but noticed your different solution.

**Comment by scottcwilson** [comment]
Reopening pending resolution of linked PR.

**Comment by neekfenwick** [comment]
> Reopening pending resolution of linked PR.

Thank you.  I'm waiting on @mc12345678 response, as we have both proposed commits that claim to solve the problem.  I just noticed https://github.com/zencart/zencart/pull/5470, I hadn't realised @mc12345678 actually submitted it as a PR.  The diff on that commit is very noisy, every line changed, and I can't see at a glance what's going on.  Why so much change when my https://github.com/zencart/zencart/compare/v158...neekfenwick:zencart:issue-5454 solves this problem much simpler?  Was there wider code improvement going on?

**Comment by mc12345678** [comment]
> > Reopening pending resolution of linked PR.
> 
> Thank you. I'm waiting on @mc12345678 response, as we have both proposed commits that claim to solve the problem. I just noticed #5470, I hadn't realised @mc12345678 actually submitted it as a PR. The diff on that commit is very noisy, every line changed, and I can't see at a glance what's going on. Why so much change when my [v158...neekfenwick:zencart:issue-5454](https://github.com/zencart/zencart/compare/v158...neekfenwick:zencart:issue-5454) solves this problem much simpler? Was there wider code improvement going on?

Please refer back to my first referenced post of this thread (which I conveniently provide again to see #3922). I'll note also that the proposed fix (#5470) referenced this issue's thread and the one I just linked again to this thread.

That said, a synopsis/analysis: the proposed pull request was to capture what @drbyte had suggested before he took some form of sabbatical to tend to important matters. In the discussion of his proposal there is a form of need or issue to address relating to form submission operation and how the form is both initially directed and what it contains when used as a `get` type form. 

Big picture about the rewrite:  distinct variables are introduced to represent the individual "task" instead of continuously adding content to a `string`. This part is a code improvement for readability and for those seeking function modification.

The parameter name change within the function parameters, improves the syntactical sugar for the parameters' intended use. 

The default value for one of the parameters was changed for a similar reason, finally acknowledging that it doesn't matter whether `SSL` is identified or not in the admin as there really is only one choice relating to the site's configuration/installation. (See the function `zen_href_link` code in `admin/includes/html_output.php`.)

Then otherwise within the function proposal, the `action` portion of the form is being built/rebuilt to use the above mentioned `zen_href_link` as is suggested/recommended even in the Zen Cart docs about adding a link to the site. An aspect about which I stated in [here](https://github.com/zencart/zencart/issues/3922#issuecomment-809298640) is that using that function may have some negative consequence. My previous discussion centered around existing code (perhaps URI rewriters) that may toy with the returned link and in so doing may actually remove the desired parameters and not be able to parse them using the proposed code. I see now though too that use of `zen_href_link`, without further observer interaction, may prevent expected operation for an off-site `action`. I had no specific testable example and haven't further evaluated though the proposed code is more than a year old.

Then there is the newly added `zen_get_url_get_params_as_array` function, as I said above, it is possible that a URI Rewriter may hijack the url and remove the search related parameters off of the link, but in current code, such code should be able to recognize that it shouldn't do that here else it risks forcing self-redirection.  Of course the function's code could all be implemented within the `zen_draw_form` function, but it appears potentially useful to other operations/callers. I see that it could be easily used to return the `cmd` portion of a link for building a new link or evaluation of parameters, but that also seems secondary. 

It seems that, and the original code author would know better, that it was added to combat an observation of operations. My understanding of the described observation was that `get` style form submission of the `action` negatively impacts the parameters of the `action`. Statement seems to imply that the search portion is obliterated, though the complete removal of the search parameters doesn't seem to happen otherwise we would all be in a different place.

What I have observed is that the applicable portion of the action is replaced by whatever tag data the form collects. That portion is what both of us have been trying to address (specifically that `cmd` needs to contain the desired value). 

I will say that a difference in implementations is that while carrying the input `$action` parameter to the value of the `cmd` hidden field *works*, doing so incorrectly carries over the other parameters in `$action` where `cmd` may not be the first parameter (assuming that `zen_href_link` isn't used internally to set the value associated with `$action` and the parameters provided for directing the form aren't considered) or where `$action` provided parameters are to be modified by the form. 

Potentially in so doing by using `$action` for `cmd`, there may be an unresolved discrepancy between the parameters of `$action` and the second parameter of `zen_draw_form` where those of `cmd` prevail.  Another way to state that is the thought about the form's handling of parameters in direct use of `$action` for `cmd` is the discrepancy of parameters between `$action` and the second parameter for `zen_draw_form` being overridden by those provided in `cmd` which is then counterproductive. 

That said, yesterday I tried to look further into the applicable RFC requirements/expectations. In [this post](https://github.com/zencart/zencart/issues/3922#issuecomment-884124740) , I had identified [RFC 1866](https://www.ietf.org/rfc/rfc1866.txt) as likely applicable, but that RFC also referred to a definition of URL as if it were somehow widely known or understood. A little further review of that RFC identified reference to [RFC 1738](https://www.ietf.org/rfc/rfc1738.txt) where `URL` is basically described as being everything basically up to the first question mark. The content after that is described as the search portion of the address. Coming through some of those details and impact is why there has been a moment of delay in further discussion. 

I'll say this, which may in part align with comments above, this issue was identified two calendar years ago, a solution was proposed by a core developer more than a year ago, within the last 8 months it has been publicly stated by a newly current core developer that basically I'm to be ignored, which after sufficient abuse (including threat of banishment from the project) and in accordance with a statement I had made regarding assistance in supporting initial development of Zen Cart 1.5.8, I withdrew (closed) all contribution to that effort to return after release. 

Part of the direction to ignore me was that whatever modification might be considered (although still met with aggression) must fix a problem. Well, wasn't a problem until release and now there is a problem and at least one potential solution. But, I proposed that solution seeing as neither of the two core developers had as a PR, so because I proposed it I wouldn't be surprised that it will either be ignored or that some "quick fix" be applied. To add further, yes the solution has been described as unnecessary or unnecessarily complicated, but simultaneously doesn't recognize the improvements easing developer understanding of operations or how/where to apply desired and effective modifications.

As to other delay in response, I also am a common user of this package (with interest to resolve this), I have other time sensitive work and while I too fully appreciate and respect your interest in correcting this, the issue went ignored for more than a year after a solution was proposed. While of interest to me to resolve, I can only expend so much time, no matter how negatively impactful on the community and this project. I still believe (however foolish the belief may be) that growth will occur,  behavior will improve, and that through all of the significant modifications that this project will continue to securely operate and regain notoriety. That's with or without me.

**Comment by neekfenwick** [comment]
@mc12345678 that was quite an info dump, I'd like to stay on topic.  I closed this issue a while back as a dupe, and it still seems so. I've tried your commit https://github.com/mc12345678/zc-v1-series/commit/2f98663bf1578aef696ff93402428c9cf27ab5e5 and it does seem to work, I see it's actually a code suggestion from @drbyte on #3922, though I'm not sure the problem you're trying to solve is really a problem.

For example, the $action passed into `zen_draw_form` is expected to be a simple string like `orders`, it's not meant to have query params on it at that point.  It would be safe to take that and use it for a value such as `cmd`, as I do in my commit.  In your proposed commit it's passed into `zen_href_link` where it has `.php` appended, `cmd=$page` added, and gets the `$href_parameters` added to it, and the result is returned as `$url`.  Then `$url` is exploded to see if `cmd` exists in it, which is not necessary.  (re: your statement above "doing so incorrectly carries over the other parameters in $action where cmd may not be the first parameter")  The `cmd` value in it is predetermined, it was the `$action` string passed into `zen_href_link`.  This is why I'm thinking simply using `cmd=$action` in `zen_draw_form` is simpler.

I don't see in the record of #3922 why it was closed by you as 'completed'.  Can we reopen it, close this as a dupe and continue the discussion there?

**Comment by scottcwilson** [comment]
I have asked Chris or Ian to weigh in on this.  Please sit tight until that happens.

**Comment by neekfenwick** [comment]
> I have asked Chris or Ian to weigh in on this. Please sit tight until that happens.

Any news on this, please? It seems we have two candidates for fixing this, one in @mc12345678 PR based on @drbyte comment here https://github.com/zencart/zencart/issues/3922#issuecomment-806266343, which I critiqued on 23 Dec above as over engineered, and second in my commit https://github.com/zencart/zencart/compare/v158...neekfenwick:zencart:issue-5454 which is much more simple and gets the job done.

**Comment by zcwilt** [comment]
Hi  @neekfenwick 
Sorry. Meant to look at this, but other things kept getting in the way.
Will look at this tonight.
Generally I would want to got with the simplest solution.

**Comment by zcwilt** [comment]
@neekfenwick 
Do you have a PR for your change.
At this point in time, I think the simpler solution is best.
I've not seen a convincing argument for anything more complicated.

**Comment by neekfenwick** [comment]
> @neekfenwick Do you have a PR for your change. At this point in time, I think the simpler solution is best. I've not seen a convincing argument for anything more complicated.

Just made one, my branch was a little out of date but it's a trivial change with no conflicts.  Thanks for coming back to us :)
