### ISSUE TITLE
allowing for no javascript?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5641]
While noticing things go awry on the shopfront (responsive classic) with javascript disabled, just wondering if this is now of no concern in this day and age?

**Comment by scottcwilson** [comment]
I would not want anyone to spend time addressing this scenario.

**Comment by torvista** [comment]
Me neither, but the question remains!

**Comment by lat9** [comment]
It depends on what `awry` behavior follows the javascript disablement.  A bunch of time has been spent in the PHP code so as not to rely on javascript checks, so I believe that form-related processing (if possible without javascript/jQuery helpers) should be OK.  I can imagine a couple of user-induced issues if a user _chooses_ to disable their browser's javascript:
- Forms might not submit (I'm thinking OPC, for example).
- Page display might be somewhat wonky without javascript helpers to aid in the formatting.

Since it's a user's choice to disable their browser's javascript, my feeling is that they can live with the results if they so choose.

**Comment by torvista** [comment]
> Since it's a user's choice to disable their browser's javascript, my feeling is that they can live with the results if they so choose

Yes, exactly.

The "awry" is the responsive resizing: colours go wonky and content goes below the footer!
