### ISSUE TITLE
Should internal links be in canonical form? 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5647]
By default, product info pages *do not* include cPath in their canonical form.
However, links from the categories index page *do* include cPath. 

For example, the category 3 index page:
http://localhost:8888/gh_demo_158/index.php?main_page=index&cPath=3

has a link to Die Hard as 

http://localhost:8888/gh_demo_158/index.php?main_page=product_info&cPath=3_10&products_id=12

when you go to this page, the `<head>` content shows:

```
<link rel="canonical" href="http://localhost:8888/gh_demo_158/index.php?main_page=product_info&amp;products_id=12">
```
 
(no cPath).

**Comment by torvista** [comment]
While not having any expertise in this aspect, bearing in mind a product that is linked into many/multiple categories, perhaps it is logical if the canonical link is deliberately "incomplete" as shown here so the category location of a product does not enter into the equation....or it should be included but always be the master category?

In the end this is to not "confuse" spiders, no?

**Comment by lat9** [comment]
I thought that the cPath parameter in a product's link (especially in the case of linked products) is the means by which the product-page's breadcrumbs were formed; otherwise, clicking on a product would always "throw you" into its master category and then you'd need to use the browser's back-button to get back to the category in which you were interested.

**Comment by scottcwilson** [comment]
> In the end this is to not "confuse" spiders, no?

Correct.

> I thought that the cPath parameter in a product's link (especially in the case of linked products) is the means by which the product-page's breadcrumbs were formed ... 

Maybe these should be nofollow links?   Or maybe we should do it differently (perhaps optionally)?  Not sure. 

I'm not positive ANY change is warranted, I just wanted to walk through this and discuss the issues.

**Comment by drbyte** [comment]
It is intentional that the cPath is excluded in the canonical link: that way the canonically-indexed URI is consistent regardless which category the product is linked to. SE spiders prefer it this way.

As for making other links nofollow, that might be overkill. You'd have to be careful that you don't block the spider's ability to actually even find the things being sought.

**Comment by scottcwilson** [comment]
Fair enough.  Thanks for weighing in.  Closing.
