### ISSUE TITLE
Shipping modules wi/Zone restrictions won't show up in Estimator if State not shown as pulldown 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5672]
When

a) Admin > Configuration > Customer Details > State field - Display as pulldown when possible? is set to FALSE
and
b) the zone restriction for a shipping module is set,

that module will not show up on the shipping estimator for non-logged in customers even if they have entered a country and state within the configured zone.

I'm not positive this is worth fixing - it would be a bunch of work for a configuration most people don't use. (It's much better to set Display as pulldown to true).

**Comment by piloujp** [comment]
Well I think I have a fix. Problem is due to different POS variable names for pull down (zone_id) and text field (state).
Without pull down you retrieve state name or code and you need to find zone_id with that.
Here is the code change I made in 'shipping_estimator.php' on line 40 :
From `$state_zone_id = (isset($_POST['zone_id'])) ? (int)$_POST['zone_id'] : $state_zone_id;`
To:
```
	if (ACCOUNT_STATE_DRAW_INITIAL_DROPDOWN === 'true') {
		$state_zone_id = (isset($_POST['zone_id'])) ? (int)$_POST['zone_id'] : $state_zone_id;
	} else {
		if (isset($_POST['zone_country_id']) and isset($_POST['state'])) {
			$state_value_id = $db->Execute("SELECT zone_id FROM " . TABLE_ZONES . " WHERE zone_country_id = '" . (int)$_POST['zone_country_id'] . "' and (zone_name = '" . $_POST['state'] . "' OR zone_code = '" . $_POST['state'] . "') LIMIT 1;");
			$state_zone_id = (isset($state_value_id->fields['zone_id'])) ? (int)$state_value_id->fields['zone_id'] : $state_zone_id;
		}
	}
```
I tested both with or without pull down menu and it works fine.
I seems that the pull down menu was forgotten in different parts of Zen Cart, see #5707.

**Comment by scottcwilson** [comment]
Cool - please PR
