### ISSUE TITLE
debug for $orders_id not set in checkout_success\header_php.php

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5742]
Now and again I get:
```
#0 includes/modules/pages/checkout_success/header_php.php(54): zen_debug_error_handler()
#1 index.php(35): require('...')
--> PHP Warning: Undefined variable $orders_id in includes/modules/pages/checkout_success/header_php.php on line 54.
```

https://github.com/zencart/zencart/blob/9ccb250afda600b06c3446b50b992406f6ae661f/includes/modules/pages/checkout_success/header_php.php#L43-L54

When there is no session order_id, it tries to use the result from the query, which may be not set if there were no previous orders.

So, some clause needs to be in there. Not sure what would be best....

**Comment by lat9** [comment]
That's very weird, as I'd expect to see a PHP Warning on line 49 if there were no previous orders, since there would be no `orders_id` element of the returned query's fields.

**Comment by torvista** [comment]
...just revisited this and yes I do get an error for that initial access on 49..I have this header and page customised so maybe mixed up the line numbers.

**Comment by scottcwilson** [comment]
If you run an order and get to the checkout success page, then walk away for a while so that you get logged out, but try to refresh the page, does this happen?

**Comment by torvista** [comment]
No, there's a redirect in the header when logged out.
And then when logged in again, at that point, there IS a past order.

What I've just done to test this is complete the order, stay on success page without logging out (to passby the redirect), then modify that query, using

> $orders_query = $db->bindVars($orders_query, ':customersID', $_SESSION['customer_id']**+1**, 'integer');

to request orders for a different customer (that has no orders).
It returns null and an error as expected for the assignment
$orders_id = $orders->fields['orders_id'];

**Comment by lat9** [comment]
There are two scenarios I can envision that would result in these logs:
1. An order-less customer logs in/creates an account, so a customers_id is present in the session, and then hand-navigates to the `checkout_success` page.
2. A customer places an order which, for whatever reason doesn't register the order in the `orders` table.

**Comment by drbyte** [comment]
Options:

1. As far as how to handle it, perhaps it would be to just redirect to the Orders History page in the My Account section.
That way you don't have to add a lot of conditional logic to the checkout_success template to explain that something unexplained went wrong.
Although I guess if it's a guest account then that's more complicated.

2. To stay with checkout_success page:
- check whether that `$orders_id` has failed to be retrieved, and if so, the $statuses query needs retrofitting.
- does the template handle an empty $statuses query gracefully? If yes, then defaulting $orders_id to 0 might be fine if the order is not found
- if the cart is not empty, then that probably indicates that checkout failed to complete, probably due to an email confirmation failure or a save-to-database failure, or some other after-order step triggered by notifiers/plugins, which failed before persisting the order to the db.
- in checkout_success header_php, the $order object (used by the template) is instantiated by passing $orders_id: if $orders_id is 0 it'll default to creating an order based on what's in the cart ... which would hopefully be empty, which isn't ideal; the goal is to have an order object that the template doesn't complain about missing properties

The shortest may just to be to explore setting $orders_id to 0 if the db query fails, and see what has to be fixed for the template to not throw errors/logs.
And then deal with whatever external things caused failures when the order couldn't be persisted to the db, so have those things happen more gracefully (preferably persisting before other things can fail).

**Comment by scottcwilson** [comment]
I have never seen this issue, and would vote for approach #1.

**Comment by lat9** [comment]
How about handling the condition in the page's `header_php.php`?  It looks like simply re-arranging those couple of processing bits so that if the `$_SESSION['order_number_created']` is set, that's used.

If not, if a non-guest customer is currently logged in (`zen_is_logged_in() && !zen_in_guest_checkout()`), the processing simply redirects to the customer's previous-orders' page and otherwise just redirects to the site's home page?

Need to see, too, how the `checkout_success` page's product-notifications plays into the mix.

**Comment by lat9** [comment]
Nope, the above's not going to work ... for OPC anyways.  There is a `$_SESSION['order_placed_by_guest']` that's set when a guest has created the order and, when set, OPC's template gives the guest an opportunity to create an account.

The ability to 'retain' the display of the `checkout_success` page is needed in case the guest-customer has supplied a password that's either too short or doesn't match the password-confirmation value.

Still thinking.

**Comment by lat9** [comment]
> Nope, the above's not going to work ... for OPC anyways. There is a `$_SESSION['order_placed_by_guest']` that's set when a guest has created the order and, when set, OPC's template gives the guest an opportunity to create an account.
> 
> The ability to 'retain' the display of the `checkout_success` page is needed in case the guest-customer has supplied a password that's either too short or doesn't match the password-confirmation value.
> 
> Still thinking.

Wrong-o.  That `$_SESSION['order_placed_by_guest']` is the order-number just placed by a guest.  OPC's observer-class, at the start-of-page notification for `checkout_success`, checks to see if it's in guest-checkout with `$_SESSION['order_number_created']` not set and, if so, sets that variable to the 'order_placed_by_guest' value.

The basic logic posted on my thumbs-down above should work.  PR forthcoming.
