### ISSUE TITLE
Question: Pros/Cons of MobileDetect library?

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#575]
Looking for feedback on benefits AND DANGERS/challenges of implementing the popular [MobileDetect](http://mobiledetect.net) library, at least catalog-side.

And also recommendations for implementation which minimizes URL-redirect-with-added-GET-params (which has caused ugly SEO-related problems in sites where I've seen MobileDetect used).

**Comment by bislewl** [comment]
Honestly, from experience I have found the MobileDetect features in some templates to make life more difficult. During Development I have to run emulators to try and recreate the device. I usually see the template using an if/ifelse/ifelse/else. And than it doesn't always work, so I have to track down someone with the same device as the customer has to recreate the problem. Additionally because of the continuous flow of new devices it isn't always accurate.
:-1:

**Comment by jtwebsitedesign** [comment]
Agreed, MobileDetect can cause issues in some cases. I find that most responsive designs work fine with simple CSS @media rules. Is there a particular situation that is requiring more comprehensive mobile detection?

**Comment by scottcwilson** [comment]
You could make it optional and provide the ability to set a mobile template and a desktop template.

**Comment by Spike00** [comment]
I'm not using mobile detect, but I'll probably switch to it. Actually I'm using custom check for just User-Agent.
I make the check in init_templates. And assign convenient value to Session variable. Then in get_template_dir I added a check for an extra dir. This way whatever the template is in use, it can be mobilized just creating a subdir (inside the 'your_template' dir) in which to place mobile version of the files you want to have in your mobile version.
Then I added other things, an array containing the pages for which a mobile version exists,  a function to check if has been requested the mobile version of a page to accomplish two requirements: 
1) beside the template thing, it may be useful to have a check, for example for those files for which override is not available
2) The check contains also a check for cookies used to force desktop version vs mobile.

Not much more.
This way there are no redirects, no different domains, no different urls, but still I may have completely different pages. Another important thing, is that this way i just don't hide useless content with css. I simply remove it from the php, having two big benefits: performance and total customization of the page without compromises

**Comment by IronLady** [comment]
### Pros
1. Better Load Speed

### Cons
1. We have to use conditional statement to achieve different result for different device. With RWD, we can just set the class name and give different style for each viewport
2. We have to "sync" the library. I see that they just build an array of devices and if there are some new devices with different user-agent launched, they need to append it to the array and we have to update the library.

MobileDetect is good for "private" project/store where you maintain it by yourself, I guess amazon and eBay use this approach. But for "public" or default template, I think it's a bad idea

**Comment by wiztechinc** [comment]
Using something that detects user agents gets problematic because of future changes to user agents. I tried it at first but there is no way to test an installation to make sure it all works. Felt like I was driving blind. There has to be a better way.

**Comment by robryanx** [comment]
I currently use it to look for the "_mobile" template directory if it indicates mobile in init_templates.
Makes sense at least in cases where people have 2 separate templates.

**Comment by Spike00** [comment]
I believe that server side detection (which does not rely only on  does not imply that the desktop template must not be RWD. Let's have both the possibilities: if someone does not want or have the budget to manage two different templates, she will go with just one, RWD (just disabling the feature). But who may afford it, can get the benefits of both the solutions: server side detection which load the right template (performance and total customization) and of course the desktop one may as well be responsive, so even if the library is out of sync, the site is ok for everyone.
By the way, after looking at mobiledetect code, I believe it covers much more different (devices/os/browser) than the coverage of css3 media queries by all existings browsers.

**Comment by zcadditions** [comment]
A well designed responsive template won't need the MobileDetect library, it will scale and manipulate the content correctly with simple CSS media queries.

The MobileDetect library in a sense should be used for tablet and mobile optimization. An example of this could be to completely remove a categories multi-level drop-down menu (html, php, css, javascript and/or jquery) from ever loading on a mobile device and replacing it with a mobile friendly, swipe enabled slide menu.

With the fast emerging of new devices, MobileDetect has proven to stay way ahead of other similar scripts.

Just my #2cents

**Comment by wiztechinc** [comment]
I completely agree. I just created a quick responsive template that yes, only sets up mobile as phone size but works without ANY changes to the cart core files or additional site checking. What I did gave me way more control over the desktop version without creating more load time for the mobile. I'm sorry I hadn't done this sooner so that I could have presented something to you much earlier on. I hate the normal responsive sites and nearly anything you see as responsive nowadays is really crappy. I do suggest sitting down and totally reviewing this whole thing before proceeding any further. Just following what's being done everywhere does not benefit a long term thing like zen cart. Let's engage in some forward thinking instead. 

I made one change to the HTML header, added one set of javascript files for image size revision that uses javascript, created a new categories box for use on mobile, pulled the full site out of the main table and used css to create the same thing, used two jquery menus for ezpages links and that categories box for a real mobile menu set. Image handler continues to work. The desktop site can still have three columns as that is the best presentation from a sales point of view. On the mobile the side columns are hidden - not the best solution to that but coupled with image handler it is the best load time effective way. 

Google approves.

**Comment by Spike00** [comment]
I think it's an interesting approach the one from Delia, but why not combine both? The quick responsive template to let desktop go with everything is needed, mobile detection with dedicated template and functionalities for those who want the best possible solution for mobile devices, regarding both functionality and performance and usability. So if MobileDetect should ever not correctly detect a mobile device, the responsive template would be there to serve it.

**Comment by wiztechinc** [comment]
Be glad to provide full access to my "stuff". Having it as a backup is not a bad idea.

**Comment by zcadditions** [comment]
I totally agree that following what's being done everywhere else does not benefit a long term thing like zen cart, the difference is that they are all on the same page but unfortunately all stuck somewhere in the first paragraph. 

Now on top of zen carts "stock" side-boxes which are all "hidden" but still loaded 2 additional side-boxes are be loaded with the same exact information. This is what I mean when I say "stuck somewhere in the first paragraph". There is no obvious way around this for desktop users but mobileDetect is capable of never loading the "stock" side-boxes on tablet and mobile devices, why not utilize that and further optimize the sites load time.

I would love to view your "stuff" delia.

**Comment by wiztechinc** [comment]
deliatest.com/readytogo - This is a template I'm using and no guarantees that every variation show perfectly on mobile. I think I have it all done but can't promise it. Most of what you need is actually there in the html.

**Comment by drbyte** [comment]
@zcadditions how much does your new DIY stuff rely on MobileDetect?  Is it essential, or can it be considered "optional"?

**Comment by zcadditions** [comment]
@drbyte 

The new DIY relies on MobileDetect as much as the current. It was and always has been an added option at the request of the community. The DIY current and new is 100% standalone and functional with/without MobileDetect.
