### ISSUE TITLE
admin: no local copy of jquery-ui

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5762]
working on a local development server, no internet.
admin, banner-manager has many console errors as jquery-ui is not loaded/there is no local fall-back copy.
Related https://github.com/zencart/zencart/issues/5425

**Comment by drbyte** [comment]
Three options:

1. Leave it as-is.

2. Add a fallback. This requires using conditional javascript. However, adding a fallback just creates validation errors because validators see duplicate calls to load it, and tools like google speed-test etc will complain about the conditional javascript wrapped around it, giving lower ratings, which then result in complaints that google is reporting "problems" even though they're false.

3. Always load local, not from CDN. But the only situation when this would be beneficial is offline development, never for a real storeowner. For that you could load your own with your own added extra JS loader script.

I recommend #1: leave as-is.

**Comment by mc12345678** [comment]
I assume leave it as is to mean don't change the default way the package is built. For those working offline locally, go ahead and incorporate a local version of the file as needed. 

I could see the addition of (a dreaded) additional conditional that is incorporated into the template to allow either the routine network call or a local implementation for those software users that don't have their "store" connected to the rest of the internet. Maybe am additional notifier, just a template mod or plug in.
