### ISSUE TITLE
Consolidate replicated references to external dependencies 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5823]
https://docs.zen-cart.com/dev/release_process/dependency_checks/

shows multiple files including jQuery and other dependencies. These references could be consolidated, reducing the number of places that need to be changed when we go to a newer version.

**Comment by neekfenwick** [comment]
Related to the FontAwesome work on PR #5845 I notice the `admin/includes/stylesheet.css` file is mentioned in the Dependencies list as relying on FontAwesome.  It does indeed require `css/font-awesome.min.css` which no longer exists in my PR because I moved the fontawesome files into `admin/includes/fontawesome` (may be a bad idea but it seemed a good idea to replicate the directory structure of the FontAwesome download bundle so I gave it a root dir to live in).  Searching for this `admin/includes/stylesheet.css` only a handful of files link to it (`salemaker_info.php` etc), and they don't seem to use the new `admin_html_head.php` file.  So, it seems `admin/includes/stylesheet.css` is obsolete, these files can be updated to use `admin_html_head.php`, remove the `admin/includes/stylesheet.css` link, and we can delete that file.

**Comment by scottcwilson** [comment]
I will begin work on this as soon as #5845 has been merged.

**Comment by drbyte** [comment]
> These references could be consolidated, reducing the number of places that need to be changed when we go to a newer version

There's not much "fluff" in there. Things are already quite consolidated. Apart from self-hosting the files, which is a different approach, there's not much to be gained. If you add "more" files to "centralize" things it creates more points of failure, resulting in the perception that "this template system is hard to use".

**Comment by scottcwilson** [comment]
My intention was to create a single PHP file in a new folder (say, /depend_inc) to pull in jquery: 

depend_inc/get_jquery.php would contain: 
<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>

Then, the two files 
includes/templates/responsive_classic/common/html_header.php
includes/templates/template_default/common/html_header.php

would use 
require 'depend_inc/get_jquery.php'; 
 
Instead of each specifying a version of jquery that would have to be updated in two places. 

And so forth, for all remotely retrieved dependencies.  

Now you can just look at the depend_inc folder and see all the specific versions being used.

**Comment by neekfenwick** [comment]
Quick comment: I'm not very familiar with these files, but we have e.g. `responsive_classic/jscript/jscript_framework.php` which includes `template_default/jscript/jscript_framework.php` which has a bunch of inline `<script>` blocks.  Thus, the two `html_header.php` files you mention should not themselves `require` anything .. you could put a `require 'jquery_deps.php'` line in `jscript_framework.php` and consolidate jquery version numbers in that one `jquery_deps.php`.  Seems a better place for it than `html_header.php`.  I might be missing something, though :)

**Comment by scottcwilson** [comment]
@neekfenwick the challenge is, html_header.php is a commonly templated file, so changing it directly shows upgraders how to make this change in their own copies more directly.   Were it not for that, I would agree with what you're saying.

@drbyte Do you like this idea or do you prefer keeping as is ?

**Comment by drbyte** [comment]
> @drbyte Do you like this idea or do you prefer keeping as is ?

I'm inclined to leave it as-is.
That said, I'm certainly compassionate to the desire to minimize the chances of "missing" certain things, and the desire to minimize the number of things that need to be reviewed periodically.

(Aside: Not a fan of the mentioned "depend_inc" naming convention, but that's a minor point.)


I think perhaps 2 more important directions to focus would be:

1. When updating said dependencies, be sure that the update is needed. Doesn't need to be bleeding-edge: more important to be stable and widely compatible. Granted, where security-patches are included in an available update then it's probably important to adapt to those as quickly as possible.

2. The option to self-host the front-end assets that are currently hosted on CDN. There's some code in the templates already to take care of this is the appropriately-named assets are present on the filesystem. The downside to self-hosting assets is that 3rd party page-speed evaluators will first complain that they're not on a fast CDN, and then complain that they're larger than needed, and recommend paring them down. Either way works, and if the storeowner is tech-savvy-enough then they can self-host minimized assets easily ... some without changing any template files at all.
Perhaps if doing this for certain kinds of assets is seen as painful, then time spent on minimizing that pain is worth the effort. I see there's another Issue open about page-speed already.

**Comment by scottcwilson** [comment]
Roger that.  Closing.

**Comment by neekfenwick** [comment]
> 1. Granted, where security-patches are included in an available update then it's probably important to adapt to those as quickly as possible.

As a separate issue to the "consolidation" being discussed here, and the page load speed discussed in #5861, this security issue is perhaps more important.  If the header has a hardcoded version number such as:

    <script src="https://code.jquery.com/jquery-3.6.1.min.js"

..and a critical security vulnerability is found in `3.6.1`, would we want store admin be able to modify the version number being used via a `configuration` value, rather than have to self-host, which may be beyond some store admins?  I feel this must have come up before, so apologies if I'm re-treading old ground.

i.e. change to:

    <script src="https://code.jquery.com/jquery-<?php echo JQUERY_VERSION ?>.min.js"

or even:

    <script src="<?php echo JQUERY_SRC ?>"

**Comment by scottcwilson** [comment]
We'd provide instructions on editing the file or provide an emergency patch, as we have done in the past - no need to add this.

**Comment by scottcwilson** [comment]
Build docs have been updated with guidance from Chris. (not required to be on latest version, just be sure we have security patches).
