### ISSUE TITLE
Admin: Categories & Products Display Order intrinsically linked

### ISSUE THREAD

**Issue by simon1066** [zencart/zencart#5897]
**Example**
`admin > catalog > categories/products > a listing of categories` selecting the **fourth** option in the 'Categories/Product Display Order' dropdown sorts the categories by  'Category ID (desc)'

proceed to

`admin > catalog > categories/products > category > a listing of products` the 'Categories/Product Display Order' dropdown defaults to the **fourth** option of 'Products Qty+, Products Name'

and vice versa.

**Expected Behaviour**
Should be able to select different sort order (configuration_value) for both a listing of categories and a listing of products.

**Version**
Zen Cart version: clean install of ZC v1.5.8a

**Comment by torvista** [comment]
>Should be able to select different sort order (configuration_value) for both a listing of categories and a listing of products.
Sounds logical.

Sorting is related to this:https://github.com/zencart/zencart/pull/4965
As you see it, shares the same initial constant, which does not seem logical.

What about a search result where they are mixed?

**Comment by proseLA** [comment]
please see this post and confirm whether it addresses the problem:

https://www.zen-cart.com/showthread.php?229613-category_product_listing-issue&p=1396101#post1396101

feel free to PR if it does.

best.

**Comment by simon1066** [comment]
The code changes in that post relate to the GitHub code post v1.5.8a release. Lines 36-42 from the 1.5.8a release are

```
if (isset($_GET['cID'])) {
  $_GET['cID'] = (int)$_GET['cID'];
}

if (!isset($_SESSION['categories_products_sort_order'])) {
  $_SESSION['categories_products_sort_order'] = CATEGORIES_PRODUCTS_SORT_ORDER;
}
```
On the off chance - adding the `pID` lines of code and making the changes to that and the `cID` code does not solve the issue.

**Comment by torvista** [comment]
I'm looking at this...

**Comment by torvista** [comment]
While reviewing this for Categories
clarification of sorting option 4,5 by status is required

![image](https://github.com/zencart/zencart/assets/4391026/ce33b0c5-e763-475b-ae5b-3c510a4f65a4)

![image](https://github.com/zencart/zencart/assets/4391026/cd7e4de9-6724-424a-9aa4-eea875d5ad40)

The text on the dropdown for 5 implies incorrectly that the sort is by enabled-categories, when in fact 4 and 5 both sort by disabled first, but secondary sort is by 
4 - name +
5 - name -

What is preferable? I would sort by 
4 - disabled
5 - enabled 
and maintain the secondary sort as name ascending.

**Comment by torvista** [comment]
Just to point out the subject of the original post is not a bug, there **is** only one sort option for both products and categories.

Aside of that, a sorting bug has surfaced as a result of examination, but that is unrelated: https://github.com/zencart/zencart/pull/5899

**Comment by proseLA** [comment]
my mistake.  i was working on solving a bug, and i thought this issue which seemed to surface at the same time as on the board was related.

this issue is that the default product sort order is not honored if one has already selected a category sort order.  do i have that correct?  

the reverse is also true; if one selects a product search order, that search order number stays with the session if one now goes to category search.

i have no problem with this behavior.   to me, it seems like a very minor issue.

**Comment by torvista** [comment]
The issue is that there is one session variable that stores the page sort order as selected, whether it be on a category or product listing: ie "4".
The sort order that that number corresponds to, can be seen in the default setting (which is used when the session var is not set/has not been changed):
![image](https://github.com/zencart/zencart/assets/4391026/ce33b0c5-e763-475b-ae5b-3c510a4f65a4)

and what is wanted for Products will not be what is wanted for Categories, depending on the admin work being done.

Personally I almost always want the Categories sorted by name, but the Products listing I change all the time, so I would agree that at least, there be two session variables for sort order, one for products and one for categories. But really the defaults should be split too.

A minor issue, but it's something that improves user experience, makes sense and does not appear to be a major effort to implement.

**Comment by proseLA** [comment]
> i have no problem with this behavior. to me, it seems like a very minor issue.

i do not want to get into another bun fight... especially if no crumpets will be served.

as i have previously stated, i have no problem with current behavior.

**Comment by scottcwilson** [comment]
Thanks guys.  @simon1066 please break the tie. Trying to skinny down the punch list for 2.0.0.
