### ISSUE TITLE
PHP Warning when checking SSL_SESSION_ID that doesn't exist

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#5940]
See [this](https://www.zen-cart.com/showthread.php?229636-Can-anyone-help-me-solve-the-plugin-error-problem&p=1396363#post1396363) Zen Cart forum thread.

Essentially if Configuration :: Sessions :: Check SSL Session ID is set to 'True' (not its default) and the subject `$_SESSION` variable doesn't exist, you'll get a PHP Warning similar to the following (line number from zc158a):
```
#0 /home/.../public_html/site/includes/init_includes/init_sessions.php(125): zen_debug_error_handler()
#1 /home/.../public_html/site/includes/autoload_func.php(40): require_once('/home/g67mwiq1l...')
#2 /home/.../public_html/site/includes/application_top.php(237): require('/home/g67mwiq1l...')
#3 /home/.../public_html/site/index.php(25): require('/home/g67mwiq1l...')
--> PHP Warning: Undefined array key "SSL_SESSION_ID" in /home/.../public_html/site/includes/init_includes/init_sessions.php on line 125.
```

**Comment by drbyte** [comment]
I wonder if we can safely just remove this check altogether.

I think it's possible the logic may be flawed anyway, insomuch as I'm not convinced that checking SSL_SESSION_ID between page visits is accurate, as I think it changes. (One [StackOverflow article makes the same suggestion](https://stackoverflow.com/questions/11065502/get-php-ssl-session-id).)

I'm also pretty sure that Nginx doesn't even set it, so it may only be an Apache thing.

In this era of SSL-everything, and where we no longer have the store jumping into SSL only for checkout pages or account changes (we used to do that because SSL was harder to come by and very expensive and URLs for ssl-protected pages were ugly if you were saving a buck on shared hosting, but that's no longer the case, in fact it's hard to even do such a configuration anymore), I'm inclined to say the attack-vector that this segment of code was intended to insulate against may not even be relevant anymore. 

I suspect most shopowners in the past 5-10 years never turned the setting on anyway.

**Comment by drbyte** [comment]
That said, if we keep that segment of code in core, then I suggest that if the `$_SERVER` array doesn't contain that element, that any checking done by this setting merely be aborted ... because if it's missing then we can't enforce it anyway.
