### ISSUE TITLE
load problem with error logging....

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#5944]
i like to look at logs.  it helps solve problems.

i also like to look at logs correctly time stamped.  unfortunately the following code:

https://github.com/zencart/zencart/blob/bd417ab84933856dcea06cd412373af821cb91bd/includes/extra_configures/enable_error_logging.php#L146-L149

gets loaded before this code:

https://github.com/zencart/zencart/blob/bd417ab84933856dcea06cd412373af821cb91bd/includes/extra_configures/set_time_zone.php#L22-L28

which means i end up looking at logs that look like this:

```
237 Aug 18 16:46 myDEBUG-20230818-234640-944827.log
```
now i am running a version of alma linux that has the timezone set to PDT:

```
[pRose@alma logs]$ date
Fri Aug 18 05:04:26 PM PDT 2023
```

and yet the timestamp on the error log is wrong.  so perhaps i have set the timezone incorrectly on my alma linux box; or something with something else...

but that said, would it not make more sense to set the timezone PRIOR to enabling the error logs which make use of a date time stamp?

**Comment by lat9** [comment]
The problem with the files in the `/extra_configures` directory is that they're loaded _in file system order_ ... not necessarily alphabetically. 

That said, we _could_ make a modification to /includes/application_top.php so that it forces a load of set_time_zone.php prior to its loading of all the /extra_configures files.
