### ISSUE TITLE
Change load-order of extra_configures etc folders?

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#5946]
@lat9 wrote:
> The problem with the files in the /extra_configures directory is that they're loaded in file system order ... not necessarily alphabetically.

With 2.0, is it time to add an alpha-sort to the code that auto-loads files in various filesystem directories?

**Comment by drbyte** [comment]
Ref: #5944

**Comment by lat9** [comment]
That could be _very dangerous_, since Linux-based sites "tend" to load in the order that the files were originally created (at least from what I've seen).  Changing the load-order could have unwanted consequences.

**Comment by lat9** [comment]
Just noting that the directories that are currently **not** loaded in alphabetic order are
- auto_loaders
- extra_configures
- extra_cart_actions

Granted, the files in the `auto_loaders` directory have some modicum of control over the order in which the files that they load are (er) loaded.

It's, IIRC, the `extra_cart_actions` that could have _serious_ unwanted consequences if the load-order was changed.  I'm remembering at least one site that I've done work on that this change would affect.

**Comment by torvista** [comment]
**Un-**intuitive loading of files sounds like a headache to debug...and something that should be prevented/controlled to ensure it's logical and identical on all platforms.

**Comment by lat9** [comment]
Changing to use a predictable load-order is _probably_ OK for the `extra_configures` and `auto_loaders` directories, but as stated above that change could have unwanted  consequences for the `extra_cart_actions`.

**Comment by proseLA** [comment]
i hate debugging load order problems, but...

it makes absolutely no sense to me to define a timezone for use, and not respect that timezone when it comes to labeling error logs.

> That could be _very dangerous_, since Linux-based sites "tend" to load in the order that the files were originally created (at least from what I've seen). Changing the load-order could have unwanted consequences.

let's just talk about the `extra_configures` directory for now.  how is defining a load order going to make it more dangerous than it is right now?

here is a directory listing for a site:
```
drwxr-xr-x.  2 jerome apache  4096 Aug 15 20:54 ./
drwxr-xr-x. 14 jerome apache  4096 Aug 16 06:56 ../
-rw-r--r--.  1 jerome apache   715 Aug 15 19:17 block_account_spammers.php
-rw-r--r--.  1 jerome apache  1297 Aug 15 19:17 bmz_image_handler_conf.php
-rw-r--r--.  1 jerome apache   872 Aug 15 19:17 bmz_io_conf.php
-rw-r--r--.  1 jerome apache  3328 Aug 15 19:17 check_restricted_ips.php
-rw-r--r--.  1 jerome apache 16429 Aug 15 19:17 dev-dBug.php
-rw-r--r--.  1 jerome apache   752 Aug 15 19:17 email_use_8bit.php
-rw-r--r--.  1 jerome apache  7259 Aug 20 07:35 enable_error_logging.php
-rw-r--r--.  1 jerome apache   419 Aug 15 19:17 media_manager.php
-rw-r--r--.  1 jerome apache   806 Aug 15 19:17 patch_clean_ampersands.php
-rw-r--r--.  1 jerome apache   934 Aug 15 19:17 pci_patch_13x_search.php
-rw-r--r--.  1 jerome apache  1718 Aug 15 20:54 prose_fixes.php
-rw-r--r--.  1 jerome apache  2015 Aug 15 19:17 security_patch_v138_20080919.php
-rw-r--r--.  1 jerome apache   864 Aug 15 19:17 security_patch_v154_and_older.php
-rw-r--r--.  1 jerome apache   982 Aug 15 19:17 security_update_20190717.php
-rw-r--r--.  1 jerome apache   806 Aug 15 19:17 set_time_zone.php
```
and here is the load order on a specific server:

```
-------->media_manager.php<---------
-------->check_restricted_ips.php<---------
-------->enable_error_logging.php<---------
-------->email_use_8bit.php<---------
-------->dev-dBug.php<---------
-------->security_update_20190717.php<---------
-------->patch_clean_ampersands.php<---------
-------->block_account_spammers.php<---------
-------->security_patch_v138_20080919.php<---------
-------->security_patch_v154_and_older.php<---------
-------->prose_fixes.php<---------
-------->pci_patch_13x_search.php<---------
-------->bmz_image_handler_conf.php<---------
-------->set_time_zone.php<---------
-------->bmz_io_conf.php<---------
```
any idea how this specific system sorted these files?

doing a little forensic digging suggests to me that this arena is not something we have really explored in the past.  if we set `DEBUG_AUTOLOAD` to true, the resulting output does NOT include the files from that directory.

doing some further digging into chat.openai:

When you use a directory handle in PHP to read the contents of a directory using functions like readdir() or DirectoryIterator, the order in which the files are read is not guaranteed to follow a specific order. The order can vary based on the filesystem and the underlying operating system.

The order of file listing might depend on factors such as:

- Filesystem Implementation: Different filesystems (like ext4, NTFS, FAT32, etc.) might have different ways of organizing directory entries. The order of listing might be affected by how the filesystem maintains its internal data structures.

- Directory Fragmentation: If a directory has a large number of files or has been heavily modified over time, the files might be stored in different parts of the physical disk. This can affect the order in which they are read.

- Operating System: Different operating systems might handle directory listing differently. Some might use a certain order, while others might not impose any specific order.

- File Creation Time: Some filesystems might order files based on their creation time or inode number. However, this is not a universal rule, and it can vary.

As of my knowledge cutoff in September 2021, PHP's directory reading functions do not impose a specific order for listing files in a directory. Therefore, you should not rely on any particular order when processing the files in your code. If you need files to be processed in a specific order, you should sort the file list after reading them from the directory.

----
i suppose this is why apache prefixs config files with a 2 character numeric designation.  so that there can be a _defined load order_ irrespective of the system running the package.

**Comment by scottcwilson** [comment]
I'd vote for making only the changes needed to fix #5944, which are pretty straightforward.  Like @lat9 I am worried about unintended consequences of going further.

**Comment by drbyte** [comment]
But...
isn't "2.0" an ideal time to give people notice about paying attention to something like this and advise them to rename/number the affected files to suit?

We could probably write a simple helper script that displays the order that their server is presenting the files, and give guidance on what things might need attention. 

Then we don't have to babysit this issue for several more years of unpredictability. 

Who knows but maybe many "unexplained" upgrade or server move "bugs" are related to this issue?

@lat9 do you recall which specific extra-cart-actions add on was having troubles?

@thatsoftwareguy do we have many plugins that contain any/many files in these affected directories? ... since it's apparently only a couple directories involved.

**Comment by torvista** [comment]
I don't think anyone would be surprised at major/breaking changes being introduced in a major version change.
In fact the surprise is in the lack of them.

**Comment by lat9** [comment]
> ... @lat9 do you recall which specific extra-cart-actions add on was having troubles? ...

It was a set of 3 extra_cart_actions for a client that  I'd developed, over time, which worked on the client's hosted Linux site (file-system load order, i.e. in order of development) but not on my Windows computer (alphabetic sort-order).

Some of those actions simply checked and reduced the amount added to the cart under specific situations and others did an `add_cart` action.  Since the `add_cart` method finishes with a redirect, it's the first one found that gets handled.

**Comment by drbyte** [comment]
> > ... @lat9 do you recall which specific extra-cart-actions add on was having troubles? ...
> 
> It was a set of 3 extra_cart_actions for a client that I'd developed, over time, which worked on the client's hosted Linux site (file-system load order, i.e. in order of development) but not on my Windows computer (alphabetic sort-order).

I'm assuming that your "fix" for that problem was to rename the files so that even on Windows the necessary load-order was attained?

**Comment by lat9** [comment]
I just gave in to the fact that any testing of changes needed to be done live.

**Comment by drbyte** [comment]
> i suppose this is why apache prefixs config files with a 2 character numeric designation. so that there can be a defined load order irrespective of the system running the package.

I wouldn't be opposed to something similar. I imagine their sort is still alphabetic in order to get the numeric values ordered as intended.

Of course, our autoloader system also uses numeric breakpoints for a similar reason. Different degree of granularity, but also more code-centric instead of easy-drop-in-to-filesystem.

**Comment by proseLA** [comment]
in looking at this further, is perhaps `enable_error_logging` in the wrong place?  this directory is `extra_configures`, and yet that script has a couple of functions, and then relies on a `DateTime` object to define debug log names.  are those really extra configures objects?

perhaps we can move the functions into the functions directory and then add the logging into part of the auto loader process.

with regards to the `extra_cart_actions`, i think sorting the files in that directory without question should get done.  we can give an example in the docs using the same type of file naming/sorting used in apache.  that would certainly prevent the kind of debugging nightmares when moving from a dev server to a live server.  the reading of those action scripts should happen in the same order regardless of the server environment.  unless of course you are using windows and IIS in which case, all bets are off!

**Comment by lat9** [comment]
Actually, on Windows, the files _always_ load in alphabetical order!

**Comment by drbyte** [comment]
> in looking at this further, is perhaps enable_error_logging in the wrong place? this directory is extra_configures, and yet that script has a couple of functions, and then relies on a DateTime object to define debug log names. are those really extra configures objects?

> perhaps we can move the functions into the functions directory and then add the logging into part of the auto loader process.

The whole enable_error_logging script is basically a standalone drop-in thing that's evolved from merely turning on logging, to now being the base of a full error-handling class.
It's probably time to move it to core.  
But then of course have to figure out how to handle things if someone's left that file in the extra_configures dir. Probably keep it as a stub file with just an on/off define setting or something (consistent with its name of "enable_...").

**Comment by drbyte** [comment]
> Actually, on Windows, the files _always_ load in alphabetical order!

And I think it's most intuitive if we do that intentionally for all OS's. And predictable, which is the crux of all frustration when debugging etc.
