### ISSUE TITLE
paypalwpp, admin_notifications: handling of no data incomplete.

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#5954]
Getting debugs from accessing an paypal order that has no data recorded, due to a bug last week.
So, an aberrant situation, but nonetheless in the admin_notification, the possibility of no data being found is partially allowed for:
https://github.com/zencart/zencart/blob/af82b732277dff904f015fb482ee11fdba8cd4f4/includes/modules/payment/paypalwpp.php#L618-L624
But it subsequently heads into the notification file with no further checks:
https://github.com/zencart/zencart/blob/af82b732277dff904f015fb482ee11fdba8cd4f4/includes/modules/payment/paypal/paypalwpp_admin_notification.php#L22-L26
Consequently, errors are triggered when the non-existent fields are accessed from here onwards.
https://github.com/zencart/zencart/blob/af82b732277dff904f015fb482ee11fdba8cd4f4/includes/modules/payment/paypal/paypalwpp_admin_notification.php#L133

**Comment by torvista** [comment]
Already did, assumed it was inadequate at the time as no comment was forthcoming.

**Comment by drbyte** [comment]
When the admin_notification screen was first built, the preference was to "still show" the empty fields. That's why the template gets called even though there's no data. Naturally, nowadays PHP is more chatty about the missing array elements.

If the consensus is now to just skip calling the template at all (or the early-return that Steve used in his PR), that's fine with me.

**Comment by scottcwilson** [comment]
Either way seems fine and if there's a PR ready, please merge.
