### ISSUE TITLE
zc_install: Need to check for minimum MySQL version prior to continuing

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#6002]
As described in [this](https://www.zen-cart.com/showthread.php?229421-1-5-8a-Missing-customer_groups-field-in-DB) Zen Cart bug-report, there have been a couple of sites that have undergone a _successful_ install/upgrade only to find that the `customer_groups` and `customers_to_groups` tables are missing:
```
PHP Fatal error: 1146:Table 'xxx.customer_groups' doesn't exist :: SELECT count(*) as total FROM (SELECT cg.*, count(ctg.customer_id) as customer_count FROM customer_groups cg LEFT JOIN customers_to_groups ctg USING (group_id) GROUP BY cg.group_id ORDER BY group_name, group_id) countresults ==> (as called by) /xxxxxxxxxxxxx/includes/classes/split_page_results.php on line 220 <== in /includes/classes/db/mysql/query_factory.php on line 667.
```

Shouldn't the zc_install process be checking for a minimum MySQL/MariaDB version before proceeding with the install/upgrade to prevent these issues?  This issue, for instance, was reported for a site running MySQL 5.5.68-MariaDB .

**Comment by scottcwilson** [comment]
I'm guessing it would be hard to verify, which is why no one has done it yet.

**Comment by drbyte** [comment]
The systemChecks.yml would be the place to register it, and then add the checking logic in the systemChecks class.

It's admittedly harder to check MySQL because it could be MariaDB instead, and while they're quite similar they've got tons of differences.

**Comment by lat9** [comment]
Understood, @drbyte, it's just that we've had a couple of upgrade fails due to _silent fails_ (albeit logged) that lead to post-install/upgrade **hard-fails** as described in that forum support-thread.

**Comment by brittainmark** [comment]
We have specified minimum DB version
Zen Cart v1.5.8 requires MySQL 5.7.8+ or MariaDB 10.2.7+
This could be checked in YML.
A MariaDB returns a version of the form N.N.N-MariaDB.....
Could use this to determine if it is a MariaDB then check the appropriate version MySQL or MariaDB.

Would have to create a new function in class.systemChecker.php 
I'll give it a go if you like.

**Comment by drbyte** [comment]
Yes, go ahead!

I recall that we used to do a MySQL version check in zc_install a long time ago, but I think it got removed because if there's no database running or not one that can be found/probed then it crashed hard. 
Like, if the config's default db-host address isn't reachable via our usual queryFactory attempt to connect in order for it to respond with a version, then it crashed hard. And, even if could bypass the hard crash, there'd be NO version detected ... which then of course can't be enforced.
That would mean that then you'd have to actually go through the db-setup step of zc_install as if the db was a supported version, and then at some point after that you'd have to give them the bad news.

I don't really want to make it so that queryFactory "always" checks the version upon every connection, because that would not be performant in high-traffic use.

But, now that v200's queryFactory has some failover built in if "server has gone away" or "cannot connect", perhaps there's a way to leverage that during zc_install to aid in this agenda.

I suppose another option would just be to fail zc_install hard on "cannot connect", treating it as though it's an unsupported version. And then in the error-message text tell them that if they manually set/correct/fix the DB_HOST setting in their configure.php file and try zc_install again, they might get better results...
