### ISSUE TITLE
PHP Fatal error:  Uncaught IntlException: datefmt_create: invalid locale: U_ILLEGAL_ARGUMENT_ERROR

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6010]
EDIT: Affects PHP 8.1.25 and 8.2.12 and 8.3-RC3/RC4/RC5+

---

Windows php 8.3.0 RC3/4 (RC2 is ok)

Here is admin login:

[11-Oct-2023 11:20:00 UTC] PHP Fatal error:  Uncaught IntlException: datefmt_create: invalid locale: U_ILLEGAL_ARGUMENT_ERROR in D:\GitHub\zencart\includes\classes\zcDate.php:87
Stack trace:
#0 D:\GitHub\zencart\includes\classes\zcDate.php(87): IntlDateFormatter->__construct('C', 3, -1)
#1 D:\GitHub\zencart\includes\classes\zcDate.php(39): zcDate->initializeConversionArrays()
#2 D:\GitHub\zencart\includes\autoload_func.php(47): zcDate->__construct()
#3 D:\GitHub\zencart\admin\includes\application_top.php(42): require('D:\\GitHub\\zenca...')
#4 D:\GitHub\zencart\admin\home.php(9): require('D:\\GitHub\\zenca...')
#5 D:\GitHub\zencart\admin\index.php(11): require('D:\\GitHub\\zenca...')
#6 {main}
  thrown in D:\GitHub\zencart\includes\classes\zcDate.php on line 87

**Comment by zcwilt** [comment]
k. I might add a non breaking test of 8.3 to our test suite

However running current tests locally, I'm seeing  a lot of deprecation errors, which probably need addressing as well

**Comment by proseLA** [comment]
first off, nice to see you torvista.

2nd off, is this issue not system dependent?  for example, one could look at available locales with:

```
print_r(IntlCalendar::getAvailableLocales());
```

i suppose we could put this into an array, and then check the `LC_TIME` constant to see it is in the array.  

unless i am missing something.

**Comment by torvista** [comment]
Thanks for the comment.

Since you've asked, FYI, Windows 11:
`Array ( [0] => af [1] => af_NA [2] => af_ZA [3] => agq [4] => agq_CM [5] => ak [6] => ak_GH [7] => am [8] => am_ET [9] => ar [10] => ar_001 [11] => ar_AE [12] => ar_BH [13] => ar_DJ [14] => ar_DZ [15] => ar_EG [16] => ar_EH [17] => ar_ER [18] => ar_IL [19] => ar_IQ [20] => ar_JO [21] => ar_KM [22] => ar_KW [23] => ar_LB [24] => ar_LY [25] => ar_MA [26] => ar_MR [27] => ar_OM [28] => ar_PS [29] => ar_QA [30] => ar_SA [31] => ar_SD [32] => ar_SO [33] => ar_SS [34] => ar_SY [35] => ar_TD [36] => ar_TN [37] => ar_YE [38] => as [39] => as_IN [40] => asa [41] => asa_TZ [42] => ast [43] => ast_ES [44] => az [45] => az_Cyrl [46] => az_Cyrl_AZ [47] => az_Latn [48] => az_Latn_AZ [49] => bas [50] => bas_CM [51] => be [52] => be_BY [53] => bem [54] => bem_ZM [55] => bez [56] => bez_TZ [57] => bg [58] => bg_BG [59] => bgc [60] => bgc_IN [61] => bho [62] => bho_IN [63] => bm [64] => bm_ML [65] => bn [66] => bn_BD [67] => bn_IN [68] => bo [69] => bo_CN [70] => bo_IN [71] => br [72] => br_FR [73] => brx [74] => brx_IN [75] => bs [76] => bs_Cyrl [77] => bs_Cyrl_BA [78] => bs_Latn [79] => bs_Latn_BA [80] => ca [81] => ca_AD [82] => ca_ES [83] => ca_FR [84] => ca_IT [85] => ccp [86] => ccp_BD [87] => ccp_IN [88] => ce [89] => ce_RU [90] => ceb [91] => ceb_PH [92] => cgg [93] => cgg_UG [94] => chr [95] => chr_US [96] => ckb [97] => ckb_IQ [98] => ckb_IR [99] => cs [100] => cs_CZ [101] => cv [102] => cv_RU [103] => cy [104] => cy_GB [105] => da [106] => da_DK [107] => da_GL [108] => dav [109] => dav_KE [110] => de [111] => de_AT [112] => de_BE [113] => de_CH [114] => de_DE [115] => de_IT [116] => de_LI [117] => de_LU [118] => dje [119] => dje_NE [120] => doi [121] => doi_IN [122] => dsb [123] => dsb_DE [124] => dua [125] => dua_CM [126] => dyo [127] => dyo_SN [128] => dz [129] => dz_BT [130] => ebu [131] => ebu_KE [132] => ee [133] => ee_GH [134] => ee_TG [135] => el [136] => el_CY [137] => el_GR [138] => en [139] => en_001 [140] => en_150 [141] => en_AE [142] => en_AG [143] => en_AI [144] => en_AS [145] => en_AT [146] => en_AU [147] => en_BB [148] => en_BE [149] => en_BI [150] => en_BM [151] => en_BS [152] => en_BW [153] => en_BZ [154] => en_CA [155] => en_CC [156] => en_CH [157] => en_CK [158] => en_CM [159] => en_CX [160] => en_CY [161] => en_DE [162] => en_DG [163] => en_DK [164] => en_DM [165] => en_ER [166] => en_FI [167] => en_FJ [168] => en_FK [169] => en_FM [170] => en_GB [171] => en_GD [172] => en_GG [173] => en_GH [174] => en_GI [175] => en_GM [176] => en_GU [177] => en_GY [178] => en_HK [179] => en_IE [180] => en_IL [181] => en_IM [182] => en_IN [183] => en_IO [184] => en_JE [185] => en_JM [186] => en_KE [187] => en_KI [188] => en_KN [189] => en_KY [190] => en_LC [191] => en_LR [192] => en_LS [193] => en_MG [194] => en_MH [195] => en_MO [196] => en_MP [197] => en_MS [198] => en_MT [199] => en_MU [200] => en_MV [201] => en_MW [202] => en_MY [203] => en_NA [204] => en_NF [205] => en_NG [206] => en_NL [207] => en_NR [208] => en_NU [209] => en_NZ [210] => en_PG [211] => en_PH [212] => en_PK [213] => en_PN [214] => en_PR [215] => en_PW [216] => en_RW [217] => en_SB [218] => en_SC [219] => en_SD [220] => en_SE [221] => en_SG [222] => en_SH [223] => en_SI [224] => en_SL [225] => en_SS [226] => en_SX [227] => en_SZ [228] => en_TC [229] => en_TK [230] => en_TO [231] => en_TT [232] => en_TV [233] => en_TZ [234] => en_UG [235] => en_UM [236] => en_US [237] => en_US_POSIX [238] => en_VC [239] => en_VG [240] => en_VI [241] => en_VU [242] => en_WS [243] => en_ZA [244] => en_ZM [245] => en_ZW [246] => eo [247] => eo_001 [248] => es [249] => es_419 [250] => es_AR [251] => es_BO [252] => es_BR [253] => es_BZ [254] => es_CL [255] => es_CO [256] => es_CR [257] => es_CU [258] => es_DO [259] => es_EA [260] => es_EC [261] => es_ES [262] => es_GQ [263] => es_GT [264] => es_HN [265] => es_IC [266] => es_MX [267] => es_NI [268] => es_PA [269] => es_PE [270] => es_PH [271] => es_PR [272] => es_PY [273] => es_SV [274] => es_US [275] => es_UY [276] => es_VE [277] => et [278] => et_EE [279] => eu [280] => eu_ES [281] => ewo [282] => ewo_CM [283] => fa [284] => fa_AF [285] => fa_IR [286] => ff [287] => ff_Adlm [288] => ff_Adlm_BF [289] => ff_Adlm_CM [290] => ff_Adlm_GH [291] => ff_Adlm_GM [292] => ff_Adlm_GN [293] => ff_Adlm_GW [294] => ff_Adlm_LR [295] => ff_Adlm_MR [296] => ff_Adlm_NE [297] => ff_Adlm_NG [298] => ff_Adlm_SL [299] => ff_Adlm_SN [300] => ff_Latn [301] => ff_Latn_BF [302] => ff_Latn_CM [303] => ff_Latn_GH [304] => ff_Latn_GM [305] => ff_Latn_GN [306] => ff_Latn_GW [307] => ff_Latn_LR [308] => ff_Latn_MR [309] => ff_Latn_NE [310] => ff_Latn_NG [311] => ff_Latn_SL [312] => ff_Latn_SN [313] => fi [314] => fi_FI [315] => fil [316] => fil_PH [317] => fo [318] => fo_DK [319] => fo_FO [320] => fr [321] => fr_BE [322] => fr_BF [323] => fr_BI [324] => fr_BJ [325] => fr_BL [326] => fr_CA [327] => fr_CD [328] => fr_CF [329] => fr_CG [330] => fr_CH [331] => fr_CI [332] => fr_CM [333] => fr_DJ [334] => fr_DZ [335] => fr_FR [336] => fr_GA [337] => fr_GF [338] => fr_GN [339] => fr_GP [340] => fr_GQ [341] => fr_HT [342] => fr_KM [343] => fr_LU [344] => fr_MA [345] => fr_MC [346] => fr_MF [347] => fr_MG [348] => fr_ML [349] => fr_MQ [350] => fr_MR [351] => fr_MU [352] => fr_NC [353] => fr_NE [354] => fr_PF [355] => fr_PM [356] => fr_RE [357] => fr_RW [358] => fr_SC [359] => fr_SN [360] => fr_SY [361] => fr_TD [362] => fr_TG [363] => fr_TN [364] => fr_VU [365] => fr_WF [366] => fr_YT [367] => fur [368] => fur_IT [369] => fy [370] => fy_NL [371] => ga [372] => ga_GB [373] => ga_IE [374] => gd [375] => gd_GB [376] => gl [377] => gl_ES [378] => gsw [379] => gsw_CH [380] => gsw_FR [381] => gsw_LI [382] => gu [383] => gu_IN [384] => guz [385] => guz_KE [386] => gv [387] => gv_IM [388] => ha [389] => ha_GH [390] => ha_NE [391] => ha_NG [392] => haw [393] => haw_US [394] => he [395] => he_IL [396] => hi [397] => hi_IN [398] => hi_Latn [399] => hi_Latn_IN [400] => hr [401] => hr_BA [402] => hr_HR [403] => hsb [404] => hsb_DE [405] => hu [406] => hu_HU [407] => hy [408] => hy_AM [409] => ia [410] => ia_001 [411] => id [412] => id_ID [413] => ig [414] => ig_NG [415] => ii [416] => ii_CN [417] => is [418] => is_IS [419] => it [420] => it_CH [421] => it_IT [422] => it_SM [423] => it_VA [424] => ja [425] => ja_JP [426] => jgo [427] => jgo_CM [428] => jmc [429] => jmc_TZ [430] => jv [431] => jv_ID [432] => ka [433] => ka_GE [434] => kab [435] => kab_DZ [436] => kam [437] => kam_KE [438] => kde [439] => kde_TZ [440] => kea [441] => kea_CV [442] => kgp [443] => kgp_BR [444] => khq [445] => khq_ML [446] => ki [447] => ki_KE [448] => kk [449] => kk_KZ [450] => kkj [451] => kkj_CM [452] => kl [453] => kl_GL [454] => kln [455] => kln_KE [456] => km [457] => km_KH [458] => kn [459] => kn_IN [460] => ko [461] => ko_KP [462] => ko_KR [463] => kok [464] => kok_IN [465] => ks [466] => ks_Arab [467] => ks_Arab_IN [468] => ks_Deva [469] => ks_Deva_IN [470] => ksb [471] => ksb_TZ [472] => ksf [473] => ksf_CM [474] => ksh [475] => ksh_DE [476] => ku [477] => ku_TR [478] => kw [479] => kw_GB [480] => ky [481] => ky_KG [482] => lag [483] => lag_TZ [484] => lb [485] => lb_LU [486] => lg [487] => lg_UG [488] => lkt [489] => lkt_US [490] => ln [491] => ln_AO [492] => ln_CD [493] => ln_CF [494] => ln_CG [495] => lo [496] => lo_LA [497] => lrc [498] => lrc_IQ [499] => lrc_IR [500] => lt [501] => lt_LT [502] => lu [503] => lu_CD [504] => luo [505] => luo_KE [506] => luy [507] => luy_KE [508] => lv [509] => lv_LV [510] => mai [511] => mai_IN [512] => mas [513] => mas_KE [514] => mas_TZ [515] => mer [516] => mer_KE [517] => mfe [518] => mfe_MU [519] => mg [520] => mg_MG [521] => mgh [522] => mgh_MZ [523] => mgo [524] => mgo_CM [525] => mi [526] => mi_NZ [527] => mk [528] => mk_MK [529] => ml [530] => ml_IN [531] => mn [532] => mn_MN [533] => mni [534] => mni_Beng [535] => mni_Beng_IN [536] => mr [537] => mr_IN [538] => ms [539] => ms_BN [540] => ms_ID [541] => ms_MY [542] => ms_SG [543] => mt [544] => mt_MT [545] => mua [546] => mua_CM [547] => my [548] => my_MM [549] => mzn [550] => mzn_IR [551] => naq [552] => naq_NA [553] => nb [554] => nb_NO [555] => nb_SJ [556] => nd [557] => nd_ZW [558] => ne [559] => ne_IN [560] => ne_NP [561] => nl [562] => nl_AW [563] => nl_BE [564] => nl_BQ [565] => nl_CW [566] => nl_NL [567] => nl_SR [568] => nl_SX [569] => nmg [570] => nmg_CM [571] => nn [572] => nn_NO [573] => nnh [574] => nnh_CM [575] => no [576] => nus [577] => nus_SS [578] => nyn [579] => nyn_UG [580] => om [581] => om_ET [582] => om_KE [583] => or [584] => or_IN [585] => os [586] => os_GE [587] => os_RU [588] => pa [589] => pa_Arab [590] => pa_Arab_PK [591] => pa_Guru [592] => pa_Guru_IN [593] => pcm [594] => pcm_NG [595] => pl [596] => pl_PL [597] => ps [598] => ps_AF [599] => ps_PK [600] => pt [601] => pt_AO [602] => pt_BR [603] => pt_CH [604] => pt_CV [605] => pt_GQ [606] => pt_GW [607] => pt_LU [608] => pt_MO [609] => pt_MZ [610] => pt_PT [611] => pt_ST [612] => pt_TL [613] => qu [614] => qu_BO [615] => qu_EC [616] => qu_PE [617] => raj [618] => raj_IN [619] => rm [620] => rm_CH [621] => rn [622] => rn_BI [623] => ro [624] => ro_MD [625] => ro_RO [626] => rof [627] => rof_TZ [628] => ru [629] => ru_BY [630] => ru_KG [631] => ru_KZ [632] => ru_MD [633] => ru_RU [634] => ru_UA [635] => rw [636] => rw_RW [637] => rwk [638] => rwk_TZ [639] => sa [640] => sa_IN [641] => sah [642] => sah_RU [643] => saq [644] => saq_KE [645] => sat [646] => sat_Olck [647] => sat_Olck_IN [648] => sbp [649] => sbp_TZ [650] => sc [651] => sc_IT [652] => sd [653] => sd_Arab [654] => sd_Arab_PK [655] => sd_Deva [656] => sd_Deva_IN [657] => se [658] => se_FI [659] => se_NO [660] => se_SE [661] => seh [662] => seh_MZ [663] => ses [664] => ses_ML [665] => sg [666] => sg_CF [667] => shi [668] => shi_Latn [669] => shi_Latn_MA [670] => shi_Tfng [671] => shi_Tfng_MA [672] => si [673] => si_LK [674] => sk [675] => sk_SK [676] => sl [677] => sl_SI [678] => smn [679] => smn_FI [680] => sn [681] => sn_ZW [682] => so [683] => so_DJ [684] => so_ET [685] => so_KE [686] => so_SO [687] => sq [688] => sq_AL [689] => sq_MK [690] => sq_XK [691] => sr [692] => sr_Cyrl [693] => sr_Cyrl_BA [694] => sr_Cyrl_ME [695] => sr_Cyrl_RS [696] => sr_Cyrl_XK [697] => sr_Latn [698] => sr_Latn_BA [699] => sr_Latn_ME [700] => sr_Latn_RS [701] => sr_Latn_XK [702] => su [703] => su_Latn [704] => su_Latn_ID [705] => sv [706] => sv_AX [707] => sv_FI [708] => sv_SE [709] => sw [710] => sw_CD [711] => sw_KE [712] => sw_TZ [713] => sw_UG [714] => ta [715] => ta_IN [716] => ta_LK [717] => ta_MY [718] => ta_SG [719] => te [720] => te_IN [721] => teo [722] => teo_KE [723] => teo_UG [724] => tg [725] => tg_TJ [726] => th [727] => th_TH [728] => ti [729] => ti_ER [730] => ti_ET [731] => tk [732] => tk_TM [733] => to [734] => to_TO [735] => tr [736] => tr_CY [737] => tr_TR [738] => tt [739] => tt_RU [740] => twq [741] => twq_NE [742] => tzm [743] => tzm_MA [744] => ug [745] => ug_CN [746] => uk [747] => uk_UA [748] => ur [749] => ur_IN [750] => ur_PK [751] => uz [752] => uz_Arab [753] => uz_Arab_AF [754] => uz_Cyrl [755] => uz_Cyrl_UZ [756] => uz_Latn [757] => uz_Latn_UZ [758] => vai [759] => vai_Latn [760] => vai_Latn_LR [761] => vai_Vaii [762] => vai_Vaii_LR [763] => vi [764] => vi_VN [765] => vun [766] => vun_TZ [767] => wae [768] => wae_CH [769] => wo [770] => wo_SN [771] => xh [772] => xh_ZA [773] => xog [774] => xog_UG [775] => yav [776] => yav_CM [777] => yi [778] => yi_001 [779] => yo [780] => yo_BJ [781] => yo_NG [782] => yrl [783] => yrl_BR [784] => yrl_CO [785] => yrl_VE [786] => yue [787] => yue_Hans [788] => yue_Hans_CN [789] => yue_Hant [790] => yue_Hant_HK [791] => zgh [792] => zgh_MA [793] => zh [794] => zh_Hans [795] => zh_Hans_CN [796] => zh_Hans_HK [797] => zh_Hans_MO [798] => zh_Hans_SG [799] => zh_Hant [800] => zh_Hant_HK [801] => zh_Hant_MO [802] => zh_Hant_TW [803] => zu [804] => zu_ZA ) `

**Comment by neekfenwick** [comment]
FYI Not PHP 8.3 related, but I've been working on PHP 8.1 and my Fedora dev system updated to `PHP Version 8.1.25` today and I'm seeing this same error thrown.

https://php.watch/versions/8.1/releases/8.1.25 indicates "Fixed bug [GH-12282](https://github.com/php/php-src/issues/12282) (IntlDateFormatter::construct should throw an exception on an invalid locale)." 

Line 81 in `zcDate.php`: `$this->locale = setlocale(LC_TIME, 0);` is returning the string `C` for my current locale, which is then not accepted in the `locale` first argument to `IntlDateFormatter` constructor.

A correct value to pass would probably be `en` or similar, but I'm too busy to spend time debugging so I've just hacked the zcDate class to pass `null` instead of the return value from `setlocale()`, i.e.:

```
            $format = new IntlDateFormatter(
                null, //$this->locale,
                IntlDateFormatter::SHORT,
                IntlDateFormatter::NONE
            );
            $date_short = $format->getPattern();

            $format = new IntlDateFormatter(
                null, //$this->locale,
                IntlDateFormatter::NONE,
                IntlDateFormatter::SHORT
            );
```

**Comment by neekfenwick** [comment]
Does the locale need setting very early in the autoload sequence, before zcDate is instantiated and certainly not as late as `lang.english.php` where it is set now?

What do you guys find your system locale is when the webserver starts (and thus, early in the ZC lifecycle when `zcDate` is instantiated)?  I'm seeing "C", which is causing the exception.

It seems our production server isn't running into this problem because it's still on PHP `8.1.24` but from the changelog given above this will break as soon as it updates to 8.1.25.  I know, I'm an early adopter of zc158, earlier versions don't use `zcDate`.  I'm trying to nail down the problem, but having trouble making my dev system default to anything other than locale 'C' when the webserver (apache2 on Fedora) starts.

Note on autoload: On admin and catalog side, zcDate is instantiated in `config.core.php` at breakpoint 0 (autoType 'class' which instantiates the object in `autoload_func.php`), where it fails because of the `C` locale being returned from `setlocale(LC_TIME, 0)` (see post above).

Later, `autoload_func` breakpoint `init_languages.php` (on catalog side, `init_templates.php`) causes first time load of `lang.english.php` which contains code that sets the locale from the default (`C` for me) to `en_US` after which zcDate can instantiate safely.  It looks like the `LC_TIME` locale needs to be set before the `zcDate` breakpoint instantiates the class at breakpoint 0.

`admin/includes/languages/lang.english.php`:
`@setlocale(LC_TIME, ['en_US', 'en_US.utf8', 'en', 'English_United States.1252']);`

**Comment by drbyte** [comment]
I believe `'C'` means "unconfigured by the host we're running on".
I'd expect that if it can be configured in `php.ini` then it might not default to `'C'` ... but we've always tried to avoid asking people to tinker with `php.ini` because there's limited consistency as to what they're allowed to do or where to find it or how to do it, depending on the hosting environment.

The `zcDate` class gets loaded and instantiated by the config autoloader system, defined at breakpoints 0 and 5 of the admin `config.core.php` array.
Thus, you can probably copy your `setlocale()` command from the language file into any of:
- `/includes/extra_configures/set_time_zone.php` (since it's loaded via the Admin's extra_configures)
- `admin/includes/extra_configures/SOMETHING.php`
- `admin/includes/configure.php`

The order I suggested above is the order I'd suggest testing it in. But the application loads in the reverse order (eg: the configure.php comes first, then the extra-configures dir, which happens to call the non-admin timezone file).

**Comment by torvista** [comment]
> Line 81 in zcDate.php: $this->locale = setlocale(LC_TIME, 0); is returning the string C for my current locale,

Ditto on local server Windows 11.

**Comment by torvista** [comment]
A value in /includes/extra_configures/set_time_zone.php permitted a partial page-load, it further failed due to a invalid locale being in the locale array in the language files, since I had various possible values for both Windows and Unix.
I once did this tool for testing these things, which was useful in this case:
https://github.com/torvista/Check_Server_Locales
 
Once the offending locale was removed, my dev site is now ok through to php8.3.0RC5 now.

I suppose it is a safe bet that 'en' is always present on every server so adding
@setlocale(LC_TIME, 'en');
to set_time_zone would solve this?

**Comment by neekfenwick** [comment]
> I believe `'C'` means "unconfigured by the host we're running on". I'd expect that if it can be configured in `php.ini` then it might not default to `'C'` ... but we've always tried to avoid asking people to tinker with `php.ini` because there's limited consistency as to what they're allowed to do or where to find it or how to do it, depending on the hosting environment.

Thanks @drbyte - I agree, many will not have host access.  Since ZC will use `setlocale()` to ensure it's set, I see why the code is in `lang.english.php`; it's only when the language strings are loaded that the ZC logic has decided which locale the system should be using.  Moving the setting of locale to earlier in the init cycle doesn't make sense (as I may have suggested earlier).  If this decision is only made then, it seems to me that `zcDate` should not be instantiated earlier than the language strings are.  This implies we should move it from breakpoint 0 to later in the init cycle.

Putting the `setlocale()` call in other files as you suggest seems wrong, since it's tied tightly into the choice of which language and locale is to be used, see next para.

I'm rather new to the sequence, but I see that `init_languages` is called just before `init_templates` in the init cycle, and `init_languages`, given a fresh session where `$_SESSION['language']` is unset, chooses `DEFAULT_LANGUAGE` as the language, which is then used to decide which templates, and thus lang strings, are loaded in `init_templates`.  So, I would propose moving the `zcDate` breakpoints in `config.core` to just after `init_templates`, e.g. a quick hack:

```
$autoLoadConfig[110][] = array('autoType'=>'init_script',
                                'loadFile'=> 'init_languages.php');
$autoLoadConfig[110][] = array('autoType'=>'init_script',
                                'loadFile'=> 'init_templates.php');

$autoLoadConfig[111][] = [
  'autoType' => 'class',
  'loadFile' => 'zcDate.php'
];
$autoLoadConfig[112][] = [
  'autoType' => 'classInstantiate',
  'className' => 'zcDate',
  'objectName' => 'zcDate'
];
```
Obviously this would cause trouble if any addons introduce breakpoint actions before 110 that require `$zcDate` to be instantiated.

Thoughts?

**Comment by neekfenwick** [comment]
> I suppose it is a safe bet that 'en' is always present on every server so adding @setlocale(LC_TIME, 'en'); to set_time_zone would solve this?

Hey :) I'm not sure how to reply "inline" to your comment on GitHub, but see my reply to Chris above.  While it may work, I'd say locale is separate to time zone, and there's a cleaner way to solve the `setlocale()` sequencing problem.  Part of my thinking is that the language preference can be specified by the client (e.g. browser requesting the page) so hardcoding defaults is "bad".  `init_languages.php` allows a `$_GET['language']` to be passed in, which ought to be honoured above any decisions ZC might make about what language (and thus, locale) should be used, so in a perfect world if `$_GET['language'] == 'es'` then at no point should ZC init anything with `en`.

**Comment by drbyte** [comment]
FYI: For background, including various design decisions considered: `zcDate` was added via https://github.com/zencart/zencart/pull/4771 and heavily discussed in https://github.com/zencart/zencart/issues/4756

**Comment by neekfenwick** [comment]
> FYI: For background, including various design decisions considered: `zcDate` was added via #4771 and heavily discussed in #4756

Thank you, I had not seen that, but have now read through it.  I've no issue with all the discussion about the need for `zcDate` and the formatting conversation, all seems sane.  It seems @lat9 proposed putting the `zcDate` instantiation at breakpoint 5 at https://github.com/zencart/zencart/issues/4756#issuecomment-1116335826 and it wasn't really challenged.  @lat9 could you consider this thread please, and my suggestion to move the instantiation from breakpoint 5 to somewhere after `init_templates` (catalog side) and `init_languages` (admin side)?

Your discussion of `setlocale(LC_TIME, 0)` being poorly documented is noted, but the issue here is that if `zcDate` is instantiated at breakpoint 5 then it is constructed before ZC has had a chance to try to set the locale, and later in the init cycle the locale is set by the language files.  I see no reason why we would need to instantiate it so early.  In the cases noted above, the initial instantiation using current system default is getting locale `C` which then causes the `IntlDateFormatter()` ctor to throw.

As it happens, `$zcDate` is re-initialised from `counter.php`, the first code to try to use `$zcDate->output`, which detects a change in locale and re-initialises itself at https://github.com/zencart/zencart/blob/ec777f0bbf75991395014d784c30fd048b68f905/includes/classes/zcDate.php#L170 .. this automatic reinitialisation isn't necessary if we simply instantiate it after the locale has been determined.

**Comment by drbyte** [comment]
@neekfenwick I was thinking along the same lines of moving from breakpoint `5` to something higher. 
Thanks for doing the legwork of identifying the language dependency breakpoints.
I largely agree that the breakpoints you identify are ideal.
One risk that must be considered is that `functions_dates.php` (which contains functions that call zcDate) and `functions_files.php` are loaded via `init_general_funcs.php` which loads several breakpoints earlier than the `init_languages.php`. Between those two files there are three functions that use the zcDate object, but none of them are currently used in any bootstrapping processes of the autoloader, so they're not posing any problem.

Another approach I was contemplating was simply adding a public method to the zcDate class to re-initialize it (re-run the constructor).

But ... apart from having no "default" locale defined sooner (and I don't care whether we do that in configure.php, with a fallback to `en_US` if not found in configure.php), if we simply (re-)instantiate the zcDate class object (again?) after the language init is completed (which does lookups to detect any preferences via `_GET` or browser-specified langs), would seem sensible, wouldn't it?

**Comment by drbyte** [comment]
Or ... maybe the PHP team will change things yet. 

Someone posted more about `'C'` being equiv to `root` which is equiv to `en_US_POSIX`, which may be determinable via `Locale::canonicalize()` with `Locale::canonicalize(Locale::getDefault());`
... which might be interesting to explore: Whether they incorporate a fallback into PHP core, or we just do another fallback lookup in our initialization of the class.

Or ... just assume `en_US` until overridden one way or another.

**Comment by drbyte** [comment]
I agree that `set_time_zone.php` isn't the best place for setting a language-related `locale`; however it **is** a spot where we can reasonably expect a storeowner to make an edit.
But IMO `configure.php` would be even more logical.

**Comment by drbyte** [comment]
For safety we should probably consider setting a default locale in `zc_install` as well. Granted, at this point I don't think we're doing anything that triggers `IntlDateFormatter` in zc_install.

**Comment by neekfenwick** [comment]
> @neekfenwick I was thinking along the same lines of moving from breakpoint `5` to something higher. Thanks for doing the legwork of identifying the language dependency breakpoints. I largely agree that the breakpoints you identify are ideal. One risk that must be considered is that `functions_dates.php` (which contains functions that call zcDate) and `functions_files.php` are loaded via `init_general_funcs.php` which loads several breakpoints earlier than the `init_languages.php`. Between those two files there are three functions that use the zcDate object, but none of them are currently used in any bootstrapping processes of the autoloader, so they're not posing any problem.
> 
> Another approach I was contemplating was simply adding a public method to the zcDate class to re-initialize it (re-run the constructor).
> 
> But ... apart from having no "default" locale defined sooner (and I don't care whether we do that in configure.php, with a fallback to `en_US` if not found in configure.php), if we simply (re-)instantiate the zcDate class object (again?) after the language init is completed (which does lookups to detect any preferences via `_GET` or browser-specified langs), would seem sensible, wouldn't it?

Hmm good point.  It would be nice to init the locale once, and instantiate `$zcDate` once, and not have a point in time when the locale changes (as you said, re-initialize it, which is done automatically when it detects change in the current locale as in my comment above), but at least if we init it to a safe default, as @torvista suggested above, somewhere like `extra_configures` which is run before the init system, then it's safe to instantiate `$zcDate` at its current breakpoint of 5 and have the language system re-set the locale and `$zcDate` re-initialise itself next time it's called.  Just seems icky to me :)

From https://docs.zen-cart.com/dev/code/extra_folders/ ""includes/extra_configures - global configuration settings which have been added. Using this folder means not having to modify includes/configure.php."" - A hard system default locale would seem to suit `configure.php`, then.  I worry about upgraders not noticing the addition.

**Comment by drbyte** [comment]
>  I worry about upgraders not noticing the addition.

I agree. I'd suggest that zcDate should query what the current locale is set to, and if not yet set to something valid, simply default to english. That way we have lots of flexibility about "where" we ask people to define it.

In summary, I propose:
1. add a setlocale() statement to configure.php
2. have zcDate's constructor inspect the currently set locale for validity (or invalidity), defaulting to english if found to be invalid
3. Thus no breakpoints need changing.  And there's very little language-specific internal processing that fires before the `init_languages`/`require_languages` is done, so the risk of displaying/building any content unrelated to the user's preferences is essentially moot.

**Comment by drbyte** [comment]
FYI The PHP team has accepted a PR https://github.com/php/php-src/pull/ 12568 _(yes, I broke that link intentionally)_ to no longer throw an exception in PHP 8.1 and 8.2 when `locale->isBogus()`. 
From comments, looks like it will still trigger in 8.3 though.

**Comment by brittainmark** [comment]
This is now affecting live systems.
@drbyte Is your proposal ready?
Will need to be back ported to 1.5.8.

**Comment by drbyte** [comment]
As for a quick fix for current live stores, I posted on the forum:

Simply add `@setlocale(LC_TIME, 'en');` to your store's 2 `configure.php` files.

**Comment by brittainmark** [comment]
Why not suggest they copy the setlocale from their lang.english.php files

**Comment by drbyte** [comment]
> Why not suggest they copy the setlocale from their lang.english.php files

1. Simpler quick fix. Don't have to guess or go hunting for "the right one" or worry about doing it wrong.
2. It gets overridden later anyway.

**Comment by drbyte** [comment]
Argh. Should have been `en_US` (or whatever you prefer), because `'en'` itself is "invalid"

**Comment by scottcwilson** [comment]
We may need to verify the zc_install handling of this directive - I know that if you use 

```
define('ADMIN_BLOCK_WARNING_OVERRIDE', '1');
```

it gets stripped out during an upgrade if the configure file is modified.

**Comment by drbyte** [comment]
Right. I was going to update the configure.php templates to incorporate it.

**Comment by drbyte** [comment]
But the more I look at it, the more I think it should just go into a core file, especially since it gets overridden later by any language-selection done by the store or the end-user's browser.

Probably just directly in application_top (or one of its dependents) like we do for some other PHP defaults that we set/reset for safety of having something dependable in place.

**Comment by drbyte** [comment]
... and it won't matter then if people have or haven't put it in their configure.php files. 
So upgrades won't wreck anything by wiping it out of the file.

...and any patching they have to do manually right now on live stores won't be a problem into the future either.

**Comment by scottcwilson** [comment]
We have a short term fix for people with live sites (thanks to your hard work!).  There's no rush for a final decision.

**Comment by drbyte** [comment]
Hopefully the PHP team release an 8.1.26 and 8.2.13 quickly ... and hosts also quickly upgrade to it ...

**Comment by drbyte** [comment]
I've proposed a PR for fixing this at the core level: #6038

**Comment by brittainmark** [comment]
Thanks for all your work.
