### ISSUE TITLE
Featured, Specials and Banners: Directly setting end-date in the past results in a never-ending time span

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#6043]
In the admin's **_Catalog :: Specials_**, **_Catalog :: Featured Products_** and **_Tools :: Banner Manager_**, hand-entering (rather than using the date-picker) a date in the past results in a never-ending time span.

**Comment by drbyte** [comment]
I'm assuming that when you say "never ending" you mean it's because you're observing that the thing using that end-date doesn't get expired correctly.

I suspect the root of the issue is that the hand-entered date isn't being received in a format that's recognized by core code when the date is parsed. The js date-picker reads the browser's settings and combines that with whatever settings core-code set for the picker and the field, so it's doing its own enforcement of backfilling any missing info and reformatting any rearranged date-formats that the end-user may have that may be different from the store (ie: commonly mm/dd being swapped for dd/mm in some locales ... or a missing time-section from the passed date).

And the resultant unparsed-at-the-browser-via-js date that comes from the hand-entered data is then not understood by the browser, and thus an "empty"/forever/0001-01-01 date is probably what's getting stored.

That's my suspicion, without looking at code or database records.

**Comment by lat9** [comment]
Each of those scripts checks for a date in the past and, if found, sets the ending date to the respective table's "never ending" value.  I'm thinking to just set the associated record's status to 'disabled' if that condition is found.

**Comment by drbyte** [comment]
Disabling it if expired seems logical.

But it seems strange that this would be a "new" condition/problem.

**Comment by lat9** [comment]
Noting that neither the "Specials" nor the "Featured" tools do any type of date validation (sigh).

**Comment by mc12345678** [comment]
> Noting that neither the "Specials" nor the "Featured" tools do any type of date validation (sigh).

Nor do any of these discussed areas establish product inactivity or process the entered dates upon admin entry. Thus, all current visiting customers reap whatever benefit is proposed regardless of when it was intended to be active. In a vanilla install, this is possible until a new session (admin or catalog) is started or the server time turns over to the next day. 

Untested is whether login of a visiting customer, where presumably at least the associated key is expected to change, also equates to a session change, I suspect no as everything else about the session is expected to remain available to that individual.
