### ISSUE TITLE
Repeated (48) use of function zen_get_product_details

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6087]
https://github.com/zencart/zencart/blob/b4f4b66fa34675c7653518bf0b57807851b3053b/includes/functions/functions_products.php#L32-L33
if I add an echo
```
    //Allow an observer to modify details
    echo '$product_id='.$product_id.'<br>';
    $zco_notifier->notify('NOTIFY_GET_PRODUCT_DETAILS', $product_id, $product);
```
This comes out 48 times on a single product page.

Is something (very) wrong here or I'm missing something?

**Comment by lat9** [comment]
Nothing's wrong, that's repetitive use of that function to reduce (and consolidate) database queries for the product's details.

**Comment by drbyte** [comment]
lat9 is correct. 
Most core code now calls `zen_get_product_details()` when querying product data. 
And since this function keeps the query syntax the same every time the product query is done, it is able to cache the response (separately for each product of course), so that subsequent calls return the cached query result, meaning less database hits.

**Comment by drbyte** [comment]
A further optimization could be to rework everything to use a Product class, so that the reaching out to the db query cache isn't needed. That's a big architectural change, impacting numerous template files, breaking old templates, obsoleting a lot of forum-help-posts about how to customize things in a site or template, as well as many plugins. Many benefits from consolidation, but many growing pains as well.
