### ISSUE TITLE
PRODUCT_ALL_BUY_NOW: can be 0 or 1234 but is not handled for both cases: PHP Fatal error

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6106]
in Admin->Configuration->All Listing
Set Display Product Buy Now Button to 0.

Shopfront:
index.php?main_page=products_all

PHP Fatal error:  Uncaught TypeError: str_repeat(): Argument #2 ($times) must be of type int, string given in includes\templates\responsive_classic\templates\tpl_modules_products_all_listing.php:103

Doing a search for PRODUCT_ALL_BUY_NOW in files shows that it is not tested for both 4 chars and 1 char.

Similarly for PRODUCT_ALL_LIST_QUANTITY and maybe the rest on that page that use 4-char definitions.

**Comment by drbyte** [comment]
The _LIST_QUANTITY stuff is correctly checked, like all those 0-vs-4-char switches, a few lines prior, and the loop is skipped when it's 0.

But yes, there's a long-standing bug which affects `PRODUCT_*_BUY_NOW` on the 3 "New", "Featured", and "All" listing pages.
Seems to only affect the *_BUY_NOW configs, specifically where it's building a buy-now button vs a more-info link/button/text and inserting line-breaks according to the config value.

https://github.com/zencart/zencart/blob/15244875dd387a49418041b3db143d1ee92b2ac1/includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php#L83-L104

Line 83 checks for `!='0'` in an `if` clause, which uses `str_repeat(..., substr(xxx,3,1))` to process the value of that constant.
But then the `else` clause on line 99 will fire when it's 0, but still calls the str_repeat (and the substr).

I'm not sure if this is an "easy" fix, because the `if` clause checks for multiple things, and generates various output segments based on multiple factors.

Preferable would be to just delete (because then less code to maintain and logic to parse when making future changes or storeowner customizations) [delete] the whole `str_repeat(..., substr(xxx,3,1))` bit from line 103, which would skip the line-breaks which that Constant is being used to control. But is that okay as far as on-screen output goes?

Alternatively of course we could just re-check-for-0 inline within the str_repeat params. (eg: `substr(PRODUCT_ALL_BUY_NOW, 3, 1)` becomes something like `substr(PRODUCT_ALL_BUY_NOW > 0 ?: '0000', 3, 1)`, although strict-type mode will probably require making the code a lot more complex).
But that's not consistent with how all the rest of the PRODUCT_*_XXXXX_YYYY switches are used in all these templates (where the `else` clause doesn't do the repeater stuff at all). Granted, maybe that's fine since this Buy-Now has some uniqueness in terms of its context.

So, needs some research on whether deleting that segment is fine in the, or is it crucial to output correctly.

**Comment by torvista** [comment]
At this point
```
} else { 
         $link = '<a class="list-more href="' . zen_href_link(zen_get_info_page($products_all->fields['products_id']), 'cPath=' . zen_get_generated_category_path_rev($products_all->fields['master_categories_id']) . '&products_id=' . $products_all->fields['products_id']) . '">' . MORE_INFO_TEXT . '</a>'; 
         $the_button = $link; 
         $products_link = '<a class="list-more" href="' . zen_href_link(zen_get_info_page($products_all->fields['products_id']), 'cPath=' . zen_get_generated_category_path_rev($products_all->fields['master_categories_id']) . '&products_id=' . $products_all->fields['products_id']) . '" title="' . $products_all->fields['products_id'] . '">' . MORE_INFO_TEXT . '</a>'; 
         $display_products_button = zen_get_buy_now_button($products_all->fields['products_id'], $the_button, $products_link) . '<br>' . zen_get_products_quantity_min_units_display($products_all->fields['products_id']) . str_repeat('<br>', substr(PRODUCT_ALL_BUY_NOW, 3, 1)); 
```
PRODUCT_ALL_BUY_NOW **IS** 0, so why not just get rid of str_repeat
`         $display_products_button = zen_get_buy_now_button($products_all->fields['products_id'], $the_button, $products_link) . '<br>' . zen_get_products_quantity_min_units_display($products_all->fields['products_id']) . '<br>'; `

Same for featured products.

**Comment by drbyte** [comment]
> At this point PRODUCT_ALL_BUY_NOW **IS** 0

Well, not necessarily. And that's the point I was making earlier. For other similar settings constants, the only check is whether it's 0 or not. But in the case of _BUY_NOW it's also checking another condition: in this case, the add-to-cart value.

So ... what I haven't studied out fully, is whether the repeated `<br>` tags are still desirable in the case of this `else` clause, and the conditions under which it is executed.

**Comment by torvista** [comment]
Yes, understood, either a tedious investigation/spring clean or invent a convoluted ternary clause to paper over it....

**Comment by drbyte** [comment]
After exploring a bit, I'm reasonably satisfied that your proposed removal of the str_repeat() is safe and an adequate solution. PR #6115
