### ISSUE TITLE
responsive classic: use of $show_table_header_row

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6194]
Is `$show_table_header_row` supposed to be there?

https://github.com/zencart/zencart/blob/a30bd090e0a3906034193e8127f83aa93e85763a/includes/modules/responsive_classic/product_listing.php#L42

I find no other reference to it.

**Comment by drbyte** [comment]
Yes. It's an undocumented override one can use to re-enable the table header row if they really want it, such as for templates that are sticking with legacy row-based listing format and want to show the click-the-heading-to-sort row despite the sort dropdown already being present.
Undocumented because it's kindof an edge case. 

If you want to use it, stick it in site-specific-settings and set it to true.

**Comment by scottcwilson** [comment]
Can this be closed?

**Comment by torvista** [comment]
documented: https://github.com/zencart/documentation/pull/1170
