### ISSUE TITLE
Further improvements to modal dialog display 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6200]
The modal display of images in 2.0.0 looks *much better* than the old style popup display. 

But there's still a gap between what we have and what the Bootstrap template has.  

Please consider: 
- adding the product name
- adding a close button. 

Screenshots: 

https://docs.zen-cart.com/user/images/popups/

**Comment by drbyte** [comment]
The modal is currently just the image.

Clicking anywhere on the modal closes it. 
Is a close-button needed? (ie: adding one would ONLY be merely a visual cue, cuz the whole modal is already a Close button)

(A more complicated approach would be to make clicking-away-from-the-image trigger the close.)

**Comment by scottcwilson** [comment]
I agree the modal is currently just the image; I'm suggesting improving it by adding these features (product name and close button). 

A close button is needed per customers of mine who find the current interface unclear.

**Comment by drbyte** [comment]
Exploring options:

1. Uncomment the "click to close" text that's already built-in:
```php
 <div class="imgLink center">--><?php //echo TEXT_CLOSE_WINDOW_IMAGE; ?><!--</div>
```
<img width="605" alt="Screen Shot 2024-02-02 at 3 44 34 PM" src="https://github.com/zencart/zencart/assets/404472/ef1c10a9-f19f-412e-9d8f-65d4df5fe8af">

2. Add a literal "X" which applies the existing close-button css:
```php
               <div class="imgmodal-close">X</div>
<!--        <div class="imgLink center">--><?php //echo TEXT_CLOSE_WINDOW_IMAGE; ?><!--</div>-->
```
<img width="657" alt="Screen Shot 2024-02-02 at 3 52 42 PM" src="https://github.com/zencart/zencart/assets/404472/36d8be46-f6e9-4d1a-bd5f-311930b75825">

3. Both
<img width="733" alt="Screen Shot 2024-02-02 at 3 48 38 PM" src="https://github.com/zencart/zencart/assets/404472/ca4286db-b6eb-4785-8f96-7f84b03a8406">
<img width="662" alt="Screen Shot 2024-02-02 at 3 49 13 PM" src="https://github.com/zencart/zencart/assets/404472/2164043f-2289-4bab-97b7-3103dc072e9b">


4. Use an icon instead of literal `X` character.

**Comment by drbyte** [comment]
With FA-icon: (X, round, square)
<img width="644" alt="Screen Shot 2024-02-02 at 4 54 08 PM" src="https://github.com/zencart/zencart/assets/404472/f394445d-7341-40e8-aee2-700756d8f65c">
<img width="645" alt="Screen Shot 2024-02-02 at 4 50 47 PM" src="https://github.com/zencart/zencart/assets/404472/0812dbd8-1a8e-4b4f-aa7f-5d70e33c35b5">
<img width="644" alt="Screen Shot 2024-02-02 at 4 52 13 PM" src="https://github.com/zencart/zencart/assets/404472/db09f177-7903-40d7-aedd-ca61e8090539">
<img width="646" alt="Screen Shot 2024-02-02 at 4 50 59 PM" src="https://github.com/zencart/zencart/assets/404472/864e89bf-8ab6-427b-a5dc-efa0fe03c64c">

**Comment by scottcwilson** [comment]
2 and 3 are good. 4 is like 2 for additional images.  Good.

**Comment by scottcwilson** [comment]
Note for documentation - redo `/images/image_modal.png` on https://docs.zen-cart.com/user/images/popups/

**Comment by drbyte** [comment]
Settled on something like this:

<img width="693" alt="Screen Shot 2024-02-03 at 7 12 28 PM" src="https://github.com/zencart/zencart/assets/404472/119ca76b-eef8-431c-a2c4-33368177fdb3">
<img width="783" alt="Screen Shot 2024-02-03 at 7 12 37 PM" src="https://github.com/zencart/zencart/assets/404472/5001fa95-0eb9-48eb-a377-afff4afab0d0">
