### ISSUE TITLE
Old style values like Sort Order Default - Product Listing don't match new SNAF configuration

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6221]
The suggested value for Sort Order Default - Product Listing (PRODUCT_LISTING_DEFAULT_SORT_ORDER) is "2a."

People who didn't come from an older installation background won't understand this.  Document or update?

**Comment by drbyte** [comment]
This is a little complicated. 
Support remains internally if one wants to still use that old legacy sort style.
But if someone puts in one of the values that the other sort switches offer, it'll use that. If not an integer (or is blank), it uses '8'.
<img width="223" alt="Screen Shot 2024-02-17 at 10 54 14 PM" src="https://github.com/zencart/zencart/assets/404472/0c569d1c-8e3d-4ca5-a6e6-b22b9d84e54a">

We could redefine the function that's used for that setting and force it to select 1-8 instead of being freeform input for an alphanumeric string, but that then forces an integer selection and prevents legacy implementations from using column-heading-clicks to sort. 
I'd prefer to do just that.
But I don't know the impact on older templates.
