### ISSUE TITLE
Define pages editor is now super skinny

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6268]
<img width="1062" alt="define" src="https://github.com/zencart/zencart/assets/4391638/92f9ae45-5d7f-44fc-baa5-b3dbb6d63bc0">

**Comment by drbyte** [comment]
Edit: instead of renaming, I think it's best to simply remove the `width:auto` CSS override that was in place for "older browsers that didn't support css width settings", as that override was put there decades ago (2006) when the browser landscape was way less mature in CSS support than it is today.
