### ISSUE TITLE
ADMIN: new custom created product types do not use the correct language file for that specific new product type

### ISSUE THREAD

**Issue by highburyeye** [zencart/zencart#6418]
**Describe the bug**
If a new custom product type is created, the language file is not used for that new prodcut type. Only seems to affect ADMIN.
For example:
If you have product_myProductType set up correctly as a new product type, you would expect to have a language file for that type
eg 
lang.product_myProductType.php 
however the lang file used by admin is ALWAYS 
lang.product.php

I am not sure if that's intended, but I have made a small fix that seems to successfully allow the correct new custom product types lang file to be used.

**Version**
Zen Cart version: 2.0.0
PHP version: 8.3
MySQL version: 
Plugins that may be related: 
What older/newer versions were also tested?

**To Reproduce**
Steps to reproduce/demonstrate the behaviour:
4. See such-and-such

** TO FIX **
change file 
admin/category_product_listing.php
line 925 
```diff
-<a href="<?php echo zen_href_link(FILENAME_PRODUCT, 'cPath=' . $cPath . '&product_type=' . $product['products_type'] . '&pID=' . $product['products_id'] . '&action=new_product' . $search_parameter); ?>" title="<?php echo IMAGE_EDIT; ?>" style="text-decoration: none">
+<a href="<?php echo zen_href_link($type_handler, 'cPath=' . $cPath . '&product_type=' . $product['products_type'] . '&pID=' . $product['products_id'] . '&action=new_product' . $search_parameter); //TC changed to $type_handler ?bug ?>" title="<?php echo IMAGE_EDIT; ?>" style="text-decoration: none">
```
AND

line 1020
```diff
-<a href="<?php echo zen_href_link(FILENAME_PRODUCT, 'cPath=' . $cPath . '&product_type=' . $product['products_type'] . '&pID=' . $product['products_id'] . '&action=new_product' . $search_parameter); ?>" class="btn btn-sm btn-default btn-edit" role="button" title="<?php echo IMAGE_EDIT_PRODUCT; ?>">
+<a href="<?php echo zen_href_link($type_handler, 'cPath=' . $cPath . '&product_type=' . $product['products_type'] . '&pID=' . $product['products_id'] . '&action=new_product' . $search_parameter);//TC changed to $type_handler ?bug ?>" class="btn btn-sm btn-default btn-edit" role="button" title="<?php echo IMAGE_EDIT_PRODUCT; ?>">
```

there is also a link  through the product image that I have not managed to find nor change as yet....

**Comment by drbyte** [comment]
Unfortunately the code change you proposed breaks all the other product-types. 😢

**Comment by drbyte** [comment]
The "old" way of creating new product type pages in the Admin was to clone `product.php` and its language file, and all the collect_info.php etc files.
And of course, that's why you're running into this situation ... because things have changed. 

Currently (as of v2.0 at least) there are no longer type-specific pages in the admin root directory. Only `product.php` (`FILENAME_PRODUCT`). And then all the corresponding `collect_info.php`/etc pages are loaded based on the product's product-type ID and corresponding type-string.
The way to handle language "overrides" in this context is not to actually override them, but to define new constants for the ones that are specific to your product-type, and load that language file in `extra_definitions`. You can see examples of this with `product_music` and `document_general` where the language files only contain the definitions unique to that product-type, and then for everything else that's still part of core base product handling, it uses `lang.product.php` because those strings are already loaded.

**Comment by highburyeye** [comment]
Thanks for explaining.
I think it didnt break mine, perhaps as my product lang files were just copy/paste with bits added or changed.
I will try changing my system to us extra_definitions .
Thanks for helping.

**Comment by highburyeye** [comment]
...your tip, using admin --> extra_definitions folder worked perfect BTW :)

**Comment by scottcwilson** [comment]
Additional note for documentation: one of the bullets in https://docs.zen-cart.com/user/upgrading/release_specific_upgrade_considerations/ for 2.0.0 upgraders discusses this, and points to the file admin/includes/modules/HOW_OVERRIDES_WORK_HERE.txt in the distribution.

**Comment by scottcwilson** [comment]
@highburyeye Please close if satisfied.
