### ISSUE TITLE
html_includes example texts in core templates

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6433]
Is there any need for these example texts to be repeated in the templates in the distribution?

![image](https://github.com/zencart/zencart/assets/4391026/6e6d6654-e7a1-4f5d-beef-a262415665e4)

**Comment by drbyte** [comment]
Unfortunately yes, because if the file doesn't exist then it cannot be edited.

Most of the files contain default text that people can reasonably use as-is, without requiring modifications (which is better than what we did years ago when we first added those files, where we put "this is sample text, please replace it", but nobody bothered to update them for their store, so their store had a bunch of "this is sample text" pages 🤦 ).

Admittedly, the hosting landscape is better nowadays, and we could probably reliably clone the file on-demand if one wanted to edit it. We definitely couldn't reliably do that until a few years ago, due to PHP file ownership/permission limitations. But it's always safer to have the user upload the file than to have PHP "create"/copy a file, because the owner starts out as "who" created it ... and if PHP created the file (on the server, not talking about "local" here), then it's very reasonable for it to get blocked by server security mechanisms in order prevent malicious activity.

**Comment by torvista** [comment]
Ok, then the default texts should be all be useable and identical to those in the templates, but neither is 100% true at the moment.

**Comment by drbyte** [comment]
Synced in https://github.com/zencart/zencart/commit/0ac925e9161eb00cd0b33db500756ee8a22e6fc4
