### ISSUE TITLE
A non-superuser Admin gets "Denied" when accessing Banner Statistics page

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#644]
Permissions for `banner manager` don't also cascade to `banner statistics`.  

(And the `banner stats` widget permission setting isn't tied to the `banner statistics` *page*)

**Comment by zcwilt** [comment]
Not sure how to address this.
There is no easy way to cascade the perms for banner stats from banner manager.

We could add an entry into admin_pages for banner_stats so that it would appear in the list of pages to authorize. However this means admin would have to `auth` both banner manager and banner stats for a profile.

**Comment by mc12345678** [comment]
Unless a little AJAX is used to coordinate the two such that banner stats follows banner manager upon change, but banner stats can be independently modified.

**Comment by proseLA** [comment]
i would propose a new table, using utilizing page_key and widget_key.  if permissions for the particular page_key are granted, it would then cascade to all widget_keys associated with the page based on the table.  if, however, permissions for a particular page_key are revoked, the admin would then have to manually remove the corresponding permissions for all widgets if so desired.  this new table can be pre-populated on install/upgrade, as well as a page for administering (or not) said relationships.  this would allow total flexibility.

i would think that using AJAX or jquery would require hard-coding specific relationships rather than providing the flexibility of a new DB table.  which could also be a viable way to go.

if you guys want to make a decision on it; i would be willing to take a crack at it.

right now, it seems one needs to authorize both/either on the profile.  where there is no cascading. which personally i think is fine.  in which case, someone should close the issue.
