### ISSUE TITLE
index/category listing, final notifier for categories_description correct?

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#6467]
https://github.com/zencart/zencart/blob/198b15002b53a534fc9fbd3907415f4612ded6a7/includes/modules/pages/index/main_template_vars.php#L230-L235

I was looking at modifying the categories description and see this notifier is after the template is loaded/after the category description is used.

**Comment by scottcwilson** [comment]
I wonder if we should add `$current_categories_description` as a parameter to `NOTIFY_HEADER_INDEX_MAIN_TEMPLATE_VARS_PAGE_BODY`.

**Comment by drbyte** [comment]
Yes that should probably be changed.

WORKAROUND: Since `$current_categories_description` is a variable in global scope, you could probably just `global $current_categories_description` in your Observer's `update` method for `NOTIFY_HEADER_INDEX_MAIN_TEMPLATE_VARS_PAGE_BODY` and alter its content directly.

**Comment by torvista** [comment]
Yes, I often do that...which makes me think why specifically pass **any** variable that is global?

**Comment by scottcwilson** [comment]
Because it makes the code more self documenting.  The intent is much clearer.
