### ISSUE TITLE
Featured Category > Add Featured Category by Selection creates incomplete list 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#6692]
The list does not include categories like DVD Movies > Comedy, which do have products. 

Repro: Admin > Catalog > Featured Categories
Press Add Featured Categories by Selection
Observe that list is missing entries.

**Comment by scottcwilson** [comment]
One way to get the right behavior is to change the call to `zen_draw_pulldown_categories_having_products` in `featured_categories.php` so that the last 3 parameters  are 

`true, true, false`

rather than 

`true,'',true`

but it seems like the root cause might be that `includes/functions/functions_categories.php` line 428 call to `includeAttributes` should be

`includeAttributes($includeAttributes);`

and rather than 

`includeAttributes($includeAttributes || $show_full_path);`

with the above change, you can now set the last parameters to `zen_draw_pulldown_categories_having_products` 

to 

`true, true, true`

(but I'm not sure if other callers depend on this behavior I am suggesting changing).

**Comment by TMCSherpa** [comment]
I don't remember where true, ' ', true came from.
Originally I replaced zen_draw_pulldown_products with zen_draw_products_pull_down_categories because that made sense but it's depreciated for some reason?
There are a couple jumps down to zen_draw_pulldown_categories_having_products so I'm sure I copied it from somewhere
