### ISSUE TITLE
Debug logs widget - make log entries clickable

### ISSUE THREAD

**Issue by zcwilt** [zencart/zencart#76]
clicking should then show the actual log entries, either in a modal or a new page

**Comment by scottcwilson** [comment]
I will do this one sometime this week.  Please assign to me, Chris.

**Comment by drbyte** [comment]
FYI: please do go ahead. I wanted to let you know that we're toying with some future changes to the way these logs are presented, but having this part taken care of now could be a good help before then. You won't be working at cross-purposes. Just wanted to let you know so that when its look and feel changes later you aren't surprised;)
