### ISSUE TITLE
Strict PHP Notices for  Undefined indexes

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#928]
for example:
Undefined index: customers_authorization in functions_prices:

`case ((int)$_SESSION['customers_authorization'] == 2):
        // customer is logged in and was changed to must be approved to see prices
        return TEXT_AUTHORIZATION_PENDING_PRICE;`

I assume the other switches also should be using isset.
There are probably only a dozen or so more of similar notices that get reported while browsing in various places, mostly in the product listing, so fairly easily fixed.

**Comment by drbyte** [comment]
Are you seeing this specifically in v160?   Or also in v155?

**Comment by torvista** [comment]
These are things I am noting/fixing as part of my 155 upgrade and then looking if the code has changed for 160. Guess I should have checked if 160 does the same...

**Comment by drbyte** [comment]
No worries. I'm surprised that you're seeing those in v155. I haven't seen them there, hence my question.

**Comment by torvista** [comment]
I use Xamppp, php 7.04 and in enable_error_logging.php I use this:

`$errors_to_log = -1;//steve set to -1 to show EVERYTHING
///// DO NOT EDIT BELOW THIS LINE /////`

This generates a big debug most of which is constant-related, but search for undefined index or undefined variable to pick up the odds and sods like this..

**Comment by scottcwilson** [comment]
I have a 6792 line log created just by displaying the home page.  Are you *sure* we want to fix these?  How about we just fix the `PHP Notice:  Use of undefined constant` errors instead, which are actual bugs?

**Comment by torvista** [comment]
99% of the log is "constants already defined" and that comes with the territory as it stands currently, so can be ignored.
The undefined indexes, constants and variables are not so many and most are easy fixes that only have to be done once. 
I would have thought this type of detail-checking would be done regularly on a changing codebase...towards the ideal of zero errors whether visible or not and 100% valid html.

**Comment by scottcwilson** [comment]
I suppose that if we replaced the PHP define statements with a function call to define if not defined, or just replaced them inline with if !defined(name) define (name) then we could shake out these errors too.  Is it worth it?

**Comment by torvista** [comment]
That seems like hiding the error rather than investigating it.
I am working through my ZC155 shop now and so far have found only one core constant not defined where I can't see why easily. The rest are mine/mods and easily fixed. I think understanding the reason for the warnings and really fixing them is important, especially as there are  so few.
Some of the undefined indexes and variables are difficult and I have left those, more reason for them to be investigated further I think, they could lead to finding logical errors and even, heaven-forbid, those elusive rounding errors!

**Comment by drbyte** [comment]
> I suppose that if we replaced the PHP define statements with a function call to define if not defined, or just replaced them inline with if !defined(name) define (name) then we could shake out these errors too. Is it worth it?

For constants in language files, this would make those files a lot more difficult to maintain. For language files, the warnings about "already defined" occur because we load lang-overrides first, then core language files, which would of course cause the duplicates-warning. Changing all that to a completely different architecture, whether stored in db or just in PHP arrays, is a more optimal way to address that, but is not something we'd do in the 1.5.x series.

**Comment by drbyte** [comment]
> Undefined index: customers_authorization in functions_prices:
`case ((int)$_SESSION['customers_authorization'] == 2): // customer is logged in and was changed to must be approved to see prices return TEXT_AUTHORIZATION_PENDING_PRICE;`
I assume the other switches also should be using isset.

I imagine that in this particular scenario if you're getting `undefined index` here then your customer is not logged in, because for a logged-in customer that index would normally be set.

Yes, one could wrap an isset() around each of those. that's one way. Kinda verbose. This is one part of PHP I dislike: the need to repeat yourself just because something might not exist yet. (ie: `if (isset($bigLongVariableNameNere) && $bigLongVariableNameNere = 'big long value or multiple conditions here to make the code unreadable') { then ... }` 

Another way is to rearchitect the use of those session vars into a customer object which would internally take care of all the isset() things. This is our preferred approach, as it also then allows for easier flexibility for plugins and addition of new features. But it's a breaking change hence why wasn't done in 1.5.x

**Comment by drbyte** [comment]
```Undefined index: call_tag in /includes/templates/template_default/common/tpl_price_block.php on line 33
Undefined index: call_tag in /includes/templates/template_default/common/tpl_price_block.php on line 39
Undefined index: customer_id in /includes/init_includes/init_customer_auth.php on line 50
Undefined index: customer_id in /includes/init_includes/init_header.php on line 64
Undefined index: customer_id in /includes/templates/template_default/common/tpl_header.php on line 46
Undefined index: customer_id in /includes/templates/template_default/common/tpl_header.php on line 49
Undefined index: customer_id in /includes/templates/template_default/common/tpl_header.php on line 52
Undefined index: customers_authorization in /includes/functions/functions_prices.php on line 179
Undefined index: customers_authorization in /includes/init_includes/init_customer_auth.php on line 177
Undefined index: customers_authorization in /includes/templates/template_default/common/main_template_vars.php on line 63
Undefined index: customers_authorization in /includes/templates/template_default/common/main_template_vars.php on line 67
Undefined index: free_tag in /includes/templates/template_default/common/tpl_price_block.php on line 36
Undefined index: name in /includes/classes/category_tree.php on line 166
Undefined index: new_products_category_id in /includes/library/zencart/ListingQueryAndOutput/src/definitions/UpcomingProductsCenter.php on line 70
Undefined index: new_products_category_id in /includes/library/zencart/ListingQueryAndOutput/src/filters/CategoryFilter.php on line 24
Undefined index: one_time in /includes/templates/template_default/common/tpl_price_block.php on line 40
Undefined index: one_time in /includes/templates/template_default/common/tpl_price_block.php on line 46
Undefined index: show_sale_discount in /includes/templates/template_default/common/tpl_price_block.php on line 39
Undefined index: show_sale_discount in /includes/templates/template_default/common/tpl_price_block.php on line 72
Undefined index: show_special_price in /includes/templates/template_default/common/tpl_price_block.php on line 39
Undefined index: show_special_price in /includes/templates/template_default/common/tpl_price_block.php on line 48
Undefined index: show_special_price in /includes/templates/template_default/common/tpl_price_block.php on line 65
Undefined index: show_special_price_sale in /includes/templates/template_default/common/tpl_price_block.php on line 61
Undefined index: show_special_price_sale in /includes/templates/template_default/common/tpl_price_block.php on line 65
Undefined index: starting_at in /includes/templates/template_default/common/tpl_price_block.php on line 32
Undefined index: starting_at in /includes/templates/template_default/common/tpl_price_block.php on line 44
Undefined property: ZenCart\ListingQueryAndOutput\definitions\FeaturedProductsCenter::$pageDefinition in /includes/library/zencart/ListingQueryAndOutput/src/definitions/AbstractDefinition.php on line 104
Undefined property: ZenCart\ListingQueryAndOutput\definitions\NewProductsCenter::$pageDefinition in /includes/library/zencart/ListingQueryAndOutput/src/definitions/AbstractDefinition.php on line 104
Undefined property: ZenCart\ListingQueryAndOutput\definitions\SpecialsProductsCenter::$pageDefinition in /includes/library/zencart/ListingQueryAndOutput/src/definitions/AbstractDefinition.php on line 104
Undefined variable: css_js_handler in /includes/modules/template_dependency_modules.php on line 23
Undefined variable: template_css_output in /includes/modules/tpl_css_js_generator.php on line 197
Undefined variable: template_js_output_bottom in /includes/modules/tpl_css_js_generator.php on line 211
Undefined variable: template_js_output_top in /includes/modules/tpl_css_js_generator.php on line 208
Use of undefined constant CSS_BUTTON_POPUPS_IS_ARRAY - assumed 'CSS_BUTTON_POPUPS_IS_ARRAY' in /includes/functions/html_output.php on line 432
```

FYI: Lots of the "undefined index" entries from tpl_price_block will disappear when using new template constructs; old templates will trigger the legacy pricing data which is less performant and less customizable, and happens to also trigger all these undefined-index warnings because legacy-mode doesn't build all those pieces.

Also, the more I dig into the undefined-index warnings about customer_id and customers_authorization, the more I"m inclined to defer them to the use of a proper customer object, since that will clean up the code significantly by removing a lot of duplication and a lot of copy-paste and a lot of unnecessary "checks", all resulting in things being speedier, as well as easier to customize and maintain.

I'd like to see the category_tree class improved in lots of ways, which would include fixing the couple similar warnings seen there.
