### ISSUE TITLE
Suggestion: method to bypass / enhance (extend in quantity) define values stored in db from backend

### ISSUE THREAD

**Issue by Spike00** [zencart/zencart#930]
It happens occasionally that someone asks me to have the possibility to have a particular value, usually set from backend, not fixed but depending on various circumstances.

Example (but there really are a lot of other situations in which it may happens):
freeshipping threshold (MODULE_ORDER_TOTAL_SHIPPING_FREE_SHIPPING_OVER) based on group pricing (or whatelse)

Since freeshipping threshold is 'used' in various files, the neatest way (at least the one I prefer) to accomplish this, is to 'work' on the define value.

Logic: put all the values you need in the same place where it is supposed by default, but separating them with a conventional character (this way you may manage as many values as you need). 

At this point you need to remove the define MODULE_ORDER_TOTAL_SHIPPING_FREE_SHIPPING_OVER from the autoloading process (init_db_config_read.php)

``` php
foreach ($configuration as $row) {
  /**
   * dynamic define based on info read from DB
   */
  define(strtoupper($row['cfgkey']), $row['cfgvalue']);
}
```

becomes

``` php
foreach ($configuration as $row) {
  /**
   * dynamic define based on info read from DB
   */
  if (strtoupper($row['cfgkey']) == 'MODULE_ORDER_TOTAL_SHIPPING_FREE_SHIPPING_OVER')    {
  $zw_multiple_freeshipping_over = $row['cfgvalue'];
}
  else define(strtoupper($row['cfgkey']), $row['cfgvalue']);
}
```

At this point, with a simple auto-loader which calls a new init_include file, you may create your logic to assign the correct value to that define.

Very easy and mantainable, requiring just one core file to modify (init_db_config_read.php).
Here is my suggestion: could be implemented a method in init_db_config_read.php that checks if there are defines to manage this way?
It could be used an array that contains each define that you want to manage this way with the corresponding variable where to store the value read from the db).
This way, we may have 'variable' defines without modifying any core file.

**Comment by drbyte** [comment]
You can already override the defines set by the autoloading process, like this:

1. Create a new file: /includes/extra_datafiles/my_settings_overrides.php

2. In that file place any necessary logic to define the value for `MODULE_ORDER_TOTAL_SHIPPING_FREE_SHIPPING_OVER` ... that could be just a simple `define` statement, or could also include other conditional logic to decide whether or not to define it. 

That's it. Then when the init_db_config_read script runs it will not (cannot, because of how defines work) define that value from the db, because it will already be set by your override.

(In the strictest sense PHP may throw a warning that the constant has already been defined. It already does that for language file overrides because of various limitations in the language infrastructure inherited from osC. 
I'd entertain a PR to change init_db_config_read to first test `if (!defined($key))` to avoid that warning ... but it's a minor thing.)


NOTES:
- your proposal here was to intercept init_db_config_read as the solution to the problem of wanting to define these settings to something else
- but that approach has a serious limitation:  VERY little of the overall Zen Cart framework has been initialized at this stage. (init_system values 0-39) so while classes have been "loaded" (not all instantiated) and db "started" ($db object is available though), there are a lot of core ZC functions and features that are not accessible 
- so any business logic that you might want to use to determine whether to redefine (ie: MODULE_ORDER_TOTAL_SHIPPING_FREE_SHIPPING_OVER) to something else based on some other conditions (ie: group pricing) may require you to get very creative with adding extra DB queries (that might otherwise not be needed) to determine your custom operation.

**Comment by Spike00** [comment]
I wrote that I use an autoloader to include the new init. I usually use 75 so, session is available. Maybe depending on the needs, different points could be needed, but for the moment 75 has always been enough.
Example:
autoloader file
`$autoLoadConfig[75][] = array('autoType'=>'init_script', 'loadFile'=> 'init_multiple-freeshipping.php');`

init file
`if (!defined('IS_ADMIN_FLAG')) {
 die('Illegal Access');
} 
$over_explode = explode('|',$zw_multiple_freeshipping_over);
if($_SESSION['customer_whole']) {
	$over = $over_explode[$_SESSION['customer_whole']];
}
else $over = $over_explode[0];
define('MODULE_ORDER_TOTAL_SHIPPING_FREE_SHIPPING_OVER', $over);`

Just because in init_db_config_read we're at an early stage of the inizialization process of the framework, my proposal is simply to defere later the definition of the defines to which I want to apply a more complex logic to assign a value.

Ad using 75 (anything after 70, when session is initialized), or any other point before or after is just a choice of who is writing the code, based on what is needed. And of course the right point will be choosen to be sure that it is initialized everything is needed by the logic you'll use.

**Comment by drbyte** [comment]
I can appreciate what you're trying to accomplish.  And I completely understand why you need to fire things after the session has started. 

So we have a few ways to proceed from here: 

a) You can make your own changes as you need to for your own sites, and where that involves altering core init_includes files, you can place those altered versions in the init_includes/overrides folder as a way of separating your changes from core files and thus making it easier to identify files that need special attention during upgrades. 
No changes to core code.

or perhaps:

b) we can entertain a way of creating an interception point for the config keys, perhaps allowing you to use the extra_datafiles folder to create or add to an array of config keys that should be deferred until a later point. In this sort of case it might work like this:
 - your `extra_datafiles` files could add values to `$deferred_config_keys[KEY_NAME_HERE] = 'undefined'`
 - `init_db_config_read` would check for entries in that array (much like your example above), and store any values for deferring as the actual array value, ie: `$deferred_config_keys[KEY_NAME_HERE] = 'actual value from db'`
 - your own custom code at a later init point (ie: after 70, or whatever) could then do its interceptions and custom defining of constants, and remove keys from the `$deferred_config_keys` array individually after it does its own defining.
 - and then add another init script to loop thru the `$deferred_config_keys` array to define any that didn't get defined already by your intercepting code

There are of course a large number of these config settings that MUST be defined for all the other init system stages (40+) to be able to function properly.  And then there are the potential odd troubleshooting challenges that could be introduced by adding this sort of complexity to the whole bootup infrastructure.

Naturally, if it were for just your own site/sites, you can do whatever you like!

**Comment by drbyte** [comment]
Or is it better to just have individual modules read the `CONSTANT` into a variable, ie: `$var = CONSTANT;`, and then check for an override someplace and update the `$var` based on that?

**Comment by drbyte** [comment]
The more I think about this, and look at code, the more I think it's better to rewrite the modules that use those constants: read the constant into a variable, then fire a notifier hook to see whether there are any overrides to apply which would redefine the value of that variable, then carry on accordingly.
