### ISSUE TITLE
Suggestion: Migrate Tutorials content to Docs site

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#962]
Moving https://www.zen-cart.com/content.php?2-FAQs-and-Tutorials 
to a subsite under http://docs.zen-cart.com/Overview/main
would make it easier to keep them up to date, index them for searching, etc.

**Comment by scottcwilson** [comment]
[how_do_i_install.md.txt](https://github.com/zencart/zencart/files/300747/how_do_i_install.md.txt)

**Comment by wiztechinc** [comment]
I do agree - I hate the way the tutorials are done on the forum - hard to find anything. This might be something I could help with.

**Comment by drbyte** [comment]
@wiztechinc wrote:
> hard to find anything

Is that because you're trying to navigate by category?
Or is your comment related to "search"?

... cuz the "search" is heavily integrated into the forum, and actually brings back results of Tutorials/FAQs inline with forum posts, based on relevance.

Admittedly there are too many categories, and the display of articles "within" categories is awkward to navigate.


But ... it's never helpful to merely say "hard to find anything" without explaining more ... right?

**Comment by scottcwilson** [comment]
> ... cuz the "search" is heavily integrated into the forum, and actually brings back results of 
> Tutorials/FAQs inline with forum posts, based on relevance.

<rant> 

So to me, this is horribly broken.  I'm on the FAQs page. I want to search FAQs, not forum posts.
I hate it when the first thing that shows up is some 5 year old post that I'm sure is out of date.  

I know I can use advanced search and just confine the search to FAQs, but what I really want to do is look at the list of content and discover what I want by exploring and browsing.  Which is quite difficult right now.  And to make matters worse, the system is clogged up by truly awful articles like this: 

https://www.zen-cart.com/content.php?204-i-currently-have-a-store-on-homesteadcom-however-i-am-dissatisfied-with-their-services-and-would-like-to-move-the-hosting-as-well-as-the-products-i-had-already-entered-into-homestead-to-zen-cart-how-can-i-do-that

This is just hideous all around.  Hideous URL, hideous title, hideous formatting, and good grief it's just a frickin' link ARE YOU KIDDING ME??

</rant>

This would have been cleaned out years ago if it had been a system that people could easily contribute to.

**Comment by drbyte** [comment]
Fair.  When searching FAQs specifically I always use the `[FAQ]` link below the search box, to pre-filter to just the FAQ pages.

**Comment by drbyte** [comment]
NOTE: I've removed that pointless article (which got promoted incorrectly to an FAQ article instead of just getting a direct reply).

**Comment by wiztechinc** [comment]
Yeah, but when I click on the prominent FAQs link, I expect to be able to search in there specifically.

**Comment by drbyte** [comment]
Some days I hate vBulletin.

But ... I hope you all realize that moving all the docs away from the forum means there will be NO search results at all ...

**Comment by barco57** [comment]
> https://www.zen-cart.com/content.php?204-i-currently-have-a-store-on-homesteadcom-however-i-am-dissatisfied-with-their-services-and-would-like-to-move-the-hosting-as-well-as-the-products-i-had-already-entered-into-homestead-to-zen-cart-how-can-i-do-that

> This is just hideous all around. Hideous URL, hideous title, hideous formatting, and good grief it's just a frickin' link ARE YOU KIDDING ME??

> Some days I hate vBulletin.

Those made me laugh, Thank You. 
I think that the "problem" is a legacy one, from the days of the project being pretty much a closed group. With the project being much more open, it probably requires more hands doing things. There is the dev team, a forum moderation team, why not a docs team to manage the FAQs and the wiki (does anyone use the wiki anymore?), even the zen-cart.com site could use some work, particularly the home page (looks dated).

**Comment by Zen4All** [comment]
Yes the wiki is still used (by me ;) ) I regularly look up stuff I do not need to remember, because we have a wiki page

**Comment by barco57** [comment]
cool good too know. 

additionally somebody need to work through the showcase, there are tons of sites in there that don't exist anymore (expired domain names), some in the wrong category, and some no longer using zen cart. Random clicking through the showcase has found woocommerce sites, shopify sites, etc

**Comment by drbyte** [comment]
Okay, while we're at it, what other things need ripping out and replacing?  If we're gonna start from scratch then write your shopping list here.

**Comment by wiztechinc** [comment]
I have an offer for you. I had started something several years ago in the hopes it would make me some money, another failed attempt at capitalism. 

I was sorely disappointed in the zen cart book due to the lousy index and I created a site allthingszencart.com which documents the zen cart admin. It's only a wee bit outdated now but I still use it when I can't remember where something is in admin. Simple database, tons of info. I can donate it to the project.

In other words, let's do look at the resources and figure out what - and- things can benefit the project, the users and the more knowledgeable zen car users and developers.

My biggest problem has always been the sheer mass of information. How to tame it?  Organize it. 

How to deliver it?
Options include books, video tutorials, specialized databases, faqs, a wiki, etc on top of the forum. Screenshots help tremendously but are rarely delivered anywhere.

What types of info?
Generalized, directed at someone who thinking about using zc
Getting started shorts for newbies, early how tos
In depth discussion of how it works from a non techie point of view, organization (core, templating, language)
Technical, directed at those who dig into the code
Admin settings


 I can hear folks yelling now because of the amount of writing involved. I don't recommend something I can't deliver. I am a writer as well as graphic designer. I just published one book. I would like to do more. 

Let's look at all the possibilities for delivering information from a top down point of view.

**Comment by scottcwilson** [comment]
Delia, would you please move your last post to a new thread?  It's way beyond the scope of this ticket, which just covers migrating the existing Tutorials to a platform where they can be updated by the community.

**Comment by drbyte** [comment]
Naw, keep it all here.  It's already way off track. Let's not start a million github tickets about things not related to code. This one shouldn't even be here in the first place.

**Comment by drbyte** [comment]
This whole discussion should be on the forum, under the Support Site section.

**Comment by wiztechinc** [comment]
Whoops, the brain started working and ran away!

**Comment by scottcwilson** [comment]
You can see what it would look like (seeded with just a handful of articles) here:
http://docs.zen-cart.com/Tutorials/main#running_your_business
