### ISSUE TITLE
Considering: Remove admin "newsletters" and "product-notifications" screens

### ISSUE THREAD

**Issue by drbyte** [zencart/zencart#977]
Contemplating removing the archaic and unmaintained "newsletter" page from the admin ... because there are much more reliable and modern newsletter-sending tools available.
Same with product-notifications, since it's really lame :)

We can still "track" the associated opt-ins as we do now, and provide an exporter for extracting relevant data to a 3rd-party system.

Thoughts?  Will anybody "miss" the old tool?

**Comment by scottcwilson** [comment]
:+1:  Do it.

**Comment by proseLA** [comment]
just so i understand what you are asking, you want to remove the following files from the admin side:

newsletters.php
includes/modules/newsletters/newsletter.php
includes/modules/newsletters/product_notification.php
includes/languages/english/newsletters.php
includes/languages/english/modules/newsletters/newsletter.php
includes/modules/newsletters/product_notification.php
includes/languages/english/modules/newsletters/product_notification.php

remove the selection from the admin -> tools menu and do some remaining cleanup.  the customer class/table remains unchanged due to wanting to export to some 3rd party tool, ie constant contact, mailchimp, etc.

is there something else i am missing?

the one thing i will say which can get confusing for the customer is allowing them to unsubscribe from the ZC website and the store owner does not unsubscribe them from the 3rd party tool.  most of the store owners focus on the subscription in my opinion.  and the 3rd party providers generally have good tools for subscribe/unsubscribe.  but that is neither here not there....  just an observation.

**Comment by drbyte** [comment]
> the thing which can get confusing for the customer is allowing them to unsubscribe from the ZC website and the store owner does not unsubscribe them from the 3rd party tool

Thoughts on managing that?

One "partial" way to address it could be to integrate an export tool such as: https://www.zen-cart.com/downloads.php?do=file&id=6

Are additional "hooks" (notifier calls) necessary on the non-admin side to allow "unsubscribes" to auto-trigger the same on 3rd party services?

**Comment by proseLA** [comment]
wow, and to think i coded the email export all from scratch!  ;)

my opinion would be to remove the option completely from a customer being able to change it on ZC.  and to not have an unsubscribe integration to 3rd party services.

ZC is a shopping cart.  keep it at that.  manage newsletters and email lists on the 3rd party services.  they are much better at that.  send subscribes to the 3rd party service.  unsubscribes go directly there.  if the store owner is using a 3rd party service, they are already there on the management page and can unsubscribe anyone.  customers receiving the email should have an unsubscribe link on any newsletter.  it's part of the service.

once a SO gets sophisticated, they have the customer list segmented into groups, and again, its much easier doing that directly on the 3rd party service, IMO.

**Comment by drbyte** [comment]
Does it make sense to extract all these components to a plugin, such as "basic newsletter" capability etc? 

Or just push it all to 3rd-party (ie: paid) services?
(vs free plugin)

**Comment by barco57** [comment]
push it too 3rd party. 
Most of the 3rd party providers have a free tier.
"basic newsletter" capabilities, like the current newsletter functionality, via a plugin cause more trouble than its worth. There is no automatic list manage functions that are required too effectively keep a server off blacklists for sending emails to spam traps (lots of email providers take old unused email addresses and make spam traps out of them), no throttling, just no good ways to keep the list clean, store owners break the rules all of the time and want too send to all customers instead of those signed up for the newsletter, and they want to force which version gets sent (txt/html) because they think they can force their will regardless of the customers wishes. Where I work we push the allowed number of emails sent in an hour down to a point where we can catch most of the people using the ZC newsletter functions so we can start the conversation about them moving their newsletters to 3rd party providers.

**Comment by drbyte** [comment]
Good points.

Thoughts about a recommended default 3rd-party to direct people to?

**Comment by judygunderson** [comment]
Love the idea of taking the newsletter function out!  

I install the Mail Chimp mod a lot for my customers.  PHPList is usually a self install on most cPanel hosting plans, people could tie into that if they wanted to.

**Comment by barco57** [comment]
who ever gives you the best affiliate deal??? lol

**Comment by drbyte** [comment]
lol, it might come down to that 

... or at least who's the easiest to code for

**Comment by proseLA** [comment]
i like the mailchimp mod for ZC as it lets prospects (as opposed to existing customers) sign up easily, with no work on the part of the SO.  i think the same goes for new customers where you can just push the address to the list.  that said, i think the learning curve of mailChimp is a bit steep.  constant contact seems to work well but i have not seen any integration tools for ZC.  i have no experience with phpList, but a cursory view has me confused.  it says  it is open source with payment plans, and i'm not real sure which server does the sending of the email.  part of the payment is ensuring that your email gets to the intended recipient.  if phpList is something installed on the same host where ZC resides, i am not a fan.

**Comment by barco57** [comment]
Phplist pushes their hosted version because they want to become mailchimp/constant contact but you can still get the self hosted. Even with Phplist's throttling you are likely to run afoul of sending limits at some hosts...cough, cough. Most people do a fairly vanilla install of phplist and don't go through the bounce email setup, which means their lists get stale and start to cause blacklisting problems for the same reason the ZC newsletter functionality does, store owners are basically lazy when it comes too that. Want too hear a store owner scream, setup their bounce functionality, and after 3 bounces their newsletter list is half the size it used too be. 
The current mailchimp mod will need to be updated soon or it is going to stop working. Mailchimp is pushing the new api they want everyone on and has announced the date for later this year when they are turning off the old api's, bang they will stop working one day. Other changes to that mod to support more things that mailchimp offers is a topic for another conversation elsewhere...unless it were to become built in.

**Comment by judygunderson** [comment]
PHPList is free if it is a part of the hosting plan in cPanel - so it is on the server, in the individual hosting accounts.  
I like MailChimp much better, but unless it could be set up to where people could input their info in the admin area, it is going to be over the shop owner's head.  And even at that... agreed it is a learning curve to set up.  The good news is... once you have your main template set up for the newsletter ... it is easy peasy from there.

**Comment by scottcwilson** [comment]
Should the up-for-grabs tag be removed from this issue?

**Comment by drbyte** [comment]
Closed by #1013

**Comment by torvista** [comment]
So, after wasting time checking out and finding a bug in the notifications, I find this thread about the whole section being removed!

I use the email exporter (with a template for making a phplist-ready csv) regularly, to update my phplist email list prior to sending a new newsletters.
I agree an external (comprehensive tool) like phplist is necessary...no need to re-invent that wheel.
So, yes I do use the field that stores the customer newsletter preference, but I would not use the newsletter function.

But the product notification is a different animal.
It can serve for product recalls or safety info to be sent out. In fact, I'm going to use it now to publicise an upgrade notice for a specific product.

So is the plan still to remove it? If so, do it now so no-one else wastes time on it!

**Comment by wiztechinc** [comment]
agree it should be removed. Many hosting companies won't even let you send mass emails anymore and there are free options available that are way better anyway.

**Comment by torvista** [comment]
> Many hosting companies won't even let you send mass emails anymore

Really? I had no problem with the three hostings I have used...but I asked them first what throttling to use for the phplist configuration.

**Comment by wiztechinc** [comment]
Even if you are able to do so, I would never advise it. There's too much blocking going on on ISPs now due to spam. Getting your ip blackballed is a true possibility. Using a third party means that can't happen.
